### ISSUE TITLE
Add a provisioning task to ingest development rasters into HDFS on the geop VM

### ISSUE THREAD

**Issue by jwalgran** [WikiWatershed/model-my-watershed#10]
Rob requested that questions regarding this process be run through the mailing list. There are a few recent threads on the topic that may be useful.

https://groups.google.com/forum/#!searchin/geotrellis-user/ingest

Rob wrote an HDFS ingestion bash script HDFS ingestion: https://gist.github.com/lossyrob/59f8116b07d37f7f45c5

**Comment by mmcfarland** [comment]
Currently, we have to development rasters and are using the deployment S3 pipeline for storage and a local SJS for starting jobs.  Processing tasks are being recorded as [data-hub issues](https://github.com/azavea/azavea-data-hub/issues)
