### ISSUE TITLE
Increase timeout for geospatial analysis to support larger AoIs

### ISSUE THREAD

**Issue by arobbi7** [WikiWatershed/model-my-watershed#1000]
**We need to confirm this with Stroud**, but now that we have reduced the maximum allowed AoI to 1,000 km^2 we have precluded selection by most of our boundaries and many AoI's as a result. It makes it really hard not to hit the size limit while exploring AoIs in the current version of the app.  We should consider increasing timeout/allowable area, or potentially removing the larger boundary layers (HUC-8. for example) as a temporary measure while they are inactive.

**Comment by jamesmcclain** [comment]
Not to flog a deceased equine, but we still have these issues: https://github.com/WikiWatershed/mmw-geoprocessing/issues/5 and https://github.com/geotrellis/geotrellis/issues/1183.  (These are substantively the same, but the second one is more clearly written.)

It may be worthwhile to consider terminating the source of the problem.

**Comment by hectcastro** [comment]
> equine, adjective
>
> of, relating to, or affecting horses or other members of the horse family: equine infectious anemia.

**Comment by jamesmcclain** [comment]
I will start by doubling it.  Will change in response to feedback if need-be.
