### ISSUE TITLE
Evaluate dynamic watershed delineation

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1005]
https://github.com/nazmussazib/RapidWatersheDelineation

Has some python scripts that do watershed delineation based on artifacts produced for the DRB for this project.  We should meet with the TauDEM folks to get an orientation of this approach and come up with a plan to implement it in the web app.

**Comment by mmcfarland** [comment]
Here is a description of the datasets and the instructions on running

https://docs.google.com/document/d/1gXhR8SZNnGs4Q7c9hj0pD8CosMeBkVbtWJCgxKnsGu4/edit#

**Comment by lewfish** [comment]
How do we want to add https://github.com/nazmussazib/RapidWatersheDelineation/blob/master/Rapid_Watershed_Delineation.py as a dependency to MMW? Should we just copy the file to the MMW repo or do something more complicated so we can get upstream updates?

**Comment by mmcfarland** [comment]
Good question.  I'm anticipating not using the script as-is after our initial deployment of it, since it's written more for a desktop execution scenario than a web request one.  I think we should set up a new wikiwatershed repo, package it up and publish it just like we are for TR55, then just include it in the requirements.txt.  I anticipate a significant amount of rework on this feature, but I'd like to get a little confirmation about the completeness of it before forking.

**Comment by mmcfarland** [comment]
To clarify my previous comment, I think we'll be iterating on it after the initial #1031 deployment to the extent that it becomes a little more robust for our environment.

**Comment by lewfish** [comment]
Is the plan to make a new repo (analogous to TR55) sometime in the future, or should I actually do that for #1031?

**Comment by mmcfarland** [comment]
Yeah, let's do it from the get-go.

**Comment by lewfish** [comment]
> I anticipate a significant amount of rework on this feature, but I'd like to get a little confirmation about the completeness of it before forking.

So, we don't want to fork https://github.com/nazmussazib/RapidWatersheDelineation? We just want to copy and paste the files in it? Sorry, I think I'm confused by what you said above.

**Comment by mmcfarland** [comment]
Yeah, I imagine that our implementation will diverge enough that a true fork is not useful.  We also, I _think_ only care about the 1 RWD.py file, the others are all for data prep.  I say copy/paste.

**Comment by lewfish** [comment]
The full data set will take 8 days to download; the sub data set will take 6 hours at current download speeds.

**Comment by lewfish** [comment]
Superceded by #1055-#1059
