### ISSUE TITLE
Updates to observation popups for styling

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1020]
To align with the new designs for the observation popups:

* Sparkline of some recent values per measurement (not necessary)
* Historical Values button to launch the plot view
* Selection mechanism on plot view to cylce through measurements

**Comment by mmcfarland** [comment]
@jfrankl I might not be finishing the task myself, can you attach a screenshot of the popup and modal so whoever picks it up has a frame of reference?

**Comment by jfrankl** [comment]
Default view:

![image](https://cloud.githubusercontent.com/assets/1809908/11280333/8d9893f8-8ec3-11e5-88f9-a57244ff3768.png)

Show elevation on hover:

![image](https://cloud.githubusercontent.com/assets/1809908/11280340/95a36f28-8ec3-11e5-8a3d-e53ee8d0b9f4.png)

Show historical data in modal when clicking on "View historical data":

![image](https://cloud.githubusercontent.com/assets/1809908/11280353/a9ca3a54-8ec3-11e5-8053-cb5c8cfe511f.png)

**Comment by mmcfarland** [comment]
A WIP commit that moves toward this design:
https://github.com/WikiWatershed/model-my-watershed/commit/6bbc261a41b9e9cb1dd0287cd3472898a20e3771

Specifically, opening the modal immediately and then having the timeseries requests happen from there to support the measurement dropdown pictured above.
