### ISSUE TITLE
Compare view scenarios not showing in ITSI snapshot

### ISSUE THREAD

**Issue by arobbi7** [WikiWatershed/model-my-watershed#1024]
The snapshot works perfectly in compare view in Safari and Firefox, but on Chrome (Mac), only the first scenario renders:
![screen shot 2015-11-17 at 3 29 05 pm](https://cloud.githubusercontent.com/assets/12868342/11224242/f99f2b12-8d41-11e5-915b-57ca0b5b70cd.png)

**Comment by rajadain** [comment]
It's actually broken on all browsers. Was probably a fluke that it worked on Firefox and Safari earlier.
