### ISSUE TITLE
Deploy working version of Rapid Watershed Delineation

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1031]
Based on #1005, get the Rapid Watershed Delineation up and running in its current form on a `worker` instance.

* Provision with dependencies
* Add celery task to execute
* Return a polygon for a point click on the map

This will be the first iteration, we'll probably need to rework to minimize disk I/O by moving shapefiles to postgis, etc.

**Comment by lewfish** [comment]
Are there data files for the region where we want to do this type of query, or should we just use the data referenced in https://docs.google.com/document/d/1p2yWFANTI2de_j5E7rrxPD0Y_oWwIvNMTbBRllupHfo/edit# ?

**Comment by lewfish** [comment]
Superceded by #1055-#1059
