### ISSUE TITLE
Benchmark Job time on different instance types

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1033]
For a known and repeatable AoI, generate job length time averages on multiple EC2 instance types.

w/ @hectcastro

**Comment by hectcastro** [comment]
**t2.medium**

![mmw-t2-medium](https://cloud.githubusercontent.com/assets/43639/11542945/ff46a546-9907-11e5-9255-1d1c8b063aac.png)

**t2.large**

![mmw-t2-large](https://cloud.githubusercontent.com/assets/43639/11542944/fc0d20da-9907-11e5-9c8b-cb05b3af8ee2.png)

**m4.large**

![mmw-m4-large](https://cloud.githubusercontent.com/assets/43639/11542932/ed0302a8-9907-11e5-83a5-ab8056b54618.png)

**m4.xlarge**

![mmw-m4-xlarge](https://cloud.githubusercontent.com/assets/43639/11542935/f4a4a4b2-9907-11e5-9e7c-e014aa669ca7.png)

**Comment by lliss** [comment]
See https://github.com/WikiWatershed/model-my-watershed/blob/feature/modeling-metrics/curl_requests/analyze-metrics.sh for the actual API requests being run.

The tests correspond to AOI sizes of:
 * 1 Km sq
 * 60 Km sq
 * 512 Km sq
 * 2019 Km sq
 * 4130 Km sq
 * 8018 Km sq

Note that the 8018 Km sq job did not succeed in any of the runs.

**Comment by lliss** [comment]
Name | RAM | Compute Units | Cores | Notes
--------|--------|--------------------|----------|--------
T2 Medium | 4.0 GB | 2 units (Burstable) | 2 cores
T2 Large | 8.0 GB | 2 units (Burstable) | 2 cores
M4 Large | 8.0 GB | 6.5 units | 2 cores | Also improved networking over previous
M4 Extra Large | 16.0 GB | 13 units | 4 cores | Also improved networking over previous

**Comment by hectcastro** [comment]
**Job workflow**:

- API calls hit a Django application (start timer)
- Django application enqueues request
- Request pulled off queue by Celery worker
- Worker makes a Spark Job Server API call to kick off the job
- Once a job is successfully kicked off, that it also enqueues a follow-up job to check for results
- That job retries every second to see if the job ID inside of SJS is complete
- When SJS says something is complete, results are saved to the database (stop timer)
