### ISSUE TITLE
Update GMaps API Key domains

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1041]
`mmw-dev` & `mmw.azavea.com` are reporting:

```
Google Maps API warning: InvalidKey: 
https://developers.google.com/maps/documentation/javascript/error-messages
```

**Comment by caseypt** [comment]
It looks as if we aren't setting the key at all. On staging and production, the script include looks like this:

![screen shot 2016-01-26 at 9 54 15 am](https://cloud.githubusercontent.com/assets/1042475/12583898/fcf4b68a-c412-11e5-8168-ecf1437853a8.png)

**Comment by caseypt** [comment]
Could be a problem with this line: https://github.com/WikiWatershed/model-my-watershed/blob/6d8eee5fca771cc88762c2a86f861455b0d306e9/src/mmw/apps/core/templates/base.html#L51 or the settings file.

**Comment by ajrobbins** [comment]
Google maps API is no longer supporting keyless access: http://googlegeodevelopers.blogspot.com/2016/06/building-for-scale-updates-to-google.html. We should address this before the next release https://github.com/WikiWatershed/model-my-watershed/issues/1376

**Comment by hectcastro** [comment]
Some settings may need to be updated by those who have access to Google Maps API admin. Looks like we need to whitelist `staging.app.wikiwatershed.org` and `app.wikiwatershed.org` (MMW URLs too, or can we finally deprecate them?):

```
js:32 Google Maps API error: RefererNotAllowedMapError https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://staging.app.wikiwatershed.org/
```
