### ISSUE TITLE
Add soil visualization / overlays

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1042]
From gSSURGO:
- ~~hydrological soil group~~ (will be added with hydrogrp for model)
- available water holding capacity
- k-factor/soil erodibility

These should be available as painted tiles in "Overlays" tab of the layer selector.

**Comment by mmcfarland** [comment]
Water holding capacity details:
> The values contained within this field are in centimeters of water depth, and we will want to display them in inches (i.e., given value / 2.54). For display purposes, I would suggest using the following categories:
> 0 – 2 inches
> 2 – 4 inches
> 4 – 6 inches
> 6 inches

**Comment by ajrobbins** [comment]
The project team did not elect to move ahead with visualizing water holding capacity or k-factor.
