### ISSUE TITLE
Water Quality Compare should be by quality component

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1046]
Don't use a stacked bar chart for all 4 components of the water quality output, instead allow one component to be selected at a time and compare against all scenarios.

**Comment by lewfish** [comment]
I'm planning on adding another dropdown that will allow selecting by component. The first component will be selected by default. Should we also do this for runoff?

**Comment by mmcfarland** [comment]
No, let's hold off on this - just an enhancement at the moment.

**Comment by ajrobbins** [comment]
Stroud would like the three water quality components (TSS, Total Phosphorus, Total Nitrogen) separated into three graphs, each with its own axis.

**Comment by mmcfarland** [comment]
Compare view is being rewritten.
