### ISSUE TITLE
Chart gets vertically squished when screen is too narrow

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#1048]
There is a min-height attribute that prevents this squishing when the chart is on the right, but when the screen gets too narrow, the chart moves below the table and the min-height doesn't seem to protect against this happening.

![screen shot 2015-12-02 at 11 26 41 am 2](https://cloud.githubusercontent.com/assets/1896461/11536936/afc3b582-98e8-11e5-975b-c31de7b67b43.png)

**Comment by mmcfarland** [comment]
Made obsolete with #1145
