### ISSUE TITLE
Determine how sub-pixel area of interests or modifications behave

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1051]
What happens when:

* A modification is drawn that is entirely within a 30x30m grid cell.
* An AoI is drawn that has many intersections with partial grid cells, in a way that the edges are a high proportion of the total number of cells that "seem" included.

**Comment by lewfish** [comment]
I've confirmed that a tiny 'sub-pixel' modification has no effect on the results.

**Comment by lewfish** [comment]
A modification entirely within the a 30x30 cell seems to have no effect on the results. I tested this in the UI by finding an isolated grid cell, creating an AOI that fell within it, and then adding a modification that fell within in. Using the debugger, I saw that the results had the same numerical values before and after adding the modification.

In another experiment, I added a thin, diagonal modification that spanned several grid cells, but that never entirely covered any of the grid cells, and that modification did have an effect on the results. This is somewhat surprising and seems to indicate that modifications that span a pixel behave different than modifications that lie within a pixel.

I'm not entirely clear on what the second bullet point above is describing.

**Comment by SRGDamia1** [comment]
It definitely acts differently if you cross a cell vs. being within a cell.

I created a really skinny AoI to try to capture only one cell in width but several in height.  Then I drew striped modifications up and down it.  If I stayed within a cell, no changes appear.  But if I catch cell edges, then things change.  Based on the amounts of runoff it's producing, I think a whole cell is changing when you catch the edge.  I'll play with it to see if I can find a good AoI to test in.  I'm not sure which is the edge that you need to catch, though (N/S/E/W).
![cell edges](https://cloud.githubusercontent.com/assets/5374350/11601724/2ffd2de4-9aa3-11e5-8184-f207278332d9.jpg)

**Comment by mmcfarland** [comment]
@jamesmcclain being most familiar with the code, can you anticipate the behavior of a modification that is smaller than a grid cell, or only partially contained in a cell?

**Comment by jamesmcclain** [comment]
My understanding is that they way this works (if not literally, than effectively) is that the polygon is rasterized into bitmap using algorithm (I have no idea which one, but [here](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm) is an example of one), then only those pixels from the data raster which line up with "colored-in" pixels from the rasterized-polygon-raster are used.

If modifications are smaller than a grid cell, then I think the details of the rasterization algorithm will dictate exactly what results are obtained.  My guess would be that lower the percentage of a pixel occupied by the modification, the less likely it is to be scored (but once again, the exact behaviour is dependant in implementation details).

**Comment by jamesmcclain** [comment]
Actually the wiki article that I linked to is for a line algorithm, but the idea is similar.

**Comment by lossyrob** [comment]
@jamesmcclain @mmcfarland one thing to keep in mind is, if a polygon does not contain the center of the cell, it is not considered part of the rasterization. This is in line with the idea that raster values represent the value at the center of the cell. If this is the issue, this has come up before, and we may want to consider changing the algorithm to optionally include partial intersections as well, which would take a bit of work.

**Comment by SRGDamia1** [comment]
Each 30x30m cell will always a single BMP or landuse, right?  So if you draw a 1x1m polygon and happen to catch exactly the center of the cell the entire 30x30 cell will change, right?
