### ISSUE TITLE
Manually install RWD and dependencies and get it running

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#1057]
Get things running manually for the Delaware River basin on the worker VM. This is a prerequisite for the provisioning task.  See https://docs.google.com/document/d/1gXhR8SZNnGs4Q7c9hj0pD8CosMeBkVbtWJCgxKnsGu4/edit#
https://docs.google.com/document/d/1p2yWFANTI2de_j5E7rrxPD0Y_oWwIvNMTbBRllupHfo/edit#heading=h.p0oxezl5jbam

**Comment by kdeloach** [comment]
I created a simple shell bootstrap provisioning script and vagrant VM which includes the core dependencies for RWD this sprint. Wasn't able to make any more progress due to problems with my system.

**Comment by lewfish** [comment]
It's probably worth trying to get this to run with the smaller enogeo dataset referenced in the following Google doc because we know the program is supposed to work with that dataset (as opposed to Delaware basin, which might not have been tested).

https://docs.google.com/document/d/1p2yWFANTI2de_j5E7rrxPD0Y_oWwIvNMTbBRllupHfo/edit#heading=h.p0oxezl5jbam
