### ISSUE TITLE
Setup provisioning and run RWD from worker task

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#1059]
Building on the previous issues, automate the installation of the RWD dependencies and transfer of the data for development and production environments. Also call the RWD code from the task stub. Depending on how big the data files are, we may need to increase the size of the worker VM hard drive.

**Comment by mmcfarland** [comment]
Also consider that we can manually create a smaller geographic-subset of the areas included for the entire Delaware for our development machines and only load the entire set if we need to debug errors in area outside of that which we find on staging.

**Comment by kdeloach** [comment]
Researching different options for storing the rapid watershed data on AWS.

**Comment by kdeloach** [comment]
Didn't make any progress this sprint due to problems with my system.
