### ISSUE TITLE
Evaluate containerizing RWD module and dependencies 

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1066]

**Comment by mmcfarland** [comment]
Include travis publishing and ansible updates to launch the container in the worker.

see https://github.com/azavea/docker-spark-jobserver

**Comment by caseypt** [comment]
Repo: https://github.com/wikiwatershed/docker-rwd
Quay.io: https://quay.io/repository/wikiwatershed/rwd

Version 0.1.0 container image: `docker pull quay.io/wikiwatershed/rwd:0.1.0`
