### ISSUE TITLE
Make RWD geodata available to script

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1068]
This may include:

* S3QL
* EBS Volume Snapshot restored on Worker
* Configuring the RWD code to point to the correct mounted path

**Comment by kdeloach** [comment]
Uploaded all shapefiles to S3 (located at s3://rwd-data) and, although RWD executed successfully using s3ql, I wasn't able to figure out an easy way to bypass the one-machine-at-a-time mounting limitation. Now I'm creating a volume snapshot containing all the necessary shapefiles.
