### ISSUE TITLE
Smooth the polygon returned by RWD

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#1084]
The polygon returned by RWD can have many points in its representation, despite covering a small area. This means that a large payload has to be transferred to the client, and back to the server when the AOI is being analyzed. We should consider smoothing the polygon on the app or worker VM before sending it back to the client.

**Comment by mmcfarland** [comment]
This may be causing errors in the `/analyze` endpoint.  RWD polygons of a modest size function well, but large ones consistently fail.  I can generate a large watershed by clicking in the Schuylkill River, just below the Strawberry Mansion bridge.

We should try simplifying the polygon before its return from the RWD service.
