### ISSUE TITLE
Re-enable and update Stream display

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1087]
Ultimately, the NHDPlusv2 data set will be added to this tool, but in the interim it should be added back to the stage/prod environment.

* Have zoom dependent display, based on stream order.  May need to play around a bit to find a reasonable match. 
* I believe we only have a subset of the DRB 50 loaded, track down the entire dataset for DRB 50 and update the loading scripts.  Don't invest in 20 or 100 as they will not likely be included in the future.

**Comment by mmcfarland** [comment]
For areas outside the DRB, we should make this  feature inactive or at least display a message about the extents that the DRB 50 exists

**Comment by mmcfarland** [comment]
I would like to chat with @jfrankl about how this might look.  Stroud is interested in keeping this a slider, but I'm not sure that's best.  We may want to evaluate some options.

**Comment by ajrobbins** [comment]
Stroud is now interested in seeing this as another overlay in the layer selector, under a new "Stream Network" category. It would have two radio buttons: "None" and a button with text that changes along with the zoom-dependent display of NHDFlowline, NHD High Resolution, or Ultra High Resolution.

**Comment by mmcfarland** [comment]
Closing in favor of #1148
