### ISSUE TITLE
Switch off of backported kernel to version with AUFS fix

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1100]
When the issue below is resolved, and a more up-to-date kernel is available for Trusty, remove the backported kernel installation in https://github.com/WikiWatershed/model-my-watershed/pull/1097.

See:

- https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1533043
- https://bugzilla.kernel.org/show_bug.cgi?id=109971

**Comment by mmcfarland** [comment]
Completed in https://github.com/WikiWatershed/model-my-watershed/commit/816f93349362c059ba05438fab03c8451b462949
