### ISSUE TITLE
Runoff table squishes chart in compare mode

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#1120]
![screen shot 2016-01-31 at 5 42 00 pm](https://cloud.githubusercontent.com/assets/1042475/12705570/0abdda52-c842-11e5-9abb-157ddd29ac6b.png)

**Comment by mmcfarland** [comment]
Was this tested on `develop`?  If not, it may have been a incorrectly resolved merge conflict or in need of a rebase.  This bit of code should be currently preventing the table showing in runoff mode:  https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/tr55/runoff/views.js#L43-L49

This is from `develop`, currently:

![screenshot from 2016-02-01 08 23 27](https://cloud.githubusercontent.com/assets/1014341/12718533/2789bcde-c8bd-11e5-9220-f3533f8e8436.png)

**Comment by caseypt** [comment]
I thought I was on `develop`, but I must have been on a branch that wasn't up-to-date or I had a stale bundle. Just confirmed this is okay on `develop`.
