### ISSUE TITLE
Soil Group Colors for Micro Site Storm Model

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#1123]
Can the selection highlights for the soil groups in the micro site model be changed to match the soils legend, just like the land covers do?  This is *very low priority*, but if it is a very simple change, it would be nice to see.

**Comment by mmcfarland** [comment]
Yep, this is easy and was an oversight, we plan on keeping that useful link between apps - thanks for the reminder.
