### ISSUE TITLE
KeyError: u'area'

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1155]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/33/](https://rollbar.com/Azavea/MMW/items/33/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 214, in run_tr55
    area = piece['area']
KeyError: u'area'
```

**Comment by mmcfarland** [comment]
We may want to try and get contextual information about saved `projectId`, if available, for this exception to help debugging.

**Comment by mmcfarland** [comment]
I'm pretty sure this is caused by a BMP drawn over another BMP.  One BMP will be clipped, and I assume the `area` attribute is not preserved in the resulting product, causing this error.  The `area` attribute should be applied post-clipping to ensure this doesn't happen.

**Comment by mmcfarland** [comment]
Not all combinations of LU/BMP will cause this.  This sequence will reliably reproduce the issue:

1. Draw a Forest reclassification
2. Partially intersect that polygon with a Green Roof
