### ISSUE TITLE
Style RWD click-snap markers

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1164]
Currently we are using the default Leaflet markers to designate the point clicked and the point on the stream that is snapped to when a user delineates a watershed. 

![screen shot 2016-02-23 at 5 10 12 pm](https://cloud.githubusercontent.com/assets/12868342/13268455/93f3b86c-da50-11e5-9101-7e4067f09946.png)
Stroud would like different markers to be used (they think students are confused by the teardrop markers). They would like different colors for the two markers (probably blue for stream snapped point), or potentially two different types of markers for the two points.
@jfrankl

**Comment by ajrobbins** [comment]
Proposed styling from @jfrankl 
![mmw-marker](https://cloud.githubusercontent.com/assets/12868342/13652833/883fa4cc-e61c-11e5-8f67-34218aba7edf.png)

**Comment by kellyi** [comment]
For reference:

It looks like this can be done by using Leaflet's built-in `circleMarker` for the points rather than a standard `marker`, and we can style the `circleMarkers` with a dictionary of options. Here's the documentation explaining how:

http://leafletjs.com/reference.html#circlemarker

Looks like this may *not* require any new image assets.

**Comment by jfrankl** [comment]
I like that idea. I'd recommend using Leaflet's divIcon instead: http://leafletjs.com/reference.html#divicon

Advantages to divIcon:
- It will allow us to do this slightly more complicated marker style, which is effectively a circle with two borders
- My understanding is that circleMarkers would be easier to restyle from within Leaflet, like if we wanted a circle to change color under some condition, but we don't need to do that here.

These are some styles you could use to create the divIcons:

http://codepen.io/lknarf/pen/bpgorX

**Comment by kellyi** [comment]
Awesome, thanks! Got this working in principle on a little demo map:

<img width="463" alt="screen shot 2016-03-17 at 11 15 59 am" src="https://cloud.githubusercontent.com/assets/4165523/13850748/adbe77bc-ec31-11e5-95a9-13645146ae20.png">

**Comment by kellyi** [comment]
Note: we should possibly also change the marker dropped on the map on selecting 

Delineate Watershed > Stream Network

to match the marker for "Original Clicked Outlet Point"

**Comment by kellyi** [comment]
For reference: gist with code for creating the custom icons from GeoJSON:

https://gist.github.com/kellyi/f976efb3d9a76d725121
