### ISSUE TITLE
Point mmw.azavea.com to new URL

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1165]
Stroud is requesting that we shift to using `app.wikiwatershed.org/model`. They are anticipating that in the future another app would be added at `/monitor`, etc.

**Comment by hectcastro** [comment]
Are they set on this `/application-type` approach? I would prefer to steer us toward an approach where the application lives at the top level of a domain (like `model.wikiwatershed.org`). It would provide greater flexibility when trying to wrangle all of these applications together.

**Comment by SRGDamia1** [comment]
Anthony sees the future with many workflow paths (ie., /model) all nestled into a single application (ie., app.wikiwatershed.org).  As yet, there aren't any other workflow paths that we have funding for, though.  Maybe @aufdenkampe can explain it better.

**Comment by ajrobbins** [comment]
Agreed-upon URLs:
app.wikiwatershed.org - main MMW production application
app.wikiwatershed.org/micro - microsite

We need to keep the old domain up while Concord sets up redirects for ITSI.
