### ISSUE TITLE
Move get_job view to core.task_helpers

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#117]
The `get_job` view will be used in every Django app that has celery tasks. It's currently in `watershed_model` and `analyze`. It should be moved to `core.task_helpers` and each app should import the function into it's `view.py`, but I ran into problems with Django REST framework. 

Here is error I was getting: 

```
AssertionError at api/analyze/jobs/<long regex> Expected a Response,  HttpResponse or HttpStreamingResponse to be returned from the view, but received a <type 'NoneType'>
```

Also revisit regex that is used to make the URL. It could possibly be simpler. See https://github.com/azavea/model-my-watershed/pull/114#discussion_r29455333

**Comment by caseypt** [comment]
Update the `get_job` in `modeling/views` to use the one in `core.task_helpers`. Make sure to migrate over [this line](https://github.com/WikiWatershed/model-my-watershed/blob/a6bd72e39e6fe3a2f20d192ff04a721d1eac7613/src/mmw/apps/modeling/views.py#L49) to the core version.

**Comment by mmcfarland** [comment]
@caseypt Looks like there are still two `get_job`s defined (https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/views.py#L163).  Can you confirm that this issue should still be resolved?

**Comment by caseypt** [comment]
Yeah, though it might be worth trashing the `core/task_helpers` file since we consolidates analyze and modeling into one app, and there are no other apps interfacing with Celery.

**Comment by caseycesari** [comment]
Over time, this has proved to not be an issue.
