### ISSUE TITLE
Password reset page not working

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1178]
Clicking on the password reset link that MMW sends leads to a blank page:

https://mmw.azavea.com/accounts/password/reset/confirm/NjI5/
![screen shot 2016-03-10 at 11 58 02 am](https://cloud.githubusercontent.com/assets/12868342/13677351/9fac9dfe-e6b7-11e5-9ec6-96b88dc04b77.png)

**Comment by mmcfarland** [comment]
Shares a point with #1179
