### ISSUE TITLE
Changing Precipitation Slider has no effect in Internet Explorer

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1185]
To reproduce:

 1. Open the micro site in IE
 2. Move the precipitation slider

Actual result:

 * Nothing happens

Expected result:

 * The values of runoff, evapotranspiration, and infiltration should change.

Seen on:

 * IE 11 on Windows 7

**Comment by rajadain** [comment]
Also, there are wrapping issues, as noted by @ajrobbins on https://github.com/WikiWatershed/model-my-watershed/pull/1184#issuecomment-195036452:

> Wrapping issue is still occurring on smaller screens on IE 
> ![screen shot 2016-03-10 at 3 36 53 pm](https://cloud.githubusercontent.com/assets/12868342/13683687/09e7e64c-e6d6-11e5-9e2a-374920e28492.png)

**Comment by SRGDamia1** [comment]
If you change the precip with the slider, and then change the land cover or soil type, it will properly recalculate for the correct precip.
