### ISSUE TITLE
No warning or error message when analyze/model fail for very large watersheds

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#1187]
When returning a very large watershed with RWD, the analyze or model may fail without warning.  I suspect it's because the area is just too big, but it would be nice to get a warning message to that effect if it is the case.

Example:  at 40.402026103094194, -74.97677564620972 analyze succeeds and gives a watershed of 17,275 km2, but modeling fails.  This is a huge chunk of the Delaware; I was surprised the analysis worked at all.  (It was slow, ~40 seconds.)  Clicking just slightly downstream, the analysis fails.
![screenshot](https://cloud.githubusercontent.com/assets/5374350/13709982/bd5cc590-e784-11e5-9d6a-938cb7755ab8.jpg)

**Comment by SRGDamia1** [comment]
it also fails without warning if I select too large an area with the free-draw:
![screenshot](https://cloud.githubusercontent.com/assets/5374350/13710034/0c993152-e785-11e5-9ad1-8972689bebcf.jpg)
I do get an error if I try to draw an area bigger than 112700 km2.

**Comment by mmcfarland** [comment]
We should tweak the `MAX_AREA` to be more consistent with the current
infrastructure's ability.

https://github.com/WikiWatershed/model-my-watershed/blob/3c28a492ec4151cf2a94a1e3847837556bb59db5/src/mmw/js/src/draw/views.js#L23

**Comment by ajrobbins** [comment]
We've added front-end guards against too-large AoIs for analyze and model.
