### ISSUE TITLE
Layers Overlay radio buttons aren't inactive for incorrect zoom levels when loading site without allowing location detection

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#1189]
When loading the site with location detection disabled in Chrome, the initial map won't zoom in on a new location. In that case, the Layers pop up does not disable the radio buttons for overlays which should require a certain zoom level to be active. Selecting these buttons won't create the overlays, and they do deactivate the zoom's changed.

Here's what it looks like in Chrome:

![screen shot 2016-03-11 at 5 52 59 pm](https://cloud.githubusercontent.com/assets/4165523/13717909/dfcfae16-e7b2-11e5-8185-fdb23a8410c7.png)

Will investigate for other browsers.

**Comment by greytilde** [comment]
<img width="959" alt="model my watershed layers" src="https://cloud.githubusercontent.com/assets/8659605/13732510/e10e36ae-e95a-11e5-9c99-08403959f813.png">
I am unable to access the 'Overlays' and 'Observations' layers at any zoom level. Experienced on android mobile 12 Mar 2016 during Schuylkill River Congress demo, and experienced right now in Chrome, on my laptop. Only 'Basemap' list displays.  A URL appears in screen bottom left (https://app.wikiwatershed.org/#overlays-layer-list) but no change to the menu. See screen shot.

**Comment by kellyi** [comment]
Checked in Safari and the layers/zoom issue happens there as well. I believe the problem's that the app's using a `zoomToggle` method to activate and deactivate the layer options in response to zoom events, and since the event the method listens for to do its work is `map.on('zoomend',`..., the layer setup's getting skipped if no zoom event has happened.

For my reference, here's the relevant loc:

https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/utils.js#L29

One possible fix might be to have the `zoomToggle` method work both on `zoomend` or `load` events. For reference, here's leaflet's catalog of map events: http://leafletjs.com/reference.html#events

Will investigate the Android/Windows issue. It may be related to touch events referenced in a comment on #1190

**Comment by SRGDamia1** [comment]
Is this the same issues as #944?

**Comment by kellyi** [comment]
I think the issue referenced in @greytilde's comment above is the same one as #944 but it looks like the active/inactive layers bug has a different cause.

**Comment by ajrobbins** [comment]
Good catch, @SRGDamia1. We'll continue to track @greytilde's issue on #944 - we know there are a bunch of outstanding issues with Windows touch screen devices (see #649). We'll use this issue to track the layers/zoom problem that @kellyi initially identified.

**Comment by kellyi** [comment]
@mmcfarland Assigned to you for now, but do feel free to reassign to someone else.

**Comment by kellyi** [comment]
Nevermind -- I meant to assign the PR.
