### ISSUE TITLE
Ingest MapShed slope dataset

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1191]
Support Tyler D in creating/processing slope dataset for Mapshed, and ingest into GT Azavea datahub. Details:
- Extent: national (lower 48)
- Resolution: 30 meters
- Data: Gridded percent slope derived from DEM
- D8 flow direction, not D-infinity
The output of ArcMap's "calculate slope" tool is sufficient for this. It's also possible that a national gridded % slope dataset exists already - hopefully Tyler can point us to this if it does exist.

**Comment by mmcfarland** [comment]
@ajrobbins and @TDahlberg produced a 0-100 % slope raster set.  Currently double checking the values match expectations (`0 <-> 100`vs `-100 <-> 100`)
![screenshot from 2016-03-31 16 49 16](https://cloud.githubusercontent.com/assets/1014341/14190724/35fd0644-f762-11e5-9bf0-3c0c7d77443d.png)

**Comment by ajrobbins** [comment]
Update: the dataset was in degrees, not % slope, and needs to be converted to percent.

**Comment by ajrobbins** [comment]
New raster, converted to percent, is ready for ingest into azavea-datahub
