### ISSUE TITLE
Enable DRB stream visualization

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1195]
Upload TauDEM stream data for DRB (TauDEM 50). We've uploaded some data for this, but are not sure if its for the entire DRB or just a subset. We want to visualize this only when the user is viewing the DRB on the map, so there should be two radio buttons in the Overlays tab of the layer selector, one for NHD+ and one for TauDEM in the DRB (TauDEM would be inactive unless in the DRB).

**Comment by mmcfarland** [comment]
One idea is to add something similar to the zoomLevel attribute for layers, which is "extent".  If the extent of the map window in entirely contained in the DRB shape (simplified & local), it could be enabled and disabled otherwise (and national disabled).

**Comment by mmcfarland** [comment]
Some information from https://github.com/WikiWatershed/model-my-watershed/issues/764 may be useful.
