### ISSUE TITLE
Create a batch job to generate static TMS tile sets in S3 from source rasters

### ISSUE THREAD

**Issue by jwalgran** [WikiWatershed/model-my-watershed#12]
We have decided that we do not need any runtime customization when we display land cover or soil rasters on the map, so we can save on redundant processing and simplify the web app by generating static tile sets. 

Added to the skeleton project created in #11

The input should be a raster, and extent, a set of zoom levels to render, and an S3 bucket+directory destination. The output should be a set of PNGs like ``soils/z/x/y.png``

**Comment by mmcfarland** [comment]
Using [data-hub issues](https://github.com/azavea/azavea-data-hub/issues) to track tiling requests.
