### ISSUE TITLE
Add "reset" button to clear map workspace

### ISSUE THREAD

**Issue by ctaylo37** [WikiWatershed/model-my-watershed#120]
![image](https://cloud.githubusercontent.com/assets/5880793/7435280/3fa1c1ee-f010-11e4-8f7d-7ccd81cf2008.png)

Users should have a way to clear everything and start over.  This is also useful for when you return home from analyze and still have a shape present and need to define a new area.

**Comment by caseypt** [comment]
Implemented in https://github.com/WikiWatershed/model-my-watershed/pull/333
