### ISSUE TITLE
Upgrade mmw-geoprocessing to 1.0.0

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1207]
Following up from https://github.com/WikiWatershed/mmw-geoprocessing/issues/22

 * [x] Upgrade GeoTrellis in mmw-geoprocessing from RC2 to 0.10.0
 * [x] Release `mmw-geoprocessing-assembly-1.0.0.jar`
 * [x] Upgrade [dependency in Ansible](https://github.com/WikiWatershed/model-my-watershed/blob/077df1bebf74fd0bcfb0044350caefa120cdc58d/deployment/ansible/group_vars/all#L47)
 * [x] Upgrade metadata to be in new format in S3
 * [x] Update layer names (done here: https://github.com/WikiWatershed/model-my-watershed/tree/feature/hmc/geotrellis-rc1)
 * [ ] Deploy MMW
 * [ ] Delete old metadata files once they are not being used by anything else (or rename and keep around for posterity)

**Comment by mmcfarland** [comment]
This is now unblocked: https://github.com/geotrellis/geotrellis/releases/tag/v0.10.0
