### ISSUE TITLE
Move forward to Analyze

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#121]
After selecting an AoI, you can hit "back" to go to the draw screen but we don't (and shouldn't) delete the shape.  We should however allow you to go "forward" to the analyze screen.  Maybe a little popup or tooltip on the shape?  Typically the analyze window is activated by completing a drawing.
![screenshot from 2015-05-01 15 10 43](https://cloud.githubusercontent.com/assets/1014341/7435797/068aa06a-f015-11e4-9dce-95c37d580731.png)

**Comment by caseypt** [comment]
Now that we are selecting predrawn AoIs from a map layer, should analyze always be kicked off from an "Analyze" button in the feature popup?
