### ISSUE TITLE
Release 1.12

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1211]
Release candidate on staging by 4/5
Testing: 4/5-4/7
Release: 4/7

To include:
- [x] DRB stream visualization https://github.com/WikiWatershed/model-my-watershed/pull/1204
- [x] NHD+ stream visualization https://github.com/WikiWatershed/model-my-watershed/pull/1197
- [x] RWD click-snap point styling https://github.com/WikiWatershed/model-my-watershed/pull/1203
- [x] Error message when attempting RWD outside of DRB https://github.com/WikiWatershed/model-my-watershed/pull/1206
- [x] [Potentially] links pointing to wikiwatershed.org - waiting on more details from Stroud https://github.com/WikiWatershed/model-my-watershed/pull/1220

**Comment by hectcastro** [comment]
Just wanted to add a note here that this process needs to include updates to the `TileDeliveryNetwork` for some newly added tile cache related resources.

**Comment by ajrobbins** [comment]
Stroud provided the links: https://github.com/WikiWatershed/model-my-watershed/issues/1210

**Comment by caseypt** [comment]
A [release branch](https://github.com/WikiWatershed/model-my-watershed/tree/release/1.12.0) has been created and the staging site is up-to-date.

**Comment by hectcastro** [comment]
This is now live. Keeping the issue open until the tag gets updated with release notes.

**Comment by ajrobbins** [comment]
Release notes are up: https://github.com/WikiWatershed/model-my-watershed/releases/tag/1.12.0
