### ISSUE TITLE
Evaluate GWN dataset

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1213]
Groundwater nitrogen cell values are based on a combination of the NLCD map and the "Porous" attribute field in the surficial geology shapefile: smb://fileshare.internal.azavea.com/projects/Stroud_ModelMyWatershed/data/MapShed/surficial_Materials The GWN grid is a depiction of groundwater N on a cell-by-cell basis for areas around the country. The values range from less than 1 (e.g., forested areas) to greater than 8 (mostly in ag areas). Like with the soil P value, you only need to find the mean value for a watershed and write it to the *.gms input file (in this case, right after the soil P value on line 37).

Need to evaluate whether we should precompute this or calculate it on the fly with a lookup table, like we plan to do for Soil Phosphorus.

**Comment by ajrobbins** [comment]
Barry found a national GWN raster at 1km resolution: smb://fileshare.internal.azavea.com/projects/Stroud_ModelMyWatershed/data/MapShed/natl_gwn/natl_gwn

**Comment by mmcfarland** [comment]
We have a 1000m grid for national ground water nitrogen, which I've converted to TIFF.  Since gwlf expects only mean GWN for the entire area of interest, and not cell pair comparisons, we don't have to align the cell size with our other data sets - making this a much smaller raster (~50mb uncompressed).  We'll want to align it to the same extent and ingest to RDD.

@rajadain - keep a lookout for mean GWN for a watershed and let me know if that description does not align with the actual code.

**Comment by mmcfarland** [comment]
![screenshot from 2016-03-24 17 10 16](https://cloud.githubusercontent.com/assets/1014341/14031468/5a560fba-f1e3-11e5-8620-94cb53a02c2c.png)

**Comment by mmcfarland** [comment]
The tiff is uploaded and needs its extent aligned and reprojected to EPSG:5070 @ajrobbins

**Comment by rajadain** [comment]
The Groundwater Nitrogen calculation seems to be a weighted average: 
[CalcGWN.vb.txt](https://github.com/WikiWatershed/model-my-watershed/files/189642/CalcGWN.vb.txt)

Essentially the algorithm is:

```python
def calc_gwn(polygon, gwn_grid):
    sum_gwn = []   # Sum of values grouped by flooring to nearest integer
    count_gwn = [] # Number of values in each group
    wavg_gwn = 0   # Weighted average groundwater nitrogen

    for cell in gwn_grid:
        i = floor(cell)
        sum_gwn[i] += cell
        count_gwn[i] += 1

    for i in sum_gwn:
        weight = ((gwn_grid.cellsize ** 2) * count_gwn[i]) / polygon.area
        wavg_gwn += (sum_gwn[i] / count_gwn[i]) * weight

    return wavg_gwn
```

It seems like the `weight` calculation assumes that the grid cellsize is the same as the polygon's, but I'm not 100% sure if that assumption applies.

**Comment by mmcfarland** [comment]
When I first read the description of the dataset, I also thought that a weighted average was more appropriate, but then assumed that the mean would essentially weight repeated cells more heavily just by the nature of their increased presence.  My concern is that with a GWN grid of 1000m, we'll have some dissonance with our other datasets - or run into "sub pixel" problems where a watershed does not intersect with the center of the cell and we lose 1000m<sup>2</sup> of data.  We may need to discuss with both Barry and GT.  We can also resample this at 30m, but it'll balloon the size the raster without adding any additional information.

**Comment by rajadain** [comment]
If we can do an on-the-fly intersection of two layers with different resolutions in GeoTrellis, we may not have to resample. The weighted average may be less authentic because of the lower resolution, but should still work. I'm not sure if this is possible though.

**Comment by mmcfarland** [comment]
What's the other layer to intersect?  It looks like it only intersects with a polygon (vector) to get a list of cells to iterate, and the just uses the total polygon area in the weight.

**Comment by rajadain** [comment]
Oh right! In that case I think we should be good to go

**Comment by rajadain** [comment]
Or wait, can GT do partial intersections? I guess that's what you meant by the sub-pixel problem if not intersecting with the center of the cell

**Comment by mmcfarland** [comment]
Yeah, exactly.  If the intersect polygon does not hit the center of (this rather large cell), I don't believe it is counted.  That leaves a lot of potential data loss for small AoIs and all along the border of any sized AoI.

**Comment by rajadain** [comment]
Seems like we can do partial intersections without increasing the resolution, thanks to a feature @jamesmcclain added to GT:

https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/rasterize/RasterizerOptions.scala#L15
https://github.com/geotrellis/geotrellis/blob/03367dad7b86f7847aa5f5a9a6cc4b63acd457a8/raster/src/main/scala/geotrellis/raster/PixelSampleType.scala#L14-L18

**Comment by mmcfarland** [comment]
Great stuff, any details on how it handles a non-center intersection?

**Comment by rajadain** [comment]
The technique GeoTrellis folks suggested was to make a vector Extent from each cell of the raster layer, and see how it intersects with the polygon. For partial intersections, we would divide the area intersecting with the total area of a cell, thus getting a percent value, which could be used as the weight.

```scala
// Suggested by @lossyrob

val rasterExtent: RasterExtent = ???
val (cw, ch) = (rasterExtent.cellwidth, rasterExtent.cellheight)
val tile: Tile = ??? // The 1 km one
val (col, row) = ??? // From Rasterizer
​
val (x, y) = rasterExtent.gridToMap(col, row)
val e = Extent(x - cw/2, y - ch/2, x + cw/2, y + cw/2)
val area = 	
	if(polygon.contains(e)) {
		e.intersection(polygon).as[Polygon].get.area
	} else {
		cw * ch
	}
```

According to them, this on-the-fly calculation should be fast enough for ~500 tiles, and since the average watershed is around 250 - 300 sq km this should be okay. However, they are confident we could optimize this code more if needed.

Resampling the dataset to a higher resolution not only has the cost of space the raster takes, but also the increased number of tiles that would have to be fetched, which would be a considerable burden.

**Comment by mmcfarland** [comment]
Yeah, I would really prefer to keep the raster at it's current resolution.  The new rasterizer stuff looks like a good option.

**Comment by mmcfarland** [comment]
So it looks like the next step for this is ingesting an extent aligned EPSG:5070 GWN raster into the data-hub.

**Comment by ajrobbins** [comment]
Can the extent be aligned via the ingest or does that need to be pre-done?

**Comment by mmcfarland** [comment]
Projection and extent alignment can be done during ingest.
