### ISSUE TITLE
Evaluate AreaD8 Method for calculating LS

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1214]
MapShed uses the AreaD8 method to calculate LS when "Flow Accumulation" is selected as the LS Method. The alternative in the UI, "Stream Density", is an outdated method for use with lower resolution data. From Dr. Evans:

> For estimating LS, our "Flow Accumulation" routine described below is the preferred option. The "stream density" method is an older approach that we used to use with lower-resolution DEM data before we found the other routine in MapWindow's TauDEM tools. If you can implement the "flow accumulation" method, that would be best.

The code that deals triggers this calculation is at `Class1.vb:3742-3750`:

```vb
' If Flow Accumulation is selected as the LS Method, derive D8 (deterministic eight-node) grids and LS using Area D8 method
...
If LSMethod = 1 Then ' Flow Accumulation option selected
    ...
    DeriveD8Grids(DEMClipPath, PitFilPath, D8Path, AreaD8Path, SlopeD8Path) ' Derive D8 (deterministic eight-node) grids
    ...
    LuAD8Analysis(AreaD8Path, LuClipPath, SlopeD8Path) ' Derive LS grid with the Area D8 method
End If
```

The two methods themselves are attached: [AreaD8Methods.vb.txt](https://github.com/WikiWatershed/model-my-watershed/files/190149/AreaD8Methods.vb.txt) (`Class1.vb:7286-7778`)

The first one, `DeriveD8Grids`, uses TauDEM and MapWindow functions to perform the D8 grid derivation `Class1.vb:7317-7324`:

```vb
' Do the D8 analysis to obtain accumulted flow area (AreaD8)
Dim TkCall As New TKTAUDEMLib.TauDEM ' Initialize Callback for D8 and AreaD8 function

' - Create the D8 raster based on the pit-filled dem and the slope of the pit-filled dem
MapWinGeoProc.Hydrology.D8(PtFillPath, D8Path, SD8Path, TkCall.Callback)

' - Create the Area D8 raster based on the D8 raster
MapWinGeoProc.Hydrology.AreaD8(D8Path, "", AD8Path, False, True, TkCall.Callback)
```

Evaluate if this would best be implemented in Python or Scala, and develop a strategy for the implementation.

**Comment by mmcfarland** [comment]
Looks like if we create a 30m pit-filled D8 Flow Accumulation grid as a dataset, we can bypass `DeriveD8Grids` altogether.   The analysis appears to use FA, Slope and LU grids merged, and does some arithmetic based on LU codes.

@ajrobbins Looks like we'll need that dataset after all.

**Comment by ajrobbins** [comment]
I'll talk to Tyler about deriving a pit-filled flow accumulation grid from the slope raster he is working on.

**Comment by ajrobbins** [comment]
To clarify: we need flow direction or flow accumulation? Both? http://help.arcgis.com/En/Arcgisdesktop/10.0/Help/index.html#/Flow_Direction/009z00000052000000/ vs. http://help.arcgis.com/En/Arcgisdesktop/10.0/Help/index.html#//009z00000051000000.htm

**Comment by rajadain** [comment]
Flow Accumulation only, I think, for this effort. Not sure if Flow Direction would be useful elsewhere.

**Comment by ajrobbins** [comment]
I believe we need Flow Direction in order to do Flow Accumulation. We'll also have to fill the sinks in the DEM, which will take a bunch of time to process.

**Comment by ajrobbins** [comment]
We will use the AreaD8/Flow Accumulation method within the DRB, using the TauDEM stream data. We will use the Stream Density method outside of the DRB.

**Comment by rajadain** [comment]
We now know when to use each method. #1231 exists to ingest Flow Accumulation dataset.
