### ISSUE TITLE
Handle new projects during ITSI workflow

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#1222]
PR #1219 added the ability to select the model package when creating new projects. According to @rajadain (see quoted text below), this behavior is incorrect when in ITSI mode.

For ITSI, passing "Model" should _not_ create a new project, but delete and replace the existing one. This may be complex and warrant a card of its own. I think the behavior should be:

 * If the user has created a project using Model A, goes back to Analyze, and then clicks on Model A again, they should return to existing project.
 * If the user has created a project using Model A, goes back to Analyze, and then clicks on Model B, they should be given a warning that this will kill their existing work, which is in Model A, and they should choose between preserving the project and proceeding with Model A, or killing it and proceeding with Model B.
 * If the user has created a project using Model A, goes back to Analyze, goes back to Draw, and changes their AoI, then they should be given a warning that their project will be killed, and if they agree, we kill the project and let them proceed with whichever model they like.

**Comment by lewfish** [comment]
I think we agreed to the following: in both ITSI and non-ITSI mode, there will a dropdown to create a new model with a specific model package, and if there is an existing project, there will be a (new) button to go back to the modeling view for that project. Is there any other behavior we should implement?

**Comment by lewfish** [comment]
It sounds like we want to do the above with the following additions/modifications: 
* When the user is in the modeling view and then goes back to the main map and tries to hit reset, we should prompt them about clearing the current project regardless of the mode and whether they are logged in (currently it only does this in ITSI mode)
* When the user clicks the new model dropdown, a new project will be created when in non-ITSI mode, and the current project will simply be cleared (scenarios deleted, etc) when in ITSI mode.

**Comment by lewfish** [comment]
> there will be a (new) button to go back to the modeling view for that project

I think we should just implement this using the browser forward button. I also don't know why we have any back buttons in the app... why not just let people use the browser back button?

**Comment by rajadain** [comment]
The back button is useful because when you come from Model to Analyze, the browser back may take you to Model, instead of Draw.

Perhaps instead of Back, it should say Draw.

**Comment by lewfish** [comment]
I can change the button to say Draw. I've decided that the original scheme you came up with, in the first comment in this thread, is going to be easier to implement, so I'm going to do that.
