### ISSUE TITLE
Ingest Flow Accumulation dataset

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1231]
TauDem dataset for use in calculating LS in the DRB - this needs to be ingested into azavea-data-hub

**Comment by mmcfarland** [comment]
Acquired tif here http://hydrology.usu.edu/mmw2/Projected/DelDem4ad8.zip  

Currently in 10x10 resolution, need to figure out best resampling method to get to 30x30.

**Comment by mmcfarland** [comment]
Nazmus is regenerating the data at 30m sq, won't be ready for a few days.

**Comment by mmcfarland** [comment]
30m data will not be sufficient so we're going to use stream density _nationally_ for LS values, but using DRB streams as appropriate.  //cc @rajadain

**Comment by mmcfarland** [comment]
Closing and removing from sprint, should not have been included due to above comment.
