### ISSUE TITLE
Change RWD placement marker

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1234]
We have received feedback that the Leaflet marker with the crosshair underneath that is used to drop a point for RWD is still confusing some folks. Just a crosshair (bolder) would be better.
![screen shot 2016-04-08 at 1 45 22 pm](https://cloud.githubusercontent.com/assets/12868342/14392613/371256d6-fd90-11e5-8029-f1455e18ef59.png)

**Comment by mmcfarland** [comment]
For clarification, the existing crosshair (not pictured in screenshot) without the pin.

**Comment by ajrobbins** [comment]
Actually, the Leaflet marker is helpful in explaining that RWD is like "dropping a raindrop" in a certain place - noticed this in an NSF classroom visit. I don't think this is an issue anymore.
