### ISSUE TITLE
Map attribution cut off on "satellite with roads" and "terrain" basemaps

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1238]
Observed on Chrome, Firefox, and Safari. 

The top of an additional line of attribution appears to be visible, so potentially there is a wrapping issue.
![screen shot 2016-04-11 at 1 33 11 pm](https://cloud.githubusercontent.com/assets/12868342/14436327/27e28ad0-ffea-11e5-8cb1-4f9d2165c63f.png)

**Comment by caseypt** [comment]
Shares a point with #1237
