### ISSUE TITLE
Model dropdown button is not contained in tab

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#1243]
When the "Model" button was converted to a dropdown button (in https://github.com/WikiWatershed/model-my-watershed/pull/1219), it was moved outside of the tab container. This results in the UI looking a little off (new on the left, old on the right).

![image](https://cloud.githubusercontent.com/assets/1042475/14613842/48fe611c-056c-11e6-82f1-b910ea8ed12d.png)

Unfortunately, this is not a simple fix. If you move the dropdown button inside the `a` tag in the tab, it is rendered outside of the tab in the browser. Other slight changes to get the dropdown in the tab prevent the dropdown items from showing up.

**Comment by ajrobbins** [comment]
Addressed with UI revamp; this design has completely changed:
![screen shot 2017-08-18 at 4 06 53 pm](https://user-images.githubusercontent.com/12868342/29475791-4ad55930-842f-11e7-9038-2585f13d9c24.png)
