### ISSUE TITLE
Improve styling of Analyze tabs

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1256]
The styling of the Draw and Model buttons look really out of place on the Analyze sidebar. We may want to consider creating a more consistent style.

![image](https://cloud.githubusercontent.com/assets/43062/14870510/c15f8206-0ca8-11e6-9907-ff236c5fa4bd.png)

Something like this?

![image](https://cloud.githubusercontent.com/assets/43062/14870580/310242c4-0ca9-11e6-8abf-c4dc950701aa.png)

**Comment by lewfish** [comment]
Looks like a duplicate of https://github.com/WikiWatershed/model-my-watershed/issues/1243

**Comment by kdeloach** [comment]
Duplicate of #1243
