### ISSUE TITLE
No navigation back to select AoI screen from analysis screen

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#1262]
After you've selected an area of interest, you're immediately moved to the analyze screen and there is now way to navigate back to re-select the area of interest other than browser back buttons.  Using the back button on the browser will not work if you enter analyze, then enter model and then use the onscreen error to return to the analyze page.  In that case the browser back button will try to return you to the /project page and the load fails.
![capture](https://cloud.githubusercontent.com/assets/5374350/14931082/c8a7462c-0e36-11e6-967d-d243934361ca.PNG)

Even if you do successfully use the browser back button, you end up back at the AoI screen and then have to hit the reset button before you can select anything new.

I think it would make more sense to have some sort of AoI reset button within the analysis (and model) pages so the user can quickly and easily get all the way back to the beginning if they are unhappy with their original AoI.

**Comment by rajadain** [comment]
We now have a "Draw" button which can take the user back to the AoI selection stage

![image](https://cloud.githubusercontent.com/assets/1430060/15755016/e8bc2cc8-28c8-11e6-97d1-ca57f6857644.png)

Where they can reset and choose another AoI or go forward to Analyze with the same one selected

![image](https://cloud.githubusercontent.com/assets/1430060/15754997/d81f5afc-28c8-11e6-9f6d-be83c8c0b4f8.png)

In addition, if you start Drawing or select another AoI, it will reset automatically before selecting the new one, without having to click Reset in between.

**Comment by SRGDamia1** [comment]
I think this can be closed.
