### ISSUE TITLE
Prevent Drawing Very Small AoIs

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1268]
See https://github.com/WikiWatershed/model-my-watershed/pull/1265#issuecomment-216648897

Similar to how we have a warning to users when the AoI is too big, similarly we may consider having a warning for AoIs that are too small. Investigate how small  is too small and implement that guard.

**Comment by kellyi** [comment]
Wonder if it's worth also reducing the guard against very large aois, too. I think there's already a guard in place against that, but if we now have a sense of what area values are too large to use to get results from the model before Celery times out, we can make the other guard more specific.

Re: the small aoi guard: the issue I saw was a divide by zero error, so I imagine there's a way to check what's the lower bound for an aoi that would result in that error happening elsewhere.
