### ISSUE TITLE
MapShed: Calculate LS

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1277]
LS can be calculated using NLCD, Slope, and Stream Density. A finer method may involve using Flow Accumulation, but unfortunately we don't have a Flow Accumulation raster at 30m resolution.

Use DRB streams if the polygon is wholly contained within the DRB, else use NHD streams.

See if this geoprocessing can be combined with any in #1272 or #1274 to improve performance.

**Comment by rajadain** [comment]
To calculate Average Slope over an entire area, use:

```json
{
  "input": {
    "polygon": [],
    "targetRaster": "us-percent-slope-30m-epsg5070",
    "rasterCRS": "ConusAlbers",
    "polygonCRS": "LatLng",
    "operationType": "RasterAverage",
    "zoom": 0
  }
}
```

**Comment by jtarricone** [comment]
Won't the average slope be calculated as part of #1289 ?

**Comment by rajadain** [comment]
You're right, it should.

**Comment by jtarricone** [comment]
Coolio, I'm at a decent stopping point until that gets merged. The LS factor calculation should be in place, so any additional work after #1289  should be minimal, barring math errors of course.

**Comment by rajadain** [comment]
This should now be unblocked

**Comment by rajadain** [comment]
It'd be great to get a PR for this up soon so I can rebase #1305 over it
