### ISSUE TITLE
Add BMPs for GWLF-E

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#1278]
Add UI for adding BMPs for GWLF-E. The existing BMP menus should be modified from TR55 so that clicking a BMP leads to another dialog that allows the user to enter the size. The Draw option should be disabled.

<img width="335" alt="screen shot 2016-05-05 at 1 39 11 pm" src="https://cloud.githubusercontent.com/assets/1896461/15051617/8da8e28e-12c7-11e6-911f-3276b939e4f4.png">

<img width="344" alt="screen shot 2016-05-05 at 1 39 17 pm" src="https://cloud.githubusercontent.com/assets/1896461/15051615/8cae0940-12c7-11e6-9973-e3cb7c4634e1.png">

**Comment by ajrobbins** [comment]
New BMP help text is here: https://docs.google.com/document/d/1aGer7yAqX1HjmVqiFY4yaWfOvJrJi0ckzefOArO7JqA/edit
