### ISSUE TITLE
Change "Turf Grass" to "Developed, Open Space"

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1295]
Change the tooltip for the "Turf Grass" land use type on the microsite to "Developed, Open Space"

![screen shot 2016-05-11 at 11 48 10 am](https://cloud.githubusercontent.com/assets/12868342/15187262/714934d0-176e-11e6-8a46-87ac29f609b5.png)

**Comment by mmcfarland** [comment]
Likewise on the map app.

![screenshot from 2016-05-11 11 54 59](https://cloud.githubusercontent.com/assets/1014341/15187479/4524a7b2-176f-11e6-884e-9bc9d3f914a0.png)

**Comment by SRGDamia1** [comment]
Why do you want to make this change?  @aufdenkampe, I thought we wanted to keep the NLCD official names.

**Comment by ajrobbins** [comment]
@SRGDamia1 I had this the wrong way initially; we want to change references to "Turf Grass" to "Developed, Open Space", correct?

**Comment by SRGDamia1** [comment]
@ajrobbins: yes, that's right.  Sorry, I read the original title and was confused.
