### ISSUE TITLE
Improve style of BMP UI

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#1315]
Some issues include verbiage, layout, and the choice of the fill patterns.

**Comment by caseypt** [comment]
Currently there are some spacing issues for modifications with long names:

![image](https://cloud.githubusercontent.com/assets/1042475/15367209/0525b692-1cf6-11e6-8249-ff880300cbf7.png)

**Comment by mmcfarland** [comment]
We should consider a sub header for Urban | Rural to allow for some visual separation.

**Comment by lewfish** [comment]
> We should consider a sub header for Urban | Rural to allow for some visual separation.

You mean to organize the thumbnails into two groups, with a header on top of each?

**Comment by lewfish** [comment]
If I do that then I won't need to find different fill patterns for the urban versions of the BMP.
