### ISSUE TITLE
Connect GWLF-E BMP UI to ScenarioModel

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#1316]
Currently, clicking Convert in the BMP UI just prints the variables that need to be added to the Mapshed data model. The Mapshed data model is also a mock object. We need to:
* add a new GwlfeModificationModel and modify the ScenarioModel (esp. the parse method) to handle it 
* (maybe) modify the backend to handle these modifications
* get the UI to add the modification to the ScenarioModel
* get the real Mapshed data model from the ProjectModel
* not show the 'Conservation Practices' dropdown until the data model comes back from the server

**Comment by rajadain** [comment]
Once the MapShed run completes, the output is saved in ProjectModel's `gis_data` field. That data can be used to configure the various modification UIs.
