### ISSUE TITLE
Install GWLF-E from PyPI

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1321]
We should link MMW to the latest release of gwlf-e just like we do for tr55.

Ref: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/requirements/base.txt#L16

**Comment by kdeloach** [comment]
The latest release is 0.2.0.

**Comment by rajadain** [comment]
What is the package name in PyPI? I searched for `gwlf`, `gwlfe`, `gwlf-e`, and `gwlf_e` and didn't find anything.

**Comment by rajadain** [comment]
Ah nevermind, found it: https://pypi.python.org/pypi/gwlf-e/

Their search index probably hasn't updated, or it may have trouble searching for names with hyphens in them. Searching for "gwlf-e" doesn't result in our package.
