### ISSUE TITLE
MapShed Workflow: UI Polish

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1323]
- [x] Add spinner / progressbar for when gathering MapShed data
- [x] Add notification / instructions for if it fails

**Comment by lewfish** [comment]
- [ ] Show x% of length or area in manual entry UI
- [ ] Disable thumbnails for BMPs that can't really be applied to the AOI

**Comment by rajadain** [comment]
I would prefer to move the above two to #1298, which has more points and few work items remaining.

**Comment by lewfish** [comment]
Ok, I moved them to #1298
