### ISSUE TITLE
MapShed: Use DRB if possible

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1335]
Most stream related methods in MapShed have a `drb` parameter, which when set to true uses DRB streams instead of NHD streams. Add functionality that tests whether or not the area of interest is completely contained within the DRB region, and if so, use DRB instead of NHD.

**Comment by rajadain** [comment]
There is _one_ case where we should always use NHD. I can't remember which one it is, but @ajrobbins should be able to track it down.

**Comment by mmcfarland** [comment]
I believe it is in the stream erosion routine?

**Comment by rajadain** [comment]
The Erosion Coefficient is looked up from the database. "Streambank Erosion" are treated as static values, according to the [GMS File Key](https://docs.google.com/spreadsheets/d/12hsklRHwl6sNum0xPk6d5Cw6ONDA3X6BR5-Pc-NwJBc/edit#gid=0). Not sure where this would fit in.

**Comment by ajrobbins** [comment]
BME says to use NHD streams for the "Stream Bank Erosion routine". If it looks like the routine uses static values, we should check with him to confirm.

**Comment by rajadain** [comment]
Just spoke with BME on the phone. He said to always use the low-res (NHD) streams for everything **except** the LS Factor. The LS Factor should use the DRB stream length if available, else it should use NHD. For everything else, such as `StreamLength`, `AgLength`, `UrbLength`, `n42`, `n42b`, `n46e`, `n46f`, etc we should _always_ use NHD.

**Comment by jamesmcclain** [comment]
That should unburden the geoprocessing service, somewhat.

**Comment by rajadain** [comment]
Alas! All those tests against the DRB dataset were for naught. May I learn about overengineering and too-eager optimizations from this.

**Comment by jamesmcclain** [comment]
Those optimizations should help support larger queries over the NHD dataset, so I think there was still some gain.

**Comment by rajadain** [comment]
This is the DRB GeoJSON: [DRB.geojson.txt](https://github.com/WikiWatershed/model-my-watershed/files/287298/DRB.geojson.txt)

Obtained thusly:

```sql
SELECT ST_AsGeoJSON(ST_ConvexHull(ST_Collect(geom)))
FROM drb_streams_50;
```

**Comment by mmcfarland** [comment]
We also already have a simplified boundary polygon that's used to enable/disable the DRB streams layer selector.

**Comment by rajadain** [comment]
Oh that's good to know! I was trying to use the calculation in GeoDjango yesterday but couldn't figure out how to do it. If we already have the logic in the front-end, we can probably include a flag in the request indicating whether or not to use it.

**Comment by rajadain** [comment]
If you're referring to this: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/draw/views.js#L77-L89 it only checks if one point is within the DRB, not an entire polygon. I guess I could extend it on the client side, but I wonder if we should be performing this calculation on the server side instead.

I will see if I can reuse the DRB shape we're using there though.

**Comment by rajadain** [comment]
Thanks to @jwalgran's help I can do the comparison in Python.

The DRB Outline I generated above looks like this:

![image](https://cloud.githubusercontent.com/assets/1430060/15681924/455e8fd0-2729-11e6-845e-6e31d7546109.png)

And the previously saved one looks like this:

![image](https://cloud.githubusercontent.com/assets/1430060/15681948/5862312c-2729-11e6-8c10-d26d68a8ebf7.png)

The latter is smaller, but I imagine it was generated to include points that would result in watersheds within the DRB, thus it may be smaller than we need it to be.

I'm going to go with the latter for now. Please let me know if I should use the former instead.
