### ISSUE TITLE
Numeric values in model 

### ISSUE THREAD

**Issue by rcheetham** [WikiWatershed/model-my-watershed#1342]
Columns of numbers are generally easier to read and compare if they are aligned to the right of the column.

![image](https://cloud.githubusercontent.com/assets/595431/15617644/e4cc1dae-2417-11e6-8b37-f023c3712b6e.png)

**Comment by lewfish** [comment]
This was actually fixed in a recent PR that's not on staging yet.

![screen shot 2016-05-27 at 2 38 48 pm 2](https://cloud.githubusercontent.com/assets/1896461/15617889/ee3354ba-2418-11e6-8030-6aad791a4e4a.png)
