### ISSUE TITLE
Optimize Map Control Positioning

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1346]
Originally the Map Controls were in the top right. Then we added the sidebar collapse button, and had to move them to the left #1142. Then we added the modification sidebar and moved them back to the right #1336. Currently this is alright since the sidebar collapse button is missing #1345, but as soon as it is fixed we will need to figure out where to position map controls so that they neither obscure anything nor are obscured by anything.

**Comment by ajrobbins** [comment]
@jfrankl

**Comment by rajadain** [comment]
Shares a point with #1345.

Currently has been set to be like this in #1350:

![image](https://cloud.githubusercontent.com/assets/1430060/15695536/34ade102-2776-11e6-9bd2-ada79ef0e7b3.png)

This card may be revisited if this positioning is not ideal.
