### ISSUE TITLE
MapShed implementation issues

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1357]
After a review by BME, the following issues in our MapShed implementation need to be resolved:

* [x] NLCD code 21 needs to be mapped to MapShed code 2 (LD Mixed)
* [x] Rural Land use `C` and `P` values are 0.0, should be assigned default values.  These should be in a MapShed routine already.
* [x] Confirm:  We are using Hi-res streams for LS, Low-Res streams for Stream Bank Erosion
* [x] Day Hours are off by one month (our March value shoudl be Feb, etc - see images)
* [x] Stream Bank AEU numbers are wrong order of magnitude.  We should evaluate how we are using County animal data and confirm with BME about the correct formula.

Orig Daylights
![screenshot 2016-06-06 at 2 54 05 pm](https://cloud.githubusercontent.com/assets/1014341/15833897/b6fd4e8e-2bf6-11e6-8aa0-20656d6aba66.png)

Our Daylights
![screenshot 2016-06-06 at 2 53 55 pm](https://cloud.githubusercontent.com/assets/1014341/15833896/b6f9c9c6-2bf6-11e6-8044-17260be5b90d.png)

**Comment by rajadain** [comment]
I have been unable to locate where "Stream Bank AEU" numbers are. If there are no suggestions, I will clarify with BME on a call tomorrow.
