### ISSUE TITLE
Update County Animal Dataset

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1360]
New dataset has been provided with additional attributes.  Update the sql tar hosted on s3.

**Comment by mmcfarland** [comment]
Loaded new shapefile into PostGIS and exported to sql, updated the s3 file.

#### Test
Load the updated data via setup script from your app VM 
-  `./setupdb.sh -f ms_county_animals.sql.gz`
- Verify the new attributes are present:

 ```
totalaeu     | double precision
grazingaeu   | double precision
totaeu_ha    | numeric(7,2)
grzaeu_ha    | numeric(7,2)
```

- The new table should have the same number of records as the old (4409)
 ```
mmw=# select count(*) from ms_county_animals;
 count 
-------
  4409
(1 row)
```

##### Steps to update
I used these two commands to produce the new sql file

```
ogr2ogr -t_srs EPSG:4326 -f "PostgreSQL" PG:"host=localhost user=mmw dbname=mmw password=mmw" -skipfailures ~/shapes/cty_animals.shp -nln ms_county_animals
```
```
pg_dump -c --if-exists -O -t ms_county_animals -h localhost -U mmw mmw > ms_county_animals.sql
```

**Comment by mmcfarland** [comment]
This will have to be run on staging/production when the associated commits are released.

**Comment by rajadain** [comment]
Thanks! Confirmed that I have the new columns. I'll make a PR to use these new values in the AEU calculation.

**Comment by rajadain** [comment]
Interestingly, the `geom` column has been renamed to `wkb_geometry` in the new dataset

**Comment by mmcfarland** [comment]
Shoot.  I'll update the column & indexes....

**Comment by mmcfarland** [comment]
s3 file is updated to `geom` and `ms_county_animals_geom_idx" gist (geom)`.

**Comment by rajadain** [comment]
Ran the script on Staging.
