### ISSUE TITLE
Observations time series chart issue: "Failed to load data" 

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1363]
Several of the observation sources display results in their popups, but fail to show a time series chart:

![screen shot 2016-06-13 at 9 47 11 am](https://cloud.githubusercontent.com/assets/12868342/16010013/4ad1ddfe-314d-11e6-8661-aab193724983.png)

Observed for the following observation sources:
- CRBCZO
- DEOS
- OSU-PRISM

**Comment by ajrobbins** [comment]
Getting a 500 Internal server error when I try to show the historical data histogram for CRBCZO at this address: https://staging.app.wikiwatershed.org/observation/services/get_asset_info.php?opt=data&asset_id=CRBCZO_WCC019&var_id=H1_Conductiv&asset_type=siso

**Comment by mmcfarland** [comment]
This appears to be an error in the upstream application.  The request is proxied directly to http://www.wikiwatershed-vs.org/services/get_asset_info.php?opt=data&asset_id=CRBCZO_WCC019&var_id=H1_Conductiv&asset_type=siso which itself returns a 500.

Tagging @emiliom to give him a heads up.

**Comment by emiliom** [comment]
This is odd. I'll look into it later today. Do you know when it started happening? Is it happening with other variables, and other web services from us?

**Comment by mmcfarland** [comment]
@emiliom we only just noticed it yesterday, not sure how long it was happening previously.  Other services randomly tested _were_ working, but we did not do an exhaustive examination.

**Comment by ajrobbins** [comment]
@emiliom these services say they have no data available when tested in the MMW UI:
- CRBCZO
- SWRC
- USCRN

and these show data but fail to show a histogram:
- CRBCZO
- OSU-PRISM

**Comment by emiliom** [comment]
Thank you, that's very helpful.

**Comment by ajrobbins** [comment]
This error is not produced by an issue in MMW; closing.
