### ISSUE TITLE
Mapshed Point Source Flow results all 0s

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1365]
Point Source Flow is showing as all 0s with multiple different HUCs tested. Example: https://staging.app.wikiwatershed.org/project/628/scenario/1184

![screen shot 2016-06-13 at 11 26 03 am](https://cloud.githubusercontent.com/assets/12868342/16012962/a7de723a-3159-11e6-9bdd-915a1ee773a5.png)

**Comment by ajrobbins** [comment]
Though I am getting some results with a different nearby HUC 12: https://staging.app.wikiwatershed.org/project/630/scenario/1188

**Comment by mmcfarland** [comment]
The referenced project executes as a Site Stormwater Model, not a Multiyear - is it the wrong link or are saved links not respecting the model type?

**Comment by mmcfarland** [comment]
Wouldn't the point source flow be 0 if there are no point source pollution sources in the AoI?

**Comment by ajrobbins** [comment]
Wrong link, I believe. Updated

**Comment by rajadain** [comment]
I think you're right, @mmcfarland 

```sql
SELECT SUM(mgd) AS mg_d,
       SUM(kgn_yr) / 12 AS kgn_month,
       SUM(kgp_yr) / 12 AS kgp_month
FROM ms_pointsource p INNER JOIN boundary_huc12 b
  ON ST_Intersects(p.geom, b.geom)
 AND b.name = 'Darby Creek';

 mg_d |       kgn_month        |       kgp_month        
------+------------------------+------------------------
      | 0.00000000000000000000 | 0.00000000000000000000
```

```sql
SELECT SUM(mgd) AS mg_d,
       SUM(kgn_yr) / 12 AS kgn_month,
       SUM(kgp_yr) / 12 AS kgp_month
FROM ms_pointsource p INNER JOIN boundary_huc12 b
  ON ST_Intersects(p.geom, b.geom)
 AND b.name = 'Chester Creek';

 mg_d |     kgn_month      |       kgp_month        
------+--------------------+------------------------
  0.8 | 8.2500000000000000 | 0.00000000000000000000
```

It would be helpful if there was a way to visualize the point sources on the map. Perhaps if no point sources are found in the area of interest, we can consider adding a disclaimer to that effect.

**Comment by rajadain** [comment]
On Friday I was actually seeing some cases when Point Src Flow and Subsurface Flow had values on my local but not on Staging. Let me confirm that's not happening anymore

**Comment by ajrobbins** [comment]
This is kind of janky but it appears that there aren't that many point source spots in the PHL area, which is where those test HUCs were from:
![screen shot 2016-06-13 at 12 13 37 pm](https://cloud.githubusercontent.com/assets/12868342/16014742/8fb16bd4-3160-11e6-8b2f-cf9e410b9c9b.png)

**Comment by rajadain** [comment]
Spot checked a handful of HUCs, staging and local have consistent results. When we see 0s, it is most likely because there are no point sources of pollution within the area of interest.

**Comment by rajadain** [comment]
Here's a map of HUC12s and Point Sources in the Greater Philadelphia Area http://bl.ocks.org/d/8e927732b3e167f98663e804dff1fe89

![image](https://cloud.githubusercontent.com/assets/1430060/16015792/6233c8e6-3165-11e6-9d39-6e54d088d43f.png)

**Comment by ajrobbins** [comment]
Confirmed that in the Plymouth Creek-Schuylkill River Huc-12 (Conshohocken), which has 5 point sources according to the data, point-source flow is not 0:
![screen shot 2016-06-13 at 1 30 53 pm](https://cloud.githubusercontent.com/assets/12868342/16016879/22a09708-316b-11e6-8782-e3ad0b244fa0.png)
