### ISSUE TITLE
Show AoI name in Model tab/workflow

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1366]
Its not intuitive to click back to the Analyze tab to see the title of the AoI you are modelling, and the Model Tab has no indication of the AoI name. We should consider adding the title to the Model tab or displaying it at somewhere on the map viewer, like we do when a user returns to draw:
![screen shot 2016-06-13 at 1 34 28 pm](https://cloud.githubusercontent.com/assets/12868342/16016965/999d0c92-316b-11e6-81b8-bb0c8d44be19.png)

**Comment by ajrobbins** [comment]
Potentially worth considering in the forthcoming UI update @jfrankl

**Comment by ajrobbins** [comment]
In the current UI, we show AoI name and info in Analyze:

![screen shot 2017-08-22 at 3 59 57 pm](https://user-images.githubusercontent.com/12868342/29584872-21d77e92-8753-11e7-8ff7-c8b7670d1a55.png)

But we lose this info in Model:
![screen shot 2017-08-22 at 4 00 14 pm](https://user-images.githubusercontent.com/12868342/29584890-2a797186-8753-11e7-8056-671959acba2e.png)

This is useful contextual information that we should preserve on the page at the model stage.

**Comment by jfrankl** [comment]
Let's remove the "Current Conditions/Scenario" toolbar when someone switches back to Analyze from the project page and show them a sidebar that looks more similar the initial Analyze view.

In addition to bringing back the AoI and area, this removes the information specific to modeling, which I think will make it extra clear that any modifications are not represented in the Analyze content.

![image](https://user-images.githubusercontent.com/1809908/29636300-190f2ea6-881e-11e7-937a-90020d7e2009.png)

**Comment by jfrankl** [comment]
In addition to the change above (remove the "Current Conditions/Scenario" toolbar when someone switches back to Analyze), we want to add the "Details" button the Project toolbar. The "Details" button would open a dropdown with information about project settings. At first, this would include the AoI and the model.

In the future, this might be how a user would change the AoI or model for their project. Note the `(Edit)` buttons in the screenshot below. However, for now, we can leave those out.

![image](https://user-images.githubusercontent.com/1809908/29676035-e96f8248-88c4-11e7-80a7-fda37a5d59fd.png)
