### ISSUE TITLE
No value for Septic Systems

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1370]
In gwlfe hydrology output, septic system source is always zero.  Check that we are estimating the values as prescribed below:

> Also check to see if you have the following code in your front-end pre-processor:

```vb
If SeptFlag = 1 And EstSS = False Then

            ' Calculate septic system values

            CalcSepticSystems()

        ElseIf EstSS Then

            ' Estimate septic system values

            SewPublic = 0

            ShortSys = 0

            SewSeptic = (SSLDR * LuArea(14)) + (SSLDM * LuArea(11)) ' Set number on direct/public systems

        End If

        NormalSys = SewSeptic ' Set number on normal systems

        Ponding = 0 ' Set number on pond systems

        ShortSys = SewOther ' Set number of short circuit systems

```

> If you do, just set SSLDR and SSLDM equal to "3.3", and you should be ok with your septic system calculations (because right now, they are probably both set to "0").

![screenshot 2016-06-15 at 10 18 15 am](https://cloud.githubusercontent.com/assets/1014341/16083456/0079f5a6-32e3-11e6-97a5-00840de1095c.png)

**Comment by ajrobbins** [comment]
Further info from BME:
- In MapShed we now use “low-density” urban land to estimate septic system populations.
- For MMW, multiply hectares of “low-density mixed” by 3.3 persons per ha to get total population of people on septic systems in the AOI
- Assign this value to the “Normal” category, which is written to position 1 on lines 86-97 of the gms file

**Comment by kellyi** [comment]
`SSLDR` and `SSLDM` are currently set to 4.4 and 2.2, respectively:

https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/gwlfe_settings.py#L471

**Comment by kellyi** [comment]
Ran `debugcelery` and it seems like this method is generating a non-zero value -- https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/mapshed/calcs.py#L572 -- so I'm going to check whether it's not getting assigned or displayed properly.

**Comment by kellyi** [comment]
`z['NormalSys']` has a value right before it's sent to the GWLF-E GMS parser to create the input file here -- https://github.com/kellyi/model-my-watershed/blob/develop/src/mmw/apps/modeling/tasks.py#L360 -- so I think that value may not be being read in GWLF-E.

**Comment by kellyi** [comment]
I put up a PR here -- https://github.com/WikiWatershed/model-my-watershed/pull/1420 -- which generates and displays values for `NumNormalSys` in the GMS file and "Total Nitrogen" for Septic Systems, but for Sediment and Total Phosphorus we are hard coding many of the required values to zero in MMW or in GWLFE.

Some of the values "Total Nitrogen" depends on are set to zeroes here:

https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/gwlfe_settings.py#L100

and here:

https://github.com/WikiWatershed/gwlf-e/blob/ec00b3853001af4975eb4d3b970bbe19ff5def14/gwlfe/gwlfe.py#L50

Sediment is set to zero here:

https://github.com/WikiWatershed/gwlf-e/blob/develop/gwlfe/WriteOutputFiles.py#L887

Should different static values be used for these? Is there code for estimating `NumShortSys` and `NumDischargeSys` similar to the code above?

**Comment by ajrobbins** [comment]
Response from BME:
>Glad you were able to get the septic system N problem fixed. With respect to sediment, septic systems do not produce that. And as for P, we have no default routine for providing a P load. Most P is tied up in the soil and does not move. If the user downloads the gms file, they can make edits to alter this. So, in short, it appears that you have fixed the problem sufficiently.
So I think you're OK to proceed on https://github.com/WikiWatershed/model-my-watershed/pull/1420.

**Comment by kellyi** [comment]
Awesome. Thanks!
