### ISSUE TITLE
Add a "totals" row to hydrology table

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1371]
Add a row at the bottom of the hydrology table with the variable totals. 

![screen shot 2016-06-15 at 10 31 19 am](https://cloud.githubusercontent.com/assets/12868342/16083796/59833a4e-32e4-11e6-936d-bcac71f26549.png)

**Comment by rajadain** [comment]
Would there be value in adding an average row as well?

**Comment by mmcfarland** [comment]
> Would there be value in adding an average row as well?

It wasn't requested, let's just keep to a totals row.
