### ISSUE TITLE
Investigate cropland and hay/pasture water quality inaccuracies

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1373]
According to BME, Cropland total nitrogen and Hay/Pasture total phosphorus loads appear incorrect relative to desktop results on the Little Neshaminy test watershed. Need to troubleshoot this.

**Comment by ajrobbins** [comment]
From BME:
>I attempted to verify that the MMW (Python) version of the GWLF-E model was giving the same results as the desktop version. I did this by doing a model run in MMW, downloading the gms file just created, running the gms file in the desktop version of the model, and comparing the output.
Based on the above activity, all of the output values checked out except for the TP value for Hay/Pasture and the TN value for Cropland as shown in the figures below. I’m not sure what the best approach would be to track this error down, but one option would be to have Ken come to Azavea to sit down with Matt or someone else there to run both models simultaneously in “edit mode” routine by routine for the purpose of comparing the values for these land use categories in step-wise fashion until a discrepancy is identified.

Model output from MMW:
![mmwoutput](https://cloud.githubusercontent.com/assets/12868342/18058611/19abf1e2-6de3-11e6-9685-f9336266b227.png)

Model output from running desktop GWLF-E on MMW-created gms file:
![gwlfeoutput](https://cloud.githubusercontent.com/assets/12868342/18058628/2bafbc84-6de3-11e6-99e5-64fd92a0f456.png)

**Comment by kdeloach** [comment]
We should be able to figure this out given the GMS file used to generate these screenshots.

**Comment by ajrobbins** [comment]
BME has provided the GMS file referenced above; it's in the project folder on the fileshare under /downloads: cropland_hay-pasture_issue.gms

**Comment by kdeloach** [comment]
Thanks. I'm attaching that file here too (drop the .txt extension).

[cropland_hay-pasture_issue.gms.txt](https://github.com/WikiWatershed/model-my-watershed/files/443266/cropland_hay-pasture_issue.gms.txt)

**Comment by mmcfarland** [comment]
Some updated information from BME:
> One quick check you could make is to see what the values are for "Dissolved P" and "Dissolved N" for Hay/Pasture and Cropland, respectively, when the "Total P" and "Total N" values are written to the MMW output table. You can then compare these values with those given in our screen capture in the "bug fix" document sent previously. I'd be curious to know if they are the same, or different, than those calculated by the desktop version of GWLF-E. Knowing this might help to hone in on potential errors in the Python model code.

**Comment by ajrobbins** [comment]
Further info:
>Attached is a document that may help you track down the value discrepancies. It is a copy of the "CalcLoads" routine in the GWLF-E model (i.e., CalcLoads.bas). Highlighted are two pieces of code you might want to focus on. I would check the values you get for "DisNitr(Y,i)", "DisPhos(Y,i)", "LuTotNitr(Y,l)", and "LuTotPhos(Y,l)" for both "Hay/Pasture" and "Cropland" at this point for both the desktop and Python versions of the model (in the case of the "LuTot" loads, check the values before and after the "solid" loads are added to the "dissolved" loads). If the values are the same at this point, the problem is probably related to calculating the "mean annual loads" later in the code. If they are different, that leads us to a different set of options.

[CalcLoads.docx](https://github.com/WikiWatershed/model-my-watershed/files/462519/CalcLoads.docx)

**Comment by kellyi** [comment]
Assuming I'm selecting the right key indices for these, it looks like these might be the values for dissolved phosphorous for hay/pasture and dissolved nitrogen for cropland when their `TotalP` and `TotalN` values are written to output in GWLF-E:

```
Hay/Pasture AvLuDisPhos => 1094.3932362
Cropland AvLuDisNitr => 30734.6543901
```
