### ISSUE TITLE
Update weather data

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1404]
A new `weatherstations.dbf` file was delivered that updated attribute values (specifically ET) for weather stations.  Import the new shapefile, create a new data dump, upload to s3 and deploy the new data to staging and production.

**Comment by mmcfarland** [comment]
Available on project share: `/data/MapShed/weather-stations`

**Comment by lewfish** [comment]
I'm done with https://github.com/WikiWatershed/model-my-watershed/issues/1404. There's no code associated with it, but if we want to review it, someone can just run `setupdb.sh -m` and make sure Mapshed still works. There should be 214 rows in the new table. I update staging, and will update production after this is reviewed. I've checked to see if there are different results with the old and new data, but they look the same. However, the sum of the old etadj is 375.28 and the new is 528.46.

**Comment by mmcfarland** [comment]
Running `./setupdb.sh -m` gives me the following error for weather stations:
```
 curl -s https://s3.amazonaws.com/data.mmw.azavea.com/ms_weather_station.sql.gz

gzip: stdin: not in gzip format
```
Is the public bit enabled on that file in s3?

**Comment by lewfish** [comment]
> s the public bit enabled on that file in s3?

Should be enabled now.

**Comment by mmcfarland** [comment]
New error.  I've seen this before when a table script has a new id column added in the pg_dump script.  The previous table has PK field `ogc_fid`, consider updating your data script to keep the the same name (presumably new one is `gid` based on the errors)

```
+ curl -s https://s3.amazonaws.com/data.mmw.azavea.com/ms_weather_station.sql.gz
SET
SET
SET
SET
SET
SET
SET
ERROR:  column "gid" of relation "ms_weather_station" does not exist
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ERROR:  current transaction is aborted, commands ignored until end of transaction block
invalid command \.
ERROR:  syntax error at or near "1"
LINE 1: 1 13876 Birmingham 70 3.10000000000000009 1386 1961-1990 196...
```

**Comment by lewfish** [comment]
> The previous table has PK field ogc_fid, consider updating your data script to keep the the same name (presumably new one is gid based on the errors)

Should be fixed now.

**Comment by mmcfarland** [comment]
+1, loads and has the right `etadj` sum

**Comment by lewfish** [comment]
I just added a spatial index and ran `setupdb.sh -m` on staging. Here are some notes on how I converted the shapefiles into a sql file.

```
On host machine run:
shp2pgsql -g geom weathstations.shp > ms_weather_station.sql
psql -h localhost -p 5432 -U mmw

\i ms_weather_station.sql
alter table weathstations rename to ms_weather_station;
alter table ms_weather_station drop et_adj2;
alter table ms_weather_station drop et_adj3;
alter table ms_weather_station drop etadj_orig;
select UpdateGeometrySRID('ms_weather_station', 'geom', 4326);
alter sequence ms_weather_station_gid_seq rename to ms_weather_station_ogc_fid_seq;
alter table ms_weather_station rename gid column to ogc_fid;
drop index ms_weather_station_idx;
create index ms_weather_station_idx on ms_weather_station using gist (geom);

on host machine run:
pg_dump -h localhost -p 5432 -U mmw -c --if-exists -O -t ms_weather_station -f ms_weather_station.sql
```
