### ISSUE TITLE
Fix the number of significant figures for the output GMS data

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1405]
When writing to the GMS file, reduce the number of significant digits used.  Target number TBD.

**Comment by ajrobbins** [comment]
Target number info from BME:

- Use only 1 decimal place for the area (ha) values that are written to position 2 of lines 20-35 of the gms file for the rural and urban land use categories
- I would recommend only using 1 decimal place for the “kg” values in the MMW WQ output table (leave the “kg/ha” and “mg/l” values as is)
