### ISSUE TITLE
Include Animal Population summary in analysis results

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1424]
Basic summary statistics for Area of Interest from national county animal population data (by animal type), including total Animal Equivalent Units (AEU), will be included in the Analyze output.

We need to:
- Add a new tab to the Analysis tab, alongside "Land" and "Soil", to read "Livestock". 
- The tab will include the AoI name/title and size, as the land and soil tabs do
- This tab will include a table of: Animal type, AEU amount, and proportion for the area of interest

Questions for @mmcfarland : should the tab also include a bar chart like we have for land/soil:
![screen shot 2016-08-18 at 1 52 34 pm](https://cloud.githubusercontent.com/assets/12868342/17784635/3890404a-654b-11e6-837c-3edbfadbc700.png)

 with proportion of AEUs by animal type?
Also, should the tab be called "Livestock" or something else, like "Animal distribution" or something?

**Comment by mmcfarland** [comment]
We probably have to proportionally weight the county to the portion that exists in the AoI (similarly to what we do for MapShed).

**Comment by mmcfarland** [comment]
Also, this should be unified as much as possible with the existing mapshed query getting animal counts.  If that is not area weighted, check out in-progress changes that deal with new attributes on that dataset which do similar things:
https://github.com/WikiWatershed/model-my-watershed/pull/1423/files

**Comment by kellyi** [comment]
Sounds good. I'll take another look at that PR to see how it's implemented.

**Comment by mmcfarland** [comment]
And just for clarification, the PR is calculating _LS_ from values on `ms_county_animals`, the actual map shed AEU stuff may already have what we want for analysis output.

**Comment by kellyi** [comment]
For reference the MapShed animal count method is here -- https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/mapshed/calcs.py#L149

**Comment by kellyi** [comment]
Dropping this here for reference, too, from a description of the USDA county animals shapefile:

> It provides information that will allow the estimation basin-level populations for 9 different types of farm animals on a per unit area basis. The key fields to be used by MapShed include “Fips_code”, “Beef_ha”, “Dairy_ha”, “Broiler_ha”, “Layer_ha”, “Hogs_ha”, “Goat_ha”, “Horse_ha”, Sheep_ha”, and “Turkey_ha”.
