### ISSUE TITLE
Change DRB to Delaware River Basin in layer selector

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1429]
![screen shot 2016-08-25 at 9 49 44 am](https://cloud.githubusercontent.com/assets/12868342/17971670/ccc4d52e-6aa9-11e6-9ed5-8252af370fa8.png)

Should read "Delaware River Basin Stream Network".

**Comment by kellyi** [comment]
Shares a point with #1431
