### ISSUE TITLE
Align rounding rules for Animal count

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1431]
We are rounding the animal count up on the front end and down in the GMS file.

**Comment by kellyi** [comment]
For reference: we are rounding the population counts down for the GMS file here:

https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/mapshed/tasks.py#L124

...and rounding them up for the frontend Analyze tab here:

https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/calcs.py#L31

I'm going to round the frontend counts down to match the work already done for MapShed.
