### ISSUE TITLE
Use DRB-specific point source data for Mapshed in DRB

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1436]
We will be receiving new Point Source pollution vector data for the DRB only, with the same schema as our existing national Point Source dataset. The new data should be used when Mapshed is run within the DRB, and the national dataset should be used when Mapshed is run outside of the DRB. We have not gotten the data yet, so we should mock up this process with identical data first.

**Comment by ajrobbins** [comment]
Scott Haag just provided a pg_dump of the new point source data for the DRB; it's on the fileshare at /projects/Stroud_ModelMyWatershed/data/MapShed/pointsource/npdes_pts_083016azavea.backup

Note that this new data should match our existing national dataset schema exactly, except for the addition of a facilityname field.

Attached here - delete the .txt ending.

[npdes_pts_083016azavea.backup.txt](https://github.com/WikiWatershed/model-my-watershed/files/445551/npdes_pts_083016azavea.backup.txt)

**Comment by lewfish** [comment]
I'm getting a syntax error when reading this file in psql using `\i npdes_pts_083016azavea.backup.txt;` 

```
psql:npdes_pts_083016azavea.backup.txt:1119: ERROR:  syntax error at or near "1"
LINE 1: 1 0101000020E61000007FA5F3E159D952C035EB8CEF8BED4340 WQG0223...
```

I also noticed that some of the column names are different. The new DRB data vs. the old `ms_pointsource` data:
```
avg_p_conc, ktn_yr, ktp_yr,
```
```
avgpconc, kgn_yr, kgp_yr
```
Does this indicate that the last two variables are actually different, perhaps using different units?

**Comment by ajrobbins** [comment]
I'll ask about the column names -not sure about the syntax error. Is there something wrong with the file?

**Comment by lewfish** [comment]
Changing the filename doesn't make a difference.

**Comment by ajrobbins** [comment]
Response re: variable names:
>They should be the same, if the units were in
avgpconc = mg/l
kgn_yr = kg total nitrogen per year
kgp_yr = kg total phosphorus per year

So I think those were typos and the variables are the same.

**Comment by ajrobbins** [comment]
[npdes_pts_083016_v2_azavea.backup.txt](https://github.com/WikiWatershed/model-my-watershed/files/445774/npdes_pts_083016_v2_azavea.backup.txt)
Updated file with corrected variable names - they should match the existing data exactly now.
