### ISSUE TITLE
Include Point Source pollution data in Analysis summary results

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1437]
Basic summary statistics for the point source pollution data that we currently use for Mapshed should be displayed in the Analysis tab, as was done with animal data in https://github.com/WikiWatershed/model-my-watershed/pull/1425

The tab should be called "Point Source". According to the contract, the statistics for display should be "limited to aggregations of the existing attributes in the table". I'm not familiar with the data attributes, so there will have to be a little back and forth with BME and Stroud as to which attributes to display and how.

Note: We will be receiving DRB-specific Point Source data. When an analysis is run on an AoI within the DRB, we should use the DRB-specific data. This DRB check will also be implemented in the Mapshed model run https://github.com/WikiWatershed/model-my-watershed/issues/1436 
For now, we can mock the DRB-specific data with an identical table, since it will have the same schema.

**Comment by kellyi** [comment]
I'm going to generate the Analyze results using the existing MapShed method, so when we're ready to switch to the using DRB data for DRB AOIs it can all be handled there.

**Comment by kellyi** [comment]
These are the columns currently available in the `ms_pointsource` table:

AVG_N_CONC, 
LBSN_YR,
MGD,
AVGPCONC,
LBSP_YR,
KGN_YR,
KGP_YR

For MapShed, it looks like we're currently using MGD, KGN_YR, KGP_YR and transforming those values into estimates of monthly nitrogen load, monthly phosphorus load, and monthly discharge.

@ajrobbins can you ask if these are the values we should output in the Analyze tab or if there are others to include as well?

**Comment by ajrobbins** [comment]
BME has provided recommended output instructions here: https://docs.google.com/document/d/1Kg93peuPF5OTQUzKCiWtzgFJY-kMegCPc0jljXI6BP4/edit

Let me know if you have any trouble viewing the document; I tried to share it with you.

**Comment by kellyi** [comment]
Thanks! I was able to see the document, so I'll adjust the code to display like that.

**Comment by ajrobbins** [comment]
@aufdenkampe requested that we include an additional column for point source name/code. So I think the table should show: Code | Location| Discharge (MGD) | TN Load (Kg/yr) | TP Load (kg/yr)
