### ISSUE TITLE
Asynchronize Analysis Requests

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1438]
As the analysis screen grows more complicated, the longest-to-calculate dataset holds back all data from the server.

Address this by having different access points for each data set. One solution may be to have different endpoints for each dataset, which would allow easy separation on both request and response side.

Another solution may be to have a single endpoint for submitting the request (since each endpoint would use the same input: area of interest), which returns two arrays: one of results and one of job ids. The results are used immediately, and the job ids can be used to poll independently.

Or use some combination of these approaches.

This should also include a way to submit multiple requests from the front-end, as well as have different spinners  indicating loading for each analysis tab.

**Comment by rajadain** [comment]
The effort to make the Analyze view asynchronous to accomodate more, longer requests is constrained by the following assumptions:

 * All endpoints require the same input data, namely the shape of the area of interest.
 * The input data can potentially be heavy, of the order of 100s of KBs.
 * Responses may be immediate (`{results: {...}}`) or asynchronous (`{job_id: 1234}`), and the request does not know ahead of time which it is going to be. Thus, the front-end should be able to handle both.
   - This is advantageous because it allows us to change the response-type from the server side without having to change the client-side code.
   - It also allows us to have one piece of code on the client-side responsible for handling all types of Analyze responses.
 * We may have a different set of Analyze requests based on configuration (MMW vs BigCZ)
 * We may have a different set of Analyze requests based on application context (inside or outside the Delware River Basin)
 * One request may populate more than one tab (Land Cover / Soil tabs are populated from a single asynchronous request)

Given the above, we ponder the following questions:

 * Should client-side requests be combined into one request, since they all require the same data? Or should they remain independent endpoints for easy addition / removal?
 * Should the list of Analyze endpoints and tabs now be represented through configuration? In some JSON object in `clientSettings`, to be used by meta code? Or should it remain a set of views and models that is used directly in hand-written JavaScript?
 * Since there are now to be a number of endpoints for Analyze, should these be pulled in to their own Django app, out of `modeling`?
 * Should the "immediately responding" endpoints return a direct response in a new structure, or return a job_id anyway and go through Celery anyway, just so that the client-side handling can be simplified and always expect the same structure? A simpler Celery job would finish quicker, although not instantaneously.

My leanings are towards:

 * Preferring hand-written JavaScript models and views to a JSON configuration structure. Trying to fit complex functionality in a JSON structure is folly, given JavaScript's limited and error-prone metaprogramming abilities, and will extremely limit what can be done in Analyze tabs. This would be especially bad since BigCZ expects a major expansion of functionality in Analyze.
 * Combining front-end requests into a single request that has two parameters: a payload (usually the area of interest), and a list of operations. The response will be an immediate hash with the operations as keys, and Celery Job IDs values.
 * Run all jobs through Celery, even those that are immediate. This allows simplification of the code in both client and server side, and since Celery is already running, has minimal overhead.
 * The Celery tasks for Analyze should be grouped together in a file under the `modeling` Django app, but we should not pull it out into its own app.

**Comment by kdeloach** [comment]
If all front-end requests are combined, how do we handle subsequent requests? Are previous requests invalidated? Would we have to reprocess jobs even when nothing relevant to that job has changed? I can explain this in person if it doesn't make sense.

**Comment by rajadain** [comment]
How does something like this sound?

 * Initial Request

      ```json
      {
        "model_input": AREA_OF_INTEREST_GEOJSON,
        "operations": [ "nlcd", "soil", "animals", "point_sources" ]
      }
      ```
 * Initial Response

      ```json
      {
        "nlcd": JOB_ID_1,
        "soil": JOB_ID_2,
        "animals": JOB_ID_3,
        "point_sources": JOB_ID_4
      }
      ```
 * Each operation is polled for independently, given its Job ID.
 * In case of partial failure, the re-run request contains only those operations which we want to refresh

     ```json
     {
       "model_input": AREA_OF_INTEREST_GEOJSON,
       "operations": ["nlcd", "soil"]
     }
     ```
   And the other tabs are not affected.

**Comment by kellyi** [comment]
Does combining these into a single job run through celery block the fast returning db queries until the slower raster stuff comes back too?

**Comment by rajadain** [comment]
No, they would all be independent Celery tasks. While it would be potentially slower than returning the query results for the initial response, it would offer a more uniform API for the client-side. The client-side may poll for raster results ~30 times on average, whereas the query results will be available on the first poll.

**Comment by rajadain** [comment]
One side effect this may have is fill up our `core_job` table a bit faster than before.

**Comment by mmcfarland** [comment]
The ordering may be important, if the slow jobs go in before the fast jobs, they still might not be completed until after the slow jobs.

**Comment by rajadain** [comment]
Another good point, especially as there are only so many Celery workers.

But I think each if operation has its own Celery chain, their tasks will find workers to execute on. Since no Celery task is very long-running (thanks to Spark JobServer, raster requests are 1 quick submit task, and many quick retrieve tasks), all tasks should find a worker to execute on pretty quickly.

**Comment by rajadain** [comment]
Alternatively, if tying all the operations together in one request is seen as too constrictive and immature optimization, we can still have independent endpoints for each operation. That would certainly be simpler.

**Comment by kellyi** [comment]
One other virtue of having multiple endpoints, each outputting to a different piece of the analyze tab, is that if one set of analysis results fails to return for whatever reason, it wouldn't prevent the others from returning and displaying.
