### ISSUE TITLE
Adjust low flow sediment value calculation

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1441]
We implemented a fix for the low-flow calculation in https://github.com/WikiWatershed/model-my-watershed/issues/1369

According to BME, it needs to be multiplied by 1000 (as is done for the "mean flow" sediment concentration estimate) to account for the fact that with sediment, we are dealing with metric tonnes (1000 kg) rather than with kg as is done with N and P.

BME is also suggesting a change to how we reach the low flow value:

> Currently, we use the mean flow value for September in the output as a proxy for the low flow. This works well in PA and the northeast in general since this month is usually the lowest or next-to-lowest flow. However, in other parts of the US, this does not work so well (e.g., Texas, where Sept stream flows are usually among the highest). As an alternative, could we read and sort the mean flows for all months in the output, and then select the lowest flow value to represent low flow for the low-flow concentration estimate?

**Comment by kdeloach** [comment]
We already find the mean flow dynamically, as described (Ref: https://github.com/WikiWatershed/gwlf-e/blob/develop/gwlfe/WriteOutputFiles.py#L742).

**Comment by ajrobbins** [comment]
Nice! Is the comment about multiplying it by 1000 still valid, @kdeloach ?

**Comment by kdeloach** [comment]
If I understand correctly, the unit of measurement conversion factor being applied to Low Flow Sediment is wrong (reportedly). 

We should verify the original units of measurement for each variable involved in the calculation and then apply the correct conversion factor based on that.

You can see from [the code](https://github.com/WikiWatershed/gwlf-e/blob/develop/gwlfe/WriteOutputFiles.py#L762) that `AvSedYield` is being converted from `KG_TO_MG`. It may be that we need to change this to `TONNE_TO_MG` instead.
