### ISSUE TITLE
Activate Point Source tooltip on table click

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1445]
Following https://github.com/WikiWatershed/model-my-watershed/issues/1444, the following behavior has been requested: When a user clicks on an item in the Point Source analysis table, highlight the appropriate point on the map and open the tooltip.

**Comment by caseypt** [comment]
If the user doesn't have the point-source layer on, should this turn on the layer and then open the tooltip?
