### ISSUE TITLE
Analysis collapse button is missing

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1453]
The button to toggle the sidebar is not visible as of 7ca369a6967bc8b5bd6887ea9611db292d206b13

![screenshot 2016-09-06 at 5 12 28 pm](https://cloud.githubusercontent.com/assets/1014341/18291336/445ca7c4-7455-11e6-8fd3-aea6b84ad157.png)

**Comment by rajadain** [comment]
It would be really simple to just add the same gray button from the modeling view to this one. Would it be okay if I also did some styling adjustments? I was thinking something more like this:

![image](https://cloud.githubusercontent.com/assets/1430060/18391580/66286cc0-767c-11e6-94ee-2fa5b0dcff14.png)

![image](https://cloud.githubusercontent.com/assets/1430060/18391608/791fac9e-767c-11e6-8dfe-8e93cd00e526.png)

And the same for the Modeling view:

![image](https://cloud.githubusercontent.com/assets/1430060/18391664/b4e01188-767c-11e6-9f22-e3b35e6e6509.png)

![image](https://cloud.githubusercontent.com/assets/1430060/18391644/9fdf9dc6-767c-11e6-9cff-1adb631441a5.png)

Note that while this does improve styling overall, and places the button where I feel it should've been in the first place, this will change any "muscle memory" our users have developed for the unfortunate existing placement.

I am currently using `chevron-right` and `chevron-left`. Alternatively, we may use one of these:

![image](https://cloud.githubusercontent.com/assets/1430060/18391789/2af06ed6-767d-11e6-9fad-af4ce6ae3614.png)

**Comment by rajadain** [comment]
In the "Draw" view that button will simply be absent.
