### ISSUE TITLE
Handle AOI shapes with intersections

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#1469]
Currently a drawn shape like this throws an error from Analyze. @mmcfarland mentioned that the shape could be normalized by giving it a buffer of 0:

![screen shot 2016-09-16 at 10 06 32 am](https://cloud.githubusercontent.com/assets/4165523/18588673/722bc3e0-7bf5-11e6-8891-93b766fd9031.png)

**Comment by kellyi** [comment]
A recent PR should have made it impossible to draw these kind of shapes in the frontend using the draw tool, so they will not end up hitting Django or the geoprocessing service on the backend.

If we decide we'd like to handle intersecting shapes, this card would involve:
- relaxing the restriction on drawing intersecting shapes in the frontend
- performing any necessary work to parse these into valid shapes which the API can process. there may be a `turf` library to normalize then before they're sent from the frontend, or it could be done in Python

**Comment by ajrobbins** [comment]
We now have a front-end guard for drawing self-intersecting AoIs, and as far as I know we have no plans to accommodate them.
