### ISSUE TITLE
Import water quality data for DRB area NHD+ streams

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1471]
This should be a table with ComID, TN, TSS, and TP. Data is on the fileshare in the project folder at /data/srat

**Comment by mmcfarland** [comment]
This new table joins `ComID` with our existing `nhdflowline` table, but only represents features in the national dataset which occur in the DRB and have had this water quality modeling applied.  We should import this data as a new table (`nhd_water_quality`?) and verify that we can successfully join on `ComID` between the two tables.  If there are significant records not included in `nhdflowlines` that are related in this new table, we may have to seek advice.  Anticipate that only a fraction of the entire national set will be represented in the new table, though.

The end goal is a table which with we can write a query for a new tiler endpoint to render nhd streams based off of the new TN, TP & TSS attributes.

**Comment by mmcfarland** [comment]
The data author anticipates that around 10k stream in the DRB area will have values, and approximately 6k streams in the DRB areas will not.  All streams outside of the DRB will not have any values.

**Comment by mmcfarland** [comment]
Additionally, the units for these values are all concentrations in mg/l.

**Comment by ajrobbins** [comment]
Sorry @arottersman but the data author just provided a slightly updated table for this. I put it on the fileshare; it's the 9_29_16 backup file.
