### ISSUE TITLE
Create class break scheme for stream water quality

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1478]
Based on #1471, the values for each TN, TP & TSS have to be broken into class breaks or color ramps for which we can generate styling rules.  This may include "high - med - low" categories, or discrete clusters of value binning.  Coordinate with Stroud to come up with the most appropriate breaks.

**Comment by ajrobbins** [comment]
BME is recommending the following break points:

|          |(kg/ha)       |(mg/l)          |
|------|-----------|------------|
|TSS    | 0-250      |     0-50       |
|           | 250-500 |     50-100    |
|           | 500-750  |    100-150  |
|           | 750-1000|    150-200  |
|           | >1000      | >200          |
|           |                  |                    |
|TN      | 0-5           | 0-1              |
|           | 5-10         | 1-2              |
|           |10-15         |2-3              |
|           | 15-20       | 3-4             |
|           | >20           | >4               |
|           |                   |                    | 
|TP       | 0-0.30      |0-0.03         |
|            | 0.30-0.60| 0.03-0.06   |
|            | 0.60-0.90| 0.06-0.09   |
|            | 0.90-1.20 | 0.09-0.12   |
|             | >1.20       | >0.12          |

**Comment by ajrobbins** [comment]
We should use a greyscale (low loading rate = light, high loading rate = dark) for the catchements (kg/ha), and a scale from green (lowest quartile) to yellow to red (highest quartile) for the stream data (mg/l).

**Comment by mmcfarland** [comment]
Here is the color brewer R-Y-G quintile break colors:
`['#d7191c','#fdae61','#ffffbf','#a6d96a','#1a9641']`

**Comment by caseypt** [comment]
Blocked on #1471

**Comment by jtarricone** [comment]
It seems like this issue can be totally absorbed by #1479 now that the discrete bins have been defined, right?
