### ISSUE TITLE
Import DRB catchment water quality table

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1480]
A shapefile will be provided which contains a Polygon layer representing NHD Catchments within the DRB.  These catchment features will have water quality attributes TN, TP & TSS as loading rates in kg/ha.  Import this data and script its inclusion to our data bucket, making sure to include a spatial index on geom.  This data will be used to render tile overlays.

**Comment by ajrobbins** [comment]
Shapefile is on the project fileshare at /data/catchement_water-quality 
![screen shot 2016-09-23 at 12 13 32 pm](https://cloud.githubusercontent.com/assets/12868342/18793087/43a14c74-8187-11e6-95dc-0163c76d38ea.png)

**Comment by ajrobbins** [comment]
Units: kg/yr/ha

**Comment by ajrobbins** [comment]
@kellyi Can you hold off on this for a bit, we will be sent a new shapefile with additional catchment attributes:

a.      TN kg/yr/ha

- TN kg/hr/ha from ag

- TN kg/hr/ha from urban

- TN kg/hr/ha from natural

- TN kg/hr/ha from point

b.      TP Same

c.      TSS Same (except we do not have an estimate of the point source loading for this)

**Comment by kellyi** [comment]
Sure, I'll put this back in the queue for now!

**Comment by ajrobbins** [comment]
@kellyi Updated data is in the same folder on the drive in a folder called 09_29_16
