### ISSUE TITLE
Create class break scheme for catchment water quality

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1481]
Based on #1480 , the values for each TN, TP & TSS have to be broken into class breaks or color ramps for which we can generate styling rules. This may include "high - med - low" categories, or discrete clusters of value binning. Coordinate with Stroud to come up with the most appropriate breaks.  Note that these values, while similar to the breaks developed for #1478, are in a different unit (kg/ha) than the streams (mg/l).

**Comment by ajrobbins** [comment]
Closing in favor of https://github.com/WikiWatershed/model-my-watershed/issues/1482 since BME has provided class break/color scheme information.
