### ISSUE TITLE
Visualize DRB Catchment water quality measurments

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1482]
Based on #1481 & #1480, create 3 tile endpoints which visualize each TN, TP & TSS attribute for DRB Catchments.  Add the three layers to the layer selector and allow them to be cached by the existing cache infrastructure.

**Comment by ajrobbins** [comment]
This card also includes assigning color breaks for catchment visualization:

Use a greyscale scheme with the following breaks:
BME is recommending the following break points (the mg/l column is the relevant one for this card):

|          |(kg/ha)       |
|------|-----------|
|TSS    | 0-250      |
|           | 250-500 | 
|           | 500-750  |    
|           | 750-1000|    
|           | >1000      | 
|           |                  |
|TN      | 0-5           |
|           | 5-10         |
|           |10-15         |
|           | 15-20       |
|           | >20           |
|           |                   |
|TP       | 0-0.30      |
|            | 0.30-0.60|
|            | 0.60-0.90| 
|            | 0.90-1.20 |
|             | >1.20       |
