### ISSUE TITLE
Use CDN for Static Assets

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1483]
- [x] Research moving all static assets, such as images, styles, and scripts, to a CDN such as CloudFront.
 - [ ] Create CloudFront account (?)
 - [x] Update app code, if needed
 - [ ] Update Jenkins code

**Comment by hectcastro** [comment]
Ideally, we'd put the entire micro site under its own domain and set a CloudFront distribution as that domain's primary DNS record. Unfortunately, I don't think we'll be able to do that here without an additional subdomain layer:

```
micro.app.wikiwatershed.org
```

That would also require a redirect from `app.wikiwatershed.org/micro` to `micro.app.wikiwatershed.org`.

The other option is to just put all of the static assets referenced from within the micro site behind CloudFront and update the references. This could something like `cdn.app.wikiwatershed.org`.

**Comment by rajadain** [comment]
@ajrobbins We may need to talk to Stroud regarding changing the domain for the micro site.

Since the Micro Site is completely static, we could even just make it into a plain HTML site, possibly into its own repo with an independent build and deploy process. I think one of the reasons we serve it via Django is so that some scaffolding (header, Google Analytics maybe) can be shared between the main and the micro sites.

I'd be fine with going with `cdn.app.wikiwatershed.org` though (and I guess we'd need a staging version too?), since that would be most transparent to the user.

**Comment by rajadain** [comment]
@hectcastro when you have some time I'd love to sit down and get an overview on the current CDN situation. I see that we do have some distributions configured, and also that we have a `tile-cache` S3 bucket. But I also see that a CDN can be placed in front of an EC2 instance, doesn't necessarily have to be an S3 bucket. And then there's the matter of payment for the CDN.

In the meantime, I'm going to assuage how difficult it would be to make the micro site it's own html page, and also to use custom URLs for static assets given an environment variable.

**Comment by hectcastro** [comment]
> On Sep 26, 2016, at 13:01, Terence Tuhinanshu <notifications@github.com> wrote:
> 
> @hectcastro when you have some time I'd love to sit down and get an overview on the current CDN situation. I see that we do have some distributions configured, and also that we have a tile-cache S3 bucket. But I also see that a CDN can be placed in front of an EC2 instance, doesn't necessarily have to be an S3 bucket. And then there's the matter of payment for the CDN.
> 
Sure.
> In the meantime, I'm going to assuage how difficult it would be to make the micro site it's own html page, and also to use custom URLs for static assets given an environment variable.
> 
I think figuring out if we can prefix all of the static asset URLs with a CDN enabled custom domain (even if that domain remains the same across envs), that might be the easiest way to go.

It'll be tricky to put the CDN between users and the MMW app ELBs just to intercept requests to the current micro site.

Making everything a standalone static site is the most attractive, but only works if it can all live on its own domain.

**Comment by ajrobbins** [comment]
It sounds like we really need Stroud to weigh in on the domain/redirects issue in order to choose a course of action. Let's hold off on this until Matt gets back and we have a conversation with Stroud about it.

**Comment by rajadain** [comment]
Alright, moving this back to Queue for now.

**Comment by ajrobbins** [comment]
@hectcastro @rajadain Verdict from Stroud: Put the microsite under its own domain, add subdomain so its at `micro.app.wikiwatershed.org`. Redirect from `app.wikiwatershed.org/micro` to `micro.app.wikiwatershed.org`. 

That seemed to be the most straightforward setup for us to implement, and Stroud is OK with it. Let me know if there's a better alternative.

**Comment by hectcastro** [comment]
Reopening this because I think we still need to issue a redirect from `/micro` to the new domain, plus actually publish the new version of the micro site.

**Comment by mmcfarland** [comment]
I've got that accounted for in #1517
