### ISSUE TITLE
Analyze & Model data input caching strategy

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1484]
Develop an ADR which defines a strategy for preserving Analysis output and Modeling input for Well Known Areas of Interest (WKAoI) which will have repeated analysis and models run against them.  

Some observations and questions:
- For all WKAoIs, it's unlikely that a majority of all features among all layers will have analysis or models run on them.  I suspect it is not worth the effort to pre-compute all output for all features, but rather capture that data on the fly when an uncached area is processed.
- The data which makes up the Analysis output is anticipated to keep changing, with new sources added.  The data that is gathered for model runs is more static in nature, but also can be refreshed periodically.  An effective method to clear the cache when data changes is crucial.  We currently cache model results _for a single project_ and a hash is generated on the input to the model to determine of the results are still valid.  Is there a similar piece of data that can be used as a key, or can something be synthesized to inform the application to use cached results or recalculate them?
- For this cache to be effective, the WKAoI needs to be identified by more than its shape.  Presently, the app treats a user generated shape the same way it treams a WKAoI - both just post the Geometry.  We'll need to switch this to a request based on Layer Id and Feature Id, with the geometry being sourced from the database.  This will also make the request faster as some AoIs are quite large (see #303).
- Analysis output is often similar to model input - can a parent set of data be generated once that would satisfy both? 
- Is it important to cache the intermediate results of the model data input, or is the end result sufficient?  Probably related to point above.
- Should discreet analysis output be cached/versioned, or should a change in one dataset invalidate the whole "analysis" package? 
- HTTP caching from the client is unlikely to be sufficient since the analysis results are polled based on a `JobId` and modeling input is not returned to the client, only modeling output.  MapShed does return GMS style data, but we may want to cache at a level of detail up from that, since GMS will contain Conservation Practices as well (which should not be cached) and I suspect serializing to GMS is not very expensive.

The goal here is to:
- Increase the speed performance of analysis and modeling requests
- Reduce the overall load on the geoprocessing pipeline for repeatable requests so that ad-hoc AoI requests have more resources
- Potentially be able to expand the size of a WKAoI that the application can handle.  This is at odds with the on-the-fly suggestion earlier (since resource exhaustion would still occur), but with this caching mechanism in place we could do targeted out-of-band result generation.  For example, we could target all HUC-08's within the DRB and generate Analysis and Model data input for them with which we populate the cache using temporary and more robustly provisioned SJS machines.

**Comment by rajadain** [comment]
> Should discreet analysis output be cached/versioned, or should a change in one dataset invalidate the whole "analysis" package?

This no longer applies since analysis is now independent for almost every tab. NLCD and Soils are still tied together though.

**Comment by rajadain** [comment]
Do we need to cache any of the database-only fetches? Water Quality seems to be the one that takes the longest, but even that isn't too bad. Perhaps it is only geoprocessing calls that need to be cached?

**Comment by mmcfarland** [comment]
The DB data is just about as static as the geoprocessing results, but is less expensive to produce.  I'm on the fence and would probably consider the cache method as part of the determining factor.  The raster analysis results are quite concise and the vector stuff can be larger, especially if we are including geometries for overlay (I don't recall if we are, or are doing on the fly requests).  I'm inclined to have this design focus on the geoprocessing generated stuff.
