### ISSUE TITLE
Delete dangling Celery / SJS jobs

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1489]
Currently, when processing a large area of interest (such as a HUC-10 or HUC-8 in MapShed), the front-end polls the endpoint 90 times (twice a second) before giving up. At this point, if the user wishes to continue, they must resubmit the job.

In the meantime, this old "dangling" job continues to be processed by Celery / SJS in the back-end. This clogs up the pipeline for other jobs, even the ones that the user may immediately re-submit.

Find a way to cancel and delete Celery and SJS jobs once they have reached a similar timeout. Consider defining this timeout value in standard configuration so it can be easily shared between components.

**Comment by mmcfarland** [comment]
Closing as we're not doing SJS calls anymore.  This could conceivably still be appropriate for just the Celery jobs based on our new setup, but lets re-evaluate when the refactored geoprocessing pipeline is stable, and open a new issue if necessary.
