### ISSUE TITLE
Rename animal types

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1494]
Replace some language to make the terms more recognizable to non-ag users.

Beef Cows --> Cows, Beef
Broilers --> Chickens, Broilers
Dairy Cows --> Cows, Dairy
Hogs/Swine --> Pigs/Hogs/Swine
Horses
Layers --> Chickens, Layers
Sheep
Turkeys

**Comment by ajrobbins** [comment]
shares a point with #1495

**Comment by kellyi** [comment]
@ajrobbins Should this change be visible only on the frontend or should it also update the names given in the GMS file? I assume just the frontend but thought I'd make sure. Here's the GMS file output:

```txt
Dairy Cows,0,Y,640,0.44,0.07,100000000000
Beef Cows,0,Y,360,0.31,0.09,100000000000
Broilers,0,N,0.9,1.07,0.3,140000000
Layers,0,N,1.8,0.85,0.29,140000000
Hogs/Swine,0,N,61,0.48,0.15,11000000000
Sheep,0,Y,50,0.37,0.1,12000000000
Horses,0,Y,500,0.28,0.06,420000000
Turkeys,0,N,6.8,0.59,0.2,95000000
Other,0,N,0,0,0,0
```

**Comment by mmcfarland** [comment]
Good question, front end only.
