### ISSUE TITLE
Update point source data

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1502]
Scott Haag will be providing updated point source data (this is the data we use in the dRB only). Should be no schema changes.

**Comment by mmcfarland** [comment]
This is meant to be just a handful of rows additional.  I suggest we load the new table with new name, and insert/join on the missing records to the old table and re-`pg_dump` it so all the indexes, etc remain the same.

**Comment by ajrobbins** [comment]
I believe this is a duplicate of https://github.com/WikiWatershed/model-my-watershed/issues/1436
