### ISSUE TITLE
Login modal design tasks

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#151]
- Need design for state when we are waiting for the server to return whether or not the login worked.
- Need design for validation errors, i.e. someone hitting enter without entering a username.
- Need sass for "incorrect username or password" as shown in mockups.

**Comment by caseypt** [comment]
This is still an issue. The most obvious issue may be the unstyled validation messages:

![image](https://cloud.githubusercontent.com/assets/1042475/19930138/6826d936-a0dd-11e6-95a8-296257e44768.png)

**Comment by ajrobbins** [comment]
Addressing with redesign in #2254
