### ISSUE TITLE
Ensure setupdb cleans up tile cache appropriately

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1511]
Most data loading tasks inside `setupdb.sh` have references to the data files they load, as well as the tile cache paths they're responsible for clearing out when data is reloaded. The DRB and MapShed tasks do not have tile cache purging paths, and at least the NHD streams paths are out of date.

**Comment by mmcfarland** [comment]
The streams are brought up to date via #1510 and the MapShed datasets aren't rendered as tiles.  Which one is the DRB task you're referring to?

**Comment by hectcastro** [comment]
I think you captured it (`drb_streams_v2 `) in #1510.

**Comment by mmcfarland** [comment]
Fixed via #1510
