### ISSUE TITLE
Modify color ramp for Water Quality Tiles

### ISSUE THREAD

**Issue by jfrankl** [WikiWatershed/model-my-watershed#1512]
Refers to #1507.

Update the color ramp for Water Quality Tiles with final colors.

@ajrobbins and @mmcfarland do you have an idea of the timeline for this?

**Comment by mmcfarland** [comment]
Some context:
6 data layers are being added to visualize specific water quality measures for 2 different feature types, Streams and Catchment areas.  A Catchment is a polygon area which contributes water flow at a single point.  The stream layer and the catchment layer both have attributes on 3 measurements of water quality (Total N, Total P and total TSS), these are broken down into quintile groups - essentially High -> Low.  The client suggested a R-Y-G diverging color ramp for streams and a gray shaded (light -> dark) for catchments.  It is possible to have the streams quality on at the same time as a the catchment quality, so they should have different colors.  The streams quality can't be on at the same time as other streams and the catchment can't be on at the same time as other polygons.

**Comment by kellyi** [comment]
#1509 has a first pass at catchment tile styling

**Comment by mmcfarland** [comment]
When adjusting the Red->Green stream colors, also invert the ramp so that low concentrations are associated with low concentrations.

https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/tiler/styles.mss#L106-L112

**Comment by ajrobbins** [comment]
Addressed in https://github.com/WikiWatershed/model-my-watershed/pull/1584
