### ISSUE TITLE
Exception: NO_LAND_COVER

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1515]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/135/](https://rollbar.com/Azavea/MMW/items/135/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/mapshed/tasks.py", line 162, in collect_data
    raise Exception(NO_LAND_COVER)
Exception: NO_LAND_COVER
```

**Comment by mmcfarland** [comment]
We generated this on purpose in RRP.  We have this exception explicitly now to catch and handle it in the UI, and have also implemented a front end guard that will prevent it from occurring in some workflows.  Basically, this error should be reduced, but if it slips through, it's handled by the UI in a graceful way (it basically means they drew a shape on a lake which doesn't have enough land cover data to run the model).  In terms of Rollbar, I think we may just want to Mute it - I don't think a fix that would prevent it from happening is possible, it's just a workflow we have to manage.
