### ISSUE TITLE
Investigate time out issues

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1516]
https://rollbar.com/Azavea/MMW/items/58/ and similar errors are coming in after the new release.

**Comment by arottersman** [comment]
**Here's a recap of some digging we did into this issue:**

There's not much info on rollbar about what might be causing these errors. We thought we'd inspect the `core_job` table in the production db to see if there was any more relevant info about the timed out jobs. Rollbar provides the `uuid` of a job, but when we queried the table for each occurrence's `uuid` we found nothing- no jobs with those `uuid`s. At the point of failure, the `uuid` hasn't been set/saved to the `task_chain.id` which seems to be what rollbar associates with it. This is all to say that when you want to look up a job with this error from the database, you have to look it up like this:
```SELECT * FROM core_job WHERE error ~ '^Job <whatever id the rollbar message has in its title>';``` 

Currently though, the attributes of the timed out jobs aren't too helpful for figuring out why they timed out. It'd be helpful to see the the shapes that are causing these timeouts. For reference, this is all going down in `mmw/apps/modeling/views.py start_celery_job` which takes a param `job_input` - in this case the AOI. On success we save the `job_input` as `model_input`, but on error we don't save it all.  https://github.com/WikiWatershed/model-my-watershed/blob/2c18298688d857f33d43513f49e4909dce923a36/src/mmw/apps/modeling/views.py#L564

**Comment by hectcastro** [comment]
This information may already be well-known, but my suspicion is that these jobs are being stopped by Celery after [enough retries occur](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/geoprocessing.py#L119-L130) to check the status of an SJS job.

Changes were made to the Spark configuration in the last release to give Spark more runway to complete a job that would have previously failed. I think we thought that guarding on a maximum AoI size would avoid timeouts like these from popping up, but perhaps our rough ratio of AoI size to timeout duration is off.

**Comment by mmcfarland** [comment]
Yeah, I agree.  The goal is now to start capturing some information about specific AoIs that fail so we can tighten up that guard based on their attributes.  Thanks for the info.
