### ISSUE TITLE
Modify Water Quality Catchment Overlay

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1522]
Connects #1512
Connects #1518 

We're adding a new tab to the analyze view that shows a table with catchment water quality data. When you hover over a row, the corresponding catchment appears on the map. Currently it's orange:
<img width="1007" alt="screen shot 2016-10-10 at 3 57 47 pm" src="https://cloud.githubusercontent.com/assets/7633670/19249766/1ebf3c8c-8f05-11e6-864f-509f35a7e1a0.png">

**Comment by ajrobbins** [comment]
Addressed in https://github.com/WikiWatershed/model-my-watershed/pull/1584
