### ISSUE TITLE
Password reset page is unstyled

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#1528]
https://app.wikiwatershed.org/accounts/password/reset/

![image](https://cloud.githubusercontent.com/assets/1042475/19281729/9259a9d4-8fb9-11e6-8b5f-d020a3ff5caa.png)

**Comment by arottersman** [comment]
Is the scope of this card just to space the elements properly?

**Comment by mmcfarland** [comment]
Yeah, baseline clean up: make the form space consistent (I'd suggest the label above the input) and reuse the button styling from elsewhere in the app.
