### ISSUE TITLE
Investigate Small Tablet Screen UI issues

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#1539]
Issue with dropdown menus overlapping on small screens:
- Android tablets, iPads, iPad minis
- Small touchscreen-enabled laptops?
- Layer selector menu covering things on analyze screen

Test on iPad, Android, and Windows tablet if possible

**Comment by kellyi** [comment]
Investigating and it looks like the active layer selector control takes up much of the map panel when the analysis sidebar's shown on iPad width devices:

<img width="814" alt="screen shot 2016-10-14 at 12 47 01 pm" src="https://cloud.githubusercontent.com/assets/4165523/19395610/7955a348-920c-11e6-89cd-58039dda519d.png">

It's slightly more reasonable when one toggles to hide the analysis sidebar:

<img width="864" alt="screen shot 2016-10-14 at 12 49 31 pm" src="https://cloud.githubusercontent.com/assets/4165523/19395651/b64b3c04-920c-11e6-9aea-5417ed9eacbe.png">

**Comment by mmcfarland** [comment]
I actually recall the issue being that the _analyze_ panel took up literally the entire screen.  I was able to replicate that behavior in the emulator by going to a phone sized device.  I think the question is, do iPad mini's display this behavior - or at one size screen does this become an issue.  I don't think it's in scope to adjust this for very small screens, but for iPad Mini and similar, we may have to.

![screenshot from 2016-10-14 12 59 34](https://cloud.githubusercontent.com/assets/1014341/19395904/159d7888-920e-11e6-9c81-468f41cd77d4.png)

**Comment by mmcfarland** [comment]
Since the Layer selector is toggleable, I don't think it's a huge issue that it covers a chunk of the map on small screens.

**Comment by kellyi** [comment]
Ah, got it. Just checked app.wikiwatershed.org on a phone and I think these are the specific issues:

Login modal is very large on iPhone 6 sized and smaller devices:

<img width="769" alt="screen shot 2016-10-14 at 1 06 59 pm" src="https://cloud.githubusercontent.com/assets/4165523/19396085/2a663466-920f-11e6-9e5f-2f47da50be2d.png">

Analysis/modelling sidebar takes up > 50% of the screen width on similar sized devices:

<img width="757" alt="screen shot 2016-10-14 at 1 07 46 pm" src="https://cloud.githubusercontent.com/assets/4165523/19396105/41f1480a-920f-11e6-80cf-e0576b7dd809.png">

These appeared to look ok on 10" screens, so I'll now check specifically Nexus 7 and iPad mini sizes.

**Comment by kellyi** [comment]
This is what the Chrome simulator looks like for iPad mini size:

<img width="915" alt="screen shot 2016-10-14 at 1 18 29 pm" src="https://cloud.githubusercontent.com/assets/4165523/19396363/c1b7ff60-9210-11e6-977e-d74cf95f276f.png">


<img width="883" alt="screen shot 2016-10-14 at 1 15 54 pm" src="https://cloud.githubusercontent.com/assets/4165523/19396287/613d38e4-9210-11e6-9f41-98c40a51ae46.png">

Here's the Chrome simulator for Nexus 7:

<img width="956" alt="screen shot 2016-10-14 at 1 17 58 pm" src="https://cloud.githubusercontent.com/assets/4165523/19396335/a8d7d40c-9210-11e6-9b9e-09e93977744d.png">


<img width="951" alt="screen shot 2016-10-14 at 1 17 21 pm" src="https://cloud.githubusercontent.com/assets/4165523/19396327/90664728-9210-11e6-94da-d87d1edbf621.png">

**Comment by kellyi** [comment]
iPhone 6 Plus size:

<img width="900" alt="screen shot 2016-10-14 at 1 29 54 pm" src="https://cloud.githubusercontent.com/assets/4165523/19396710/5e1ef038-9212-11e6-9f58-a17051dcb091.png">

<img width="905" alt="screen shot 2016-10-14 at 1 31 23 pm" src="https://cloud.githubusercontent.com/assets/4165523/19396742/88f52cd2-9212-11e6-99b3-40877b475ba1.png">

**Comment by kellyi** [comment]
Appears that devices with widths < 768px were not triggering a rule to force the width of the sign-on modal to be 400px. I think the idea may have been that the modal would fit entirely on the page without scrolling, but it doesn't.

If I adjust the rule to set the with to 400px at a `min-width` of 568px, devices sized between iPhone 5s and iPad minis have the modal sign on go from this:

<img width="636" alt="screen shot 2016-10-14 at 1 52 31 pm" src="https://cloud.githubusercontent.com/assets/4165523/19397419/cb52f96c-9215-11e6-895c-43bf34e24047.png">

to this:

<img width="643" alt="screen shot 2016-10-14 at 1 53 43 pm" src="https://cloud.githubusercontent.com/assets/4165523/19397428/d1a2bece-9215-11e6-9d24-412b604ff29e.png">

The user has to scroll to reach the rest of the form, but the user had to scroll to do that anyway even with the width set.

**Comment by kellyi** [comment]
I investigated this and it seems like issues begin to appear on screens narrower than 768px wide. 

The analysis tab took up <= half the screen width on iPad Mini and Nexus 7 sized devices.
