### ISSUE TITLE
Change "agrarian" to "agriculture" in catchment popup

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1546]
Popup when catchment ID is clicked under "Water Quality" tab of analyze:

![screen shot 2016-10-18 at 5 15 55 pm](https://cloud.githubusercontent.com/assets/12868342/19496701/b52a6eec-9556-11e6-89a6-64d8c88d8a39.png)

**Comment by lewfish** [comment]
Shares a point with #1537
