### ISSUE TITLE
Remove Django registration templates

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#155]
In the current mock-ups, logging in, signing up, etc. is all handled in a modal. We have basic templates from django-registration that add full pages for each of these steps. Do we want to use these? Or will we just stick to the modal?

If not, we should remove them. If so, we need mock-ups for them.

**Comment by ctaylo37** [comment]
I imagined when the user clicks "sign up" the login card flips horizontally and has the sign up form seemingly on the back of the card.  I can mock this up.  What are the required fields?  I lobby for first name, last name,  and email.  If there are additional fields we need from the user, we can send them an email to complete sign-up.

**Comment by caseypt** [comment]
Registration workflow using modals has been implemented. No need for the templates anymore.

**Comment by caseypt** [comment]
We are using some of these templates, but I think the following templates are not being used:

- activation_email_subject.txt
- logout.html
- registration_closed.html
- registration_complete.html

It's possible that some of the other templates are not being used.

**Comment by caseycesari** [comment]
Over time, this has proved to not be an issue.
