### ISSUE TITLE
Coverage layer slider overlaps layer control on tablets

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#1550]
#1548 enables the layer selector to work on touch screen devices like iPads, iPad Minis, etc. However, once the layer selector works, turning on one of the coverage layers causes the slider to appear overlapping the layer control icon.

To replicate the issue, start a version of `develop` once #1548 is in, use an iPad to access your running version at `<your-local>.local:8000`, tap the layer control, then select the overlays tab, then select one of the coverage layers. The slider will partially overlap the layer control button.

**Comment by ajrobbins** [comment]
The layer selector has been revamped.
