### ISSUE TITLE
Update link to to micro site

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1552]
The app currently has a link to the micro site from the Site Storm Model results tab, which currently points to http://app.wikiwatershed.org/micro.  We can avoid the redirect by updating this directly to http://micro.app.wikiwatershed.org instead.

![screenshot 2016-10-20 at 10 01 08 am](https://cloud.githubusercontent.com/assets/1014341/19562970/695e922a-96ac-11e6-9913-fd410abefc03.png)

**Comment by kellyi** [comment]
Shares a point with #1547

**Comment by mmcfarland** [comment]
Shares a point with #1547
