### ISSUE TITLE
Release 1.16

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1553]
Prepare for a new release targeting a release date of Tuesday 11/1.
##### Performance improvements
- Mapshed sub-jobs are spread across multiple workers
- Geoprocessing calls reduced for Site Storm Model by reusing Analyze census
- Job submission time at `/mapshed` is significantly reduced
##### New Features
- Water Quality Analysis results with catchment hover/popop
- 3 Stream Concentration Water Quality overlays 
- 3 Catchment Water Quality overlays

##### Bug fixes and other changes
- Micro Site available on subdomain and app redirects to it at `/micro`
- Failed celery jobs will persist input data in Jobs table to aid in debugging
- Bug fix to RWD shapes failing to draw, even though they were valid
- Point source observation vector loading is deferred from page load to Layer Selector open
- Facility Name is added to `point source` analyze popup
- Styled alert modals replace `window.alert`
- Prevent self intersecting AoI polygons from being drawn
- Prevent MapShed jobs from running when LC analyze results indicate there isn't appropriate LC coverage for success.
- Improved touch support for Overlay and Dropdowns for devices that use Touch + Mouse events, as well as certain orientations for tablets.

#### New/Updated Data

Two new water quality tables will be added.  They are grouped together under `setupdb.sh -q`
- nhd_water_quality.sql.gz
- drb_catchment_water_quality.sql.gz

#### New/Updated tiler styles requiring cache clear

None

#### Migrations

None

**Comment by kellyi** [comment]
I'd be interested in pairing to help out with this when it happens.

**Comment by hectcastro** [comment]
Do any of these style changes impact tiles that were created prior to #1509?

**Comment by mmcfarland** [comment]
No, they should all be for data/tiles that have never been rendered on production before, #1509 through #1584

**Comment by mmcfarland** [comment]
(reopened for sake of waffle.io points)
