### ISSUE TITLE
Upgrade django-registratrion-redux

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#156]
Example command output:

```
System check identified some issues:

WARNINGS:
registration.RegistrationProfile.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Operations to perform:
  Synchronize unmigrated apps: gis, watershed_model, staticfiles, geocode, messages, watchman, debug_toolbar, water_balance, humanize, rest_framework, analyze
  Apply all migrations: core, sessions, admin, predefined_shapes, contenttypes, auth, registration
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying core.0001_initial... OK
  Applying predefined_shapes.0001_initial... OK
  Applying registration.0001_initial... OK
  Applying sessions.0001_initial... OK
```

**Comment by maurizi** [comment]
This may have been fixed by version 1.2: https://github.com/macropin/django-registration/releases

**Comment by jamesmcclain** [comment]
I think that the page linked to above actually goes to django-registration-redux: If you go to https://github.com/macropin/django-registration then click on the pypi package 1.2 button
![screenshot from 2015-07-07 16 31 31](https://cloud.githubusercontent.com/assets/11281373/8556571/e7b195aa-24c5-11e5-96b1-24d586d53dd2.png)
you are sent to this page https://pypi.python.org/pypi/django-registration-redux/ .

**Comment by caseypt** [comment]
@jamesmcclain This package has a confusing lineage, but you are correct. The github repo linked above is the django-registration-redux repo, despite `redux` not being in the name.

For reference: https://bitbucket.org/ubernostrum/django-registration/wiki/Home

**Comment by jamesmcclain** [comment]
Okay, that makes sense.  Should I close this issue then?

**Comment by caseypt** [comment]
We still need to upgrade the library. We are currently using a version that isn't officially supported by Django 1.8.

We are [using 1.1](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/requirements/base.txt#L8). We need to upgrade to 1.2 and remove work around I mentioned above.

**Comment by jamesmcclain** [comment]
Oh, okay.  I had thought that the task was to migrate back to `django-registration`.  I'll keep going.
