### ISSUE TITLE
Fix: hover tooltip persists after view re-render

### ISSUE THREAD

**Issue by jtarricone** [WikiWatershed/model-my-watershed#1565]
![20161024_mmw_bug](https://cloud.githubusercontent.com/assets/18290666/19661787/0d3aa95c-9a03-11e6-944e-496dae758352.png)

It only appears to happen if the cursor remains on the chart region, making the tooltip for the chart active, when the asynchronous call returns and the view re-renders. The tooltip will then persist through all app states until a full refresh occurs.

**Comment by mmcfarland** [comment]
Nice job noting the steps to reproduce.  I've had this intermittently, but can get it every time with those steps.  

Tagging this as NSF since it was reported by classroom groups.
