### ISSUE TITLE
Analysis results excessively re-render

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1568]
While in a model project screen, switching between scenarios needs to re-render the model results (which differ between scenarios) but unnecessarily re-renders Analysis results (which are the same between scenarios.  When Analysis results contain large tables, this transition is extremely slow.  

The same statement could be said about transitions from Analyze -> Model more generally, is there a reason to re-render Analyze if it's already been done?

To see the long lag, select Bucks County and start a Site Storm model.  With ~5k water quality rows, switching between scenario tabs takes several seconds, even with improvements made in #1566

**Comment by ajrobbins** [comment]
I just tested Bucks on staging, and this issue seems to have been resolved.
