### ISSUE TITLE
Exception occurs when navigating away from modeling page before job completes

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1572]
When you start a modeling job, then go back to draw mode, the modeling job callbacks try to render results to views/regions that no longer exist.

![](https://cloud.githubusercontent.com/assets/7633670/19740461/bf498124-9b8c-11e6-9f37-01e2d8b22fd9.png)
#### Steps to reproduce
1. Draw AOI
2. Run tr-55
3. Press "back" twice
4. When polling completes for tr-55 job, there should be 2 exceptions in the console

**Note:** There should only be 1 exception in the console after #1564 has been merged.

**Comment by rajadain** [comment]
Also seeing this when there is a very large (~66000 sq km) AoI in TR-55 when analyze is not finished

**Comment by ajrobbins** [comment]
I followed these steps and see no errors in the console; this issue appears to have been resolved.
