### ISSUE TITLE
Retry SJS Celery Job on requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1573]
In some cases when there is a connection error between Celery and SJS, [this line](https://github.com/WikiWatershed/model-my-watershed/blob/90edb189e99848ce262f778996648a212ee603e3/src/mmw/apps/modeling/geoprocessing.py#L63) fails and throws a `requests.exceptions.ConnectionError` exception, which causes the entire Celery chain to fail.

Add a catch handler for that exception which retries the job instead. A-la:

``` python
try:
    response = requests.post(jobs_url, data=json.dumps(data))
except ConnectionError:
    if (retry):
        retry()
```

**Comment by hectcastro** [comment]
Only concern with doing it at the Celery level vs. Requests level is that we may not want to retry the HTTP request as many times as we might already be retrying the entire job.

An overview of retries at the Requests level is summarized nicely [here](http://www.coglib.com/~icordasc/blog/2014/12/retries-in-requests.html).

**Comment by rajadain** [comment]
We can also split this into it's own Celery task with a different number of retries.
