### ISSUE TITLE
Update analysis tab descriptions

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1577]
From Stroud:
- **Land:** Land cover distribution from National Land Cover Database (NLCD 2011)
- **Soil:** Hydrologic soil group distribution from USDA (gSSURGO 2016)
- **Animals:** Estimated number of farm animals
- **Point Sources:** Discharge Monitoring Report annual averages from EPA NPDES
- **Water Quality:** Delaware River Basin only: Stream Reach Assessment Tool model estimates.

**Comment by ajrobbins** [comment]
This should be targeted at the release branch.

**Comment by arottersman** [comment]
Shares a point with...
https://github.com/azavea/pwd-stormdrain-marking/issues/246
https://github.com/WikiWatershed/model-my-watershed/issues/1590
https://github.com/WikiWatershed/model-my-watershed/issues/1595
