### ISSUE TITLE
Sometimes the map tile requests stop resolving

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#158]
I haven't spent the time yet to figure out what's going on here, but this happens about once a week to me. 

At some point, when developing and refreshing the app a bunch oft times, the tile requests stop resolving:

![selection_010](https://cloud.githubusercontent.com/assets/1042475/7621333/056c09a2-f994-11e4-8666-a83377d8f8e2.png)

I've switched the tile provider, and that fixes the problem temporarily. But eventually, the same thing happens again. 

The only solution I've found is to reprovision the app VM.

**Comment by caseypt** [comment]
This hasn't happened since I upped the app VM to 1024 mb of RAM locally.

**Comment by mmcfarland** [comment]
Also has not happened to me, though my VM is unmodified.  Closing until we see this come back.

**Comment by caseypt** [comment]
This started happening to me again.
