### ISSUE TITLE
RWD not working on border of DRB

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1583]
RWD appears to not be working on the boundary edge, though Stroud reports that the point tested is indeed in the DRB and works on desktop GIS.

**To replicate:**
1. Search for "Avon Grove Intermediate School" and select the PA location
2. Zoom in, turn on the DRB streams, and select a point near the stream, between Avon Grove and Penn London schools
3. You should get an error message: Selected point is outside the DRB

**More info:**
>I’m working in the live version of MMW and have found an issue delineating a watershed on the western border of the DRB. Attached is a screenshot. It appears that the delineation function is not working on the boundary edge. It is working further within the DRB. We must be getting some kind of boundary effects. The location I’ve selected is within the DRB but near the edge (Avon Grove Intermediate School) in Chester County a little south of Rt. 1.

![delineateissue](https://cloud.githubusercontent.com/assets/12868342/19855500/4df930c4-9f4b-11e6-8366-1bd6d685f47f.PNG)

From David Tarboten:
> I experimented with this a bit to see if there was a problem with the underlying data for watershed delineation.  I was able to reproduce the problem on the live website, but when I go into a local GIS and enter the coordinates of a point as close as I could get to where Steve seems to be clicking, I am able to delineate a watershed.  The watershed delineated is below (yellow).
 
>Here is some technical information that may be helpful to Azavea in tracking this down.
 
>The longitude and latitude of point I am using is -75.883125  39.798818.  This lies within subwatershed number 2348.  This is what is highlighted.  If you look at the shapefile in \Main_Watershed\delaware_gw_5000_diss.shp from http://hydrology.usu.edu/mmw2/PreProcessed_Product_RWD/  this point should lie in shape with GRIDCODE 2348.  This should be used by the code to identify the subwatershed folder to start the watershed delineation.

![image002](https://cloud.githubusercontent.com/assets/12868342/19855520/72df7466-9f4b-11e6-8ba7-7e32c02f2435.png)

**Comment by ajrobbins** [comment]
This is likely due to the simplified DRB polygon we use to validate RWD requests on the front end.

**Comment by mmcfarland** [comment]
I think our best bet will be to either:
* simplify the polygon less, 
* buffer the polygon slightly (make it larger), then simplify to the same degree,
* leave as is, but do a distance check for the point to an edge and allow if it's within some tolerance.

Mostly we don't want the geojson size to increase substantially and be a large payload for page load.
