### ISSUE TITLE
Update setupdb.sh path to clear dep_urban_areas tiles

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#1595]
The `setupdb.sh` script seems like it may list the wrong path for clearing the `dep_urban_areas` tilers, so we should update it to match the dir where the tiler's storing the tiles.

**Comment by hectcastro** [comment]
As it stands currently, `setupdb.sh` needs to replace the following:

- `dep_urbanareas -> urban_areas`
- `dep_municipalities -> municipalities`

```bash
❯ aws --profile mmw-prd s3 ls s3://tile-cache.app.wikiwatershed.org | egrep "urban|muni" 
                           PRE municipalities/
                           PRE urban_areas/
```

**Comment by arottersman** [comment]
Shares a point with...
https://github.com/azavea/pwd-stormdrain-marking/issues/246
https://github.com/WikiWatershed/model-my-watershed/issues/1590
https://github.com/WikiWatershed/model-my-watershed/issues/1577
