### ISSUE TITLE
Build TR55 geoprocessing endpoint

### ISSUE THREAD

**Issue by jwalgran** [WikiWatershed/model-my-watershed#16]
Added to the skeleton service in #11

## TR55 Service Description

Counts the number of cells in the area of interest for each unique combination of land use and soil type.

### Inputs

Input                            | Type
------------------------------|---------------
NLCD + Custom local | Raster(s) (static)
Soil Type + Custom local | Raster(s) (static)
Calculation Area | Polygon (per request)
BMPs | Set(PolygonWithTypeCodeAttribute) (per request)
Land Cover Changes | Set(PolygonWithTypeCodeAttribute) (per request)


### Outputs

(Assuming 2 soil types, 2 land use types, and 2 BMP types)

```javascript
{
  "result": {
    "cell_count": N, // equals the sum of all values under distribution
    "distribution": {
      "soilA:landUseA": N,
      "soilA:landUseB": N,
      "soilA:BMP1": N,
      "soilA:BMP2": N,
      "soilB:landUseA": N,
      "soilB:landUseB": N,
      "soilB:BMP1": N,
      "soilB:BMP2": N,
      "NODATA", N
    }
  }
}
```

or

```javascript
{`
  "error": {
    "message": "boom!"
    "trace": "blah at line 2"
  }
}
```

**Comment by mmcfarland** [comment]
Implemented
