### ISSUE TITLE
Update MapBox account

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1602]
Change Mapbox account info from Sara's personal to Stroud general account.

**Comment by rajadain** [comment]
Where's the information kept? I only see Sara's on the wiki

**Comment by ajrobbins** [comment]
Waiting on final account info from Stroud; I'll mark this as blocked in the meantime.

**Comment by mmcfarland** [comment]
We have the credentials for the account and I put them in the CA LastPass folder.
