### ISSUE TITLE
Smarter caching of JS/CSS assets

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1607]
*NSF feature request*

Presently, the app uses a combination of headers (`Cache-Control`, `ETag`, `Last Modified` and `Expires`) to control the caching of JS & CSS assets (vendor and bundle).  In practice, after a deployment the user must manually refresh the browser several times to see consistent changes - and if that doesn't happen, they will often report a bug, the solution to which is to refresh the browser.

I do see `If-None-Matched` getting sent on the request and a `304` being returned as result.  Investigate if other cache headers are conflicting with the intended behavior, or if we should implement more drastic features like adding a hash to the built assets and having the references in `index` templated at build time.

**Comment by hectcastro** [comment]
Is it easy enough to append a checksum of the static asset bundles? That would allow us to continue to be aggressive on the caching front, but also avoid staleness issues on the frontend.

**Comment by lewfish** [comment]
It wouldn't be too difficult. I just think we should go with the builtin etag mechanism which checks the server to see if it the content needs to be sent, unless the network overhead of the check is really a problem.
