### ISSUE TITLE
Release 1.17

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1615]
The final planned release under the OSI contract, release scheduled for 12/7.

#### Features
* RWD based from NHD derived data.  A new UI option for Mid-Atlantic RWD is present which returns large but simplified polygons
* Styles account pages (password reset)
* Buffered area for RWD front end validation
* Point source analyze results show entire total
* Production relies on ETag caching for static assets and reduced max-age cache
~ITSI anonymous mode~
* Small bug fixes (perennial ice, RWD text updates)
* Decreased polling for model/analyze results

#### New/Updated Data
* Catchment Water Quality (`setupdb.sh -q`)
* The EBS volume with RWD data has been updated to `snap-090ac799996dba0a4` - the snapshot is shared with the production account.

#### New/Updated tiler styles requiring cache clear
* Cached tiles related to Catchment quality data overlay, as above.
* No independent style changes.

#### Migrations
* ~~https://github.com/WikiWatershed/model-my-watershed/commit/c599556d6e51f5c885a822f8766c11677bec8303 - we may want to modify this to be backwards compatible.  The dark stack will generate exceptions while saving projects until the migration has been run on the production RDS.~~ This has been reverted
* 822bc71bc8153db2b403bcaadb65755e7563ddb2 - a data migration that clears out cached results for some saved projects.  Entirely backwards compatible.

Originally 8 pts

**Comment by kellyi** [comment]
- 1 for https://github.com/WikiWatershed/model-my-watershed/issues/1614

**Comment by mmcfarland** [comment]
+3 from https://github.com/WikiWatershed/rapid-watershed-delineation/issues/45

**Comment by arottersman** [comment]
-1 for https://github.com/WikiWatershed/model-my-watershed/issues/1632

**Comment by arottersman** [comment]
-1 for https://github.com/WikiWatershed/model-my-watershed/issues/1635

Did this start at 8pts and now has 9?

**Comment by kellyi** [comment]
Just in case we need to note it here: the water quality table is being updated in #1634 for this release, which I think might mean needing to clear those cached tiles too.

**Comment by mmcfarland** [comment]
The tile cache is purged by virtue of running the particular data update:  https://github.com/WikiWatershed/model-my-watershed/blob/develop/scripts/aws/setupdb.sh#L129-L136

If you mean the overlay that happens on hover from the water quality table, those aren't tiles but vectors loaded fresh from the database and don't need to be recreated.
