### ISSUE TITLE
Add Stroud center logo to header bar

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1618]
Per Stroud: 
>Add a small Stroud Center logo to the black bar at the top of every page of the MMW app

All-white logo is attached (delete the .txt extension). May need @jfrankl consult to see if this looks ok/take it out of AI format

[stroud_logo_white_text_white_waves.ai.txt](https://github.com/WikiWatershed/model-my-watershed/files/604388/stroud_logo_white_text_white_waves.ai.txt)

**Comment by jfrankl** [comment]
Please use this png with transparency: http://sandbox.azavea.com/stroud-logo.png

Please apply the following css to the image, through a class or other means.

```css
height: 24px;
position: relative;
top: -2px;
```

**Comment by caseypt** [comment]
The link to the image above doesn't resolve anymore, so I created a new version of the AI file, which is attached here for reference.

![stroud-logo](https://cloud.githubusercontent.com/assets/1042475/20633657/122794ac-b317-11e6-8700-29232f7216c6.png)
