### ISSUE TITLE
Update point source and water quality data

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1624]
Updated catchement water quality data (shapefile) and point source data is here: https://drive.google.com/file/d/0B0H6Pk_Y-GvtTm55TTVydFFjUE0/view?usp=sharing

I _think_ the last file is the water quality by stream reach data.

There should be no schema changes.

**Comment by jtarricone** [comment]
I imported/dumped the shapefile and uploaded it to S3; I looked fine in my testing. @rajadain  would you mind reloading your database to confirm?

**Comment by rajadain** [comment]
Reloading database now.

**Comment by rajadain** [comment]
Okay the data is in. Anything specific I can look at to confirm?

**Comment by jtarricone** [comment]
Maybe try loading the DRB layers, or else browse them using qgis or something. I was less worried about the data itself than about configuring S3 correctly.

**Comment by rajadain** [comment]
Just loaded (in a fresh `services` VM) the DRB and Water Quality layers, they loaded correctly. The S3 configuration seems to be working.

**Comment by rajadain** [comment]
Just tried the rest, they're working too. 👍
