### ISSUE TITLE
Total N value is low

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1625]
In the Water Quality tab, the values for "Total N (kg/ha) differ from the `tn_tot_kgy` field in the shapefile. I'm thinking it might be a unit conversion problem?

For example, check out the value for catchment #1994, located just southwest of center city, west of the Schuylkill:

MMW - 
![screen shot 2016-11-28 at 5 39 16 pm](https://cloud.githubusercontent.com/assets/12868342/20690533/2b9f3186-b599-11e6-864c-ddaf8c5cd5f7.png)
![total_n](https://cloud.githubusercontent.com/assets/12868342/20690561/5602fc1e-b599-11e6-84d2-b699a5347f35.png)

final_lateralshed_11_28_16 file - 
![screen shot 2016-11-28 at 6 37 00 pm](https://cloud.githubusercontent.com/assets/12868342/20690639/cfcacb6c-b599-11e6-84fd-94d6e3e2bf7a.png)

**Comment by jtarricone** [comment]
It's because the displayed value is on a per-hectare basis. "Total N" might not be the clearest name but the units indicate how the value is derived.

**Comment by jtarricone** [comment]
It also may be notable to hydrologists that the basis of measurement is kilogram-years, I can't speak to that.

**Comment by ajrobbins** [comment]
I thought the units in both cases (source data and the data we are displaying) were kg/yr/ha. Are we using the `tn_tot_kgy` field for our Total N field in the app? If so, are we doing any conversions on it?

**Comment by jtarricone** [comment]
The app is dividing `tn_tot_kgy` by `areaha`, which presumes that the UoM of `tn_tot_kgy` is kg-years.

**Comment by mmcfarland** [comment]
I agree that it's working as requested - we're dividing kg by area.  They requested results to be shown as kg/ha.  It could be that the source data `tn_tot_kyy` is not the unit the name implies, but the conversion looks correct based on the labels.

**Comment by jtarricone** [comment]
Based on this --> http://ec.europa.eu/eurostat/statistics-explained/index.php/Agri-environmental_indicator_-_gross_nitrogen_balance

It seems like the UoM of `tn_tot_kgy` may actually be kg-yr/HA (or kg / HA /year, assuming equivalence), since it looks like the standard way of measuring nitrogen surplus.

**Comment by mmcfarland** [comment]
Yeah, some of the emails anticipating the data being delivered claim it will already be per ha.  @ajrobbins can you confirm that `tn_tot_kgy` is already per ha?  If so, we can just drop the division.

**Comment by jtarricone** [comment]
The other "total" fields are also divided by the area, are those suspect as well?

**Comment by ajrobbins** [comment]
I'll check, thanks for the clarification @jtarricone

**Comment by ajrobbins** [comment]
Confirmed by Scott Haag, the `tn_tot_kgy` is already divided by area, we are currently double dividing it. He says Total TSS and Total P are also already divided by area, so we should fix those as well.

**Comment by ajrobbins** [comment]
Are we making any conversions on Average TN, TP or TSS?

**Comment by jtarricone** [comment]
The averages appear to be unmodified in the front end.
