### ISSUE TITLE
Update Water Quality Data

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1634]
There was another revision to the water quality figures, so we need to update the data as was done in https://github.com/WikiWatershed/model-my-watershed/issues/1624. Data is on the fileshare at /data/catchement_water_quality/lateralsheds_12_06_16

**Comment by jtarricone** [comment]
I uploaded the data to S3; @rajadain or @arottersman can one of you check it out? It should be enough to just drop the tables in the `services` VM and rerun the database setup script, then do a few things in the app that touch those tables.

**Comment by jtarricone** [comment]
It looks like the `tss_rip_kg` is missing after the import, so I'm going to restore the backup on S3. @ajrobbins is this more likely a problem with the import or with the shapefile?

**Comment by jtarricone** [comment]
I looked at the DBF file and it appears the field is not there.

**Comment by ajrobbins** [comment]
I think this field was renamed from `tss_rip_kg` to `tss_ripari` in the newest data.

**Comment by jtarricone** [comment]
I redid the import and changed the field name to `tss_rip_kg`, and uploaded the file to S3, if someone wants to try importing it.

**Comment by rajadain** [comment]
Giving it a go

**Comment by rajadain** [comment]
The import worked correctly. Regarding the discrepancy in rows, I'd advise keeping the last find around in case we need to switch it.

**Comment by jtarricone** [comment]
I'll create a `backup` directory in S3.

**Comment by jtarricone** [comment]
I refreshed the staging database as well.
