### ISSUE TITLE
Snapshot has offset map in some cases

### ISSUE THREAD

**Issue by scytacki** [WikiWatershed/model-my-watershed#1639]
You can test this by
1. logging into the [ITSI portal](https://itsi.portal.concord.org). 
2. Then open this URL: https://authoring.concord.org/activities/5644
3. Scroll down until you see the MMW interactive.
4. Click the interactive to open it
5. Change the Basemap to "Satellite with Roads"
6. Select a square kilometer somewhere not in the center of the map.
7. Take a snapshot.

You should see something like this:
![screen shot 2016-12-09 at 12 39 57 pm](https://cloud.githubusercontent.com/assets/86016/21058590/abf5bfd2-be0c-11e6-9da0-93898d004113.png)

Look in the "Editing snapshot" window. Notice the grey bar on the left and notice the map tiles are shifted right and no longer line up with the selection box.

If you switch the Basemap to something else. And then switch it back to "Satellite with Roads" then the problem goes away. This type of problem occured before the `itsi_embed=true` parameter was added.  I believe it has to do with leaflet using 3d css transforms to move the tiles around.  The snapshot service doesn't handle 3d css transforms. So `itsi_embed=true` is supposed to disable these transforms.  It seems the "Satellite with Roads" is still using them.

**Comment by mmcfarland** [comment]
Related to #1640, most likely same issue.  Shares points.
