### ISSUE TITLE
Update RWD data volume

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1642]
Update RWD data volume AMI snapshot ID to the latest version.

Depends on https://github.com/WikiWatershed/rapid-watershed-delineation/issues/46

**Comment by hectcastro** [comment]
Is the data needed on the volume going to increase?

**Comment by kdeloach** [comment]
We may need up to 500GB depending on how effective data compression is.

See https://github.com/WikiWatershed/rapid-watershed-delineation/issues/46#issuecomment-267411647

**Comment by hectcastro** [comment]
There is some good information around compression and TIFFs [here](https://github.com/landsat-pds/landsat_ingestor/blob/master/Compression.md).

**Comment by kdeloach** [comment]
This was pointed too high. We should change this from 3 points to 1 point next sprint.
