### ISSUE TITLE
Define model packages

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#165]
Model packages contain the following:

- A name (ex. TR-55)
- A list of modification tools (ex. land cover drawing tool, conservation practice drawing tool)
- A list of input tools (ex. rainfall parameter selector)

@mmcfarland and I briefly discussed this. There will likely be nothing stored in the database regarding the package.

Consider a JSON structure that then can be used to construct UI tool components with Backbone models and views for the modeling page.

**Comment by mmcfarland** [comment]
This has been implemented through various commits linked to here.  There may ultimately be more work, but closing in favor of new issues when necessary.
