### ISSUE TITLE
Update NHD boundary

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1656]
Create a simplified NHD v2 boundary for the frontend, to avoid running RWD if the clicked point is outside of the data bounds.

The current boundary exists for a single region, but the updated NHD dataset covers the entire US.

**Comment by kdeloach** [comment]
The simplified NHD boundary has been uploaded to the GDrive here (thanks @ajrobbins):

> Stroud >NHDPlus>RWDContUSA>Main_Watershed.zip>domainfromregions.shp

Ref: https://github.com/WikiWatershed/rapid-watershed-delineation/issues/53

**Comment by rajadain** [comment]
Effectively in effect via #3661
