### ISSUE TITLE
Allow viewing large watersheds that cannot be analyzed

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1657]
With the recent addition of National RWD, it is possible to generate watershed which are too large to be analyzed or modeled.  Currently, it results in a warning and then removes the polygon in the map.  The behavior should instead be that the polygon is viewable, but the user is unable to move to the analyze step.  The message should still be displayed, somehow.  Consult design to agree on a conceptual workflow.

**Comment by kdeloach** [comment]
We should also gracefully handle errors if watershed is null.

![image](https://cloud.githubusercontent.com/assets/43062/21994219/95c0a3f0-dbec-11e6-9d3e-cbc2aa24fd84.png)

![image](https://cloud.githubusercontent.com/assets/43062/21994200/8211d77a-dbec-11e6-9be2-205875279954.png)
