### ISSUE TITLE
Display current lat lng on map

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1662]
Create a new map control which displays the current lat lng under the cursor for debugging purposes.

**Comment by rajadain** [comment]
I think it would be kinda cool if this was inside a function that we could trigger. So it wouldn't show up automatically, but if we were to open the console and type in `MMW.debug();` it would. This would allow us to debug even production.

**Comment by kdeloach** [comment]
While implementing this, I realized that it might make more sense to just attach the leaflet map to `window`. Then you could easily call `getCenter` or `setView` etc. in staging/production.

**Comment by rajadain** [comment]
We could also do

```js
var map = MMW.getLeafletMap();
map.getCenter();
```

Since `MMW` is attached to `window` already. But references are cheap, and making debugging easier is useful.

**Comment by kdeloach** [comment]
Oh, I didn't realize that. Very cool.
