### ISSUE TITLE
No support for `Intl` in Safari

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1668]
Can't load the app at all in safari
<img width="1279" alt="screen shot 2017-01-18 at 4 04 33 pm" src="https://cloud.githubusercontent.com/assets/7633670/22082945/d2c8bf10-dd97-11e6-9817-60d1a7b3aa1c.png">

Fails when trying to use `Intl` (not supported by Safari) for formatting:
https://github.com/WikiWatershed/model-my-watershed/blame/73294b47e3fcf6e09dc0822736ce8eabe9a14841/src/mmw/js/src/core/filters.js#L9

We should consider using https://github.com/andyearnshaw/Intl.js

**Comment by mmcfarland** [comment]
Great catch.  We should be able to accomplish the same with `toFixed` and `toLocaleString('en')` like we do elsewhere in the app, without needing another dependency.

**Comment by rajadain** [comment]
I don't see any issues in the latest Safari:

![image](https://cloud.githubusercontent.com/assets/1430060/22896840/9f8a3acc-f1ef-11e6-9c6f-5339fe8fdbc0.png)

I also see that ES Internationalization Standard was added to Safari recently

 * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Browser_compatibility
 * https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html

It seems to be supported on all major desktop and tablet browsers. Should we still make the switch?

/cc @ajrobbins

**Comment by mmcfarland** [comment]
Interesting, I thought it was strange that we hadn't received the report before.  @arottersman what version are you running, and is it still crashing?

**Comment by arottersman** [comment]
Yes, still can't load staging. Running `9.1.1`

**Comment by rajadain** [comment]
This change was added in #1566, and it seems the general consensus at the time was that it was indeed working and useful. Not sure if we are obligated to support older versions of browsers.

I think the cost of lowering performance on _all_ browsers is too high to support an older version of _one_ browser, especially one that doesn't have too much market share.

Is anyone opposed to closing this card?

**Comment by ajrobbins** [comment]
We are not obligated to support older versions of browsers, so I'm ok with closing this. Sorry, Alice...

**Comment by arottersman** [comment]
Guess I should finally update safari 😢

**Comment by rajadain** [comment]
Thanks. Feel free to bring in another 1 pointer in its place.
