### ISSUE TITLE
Implement model input tools

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#167]
Depends on #165

The model input tools provide input parameters to the model, such as the amount of rainfall.

There needs to be a two-way relationship between these tools and the scenarios. For example, when setting the rainfall value to 2", this value gets pushed to the scenario. Then, we reloading this project, the slider should be set to 2" based on the stored value in the scenario.

Ex (though I think this is being converted to a simple slider).

![selection_018](https://cloud.githubusercontent.com/assets/1042475/7656009/baae08da-faf5-11e4-89ea-614e56f34cdf.png)

**Comment by mmcfarland** [comment]
Correct, replace the drop down with a slider.  We'll have to see what range and increments are appropriate, so for now, lets just do .05 to 6 with half inch tics.

**Comment by mmcfarland** [comment]
Reminder that this input tool is associated with the tr55 model package.  The UI description will be client side only as part of that backbone model, but the value should be stored as `inputs` - which doesn't exist yet - on the scenario django model as serialized json, similar to `modifications`.
