### ISSUE TITLE
Layer Picker visible during login

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1677]
Currently the new layer picker is visible when the login modal hides everything else:

![image](https://cloud.githubusercontent.com/assets/1430060/22299374/cd0d6954-e2f1-11e6-866f-dd19ef558949.png)

It should also be hidden / darkened at this stage.

**Comment by rajadain** [comment]
Also consider adjusting the style so it has the same kind of outline / drop shadow as all other map controls:

![image](https://cloud.githubusercontent.com/assets/1430060/22299440/155a1360-e2f2-11e6-8d31-ff4134ac23c2.png)

**Comment by mmcfarland** [comment]
Perhaps the map(ish) element should be the parent of the layer selector, as it was before.
