### ISSUE TITLE
Fix Scenario renaming behavior

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1682]
When the user tries to rename a scenario by selecting "Rename" from the dropdown, the default tab title is not highlighted and the cursor is at the beginning of the text. It's also not possible to double click on the title to edit the whole thing.

![screen shot 2017-02-03 at 11 04 25 am](https://cloud.githubusercontent.com/assets/12868342/22598282/ea046a60-ea00-11e6-8aa4-6ab0078ee9ec.png)

Selecting "rename" should select the default scenario name text to facilitate easier renaming.

**Comment by rajadain** [comment]
This has _always_ annoyed me
