### ISSUE TITLE
Update Stroud logo

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1686]
Logo file is attached, use https://github.com/WikiWatershed/model-my-watershed/issues/1618#issuecomment-262029222 for css rules

Converted to png format:
![stroud-white-white](https://cloud.githubusercontent.com/assets/12868342/22740283/1f7abb10-eddd-11e6-8b61-d9c2661c2559.png)

Original, in svg format (remove `.txt`):
[stroud-white-white.svg.txt](https://github.com/WikiWatershed/model-my-watershed/files/760788/stroud-white-white.svg.txt)

**Comment by mmcfarland** [comment]
shares a point with #1668
