### ISSUE TITLE
Add "original clicked point" when RWD is initiated

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1687]
A visual cue that the process is underway.

**Comment by kellyi** [comment]
#1693 creates the marker and it should work on RWD success & failure, but I'm still setting up the RWD data on my local so I've only checked the failure case so far.

**Comment by kellyi** [comment]
Got RWD data set up and tested the success case. It worked, so I assigned #1693 for review.
