### ISSUE TITLE
Implement project drop-down functionality

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#169]
May want to start with some of the basic stuff first, then move on to *My Projects* and *New Project*.

![selection_020](https://cloud.githubusercontent.com/assets/1042475/7656730/705386d4-fafa-11e4-9848-61e9ee190fa7.png)

**Comment by mmcfarland** [comment]
Let's just implement Rename and Delete for this issue.  Share and Print are not ready yet, and Add Tags will be its own thing.
