### ISSUE TITLE
Description text at top of model output tabs

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#1690]
@ajrobbins, last week we had a question come in from a MMW.

> How do I determine the lbs/year load reduction form the water quality data? Is the 'Load (kg)' already in kg/yr? If so, I can convert it to lbs.

This helped me realize the need for some text at the top of each of the Model output tabs, similar to what we have at the top of the Analyze output tabs. Here are some suggestions.

For the Site Storm Model:
* Hydrology: "Water fluxes in a single, 24-hour hypothetical storm event as simulated by SLAMM & TR55 model algorithms. "
* Water Quality: "Total loads delivered in a single, 24-hour hypothetical storm event as simulated by EPAs STEP-L model algorithms. "

For the Watershed Multi-Year Model:
* Hydrology: "Average monthly water fluxes in cm (= 10 L per square meter) from 30-years of simulated daily water balance calculated by the GWLF-E (MapShed) model."
* Water Quality: "Average annual loads from 30-years of simulated daily fluxes calculated by the GWLF-E (MapShed) model."

Please suggest edits. Let's put this in the queue to implement sooner than later.

**Comment by ajrobbins** [comment]
@aufdenkampe I agree, some explanatory text for the model tabs makes sense. Tagging @jfrankl to consider styling for this and the analysis description text for future UI updates.

For the text:

**Site Storm Model**
- Hydrology (runoff): What about something like:
"Results of a 24-hour hypothetical storm event as simulated by SLAMM & TR55 model algorithms. "
- Water quality: looks good, I'd remove "single" for brevity

**Watershed Multi-Year Model**
- Hydrology: I'm confused by the unit conversion. To clarify, does 1cm water depth = 10L per square meter?
- Water Quality: how about "Average annual loads from 30-years of daily fluxes simulated by the GWLF-E (MapShed) model."

**Comment by aufdenkampe** [comment]
@ajrobbins, thanks for the feedback. I like your wording suggestions. 

Is it possible to include these short text explanations in the present UI? I'm thinking they could go in the top of each of the Model tabs, just like we do with the Analyze tabs. I assume the machinery is all there, and it would be very nice to include this text sooner than later (as in the next release). Let me know if this might be possible. I'm getting questions about these details and minor differences several times per week.

To clarify the third item, it is a unit conversion. 1 cm of rain on a square meter of land equals 1% of a cubic meter. Given that a cubic meter is 1000 L, then 1 cm of rain is 0.01 m3/m2 or 10L/m2. We do that unit conversion for the user in the Site Storm Model Hydrology tab, but not in the Watershed Multi-Year Model. Let's move forward without my parenthetical unit conversion but perhaps think about whether to include a unit conversion for the table.

**Comment by ajrobbins** [comment]
@aufdenkampe sounds good. **Here is the final wording**:

**Site Storm Model**
Runoff tab: "Results of a 24-hour hypothetical storm event as simulated by SLAMM & TR55 model algorithms. "
Water quality tab: "Total loads delivered in a 24-hour hypothetical storm event as simulated by EPA's STEP-L model algorithms. "

**Watershed Multi-Year Model**
Hydrology tab: "Average monthly water fluxes in cm (= 10 L per square meter) from 30-years of simulated daily water balance calculated by the GWLF-E (MapShed) model."
Water quality tab: "Average annual loads from 30-years of daily fluxes simulated by the GWLF-E (MapShed) model."

These labels should be placed above the charts/tables in their respective tabs, as we've done for the analysis tab: 
![mmw](https://cloud.githubusercontent.com/assets/12868342/23141814/99166b10-f786-11e6-9186-32a674a94605.png)

**Comment by aufdenkampe** [comment]
This all looks great! Thanks.

**Comment by aufdenkampe** [comment]
@rajadain & @ajrobbins , let's simplify the text for

Watershed Multi-Year Model, 
Hydrology tab: "Average monthly water fluxes in centimeters from 30-years of daily water balance simulated by the GWLF-E (MapShed) model."
