### ISSUE TITLE
RWD Draw Tool Issues

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1708]
Noticed 2 issues on staging when delineating a DRB watershed:

1. Null reference exception happens when you delineate a point outside of DRB bounds. I believe there is a condition where we try to remove `rwdClickedPoint` from the map before it gets created.

2. Reset button does not clear the `rwdClickedPoint` marker.

**Comment by kellyi** [comment]
Possibly part of the same bug but it looks like clicking "Reset" doesn't actually stop RWD from running. On staging, for instance, you can click to start an RWD job, then click "Reset" and everything will appear to have cleared except the marker. However, it seems like the polling continues and the RWD shape will eventually load if the app's left alone after clicking reset.

I'm guessing that the deferred's not rejecting on clicking "Reset", which would explain why the fail block doesn't trigger immediately for the original clicked point marker.

**Comment by kdeloach** [comment]
Good point. If we can easily reject the deferred when the reset button is pressed, I think it's worth doing. But if it's too much of a hassle then maybe we should leave it as-is. More important is fixing the null reference error.

**Comment by kellyi** [comment]
Going to check whether other kinds of polling results have the same behavior.

**Comment by kellyi** [comment]
Investigated a little more and it does seem like the deferred's not rejecting on clicking the reset button/calling `reset()` on the `rwdTaskModel`. I got a hacky version of rejecting this to work by giving the taskModel a reference to the deferred object for whatever polling is currently taking place, then doing something like

```js
if (this.rwdTaskModel.defaults.defer) {
    window.console.log('rejecting');
    this.rwdTaskModel.defaults.defer.reject('rejected');
}
```

in the function called on clicking the "Reset" button; rejecting the deferred here causes the polling to cease after about 5 more tries, then displays the standard failure error message.

I'm tempted to spin handling that off into another issue, as I think an actual fix involves a more through update to the task model. Incidentally, I *think* the non-rejected-deferred may also be what causes these errors when running TR-55 then immediately clicking the back arrow and waiting a bit for the results to trigger an error:

<img width="917" alt="screen shot 2017-02-28 at 11 21 51 am" src="https://cloud.githubusercontent.com/assets/4165523/23415016/e19fc978-fdab-11e6-8c33-2e0bb06e2635.png">

<img width="931" alt="screen shot 2017-02-28 at 11 21 58 am" src="https://cloud.githubusercontent.com/assets/4165523/23415022/e5aa4002-fdab-11e6-97fe-e2204b8287e7.png">

In that case I think the `reset` call on leaving the TR-55 results tab doesn't cause its polling to stop either, but when it resolves with data the container where it belongs is gone.

**Comment by kellyi** [comment]
Spoke with @ajrobbins and I'm going to work on fixing the second so that we'll have it in the release; otherwise we should remove the initial clicked RWD point altogether.
