### ISSUE TITLE
Layer selector text too light

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1725]
I have trouble reading the text of the layer selector options in Chrome on Linux, disabled text is nearly invisible.

Normal and disabled:
![screenshot from 2017-03-07 13 40 39](https://cloud.githubusercontent.com/assets/1014341/23672160/c070febc-033b-11e7-940e-d65ef2ab2c28.png)

A highlighted row is easy to see

![screenshot from 2017-03-07 13 44 02](https://cloud.githubusercontent.com/assets/1014341/23672258/235feba0-033c-11e7-84a9-9a5e47db8d15.png)

@jfrankl Can we darken these?

**Comment by jfrankl** [comment]
Yes definitely let's do that.
