### ISSUE TITLE
Left align UI elements

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#1731]
I think the header text, map controls, and layer selector should all have the same left alignment.

<img width="296" alt="mmw-align" src="https://cloud.githubusercontent.com/assets/1042475/23719254/9a654c32-0408-11e7-8566-cb8005785f12.png">

**Comment by caseycesari** [comment]
The text in the header has a left padding of `1rem`. Setting this on the search bar and layer picker results in this:

<img width="304" alt="screen shot 2017-03-08 at 2 24 59 pm" src="https://cloud.githubusercontent.com/assets/1042475/23719905/0a44b0fe-040b-11e7-8923-b68b6cd169d8.png">

**Comment by mmcfarland** [comment]
Closing, the new UI doesn't have left justified map tools.  The search bar is right-justified with the map controls in the new version, as well.

![screenshot from 2017-08-31 15 37 13](https://user-images.githubusercontent.com/1014341/29941980-4c2ab090-8e62-11e7-8ea8-44a4779374af.png)
