### ISSUE TITLE
Download analyze and model results as CSV

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1736]
Each panel of analysis and model results should get a "Download Data" treatment as displayed on p1 of the wireframes (p9, shows additional panel). These datasets are smallish and already loaded into the browser.  Rather than generate additional load on the server, or cache them there, we should attempt to assemble the downloadable CSV from the content the browser has already assembled for display.  Are there disadvantages from doing this?

I've used and have had good experience with http://papaparse.com/.  It can be evaluated for use in this feature. 

https://drive.google.com/drive/folders/0B0hs2mX4ApaLN0xLSjY0cVhDckk

**Comment by kellyi** [comment]
Q to clarify the desired behavior for this:

Each panel should get a download button which creates a CSV using *only* the data visible on that panel -- and *not* the data visible on the panel + the other data?

**Comment by mmcfarland** [comment]
Yes, this is intended to be a per-dataset download, we won't be making a zip file of multiple results at once.
