### ISSUE TITLE
Allow overlay layer association from Analyze

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1745]
As per p16 of the wireframes, a section is added to analyze pages that have a corresponding layer in the layer control. For example, the `Land` tab should allow toggling on the NLCD.  

* Some tabs don't have a layer (Animals)
* Some tabs may have multiple layers.
    * Water quality is NHD catchment, which can be visualized on TN, TSS or TP
* Some tabs are "obeservations" (Point Source)

https://drive.google.com/drive/folders/0B0hs2mX4ApaLN0xLSjY0cVhDckk

**Comment by mmcfarland** [comment]
@jfrankl I missed this in earlier wireframe reviews.  Can you advise on approach for the point above where there are multiple layer associations for an Analyze tab?  In this case, there are 3 layers for the "Water Quality" tab.

**Comment by arottersman** [comment]
For more context, here are the layers, and what they look like all stacked on top of one another:

![screen shot 2017-03-28 at 10 16 34 am](https://cloud.githubusercontent.com/assets/7633670/24409930/aa23de1c-139f-11e7-943a-8a501ec8ee8a.png)

**Comment by arottersman** [comment]
Also @jfrankl what shade of blue should the "Turn on/Turn off" be?
