### ISSUE TITLE
Expand map button is visible in compare view on staging

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1747]
![screen shot 2017-03-23 at 9 14 02 am](https://cloud.githubusercontent.com/assets/12868342/24249419/92554b9e-0fa9-11e7-829e-ddc1b238303a.png)

We had the same issue in the bee pollinator app: https://github.com/project-icp/bee-pollinator-app/issues/39

**Comment by arottersman** [comment]
Shares a point with #1749
