### ISSUE TITLE
Add minimize/collapse button to layer selector

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1748]
Currently, clicking on the active layer type icon collapses the layer selector into its bottom bar. We've gotten reports from Stroud that this is not discoverable enough, so we should consider adding an explicit minimize button to the layer selector.

**Comment by ajrobbins** [comment]
@jfrankl thoughts?

**Comment by jfrankl** [comment]
I think adding a caret to the layer selector would make the collapse functionality more discoverable:

![image](https://cloud.githubusercontent.com/assets/1809908/24406310/0224e200-1396-11e7-8eb9-a2eadbbb9246.png)

In this case, clicking on the caret or "Coverage" would collapse the layer selector. Clicking on the active icon would continue to collapse the layer selector.

**Comment by ajrobbins** [comment]
@jfrankl I think that the caret makes it kind of look like a collapsible list, like we have on TNC. I would expect clicking the caret to collapse the list items into "coverage", not necessarily collapse the whole layer selector. Could we do a caret or other minimize icon at a level above the "coverage" title?

**Comment by jfrankl** [comment]
It's going to make the layer picker take up more space. Worth trying?

**Comment by ajrobbins** [comment]
Yes, I think the tradeoff is worth it if it makes it easy to minimize completely.

**Comment by jfrankl** [comment]
Sounds good. Here are two directions—please send feedback.

### Variation 1
#### Open
![open](https://cloud.githubusercontent.com/assets/1809908/24408326/56f735ee-139b-11e7-832f-f81fb2187297.png)
#### Closed
![closed](https://cloud.githubusercontent.com/assets/1809908/24408327/56f8a442-139b-11e7-9dda-1c95f52706d2.png)

### Variation 2
#### Open
![open](https://cloud.githubusercontent.com/assets/1809908/24408335/5f5f0b3a-139b-11e7-8952-64a905800587.png)
#### Closed
![closed](https://cloud.githubusercontent.com/assets/1809908/24408340/6100749c-139b-11e7-8322-84a53cdfb71e.png)

**Comment by ajrobbins** [comment]
I like var. 2

**Comment by rajadain** [comment]
I like var 2 as well. It seems like clicking the black title bar will re-open the last opened tab?

At first I thought that the highlight on the tab selector area should persist even when collapsed, but rethinking it I like the way it looks in the screenshot. The tab highlight should only be visible when the tab itself is visible. Clicking any tab should expand the selector (if it isn't already) set to that tab.

**Comment by jfrankl** [comment]
A third option is to not show the icons at all while the layer picker is selected:

![closed copy](https://cloud.githubusercontent.com/assets/1809908/24414831/78af4912-13ad-11e7-9fac-a329150d26fa.png)

@ajrobbins @rajadain curious which you think works best. One takes up less space, the other makes it faster to jump back into a particular set of layers.

@rajadain I agree that the previously selected tab should persist when the layer selector is reopened.

**Comment by rajadain** [comment]
I think option 2 is a good balance of space and utility.

**Comment by ajrobbins** [comment]
agreed, +1 for option 2
