### ISSUE TITLE
Estimate SoilP value

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1752]
Calculate “Soil P” value (second position `[Pload, SedPhos]` on Line 37 of “*.gms” file (see “MapShed GMS File Key.doc” for further detail). This particular value is currently calculated using a lookup table. The current approach is to be replaced by this newer approach below.

Procedure:
* Use new `soilpallland2` grid to calculate this value (#1751)
* For a given AOI, calculate the weighted average value
* Calculate the new `Pload` value as the weighted average x 1.6, and write this value to Line 37

Depends on #1751

**Comment by arottersman** [comment]
Swapped out of queue for #1804

**Comment by mmcfarland** [comment]
Note: Here "weighted average" indicates a proportional weight for the total area a particular value has compared to the total AoI area.  This can be accomplished identically with a simple average of all cell values within the AoI.

**Comment by kellyi** [comment]
Swapped out for #2103

**Comment by arottersman** [comment]
Moved ingests done in #1751 to better conform to our MMW ingest conventions:

`s3://datahub-catalogs-us-east-1/soilpallland2_5070/soilpallland2_5070/0/` --> `s3://datahub-catalogs-us-east-1/soilpallland2-epsg5070/0/`

`metadata` json moved to `_attributes` dir at the top level of the bucket.
