### ISSUE TITLE
Ingest SoilN raster

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1753]
Ingest new raster provided as `soiln`.

Ensure that projection, extent & grid size are compatible with our other layers if this layer is to be used in conjunction with them.

**Comment by arottersman** [comment]
Ingest complete. For consistency, I did this the same way we did the other two sibling layers `soilpalland2` and `bfigrd48`: with the default gt etl class using the input/output jsons. 

* [Commit with configs, commit message has any pre-processing steps](https://github.com/azavea/civic-apps-etl/commit/271c8fbd7edce9846665ab50097a81621dfdd91d)

* raw chunks in  `s3://datahub-rawdata-us-east-1/soiln_5070/chunks`

* final layer in `s3://datahub-catalogs-us-east-1/soiln_5070`

-------

Original raster metadata
```
Metadata:
    STATISTICS_MAXIMUM=2200
    STATISTICS_MEAN=344.91944809522
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=194.92818066816
```

Layer cell type is `int16, tile size `256x257`
