### ISSUE TITLE
Estimate SoilN value

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1754]
Calculate `Soil N` value (first position `[SedNitr]` on Line 37 of “*.gms” file (see MapShed GMS File Key.doc for further detail). This particular value is now set by default as `2000`.

Procedure:
* Use new “soiln” raster to calculate this value ( #1753 )
* For a given AOI, calculate the “weighted average”
* Calculate the new `SedNitr` value as the weighted avg x 4.0, and write this value to Line 37

Depends on #1753

**Comment by arottersman** [comment]
@rajadain moved ingests done in #1751 to better conform to our MMW ingest conventions:

`s3://datahub-catalogs-us-east-1/soiln_5070/soilpn_5070/0/` --> `s3://datahub-catalogs-us-east-1/soiln-epsg5070/0/`

`metadata` json moved to `_attributes` dir at the top level of the bucket.
