### ISSUE TITLE
Ingest bfi48grd raster

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1755]
Ingest new raster provided as `bfi48grd`.

Ensure that projection, extent & grid size are compatible with our other layers if this layer is to be used in conjunction with them.

**Comment by mmcfarland** [comment]
For reference, extent and projection should match our other ingests and use the smallest datatype appropriate for the values.

```
CRS=EPSG:5070
LAYOUT_EXTENT=-2493045.000,177285.000,2342655.000,3310005.000
```

**Comment by arottersman** [comment]
Ingest is here: `s3://datahub-catalogs-us-east-1/bfi48grd_5070`

This raster was even coarser than `soilpallland2`:

```
Pixel Size = (5360.720562390157284,-5360.720562390157284)
```
Stats
```
 Minimum=0.000, Maximum=255.000, Mean=194.036, StdDev=81.224
  Mask Flags: PER_DATASET ALPHA
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=194.03568594957
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=81.224485012157
Band 2 Block=999x2 Type=Byte, ColorInterp=Green
  Minimum=0.000, Maximum=255.000, Mean=194.036, StdDev=81.224
  Mask Flags: PER_DATASET ALPHA
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=194.03568594957
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=81.224485012157
Band 3 Block=999x2 Type=Byte, ColorInterp=Blue
  Minimum=0.000, Maximum=255.000, Mean=194.036, StdDev=81.224
  Mask Flags: PER_DATASET ALPHA
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=194.03568594957
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=81.224485012157
Band 4 Block=999x2 Type=Byte, ColorInterp=Alpha
  Minimum=255.000, Maximum=255.000, Mean=255.000, StdDev=0.000
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=255
    STATISTICS_MINIMUM=255
    STATISTICS_STDDEV=0
```
Branch with configs: https://github.com/azavea/civic-apps-etl/commit/2978041b78cf7f5539d8bddd7212476550e0f45f

#### Process
- Original raster on fileshare in .adf format --> converted to .tif with QGIS
- Projected to 5070 w gdal
`gdalwarp -overwrite -t_srs EPSG:5070  -of GTiff raw/bfi48grd.tif raw/bfi48grd_5070.tif`
- Chunked
`gdal_retile.py -of GTiff -co compress=deflate -targetDir raw/bfi48grd_chunks/ raw/bfi48grd_5070.tif`
- Uploaded chunks to s3
`aws s3 cp --recursive raw/bfi48grd_chunks/ s3://datahub-rawdata-us-east-1/bfi48grd_5070/chunks --profile arottersman`
- Ran ingest
`make local-ingest`

**Comment by rajadain** [comment]
Does this mean we can use Int8 for this?

**Comment by arottersman** [comment]
Yes — the original raster is type `Byte`. The ingest should have inherited it.
