### ISSUE TITLE
Estimate the Local Groundwater Recession Coefficient

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1756]
Calculate the “Groundwater Recession Coefficient” value (second position `[RecessCoef, RecessCoef]` on Line 2 of “*.gms” file (see “MapShed GMS File Key.doc” for further detail). This particular value is currently set by default as `0.06`.

Procedure:
* Use the new `bfi48grd` grid to calculate this value ( #1755 )
* For a given AOI, calculate the weighted average
* Calculate the new `RecessCoef` value as `RecessCoef = (-0.0015 x weighted avg) + 0.1103`

Note: if calculated value is _EDIT: less than_ `0`, set `RecessCoef = 0.01`

Depends on #1755

**Comment by mmcfarland** [comment]
Note: Here "weighted average" indicates a proportional weight for the total area a particular value has compared to the total AoI area.  This can be accomplished identically with a simple average of all cell values within the AoI.

**Comment by arottersman** [comment]
Moved ingests done in #1755 to better conform to our MMW ingest conventions:

`s3://datahub-catalogs-us-east-1/bfi48grd_5070/bfi48grd_5070/0/` --> `s3://datahub-catalogs-us-east-1/bfi48grd-epsg5070/0/`

`metadata` json moved to `_attributes` dir at the top level of the bucket.
