### ISSUE TITLE
Implement UI for shapefile/geojson upload

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#1760]
Move the UI to the sidebar and add a file selector input (per the wireframes, once  #1743 is in).

We'll also need a loading spinner, though most tests I have done are instantaneous.

We should also add an area in the UI where we can list the requirements:
- Must be a shapefile or geojson
- Less than 200 MB
- Only the first feature is used.

**Comment by caseycesari** [comment]
After some feedback from the client, we'll also need to make changes to how this works.

Instead of accepting a `.shp` file, we should accept only a zipfile that contains all of component parts that make up a shapefile. 

For now, just unzip the file and add the shape to the map as before.

We'll still be accepting geojson files directly.

**Comment by caseycesari** [comment]
This may be useful: https://gildas-lormeau.github.io/zip.js/

**Comment by arottersman** [comment]
@caseycesari any reason you suggest `zip.js` over `JSZip` https://www.npmjs.com/package/jszip ? It seems like `zip.js` is a little better managed and more actively developed, but there's no npm package.

**Comment by caseycesari** [comment]
Nope! They both seem like they are worth a try.
