### ISSUE TITLE
Display boundary layer search results

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1762]
Update the geocoder component to query the boundary layers search endpoints and combine results in the autocomplete dropdown. Clicking the result in the dropdown should display the feature on the map and zoom to the boundary layer extent.

Page 9 of [2017_03_16_mmw-v6.pdf](https://drive.google.com/open?id=0B0hs2mX4ApaLUlhaaWNYTE5CMEk) has a mock up of how the geocoder results dropdown should change as a result of this feature.

![screenshot 2017-03-23 at 17 39 03](https://cloud.githubusercontent.com/assets/43062/24271463/a3cddb2a-0fef-11e7-8c85-b96567bb235f.png)

**Comment by kdeloach** [comment]
Depends on #1765

**Comment by kdeloach** [comment]
For the initial iteration, could we just limit the total number of boundary suggestion to 5 or 10, instead of adding a "view more" link to the search box results?

![image](https://cloud.githubusercontent.com/assets/43062/25093579/d9cc4bc4-2360-11e7-8ed6-ea7a789bf8c6.png)

@jfrankl ^

**Comment by ajrobbins** [comment]
>For the initial iteration, could we just limit the total number of boundary suggestion to 5 or 10, instead of adding a "view more" link to the search box results?

I think it's fine to limit to 5 results for this iteration.
