### ISSUE TITLE
Determine list of data API sources

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1764]
Research which data sources we will support and develop a strategy to interact with them.

Considerations:

* Fetch metadata in real-time or ahead of time?
* How frequently should we refresh metadata?
* Should we proxy all API requests through the backend? Or should all API requests be client-side only?

**Comment by kdeloach** [comment]
Waiting to receive a concrete list of APIs to support before proceeding any further.

**Comment by kdeloach** [comment]
We're ready to reevaluate the list of API data sources, so this is no longer blocked. We'll use text search instead of multiple facets, and we'll fetch everything in real-time in one synchronous server-side request.

**Comment by mmcfarland** [comment]
### CINERGI
An esri geoportal implementation, though the api syntax doesn't seem to match the general geoportal implementation at a quick pass.

By inspecting the XHR requests powering the portal, a free text query can be constructed via:
POST http://132.249.238.169:8080/geoportal/elastic/metadata/item/_search?from=0&size=10

Request Payload (`aggregations` is not clear to me if it is necessary or useful):
```json
{
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "analyze_wildcard": true,
                        "query": "diamond"
                    }
                }
            ]
        }
    },
    "aggregations": {
        "id_uniqName_7_2": {
            "geohash_grid": {
                "field": "envelope_cen_pt",
                "precision": 2
            }
        },
        "id_uniqName_7_3": {
            "nested": {
                "path": "timeperiod_nst"
            },
            "aggregations": {
                "dates": {
                    "date_histogram": {
                        "field": "timeperiod_nst.begin_dt",
                        "interval": "year",
                        "min_doc_count": 1
                    }
                },
                "endDates": {
                    "date_histogram": {
                        "field": "timeperiod_nst.end_dt",
                        "interval": "year",
                        "min_doc_count": 1
                    }
                }
            }
        },
        "id_uniqName_7_4": {
            "date_histogram": {
                "field": "sys_modified_dt",
                "interval": "day",
                "min_doc_count": 1
            }
        },
        "id_uniqName_7_5": {
            "terms": {
                "field": "sys_owner_s"
            }
        },
        "id_uniqName_7_6": {
            "terms": {
                "field": "apiso_TopicCategory_s"
            }
        },
        "id_uniqName_7_7": {
            "terms": {
                "field": "sys_metadatatype_s"
            }
        },
        "id_uniqName_7_8": {
            "terms": {
                "field": "contact_organizations_s"
            }
        },
        "id_uniqName_7_9": {
            "terms": {
                "field": "keywords_s",
                "size": 20
            }
        },
        "id_uniqName_7_10": {
            "terms": {
                "field": "src_source_name_s",
                "size": 20
            }
        },
        "id_uniqName_7_11": {
            "terms": {
                "field": "categories_cat",
                "include": "science domain.*",
                "size": 1000
            }
        },
        "id_uniqName_7_12": {
            "terms": {
                "field": "categories_cat",
                "include": "material.*",
                "size": 1000
            }
        },
        "id_uniqName_7_13": {
            "terms": {
                "field": "categories_cat",
                "include": "property.*",
                "size": 1000
            }
        },
        "id_uniqName_7_14": {
            "terms": {
                "field": "hierarchies_cat",
                "include": "category.*",
                "size": 1000
            }
        }
    }
}
```

**Comment by mmcfarland** [comment]
## HydroShare

Hydroshare API docs: https://github.com/hydroshare/hydroshare/wiki/HydroShare-REST-API

Hydroshare python API: http://hs-restclient.readthedocs.io/en/latest/

**Comment by mmcfarland** [comment]
## QUASHI
TBD. http://data.cuahsi.org/

**Comment by mmcfarland** [comment]
## IEDA
Lower priority, hold off on backend

http://www.iedadata.org/services/sesar_api

**Comment by kdeloach** [comment]
### CUASHI
http://hiscentral.cuahsi.org/webservices/hiscentral.asmx
http://hiscentral.cuahsi.org/webservices/hiscentral.asmx/GetWaterOneFlowServiceInfo (according to https://www.cuahsi.org/standards)

### HydroShare
DRF API Endpoint (slow): https://www.hydroshare.org/hsapi/resource/

### CINERGI
APIs: http://cinergi.sdsc.edu/api/
Geoportal: http://cinergi.sdsc.edu/geoportal
Example ESRI Rest API Request: http://cinergi.sdsc.edu/geoportal/rest/find/document?searchText=diamond&f=pjson
