### ISSUE TITLE
RWD click/snap points persisting across projects

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1767]
If I create a project with an RWD AoI, then launch a different project, the click & snap points from the first project persist in the second. To replicate:
- Log in to MMW
- [If you don't have any project saved] create and name a new project, can be anything
- Create a project using RWD
- Navigate to your first project and zoom/pan so that the click & snap points from your RWD are in view

As you can see here, this is a project based on a County AoI but RWD click & snap points are visible:
![screen shot 2017-03-24 at 10 19 52 am](https://cloud.githubusercontent.com/assets/12868342/24298148/81bddc92-107b-11e7-9796-30ddad201015.png)

**Comment by kellyi** [comment]
I was able to replicate this via the steps described above:

<img width="1021" alt="screen shot 2017-03-24 at 11 44 06 am" src="https://cloud.githubusercontent.com/assets/4165523/24301918/3b2323d0-1087-11e7-909c-147bde651b38.png">

**Comment by kellyi** [comment]
Investigating this a bit more and it looks as if the RWD points are cleared when selecting a new aoi via the draw & boundary selection tools, so I assume that switching between projects skips past a clearing step that we're performing there.

**Comment by kellyi** [comment]
More detail: the points are cleared when the a new drawing option, boundary option, or reset is clicked.

**Comment by kellyi** [comment]
This is the fn getting called there: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/draw/views.js#L825
