### ISSUE TITLE
Analyze results should be recalculated after Project reload

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1768]
Analyze results for a given AoI can get out of sync with the currently loaded AoI if the geometry is switched out due to navigating to a saved project.  Loading a saved project should retrigger an `/analyze` request.

Reproduce the bug with the following steps:
1. Log into your MMW account
1. Select an AoI by any means, and observe the Analysis results
![screenshot from 2017-03-24 10 16 25](https://cloud.githubusercontent.com/assets/1014341/24297967/fa9199de-107a-11e7-80a2-d40f79dad4c8.png)
1. Navigate to Site Stormwater model and the project is saved by doing so
1. Rename the project to something meaningful for this test
1. Navigate back to the Draw screen and create a new AoI, preferably somewhere were the land cover details will be significantly different than your previous AoI.  A river or lake will do.
1. Navigate to Analyze
1. In the upper right corner, select My Projects and choose to launch the saved project from the previous steps
1. When the project loads, notice that the analyze results still represent the previous AoI.  This should have triggered a re-analyze and update the UI.  The name of the project was refreshed, but not the output.
![screenshot from 2017-03-24 10 18 46](https://cloud.githubusercontent.com/assets/1014341/24298070/4793c662-107b-11e7-90ae-631881d75d39.png)

**Comment by rajadain** [comment]
It is possible that [`fetchAnalysisIfNeeded`](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/controllers.js#L134) needs to be added somewhere in [here](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/controllers.js#L20).
