### ISSUE TITLE
Zoom control vertically stacked on Firefox

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#1782]
<img width="436" alt="screen shot 2017-04-03 at 11 53 41 am" src="https://cloud.githubusercontent.com/assets/4165523/24618182/45ff251c-1864-11e7-96e2-becf28da0bfa.png">

**Comment by rajadain** [comment]
Seems to be okay on latest develop using latest Firefox:

![image](https://cloud.githubusercontent.com/assets/1430060/24815813/904640e0-1ba4-11e7-97a3-4b7157d93952.png)

Do I have to do something to get it broken?

**Comment by kellyi** [comment]
Probably worth having a third person check this as staging still looks like this for Firefox on my local:

<img width="640" alt="screen shot 2017-04-07 at 4 02 37 pm" src="https://cloud.githubusercontent.com/assets/4165523/24817745/c50b035e-1bab-11e7-96f1-315e857a7cdc.png">

**Comment by kellyi** [comment]
(Running the same FF version, btw.)

**Comment by rajadain** [comment]
I just checked Staging as in your screenshot, and that looks okay too:

![image](https://cloud.githubusercontent.com/assets/1430060/24817891/5637cdbc-1bac-11e7-9d1e-f79171012728.png)

Can another person verify this?

**Comment by arottersman** [comment]
Looks fine on mine, and I'm assuming @caseycesari  (we both tested all major browsers for this change's PR https://github.com/WikiWatershed/model-my-watershed/pull/1769#pullrequestreview-28982451 )
![Uploading Screen Shot 2017-04-07 at 4.14.04 PM.png…]()

**Comment by caseycesari** [comment]
Yeah, still fine for me in Firefox:

![image](https://cloud.githubusercontent.com/assets/1042475/24908553/69ea3680-1e8e-11e7-84f2-349746248bf2.png)

**Comment by kellyi** [comment]
This looks to have been happening because I had `touch_events_enabled` set to true in Firefox's `about:config`:

<img width="769" alt="screen shot 2017-04-11 at 11 06 05 am" src="https://cloud.githubusercontent.com/assets/4165523/24916016/e0e0313c-1ea6-11e7-912d-21c7f9ee87f2.png">

It turns out this triggers Leaflet to apply a `leaflet-touch` class to the entire leaflet-container which then reduces the width of the zoom control box by 2 pixels, narrowing it enough that it dips beneath the 80px width threshold required for the buttons to display horizontally & not stack.

This possibly means that Windows laptops with touch screens see the same behavior in Firefox, assuming Firefox's default config for such devices is to set `touch_events_enabled` true.

**Comment by rajadain** [comment]
I'm going to test on touch-enabled versions of Chrome, IE, Edge, and Firefox to see if they exhibit this bug.

**Comment by ajrobbins** [comment]
@rajadain I can do this testing, I'm doing full QA this sprint.
