### ISSUE TITLE
Indicate active draw tool, option, or boundary in pane

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#1784]
From a comment on #1778 

> clicking on a tool doesn't appear to do anything unless you know how to use it on the map. There could be some sort of active styling on the selected tool to alleviate this

**Comment by kellyi** [comment]
> One thing for a follow up card; for "Select by Boundary", when you choose a layer it should become highlighted in a way other than the browser focus highlight.

**Comment by jfrankl** [comment]
Should be addressed by #1835.

**Comment by caseycesari** [comment]
Closed by https://github.com/WikiWatershed/model-my-watershed/issues/1835
