### ISSUE TITLE
Adjust draw tools "Reset" behavior

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#1785]
From a comment on #1778:

> I'm sure @jfrankl can speak to this better, but I wonder if the reset button should be for each tool, not each tool dropdown. Currently the "x" looks like it should close the accordion, not reset the drawing. Alternatively, maybe it'd be better to have explicitly "Reset"

**Comment by jfrankl** [comment]
This should be addressed by #1835.

**Comment by rajadain** [comment]
Closing this in favor of #1835
