### ISSUE TITLE
WQ Results for 100% forest identical to current conditions

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#1786]
This came in on our bug report form:

I've been playing for it for 2 days and done at least 12 projects, each with 2-4 scenarios.  When I hit "compare" the runoff calculations seem to work fine, but the water quality calculations always show the "100% forested" and "current condition" graphs to be identical.  This even with extremely urban watersheds.  It seems like the wq model is not pulling from the current land cover data correctly(?)  Or, I guess the problem could be with the 100% forested scenario calcification but the loadings numbers are always quite low, so I'm guessing the problem is with the current conditions.

An example scenario:
https://app.wikiwatershed.org/project/11682/scenario/20037

**Comment by SRGDamia1** [comment]
Sorry, I forgot to clarify that this is a problem in the site-storm model.

**Comment by ajrobbins** [comment]
I clicked on the above linked scenario and am seeing very different 100% forest vs. Current Condition results:

![screen shot 2017-04-06 at 1 55 19 pm](https://cloud.githubusercontent.com/assets/12868342/24768510/c3c036c6-1ad0-11e7-94d5-475333cae848.png)

I'm going to continue to try to replicate with other scenarios, but perhaps this was a caching issue with an already-fixed bug.

**Comment by SRGDamia1** [comment]
@ajrobbins - your screenshot is of the runoff output, which looks fine.  It's the water quality output that's the problem.  When looking at the water quality bar graphs, everything always looks the same because of the different scales ( #1046 ), so it's hard to tell there's any problem.  But if you hover over to get the numbers, you see they are *exactly* the same between current conditions and 100% forest.  The different scenarios do have different numbers, though.

**Comment by ajrobbins** [comment]
My mistake! In what situation should we be seeing the biggest difference, for testing purposes? Highly developed urban environments? @SRGDamia1

**Comment by SRGDamia1** [comment]
Yes, I think the biggest differences would be in urban environments.
