### ISSUE TITLE
Odd "units" appear in WQ in the compare view for site-storm model

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#1787]
When the numbers in the pop-over for the water-quality compare view switch to a different unit than the typical kg/ha, the new units do not appear correctly.  Instead of seeing "mg/ha", we see "m kg/ha."

This screenshot is taken from the same scenerio as in #1786 : https://app.wikiwatershed.org/project/11682/compare

![capture](https://cloud.githubusercontent.com/assets/5374350/24720143/1de0c408-1a0a-11e7-8be7-80a91ea68d77.JPG)

**Comment by ajrobbins** [comment]
Confirmed - hover over the phosphorus part of the bar graph (very small, at top of bar) to replicate.

**Comment by mmcfarland** [comment]
The charting library adds `micro-` and `milli` symbols to very small decimal values for the labels.

![screenshot from 2017-04-13 10 01 06](https://cloud.githubusercontent.com/assets/1014341/25008370/7b384586-2031-11e7-8a9b-57eaa3552caf.png)

Also for the y axis ticks, if it is overall small enough.  

![screenshot from 2017-04-13 10 07 06](https://cloud.githubusercontent.com/assets/1014341/25008240/26208914-2031-11e7-9f50-fce348ebf95c.png)

This could probably be overridden in some fashion, however it's really more of a conceptual problem arising from using a stacked bar chart to represent these water quality numbers.  Unlike runoff, there is no "whole" value for which these are component parts of, and which could have equal axis ranges for comparison purposes.  This also makes it difficult to compare small proportional sections, like phosphorous, across the different scenarios when there are much larger quantities of other unrelated components.

I'd advise not investing time in trying to resolve these labeling inconsistancies here, and instead have it resolved from https://github.com/WikiWatershed/model-my-watershed/issues/1046 when each component of water quality is independent.  At that time, it may make sense to adjust the units from kg/ha to mg/ha dynamically depending on the scale of the values across all scenarios.

**Comment by SRGDamia1** [comment]
I think that's wise.

**Comment by mmcfarland** [comment]
Compare being rewritten with new charts.
