### ISSUE TITLE
Sidebar doesn't scroll if content is too long

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#1792]
To reproduce, copy and paste the `p` element that is at the top of the sidebar until the contents of the sidebar are moved off-screen. 

<img width="481" alt="screen shot 2017-04-06 at 12 43 05 pm" src="https://cloud.githubusercontent.com/assets/1042475/24765660/9b9913ca-1ac6-11e7-881a-aa00eafafe7f.png">

**Comment by rajadain** [comment]
Similar work was done here: https://github.com/project-icp/bee-pollinator-app/pull/151
