### ISSUE TITLE
Improve tooltip interactivity

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#1793]
https://github.com/WikiWatershed/model-my-watershed/pull/1791 introduced tooltips that open on click instead of hover, and that are closed by clicking anywhere. This generally works well, but it may not be clear that the tooltip can be closed by clicking anywhere. We could add a close button for this (there appear to be [many solutions](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=add+close+button+to+bootstrap+popover&*), though none are that clean).

Also, when clicking anywhere to close the tooltip, you may click on another interactive element of the app. It's not clear if this is desirable. To prevent this, we could add a transparent mask over the app when a tooltip is activated that captures clicks and closes the tooltip.

**Comment by arottersman** [comment]
Tooltip doesn't work when is activated, but it probably should. This is especially noticeable when waiting for RWD to finish.

**Comment by kellyi** [comment]
Cataloguing some desired behavior for this:

- [ ] tooltip should close on clicking anywhere outside the tooltip, but those clicks shouldn't propagate through to other elements
- [ ] tooltip should close on clicking the ? icon a second time when it's already open
- [ ] tooltip should have an X to close button somewhere
- [ ] tooltips should be open-able when the draw tools are active

Should the tooltip close on clicking the tooltip text? Or only on the X to close button? If it's the former, we could just add a placebo X to close and have the cursor turn into a pointer on hovering over it, since clicking anywhere on the tooltip would close it already.

**Comment by kellyi** [comment]
> Tooltip doesn't work when a tool is activated, but it probably should. This is especially noticeable when waiting for RWD to finish.

Investigated this and got the circumstances in which this happens narrowed down somewhat. I started replacing the `a` tags we used to trigger these popovers with `button` elements instead. Currently it looks like what happens is that:

- click on a draw tool to activate it disables that tool's button and the other draw tool buttons in that slideout
- the tooltips in that slideout are also non-functional at that moment
- clicking on a draw different draw tool to open its slideout renders it with the draw tool buttons disabled but the popover buttons working
- clicking on the active draw tool's button to open its slideout again renders it as before except the popover buttons now work

I assume there's something happening to the whole slideout on activating a draw tool which causes everything to be non-functional except the close button. This probably also doesn't happen inherently on first rendering the thing, and the slideouts are all re-created anew each time they're opened.

**Comment by kellyi** [comment]
(Checked staging and the popovers also currently behave a described there.)

**Comment by kellyi** [comment]
Also notably this does not happen with the boundary selection tool, which is a component in which the boundary options are not disabled automatically when another tool is active.

**Comment by kellyi** [comment]
Looks like the `SelectAreaView` is the only one of these tools which doesn't call `this.render()` in response to the `change:toolsEnabled` model event.

**Comment by kellyi** [comment]
I think the tooltip is disabled if `render` is called again at all on an existing tool's slideout, regardless of what's happening in the model.
