### ISSUE TITLE
Add support for reprojecting uploaded shapefiles to web mercator

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#1800]
Depends on #1761 

We should expect that shapefiles will be uploaded in many different projections. We should determine the projection, and if needed, reproject the shape to web mercator

This library may be useful https://github.com/perliedman/reproject.

We could also support this for GeoJSON if the file contains the `crs` block.

**Comment by ajrobbins** [comment]
FYI from David Tarboten on how HydroShare handles this:
>Following up on the call today, code we have in HydroShare for handling shapefiles that we receive in arbitrary projections is in
https://github.com/hydroshare/hydroshare/blob/develop/hs_geographic_feature_resource/parse_lib.py
 
>There is also similar code for handling rasters in
https://github.com/hydroshare/hydroshare/blob/develop/hs_file_types/raster_meta_extract.py
 
>Note that this does not do exactly what you want.  It identifies the projection, extracts a bounding box and converts that to WGS84 coordinates.  Hopefully this provides an example of the use of ogr transformation information that it could be applied to the shapes you ingest.
