### ISSUE TITLE
Uniform Height of Map Controls

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1803]
Currently the Layer Selector buttons are less tall than map controls. This looks odd when the layer selector is collapsed:

![image](https://cloud.githubusercontent.com/assets/1430060/24883493/1b41df7c-1e13-11e7-9acf-a820334cf2ac.png)

Either make the layer selector tab bar taller, or the map controls shorter / smaller.

**Comment by ajrobbins** [comment]
Now that we have a header bar that's there when the selector is collapsed, I find the height differential less noticeable:
![screen shot 2017-04-12 at 5 08 04 pm](https://cloud.githubusercontent.com/assets/12868342/24979567/af6121d2-1fa2-11e7-94d8-d5d6def8c2e9.png)

**Comment by rajadain** [comment]
Agreed. Closing this.
