### ISSUE TITLE
Staging Broken on iPad

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1804]
![img_0091](https://cloud.githubusercontent.com/assets/1430060/24916184/6ada64de-1ea7-11e7-9101-187ef7197276.png)

Tried in Safari and Chrome. Production works correctly.

**Comment by kellyi** [comment]
Here are instructions for debugging iPad Safari by connecting it to a Mac:

https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html

**Comment by kellyi** [comment]
This is the first LOC at which staging fails on iPad:

<img width="817" alt="screen shot 2017-04-11 at 2 45 59 pm" src="https://cloud.githubusercontent.com/assets/4165523/24925262/b00b866e-1ec5-11e7-8183-a67486a706c7.png">

**Comment by rajadain** [comment]
Ah this is #1668. We should try and test using a current iPad to see if it fails there too.

**Comment by kellyi** [comment]
I think it'll pass on a current iPad if the compatibility matrix here is correct:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

However, looks like it would fail on Android altogether.
