### ISSUE TITLE
Add Promise polyfill To Support Uploading Zips on IE11

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1820]
`JSZip` uses the native `Promise` which aren't supported on IE11 out of the box.

**Comment by mmcfarland** [comment]
`JSZip` also claims to use an internal shim, though it doesn't appear to actually do it in our usage.

https://stuk.github.io/jszip/documentation/api_jszip/external.html

**Comment by mmcfarland** [comment]
Turns out `JSZip` is correctly filling  `Promise` internally as it claims, it's the `shapefile` library however that's referencing native Promises.

https://github.com/mbostock/shapefile/blob/master/index.js#L26
