### ISSUE TITLE
No error or warning should show when draw action is canceled.

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#1827]
To reproduce:

- Navigate to the select area page.
- Expand the "Draw area" section.
- Select "Free Draw"
- Click the "X" in the "Draw area" section.
- An error modal is displayed.

Clicking the "X" should act as a cancel and no error message should be displayed.

**Comment by caseycesari** [comment]
Related to https://github.com/WikiWatershed/model-my-watershed/issues/1835

**Comment by arottersman** [comment]
Related to #1716
