### ISSUE TITLE
Style Water Quality Related Layers

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1834]
Only one of these layers can be on at a time, so condense them into a single toggle control...see @jfrankl for more details

![screen shot 2017-04-19 at 5 16 12 pm](https://cloud.githubusercontent.com/assets/7633670/25202604/ee75a93e-2523-11e7-92ed-976e4bb72fc0.png)

Also consider adding a message for when there are no available layers for the extent, and the view is empty (See https://github.com/WikiWatershed/model-my-watershed/pull/1829#pullrequestreview-33618739).

**Comment by jfrankl** [comment]
@ajrobbins and I decided to go with the following dropdown approach.

Notes:
- Only one layer can be selected at a time
- In the dropdown list, clicking on a layer that is currently selected should unselect it

#### Default view

![related layers multiple default](https://cloud.githubusercontent.com/assets/1809908/25242792/e86c3a62-25c8-11e7-965e-a748a2fb5c64.png)

#### Dropdown open

![ipad portrait copy 29](https://cloud.githubusercontent.com/assets/1809908/25242805/f37407f0-25c8-11e7-98f6-7d33bd563a8a.png)

#### Layer selected
![ipad portrait copy 30](https://cloud.githubusercontent.com/assets/1809908/25242821/fce3d022-25c8-11e7-8819-1cdd21864abc.png)

#### Layer selected, dropdown open
![ipad portrait copy 33](https://cloud.githubusercontent.com/assets/1809908/25242835/0745b2b0-25c9-11e7-81c7-ccd7fb22c552.png)

**Comment by ajrobbins** [comment]
I'll add that when the layer is selected, a preceeding label should read "Related layer: <layername>" so that it matches the styling of the single-layer implementation.

**Comment by jfrankl** [comment]
@ajrobbins I updated the screens above to reflect that change.

Another note: the labels in these screens are shorter than in the current application. For this layout to be successful, I think we will need to use shorter labels similar to the ones in these screen shots.

**Comment by arottersman** [comment]
@ajrobbins do we have the okay to drop the long layer title all together?

Wondering if we should do:

a) Always abbreviate in analyze sidebar, keep long title in layerpicker

![screen shot 2017-04-24 at 11 35 07 am](https://cloud.githubusercontent.com/assets/7633670/25345197/69553888-28e2-11e7-9bdd-e13bef752b0a.png)



b) Abbreviate in dropdown, but show full title once selected

![screen shot 2017-04-24 at 11 36 51 am](https://cloud.githubusercontent.com/assets/7633670/25345198/6957170c-28e2-11e7-92e1-4f22b376e853.png)

**Comment by ajrobbins** [comment]
@arottersman Let's do option b. I'd like to shorten the layer picker titles entirely in a later task, likely to "TN loading rates from SRAT catchments" so it will look better in full in the future.
