### ISSUE TITLE
Adjust draw option behavior

### ISSUE THREAD

**Issue by jfrankl** [WikiWatershed/model-my-watershed#1835]
Just discussed this with @kellyi. Looks like there was a screen missing or a miscommunication about how this feature should work. Here is what the workflow should look like:

#### Initial View
![image](https://cloud.githubusercontent.com/assets/1809908/25236611/46a1eafe-25b6-11e7-8aae-5cd26a362a07.png)

#### Draw Type Dropdown
![image](https://cloud.githubusercontent.com/assets/1809908/25236934/32b114b0-25b7-11e7-94c7-d8761290ae78.png)

#### Draw Instructions
- Clicking "Reset" would return to Initial View
- Clicking on any of the dropdowns should open the dropdown while maintaining current drawing mode
- Choosing a different drawing mode will end the previously selected drawing mode
![image](https://cloud.githubusercontent.com/assets/1809908/25236955/40e3175e-25b7-11e7-8ba4-5a4fb183c8d4.png)

**Comment by lewfish** [comment]
Jeff sent me this updated mockup which clarifies the desired behavior:

![pasted_image_at_2017_04_21_11_27_am](https://cloud.githubusercontent.com/assets/1896461/25291629/d94a5374-26a0-11e7-8e62-fbe234b45304.png)
