### ISSUE TITLE
Initial UI for data catalog search

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1840]
A new sidebar stage with a single search text box as a placeholder for data catalog search.

* New container and template
* Feature gated to only BigCZ build
* Route (`/search`) for post AoI selection step, instead of analyze

Note, this doesn't need to actually interface with the in-development API endpoint.  That will be handled subsequently.

**Comment by mmcfarland** [comment]
This got more detail on today's call.  @ajrobbins can you follow up with details?

**Comment by ajrobbins** [comment]
Sure:
- There will be an MMW-like analyze stage after AoI selection, so the /analyze route should be preserved after /draw
- A /search route will be available once the user has reached the Analyze step, which would enable the search text box as the original issue stated
@arottersman I realize this conflicts with your implementation. We were operating under the wrong impression regarding the removal of Analyze.

**Comment by ajrobbins** [comment]
I think for now we should change the "Model" button that appears on the Analyze screen to "Search for data", make it not a dropdown, and have that button lead to the new text search screen. @jfrankl @mmcfarland Does that match your understanding from today's call?

**Comment by jfrankl** [comment]
I think that is fine as a placeholder. We're still early in the design stage for MMW, so this might need to change quite a bit in the upcoming sprints.
