### ISSUE TITLE
Paginate through data catalog search results

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1850]
Each data catalog has a different mechanism for paginating results. Figure out a standard approach and implement pagination for each catalog.

### CUAHSI

Doesn't support pagination.

### CINERGI

The result payload contains these fields:

```
"more": "http://cinergi.sdsc.edu:8080/geoportal/rest/find/document?searchText=diamond&after=2016-05-25&before=2016-06-30&f=pjson&start=11",
"totalResults": 142,
"startIndex": 1,
"itemsPerPage": 10,
```

### HydroShare

The result payload contains these fields:

```
"count": 297,
"next": "https://www.hydroshare.org/hsapi/resource/?format=json&full_text_search=water&page=3",
"previous": "https://www.hydroshare.org/hsapi/resource/?format=json&full_text_search=water",
```

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by rajadain** [comment]
Using various pagination support in different back-ends, get all results for each API at once, either by supplying a greater `itemsPerPage` or by iterating through all pages for Hydroshare.

**Comment by rajadain** [comment]
The new CINERGI API takes `size=n` and `from=n` query arguments instead of `itemsPerPage` and `startIndex` from before. It also takes a `sort={field_name}:{asc|desc}` query argument for sorting. Other behavior can be observed here: http://geoss.esri.com/geoportal2/

**Comment by rajadain** [comment]
Hydroshare does not support sorting. To do so we'd have to page through all results in Django and return a sorted set.
