### ISSUE TITLE
Include detail URL for each site in CUAHSI results

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1859]
Figure out if this URL exists, and if so, where it comes from. Do "site" detail URLs exist, or just "service" URLs ([ref](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/bigcz/clients/cuahsi.py#L32))?

**Comment by kdeloach** [comment]
Blocked until #1858 is complete.

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by ajrobbins** [comment]
We've been provided with instructions for constructing detail URLs here https://github.com/WikiWatershed/model-my-watershed/issues/1931#issuecomment-306838234
