### ISSUE TITLE
Update splash page

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1869]
- Add stroud and wikiwatershed logos
- Style buttons

![screen shot 2017-05-04 at 12 15 42 pm](https://cloud.githubusercontent.com/assets/7633670/25713649/69c94a78-30c3-11e7-918e-9df4c4e237f5.png)

**Comment by arottersman** [comment]
@jfrankl Where'd those logos come from?

**Comment by jfrankl** [comment]
I sent logo images to @arottersman. Let me know if you need anything else from me.

**Comment by arottersman** [comment]
![logo-wikiwatershed](https://user-images.githubusercontent.com/7633670/28034035-059c221a-657e-11e7-8497-2428be51854f.png)
![logo-stroud](https://user-images.githubusercontent.com/7633670/28034034-059bb55a-657e-11e7-8aa3-f4d3b273436c.png)
