### ISSUE TITLE
Revamp analyze stage

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1871]
- Remove "Analyze" as title to the panel
-  Move AoI description above tabs and show AoI county (?)
   @jfrankl, Wireframe says "Philadelphia, County 370km2" What if the AoI crosses multiple counties? 
- Style description: break down into header-styled title, related layer, and source
- Add buttons to bottom: "Change area" (the "Draw"/"Back" button of yore) and "Start modeling"
- Add "Select a model" panel. Replaces "Model this area" dropdown

![screen shot 2017-05-04 at 12 21 47 pm](https://cloud.githubusercontent.com/assets/7633670/25713893/449dd65a-30c4-11e7-8c98-dfa181d6aa64.png)

![screen shot 2017-05-04 at 12 22 40 pm](https://cloud.githubusercontent.com/assets/7633670/25713929/629afeb2-30c4-11e7-970d-ceb69d8950ea.png)

**Comment by rajadain** [comment]
> Wireframe says "Philadelphia, County 370km2" What if the AoI crosses multiple counties?

I think "Philadelphia County" is the name of the AoI, which gets set by the draw view, and "370 km²" is just the total area. If the user selects a predefined shape, then its name is used. Else we just say "Selected Area".

**Comment by ajrobbins** [comment]
^That's correct. One formatting change that is made in these wireframes (unsure if it was intentional) is that we currently show "County: Philadelphia", and the wireframes show "Philadelphia, County".
