### ISSUE TITLE
Analyze/Model toggle in model stage should hide scenario toolbar

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1873]
Drop this tab navigation:

<img width="543" alt="screen shot 2017-05-04 at 12 33 00 pm" src="https://cloud.githubusercontent.com/assets/7633670/25714513/4102e128-30c6-11e7-9a25-e6a7ec8e5b24.png">

Replace with a toggle in the project bar:

![screen shot 2017-05-04 at 12 38 52 pm](https://cloud.githubusercontent.com/assets/7633670/25714638/a94badd2-30c6-11e7-984c-c9b3455e6c94.png)

**Comment by arottersman** [comment]
#1890 Moves the tab navigation into the header, but the toggle still needs to be wired up to hide the scenario toolbar in "analyze" 
**Wireframe**
![img](https://cloud.githubusercontent.com/assets/7633670/26077414/edff84dc-3989-11e7-9e56-dfc95fd27f94.png)

**Comment by rajadain** [comment]
I believe this has been implemented:

![2018-01-24 13 23 34](https://user-images.githubusercontent.com/1430060/35349788-ea3192bc-0109-11e8-91a9-962ebe572272.gif)

Can this be closed?

**Comment by arottersman** [comment]
Sure can!
