### ISSUE TITLE
Add "Change Area" button

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1874]
* May not be the final button text
- Clears the aoi and takes you back to the draw stage to start a new project
![screen shot 2017-05-04 at 12 39 46 pm](https://cloud.githubusercontent.com/assets/7633670/25714690/d037145e-30c6-11e7-8227-4c582b961427.png)

**Comment by jfrankl** [comment]
- Final button text: "New project"
- This should take you back to the draw view with default zoom level
