### ISSUE TITLE
Style Scenario Rename Workflow

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1887]
See https://github.com/WikiWatershed/model-my-watershed/pull/1883#issuecomment-300795108

cc/ @jfrankl

**Comment by jfrankl** [comment]
Could you please use the modal styling from renaming a project?

![image](https://cloud.githubusercontent.com/assets/1809908/26006823/e5ae2778-370b-11e7-92b7-d745adc69ed3.png)

**Comment by arottersman** [comment]
I brought this in because it made it easier to complete #1984
