### ISSUE TITLE
trigger resize on bar chart in modeling view

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#189]
The following needs to be done:

 * Trigger resize on the analyze bar charts when hitting the back button on the top of the modeling view (so that the bar charts will be the right size if a resize occurred while the modeling view was open)
 * Trigger resize on the modeling bar charts when modeling window is done being animated (so that the charts take up the full height of the tab).

**Comment by kdeloach** [comment]
Do we still need to do this?

**Comment by lewfish** [comment]
I just checked and I think the answer is no.
