### ISSUE TITLE
Data Catalog To Analyze Transition Isn't Smooth

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1895]
See https://github.com/WikiWatershed/model-my-watershed/pull/1890#issuecomment-302102526

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by rajadain** [comment]
This does not apply anymore, because we use the same switcher as MMW for going between Search and Analyze, and the two sidebars are the same width so there is no jerking of the map.
