### ISSUE TITLE
Style cleanup

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1897]
- [x] Upload a file unstyled
![screen shot 2017-05-18 at 10 41 49 am](https://cloud.githubusercontent.com/assets/7633670/26208341/d3e9715e-3bb7-11e7-9a6d-49e9c8117404.png)

- [x] Long named draw tools (e.g. RWD) push icons off line
![screen shot 2017-05-18 at 10 41 40 am](https://cloud.githubusercontent.com/assets/7633670/26208342/d3ecbd6e-3bb7-11e7-8dfe-05a56b87505c.png)

![screen shot 2017-05-18 at 10 51 47 am](https://cloud.githubusercontent.com/assets/7633670/26208416/049b6ab4-3bb8-11e7-807e-5b03abe1eace.png)

- [x] Long WKAoI names don't have enough bottom padding in analyze aoi header
![screen shot 2017-05-18 at 1 07 50 pm](https://cloud.githubusercontent.com/assets/7633670/26214751/889cb8a0-3bcb-11e7-8007-c5bf168af495.png)

- [x] Firefox doesn't wrap thumb select text
<img width="421" alt="screen shot 2017-05-19 at 1 18 40 pm" src="https://cloud.githubusercontent.com/assets/7633670/26260586/bfb3338e-3c9b-11e7-80ed-8ab1ebafb247.png">

**Comment by kellyi** [comment]
> Firefox doesn't wrap thumb select text

Checking into this one and it seems like it may already have been fixed.

**Comment by kellyi** [comment]
Checked the thumb select text in Firefox, Chrome, and IE11 and couldn't reproduce the issue.
