### ISSUE TITLE
Confirm ElastiCache eviction policy

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1898]
Now that we're using redis/eslasticache to store intermediate geoprocessing results, we should confirm that the eviction policy used in AWS is appropriate.

https://redis.io/topics/lru-cache

**Comment by hectcastro** [comment]
It looks like we are currently operating with the `volatile-lru` which is probably not desirable because we aren't setting expiration on keys. This setting likely needs to be changed to `allkeys-lru`.
