### ISSUE TITLE
Add WKAoI field to Project Model

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1899]
Currently we only use WKAoI for new projects. When resuming an old project, we only hydrate the area of interest shape and name from the database, making it impossible to take advantage of the caching functionalities when resuming saved projects. Add a `wkaoi` field to the Project model and wire it through to the front-end so it is used when resuming saved projects.

**Comment by mmcfarland** [comment]
To be clear, this will effect existing projects only after this change is made, correct?  _Old_ old projects' AoI provenance is lost to history.

**Comment by rajadain** [comment]
Correct. And _all_ projects will still save the area of interest. When running geoprocessing, we attempt to use the WKAoI if available and valid, otherwise fallback to the area of interest. This is purely an enhancement with no loss of current functionality.
