### ISSUE TITLE
Improve appearance of bar chart

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#190]
The following needs to be done:

 * Use colors that are consistent with the app color scheme for the stacked bar chart.
 * Fix the space between the left-most bar and the y-axis (when in vertical bar mode) so that the y-axis label doesn't get occluded.
 * Make the order of the colors/labels in the legend match the order of the colors within the bars.
 * Make x-axis labels aligned with bars. (This used to work...)

**Comment by lewfish** [comment]
@ctaylo37 Could you please re-open this issue? (I think Github only lets the closer re-open an issue.) You fixed two of the bullet points (which I've removed), but there are still two left to do.

**Comment by lewfish** [comment]
@ctaylo37 Actually, nevermind. It'll just be less confusing if I make a new issue.

**Comment by ctaylo37** [comment]
@lewfish the order of the legend will need to be addressed in D3.  I cannot fix that.  As far as the Y-Axis issue, can you show me what that is when you get a sec?
