### ISSUE TITLE
Load BiG CZ settings based on HTTP Host

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1904]
Instead of relying on the `MMW_BIGCZ_MODE` environment variable to pick the correct application settings, check the HTTP `Host` header field.

The rationale is that we'd like to host both MMW and BiG CZ using the same infrastructure, but using different URLs.

We may need to keep the environment variable around for local development, but we should be able to remove all of the provisioning logic from the deployment scripts.

**Comment by hectcastro** [comment]
It is possible that we want to use the `Host` header here vs. the `Referer` header, with a default case when neither domain matches (thinking about when we test the dark stack directly with the ELB domain).

**Comment by mmcfarland** [comment]
Good point about the dark stack, hadn't considered that.  We could supplement our test on the appropriate header with an optional query string parameter that could force a particular mode to aid in testing both frontends in a dark stack when we haven't got a reliable `Host`.

**Comment by kdeloach** [comment]
Thanks. We definitely intended to detect this setting based on the HTTP `Host` header field. Updated the issue title and description to reflect this.
