### ISSUE TITLE
Setup BigCZ domains for existing MMW environments

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1908]
http://portal.bigcz.org is currently resolving to a temporary server, and we have the contact for the person who manages the domain.  We'll want to establish 2 domains, one for each existing MMW environment (presumably `staging.portal.bigcz.org`).  

When finalized, it will inform the implementation of #1904

**Comment by hectcastro** [comment]
Any idea if we can take this opportunity to stop supporting the `mmw.azavea.com` and `mmw-dev.azavea.com` domains?

**Comment by mmcfarland** [comment]
> Any idea if we can take this opportunity to stop supporting the mmw.azavea.com and mmw-dev.azavea.com domains?

For the record, confirmed with Concord that we can.
