### ISSUE TITLE
Layer picker tooltip cut off

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1916]
Chrome on 13" macbook:

![screen shot 2017-05-22 at 2 28 58 pm](https://cloud.githubusercontent.com/assets/12868342/26323431/d3e940ba-3efc-11e7-8dc3-49bdb5d6a243.png)
Layer picker item tooltip is cut off on right. If the layer picker is going to stay in the bottom right, the tooltips may need to be placed above or on the left.

**Comment by ajrobbins** [comment]
To address this, move layer picker to bottom left. Move map controls to...? @jfrankl

**Comment by arottersman** [comment]
@jfrankl, any updates on where the map controls should go?

**Comment by jfrankl** [comment]
Let's put them in the bottom right. See mockup below.

![image](https://user-images.githubusercontent.com/1809908/27435688-e7edf6d2-572a-11e7-9f07-87d77512a63b.png)

**Comment by arottersman** [comment]
@jfrankl, thanks! Should we also move search to upper left like that mockup?

**Comment by jfrankl** [comment]
Upon further reflection, let's keep it in the top right.

![image](https://user-images.githubusercontent.com/1809908/27437318-dfa5a22c-572f-11e7-8d45-b1553950023f.png)

**Comment by rajadain** [comment]
As a result, the "sidebar toggle" / "map expand" button is now far away from the sidebar. But given its iconography which emphasizes the map state rather than the sidebar, I think this users will quickly learn what it does.

**Comment by jfrankl** [comment]
@rajadain That's what I'm thinking, Terence. On top of that, making the map full screen might be helpful in some cases, but it's not essential functionality. With the layer picker and other map buttons on the bottom of the screen, there will be less clutter at the top of the screen when the user is in the model view, which involves several headers and buttons at the top of the screen.
