### ISSUE TITLE
"Turn on" related layer wraps to next line

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1917]
"Turn On" should be inline
![screen shot 2017-05-23 at 9 12 27 am](https://cloud.githubusercontent.com/assets/12868342/26355811/0770262e-3f98-11e7-9660-fbea1f039551.png)

Viewed on 13" macbook air, Chrome

**Comment by caseycesari** [comment]
This appears to have been fixed by https://github.com/WikiWatershed/model-my-watershed/pull/2017 and/or https://github.com/WikiWatershed/model-my-watershed/pull/2019

**Comment by caseycesari** [comment]
Swapped out for https://github.com/WikiWatershed/model-my-watershed/issues/2050
