### ISSUE TITLE
Format model title

### ISSUE THREAD

**Issue by jfrankl** [WikiWatershed/model-my-watershed#1920]
Currently, the title on the model page is one block of text:

![image](https://cloud.githubusercontent.com/assets/1809908/26419808/e04b397e-408e-11e7-8b67-d61522bf5ae8.png)

Please separate the title ("Results of a 24-hour hypothetical storm event") from the model description ("Simulated by SLAMM and TR-55 model algorithms").

![image](https://cloud.githubusercontent.com/assets/1809908/26419846/f4cf25c2-408e-11e7-8854-fb4b8cdb2c97.png)

**Comment by jfrankl** [comment]
This structure will make it easier to read the title.

**Comment by arottersman** [comment]
This is a duplicate of #1872

**Comment by jfrankl** [comment]
Thanks Alice!
