### ISSUE TITLE
Cache CUAHSI GetServicesInBox2 results

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1932]
> BTW, for future consideration: it occurred to me that currently there are only 94 "data services" in WDC (ie, the maximum total that can be returned by GetServicesInBox2), and those change rarely. Maybe a future strategy for better search responsiveness could be to get all services in the US lower 48 (based on a GetServicesInBox2 query) and cache them once a day, then just use that cache together with the actual query results from GetSitesInBox2.

Ref: https://github.com/WikiWatershed/model-my-watershed/issues/1931#issuecomment-305317545

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by rajadain** [comment]
This can be done easily along these lines:

```diff
diff --git a/src/mmw/apps/bigcz/clients/cuahsi/search.py b/src/mmw/apps/bigcz/clients/cuahsi/search.py
index 08622b4..955f8cd 100644
--- a/src/mmw/apps/bigcz/clients/cuahsi/search.py
+++ b/src/mmw/apps/bigcz/clients/cuahsi/search.py
@@ -124,8 +124,16 @@ def group_series_by_location(series):
 
 
 def make_request(request, **kwargs):
+    key = 'bigcz_{}_{}'.format(request.__name__,
+                               hash(frozenset(kwargs.items())))
+    cached = cache.get(key)
+    if cached:
+        return cached
+
     try:
-        return request(**kwargs)
+        response = request(**kwargs)
+        cache.set(key, response)
+        return response
     except URLError, e:
         if isinstance(e.reason, timeout):
             raise RequestTimedOutError()
```

Will need to ensure that this expires at appropriate times, because this is not an immutable operation.
