### ISSUE TITLE
Wire up date range filters

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1933]
The BiG CZ search API supports `to_date` and `from_date` params ([Source](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/bigcz/views.py#L31)). These need to be wired up from the frontend.

![screenshot 2017-06-01 at 10 56 39](https://cloud.githubusercontent.com/assets/43062/26685768/042c78e6-46b9-11e7-9776-be904d6cc331.png)

![screenshot 2017-06-01 at 10 56 04](https://cloud.githubusercontent.com/assets/43062/26685737/f180e70e-46b8-11e7-8a70-29b1fbd7a251.png)

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by ajrobbins** [comment]
Implement for CUAHSI WDC to start.

**Comment by rajadain** [comment]
The date filter must operate on the date measurements were taken, not of the creation or updated date.

**Comment by mmcfarland** [comment]
@jfrankl It's not completely clear from the wireframe shots above what the trigger should be for executing a search when the date range is in play.  Currently, search is on `enter` from the main search box.  Doing a search on change/blur for the dates doesn't seem ideal, especially if you haven't entered main search text yet.  Entering text, searching and then adding a date filter would require the user focusing the search box again and hitting enter.  

In the absence of a search button, I think keeping it just on search enter is the most straight forward.  Thoughts?

**Comment by jfrankl** [comment]
Sorry I lost track of your question, Matt. I agree, this should happen on "enter". We might also need to have a "submit" type button.
