### ISSUE TITLE
BiG CZ details view

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1934]
Clicking on search results should open a details view. The main difference between the list view and the details view is the expanded "description" section and download buttons.

Other details:

* We don't need to expand the description field in the listing view anymore. This functionality can be removed.
* Author and date sections should read "Not Available" if that data is null or empty.
* Context is not always available for service links. Some services point to a details page, some point to an XML file, etc. So we may not be able to display 3 distinct download buttons.
* The list view will show all available boundaries on the map, the details view will only show the boundaries relevant to the selected search result. The actual implementation to show boundaries on the map is not part of this task.

![screenshot 2017-06-01 at 11 03 48](https://cloud.githubusercontent.com/assets/43062/26686127/106c04ae-46ba-11e7-9faa-721e15bf1933.png)

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by mmcfarland** [comment]
This issue is a few months old.  @ajrobbins or @jfrankl can you comment on if the screencap and description are still valid with the latest design and thinking?

**Comment by jfrankl** [comment]
There might need to be other details listed in addition to the author and year. Those details should match what we are now showing on the search results for each catalog. @ajrobbins what do you think?

**Comment by ajrobbins** [comment]
The contents of the detail page will differ across catalogs. For this card, I think we should implement the basic detail page interaction and design (clicking on result slides out a detail page with an X to close), and include the title, author, date, and description from the result as the screencap shows.

As we get finalized detail on other elements to include, we can implement them in subsequent tasks.
