### ISSUE TITLE
Client-side filter CUAHSI search results 

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1936]
Implement ad-hoc client-side filter for CUAHSI search results. Other catalogs support free text search, but CUAHSI only supports "keyword" search, from a list of pre-defined keywords. Since our implementation expects users to type free text instead of selecting keywords from a list, we currently don't support searching for CUAHSI results based on text/keywords.

One workaround discussed is to do a client-side filter of CUAHSI search results based on the available fields returned from the API. Since CUAHSI doesn't support pagination, it makes sense to do this filter client-side to avoid a round-trip request.

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by rajadain** [comment]
Implemented in #2439.
