### ISSUE TITLE
BiG CZ design support

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1938]
Sidebar body contents height should be 100%:

![image](https://user-images.githubusercontent.com/43062/27052175-d9412420-4f86-11e7-90c8-a5e80bcf9260.png)

Sidebar contents should be scrollable; We also need icons and formatting for the date & author fields:

![image](https://user-images.githubusercontent.com/43062/27052218-03909b52-4f87-11e7-9bc5-eb1da4fad094.png)

Need styling for "optional service description" area beneath WDC service tab:

![image](https://user-images.githubusercontent.com/43062/27052321-5a162bcc-4f87-11e7-92d4-e655e115246f.png)

**Comment by kdeloach** [comment]
Updated this issue to include 3 known design issues we may need help with.

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.
