### ISSUE TITLE
Improve BiG CZ search API error handling

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1941]
Return a valid JSON response instead of a 500 error in the case of exceptions during a search request. Exceptions may be `ValueError` or `IndexError` due to malformed API responses, or timeout errors. The frontend should also handle errors gracefully.

**Comment by kdeloach** [comment]
Here's an example of a bad request I received from CINERGI:

```
{  
   "detail":"{u'error': {u'message': u'None of the configured nodes are available: [{#transport#-1}{Ichj8wWZRqqjHllBZXYycw}{localhost}{127.0.0.1:9300}]'}}"
}
```

**Comment by kdeloach** [comment]
CUAHSI requests timeout if the AOI is too large. We'll need to add a maximum bounding box constraint for this service.

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by ajrobbins** [comment]
We're implementing an 8,000 sq km maximum bounding box (was 1,500), and we'll test the timeout occurrence.
