### ISSUE TITLE
Sidebar content disappears when 1st new scenario is added

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1943]
To replicate:
- run Site Storm model on an area
- click "add changes to this area" to create a new scenario from Current Conditions
- observe that the sidebar content (charts and table) disappears (and appears to be rerun)

This content should remain, since it's just being copied to the new scenario.

**Comment by ajrobbins** [comment]
This is the same behavior as the "old" UI, so I'm marking it as an enhancement.

**Comment by arottersman** [comment]
Briefly considered tackling this while working on https://github.com/WikiWatershed/model-my-watershed/issues/1901, then decided not to. Some thoughts:

- Seeing the model run for every new scenario became most apparent after working with bees, where we copy the current crop map (ie current conditions) to all new scenarios. The logic for this copying was simple in that all changes to the current crop map should apply to all scenarios. This is not the case for MMW, where a change to the current condition's precipitation slider input should not apply to subsequent scenarios. 
- I considered
   (i) Keeping an un-modifiable scenario on the `ProjectModel` to copy to every other scenario when they're created
   (ii) Copying the current conditions results to all new scenarios if current conditions hasn't been modified yet. If it has, re-run the model as usual

**Comment by ajrobbins** [comment]
>This is not the case for MMW, where a change to the current condition's precipitation slider input should not apply to subsequent scenarios.

I'm wondering if that's true, though - if a user changes the precip on current conditions, why shouldn't we copy that to subsequent scenarios? a) there's not really a reason why the user-adjusted precip is less valid than the automatic 2.5cm precip (unless there is one that I'm unaware of), and b) in compare view we sync precip across scenarios anyway.

It seems like it would make sense to apply the current condition's precipitation slider input (and thus everything in the scenario sidebar, basically) to the new scenario.

**Comment by arottersman** [comment]
Great point, especially considering the compare view precipitation slider behavior. 

I should have written "where a change to the current condition's precipitation slider input ~should not~ currently does not apply to subsequent scenarios"

**Comment by ajrobbins** [comment]
Related to #2084
