### ISSUE TITLE
Filter BiG CZ results based on AOI bounds

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1947]
During development, we use Leaflet map bounds to filter BiG CZ search results (for convenience). However, the search view should depend on selecting an AOI first. Search results should be filtered by the bounding box of the currently active AOI.

Ref: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/data_catalog/models.js#L61

Consider reverting https://github.com/WikiWatershed/model-my-watershed/commit/596647342256634582ffad8ddd66f6b42b1af1b3.

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by ajrobbins** [comment]
Also, drop the points outside the AoI but within the bounding box on the front end.

**Comment by rajadain** [comment]
Also, redirect landing on `/search` to `/`.
