### ISSUE TITLE
Summarize precipitation and temperature in Analysis

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1949]
Following up on https://github.com/WikiWatershed/model-my-watershed/issues/1905, add a "Climate" tab to Analysis for BiG CZ. This will show summary output for mean monthly precipitation and temperature. The rasters have been ingested for analysis.

Some more details on the desired summary output:

We'll be showing average mean precip and temp per month. Apparently this is common, and known as Mean Annual Precipitation (MAP) and Mean Annual Temperature (MAT).

These means are calculated both over time and space, and the spatial means between observation stations are spatially weighted averages/means. Emilio is providing the time means (by month), we'll do the spatial averaging. We'll also calculate Mean Annual values from the Mean Monthly values.

For MAP, we sum the mean monthly precipitation
For MAT, we average the mean monthly temperature

|Month   | Mean Precip.   |   Mean Temp.  |
|--------|----------------|---------------|
|Jan       |     120mm          |   12 C               |
|Feb       |     100mm          |   10 C               |
|...          |     ...                   |         10 C​         |
|**Annual**|    **1200mm** |  **18 C​**       |

Bottom row above shows MAP and MAT

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by rajadain** [comment]
Do we know what is the Source of the data? USGS, NWS, etc.

**Comment by mmcfarland** [comment]
PRISM
http://www.prism.oregonstate.edu/normals/
