### ISSUE TITLE
Bake CSRF token in all Backbone requests

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#197]
When we make AJAX requests to Django from Backbone, especially when a user is logged in, each request must specify an X-CSRFToken header. This has been implemented during user login as follows:

```javascript
    getUserOrShowLogin: function() {
        var csrftoken = helpers.Cookie.get('csrftoken');

        this.user.fetch({
            beforeSend: function(xhr) {
                xhr.setRequestHeader('X-CSRFToken', csrftoken);
            }
        });
    },
```

So that we don't have to specify this `beforeSend` function and have code duplication for every `.get()` or `.fetch()` or `.save()` on every model and collection, we should bake this mechanism into [`Backbone.sync`](http://backbonejs.org/#Sync).  This is one example of how to do it: https://gist.github.com/gcollazo/1240683

We should probably do this in `src/mmw/js/shim/backbone.js` so it is always imported.

Once this fix is available, please update all occurrences of the above code since we don't need a second `X-CSRFToken` header.

It should be noted that even if we override `Backbone.sync` to include this header, any `$.ajax()` requests will still require specifying the token. There exists even wider implementations which bake in the token to all `$.ajax()` requests, such as https://gist.github.com/justinperkins/3960219, and this will work for both `$.ajax()` and all Backbone requests since `Backbone.sync` uses `$.ajax()` under the hood. However, if we make any `$.get()` requests to third party domains, we will expose the CSRF token. If we are certain that will not be the case, we can consider this second option as well.

**Comment by kdeloach** [comment]
Here's the solution used on NYC: https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/js/src/csrf.js

**Comment by rajadain** [comment]
Great, that seems to be akin to the second option mentioned in the Issue description, one that overrides `$.ajax()` across the app. The drawback being that it could potentially expose the CSRF Token to 3rd party sites if any cross domain requests are made, but perhaps [this line](https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/js/src/csrf.js#L32) explicitly forbids those? Perhaps @jwalgran could confirm this?

In this case we should definitely adopt the same approach here.
