### ISSUE TITLE
Google Maps API Key Error on BiG-CZ

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1972]
Because of the different domain, the Google Maps API key doesn't work. Either add the following domains to the current API key, or procure a new API key:

 * staging.portal.bigcz.org
 * portal.bigcz.org

![image](https://user-images.githubusercontent.com/1430060/27188824-6a7e6f82-51bd-11e7-9902-4cba5c2a6ba0.png)

**Comment by ajrobbins** [comment]
Stroud's webmaster added `*.bigcz.org/*` to the Google Maps API whitelist. May take up to 5 minutes to take effect.

**Comment by rajadain** [comment]
Just tried staging: https://staging.portal.bigcz.org/ and still seeing the error:

![image](https://user-images.githubusercontent.com/1430060/27237482-3e2a862a-5297-11e7-8e66-f3e04279b62f.png)

**Comment by ajrobbins** [comment]
Changes made:
![image 6](https://user-images.githubusercontent.com/12868342/27239878-c03d4b44-52a0-11e7-8fc1-c573d7227423.png)

And basemap works!

![screen shot 2017-06-16 at 2 47 42 pm](https://user-images.githubusercontent.com/12868342/27240463-ca115ff0-52a2-11e7-80f2-7aa4bb6f3b50.png)
