### ISSUE TITLE
Add temp and precip charts to climate tab

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1975]
As we do for Multiyear model in MMW:
![screen shot 2017-06-15 at 1 51 54 pm](https://user-images.githubusercontent.com/12868342/27194773-e1c628a0-51d1-11e7-8281-4a64710d1b3b.png)

**Comment by rajadain** [comment]
Commenting to subscribe to this thread and get email notifications.

**Comment by rajadain** [comment]
Question: In almost all other spots in the app, precipitation is always in **cm**. In this page it is in **mm**. Should we change it to cm to be consistent, or keep it in mm because Mean Annual Precipitation expects those units (does it?)? /cc @aufdenkampe @emiliom

**Comment by emiliom** [comment]
> Question: In almost all other spots in the app, precipitation is always in cm. In this page it is in mm. Should we change it to cm to be consistent, or keep it in mm because Mean Annual Precipitation expects those units (does it?)?

I don't exactly know what "this page" ("climate tab"?) is. I assume it's a new analysis tab where you'll present the monthly climatology values for the user-selected AOI, as currently done for land cover and soil types? If so, the units on the monthly climatologies we provided (cc @lsetiawan) are in mm/month. I think consistency is desirable, so I'd agree that precip should always be presented in the same units across the application, whenever possible. **cm** is fine with me, though I do think **mm** is a bit more common (my 0.2 cent).

**Comment by rajadain** [comment]
Sorry, yes, this is the new Climate tab under Analyze.

Very well, I'll switch to **cm** here.

**Comment by aufdenkampe** [comment]
Let's switch to cm here for now.
Emilio is right that mm is more common for precipitation (an runoff). Let's reconsider when we address the ability to switch between units (#2264).
