### ISSUE TITLE
Cannot Remove Modifications from MapShed

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1982]
Create a MapShed scenario, add Veg Buffer Conservation Practice to it. Try to remove it from the sidebar.

It should be removed, but the button doesn't do anything.

![mmw-cannot-remove-modifications-mapshed](https://user-images.githubusercontent.com/1430060/27399378-8f050f10-568a-11e7-8d1a-446f2f59ab7a.gif)

**Comment by rajadain** [comment]
Also, in IE11, long names such as Veg Buffer Strips (Urban) doesn't wrap as it does in Chrome, causing hover issues:

![image](https://user-images.githubusercontent.com/1430060/27399555-2515f406-568b-11e7-8eef-7ac695349469.png)

**Comment by arottersman** [comment]
The delete button is broken because we changed the css class, without updating the marionette view. To fix:
```diff
diff --git a/src/mmw/js/src/modeling/views.js b/src/mmw/js/src/modeling/views.js
index 5b53b75..121b738 100644
--- a/src/mmw/js/src/modeling/views.js
+++ b/src/mmw/js/src/modeling/views.js
@@ -676,7 +676,7 @@ var GwlfeToolbarView = ScenarioModelToolbarView.extend({

     ui: {
        thumb: '#gwlfe-modifications-bar .thumb',
-       deleteButton: '.delete-button',
+       deleteButton: '.delete-modification',
        closeButton: 'button.close'
     },
```

**Comment by rajadain** [comment]
Shares points with #2025

**Comment by rajadain** [comment]
made #2039 for the IE11 hover issue.
