### ISSUE TITLE
Search Bar Visible in My Projects Page

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#1987]
![image](https://user-images.githubusercontent.com/1430060/27488119-e4ce3c94-5803-11e7-94a8-03d4aa6abf1f.png)

It should not be visible on this page.

Seen on Chrome and Safari, didn't check others but they may have it too.

**Comment by rajadain** [comment]
It is also visible in the Model page, where it shouldn't be either:

![image](https://user-images.githubusercontent.com/1430060/27488208-3aba95d0-5804-11e7-9f38-5f76cb760942.png)

**Comment by arottersman** [comment]
also see https://github.com/WikiWatershed/model-my-watershed/issues/1912

**Comment by rajadain** [comment]
Ah, alright. Closing this duplicate in favor of #1912.
