### ISSUE TITLE
Add timeout to third-party search HTTP requests

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1989]
When making HTTP requests against the following services, entire that the `requests` and `suds` contain a reasonable timeout (3-5 seconds?) so that the application web workers aren't tied up waiting for a response:

- https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/bigcz/clients/cinergi.py#L131
- https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/bigcz/clients/cuahsi.py#L25
- https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/bigcz/clients/hydroshare.py#L74

If the services can't respond within that window, then we may need to consider some alternative approaches.

<img width="1175" alt="screen shot 2017-06-28 at 14 49 18" src="https://user-images.githubusercontent.com/43639/27654773-08119d84-5c11-11e7-99b4-311595ffa903.png">

**Comment by ajrobbins** [comment]
5 seconds seems reasonable to start - I'm getting results in under 3 seconds for about 1 square km areas, which is good for testing.
