### ISSUE TITLE
Soil chart cut off

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1998]
13" macbook, Google Chrome - 

Staging:
![screen shot 2017-07-06 at 2 18 42 pm](https://user-images.githubusercontent.com/12868342/27926364-2f4a0c88-6256-11e7-9ae0-bd2d7d54c65c.png)

Prod:
![screen shot 2017-07-06 at 2 19 17 pm](https://user-images.githubusercontent.com/12868342/27926374-398513fa-6256-11e7-97c0-538cf8d0fcaa.png)

Note that the % figure overlap at the right end of the X axis was a pre-existing issue.

**Comment by kellyi** [comment]
Checked this on my Macbook and I don't see the error on staging Chrome but I do see it in Firefox:

<img width="1010" alt="screen shot 2017-07-10 at 10 51 41 am" src="https://user-images.githubusercontent.com/4165523/28024102-c49d9610-655d-11e7-8119-bf862a227934.png">

**Comment by kellyi** [comment]
n.b. This isn't visible on Retina screens in Chrome but is visible on non-Retina screens regardless of the screen width. Also visible in Firefox on Retina screens.
