### ISSUE TITLE
Remove puppet-agent

### ISSUE THREAD

**Issue by jwalgran** [WikiWatershed/model-my-watershed#20]
I saw this error message in Kibana

```
Mar 26 15:46:24 puppet-agent: Could not request certificate: execution expired

**Comment by hectcastro** [comment]
I think this can be closed. I looked on staging today and could not find any references to Puppet (except the ones created by cloud-init, but I think that is just a standard cloud-init module).

**Comment by mmcfarland** [comment]
Closing based on above comment.
