### ISSUE TITLE
"Copy link" button on share modal doesn't copy link

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2000]
To replicate:

- Create a project and add scenarios
- Open the scenario dropdown
- Click on the ellipses next to a scenario
- Click the "copy link" button on this modal:
![screen shot 2017-07-06 at 2 45 54 pm](https://user-images.githubusercontent.com/12868342/27927511-019ebd70-625a-11e7-9e3a-3d811fe97e83.png)
- Try to paste it

Observed: the correct link was not pasted.

Also observed: copy link doesn't work when sharing from the project-level dropdown in the model view, or from the My Projects page, either.

**Comment by rajadain** [comment]
2000th issue! 🎉

**Comment by ajrobbins** [comment]
shares a point with #1999
