### ISSUE TITLE
Opening project from share link results in an error

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2001]
See: https://staging.app.wikiwatershed.org/project/823
![screen shot 2017-07-06 at 2 51 06 pm](https://user-images.githubusercontent.com/12868342/27927685-952751c4-625a-11e7-9ce4-c9eb9aadb270.png)

To replicate, create a project and share it. Copy the link manually and paste into a new browser.

**Comment by ajrobbins** [comment]
Compare and analyze views still work, though.

**Comment by kellyi** [comment]
Here's the error message which shows up on that link:

```
{"status":"failed","started":"2017-07-10T19:54:28.853Z","finished":"2017-07-10T19:54:35.841Z","result":"","error":"Missing censuses for modifications","job_uuid":"e745884e-8176-407a-b966-4c74ea7523b9"}
```
