### ISSUE TITLE
Login modal errors overlap with modal text

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#2002]
![image](https://user-images.githubusercontent.com/1042475/27933459-8811c45a-626f-11e7-8652-b53d7b8bf214.png)

**Comment by rajadain** [comment]
Duplicate of https://github.com/WikiWatershed/model-my-watershed/issues/1969

**Comment by caseycesari** [comment]
Sorry!

**Comment by rajadain** [comment]
No worries, didn't mean to be short. There's so many issues out there that it's almost hard to keep track of!
