### ISSUE TITLE
Projects created prior to #1802 need data migration

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#2004]
Projects created before #1802 was merged that have stored water quality results need to be migrated to the new format. Or we could remove the stored results so that they are regenerated when a project is loaded.

Here's a project on staging that will reproduce the bug: https://staging.app.wikiwatershed.org/project/661/scenario/1251.

**Comment by arottersman** [comment]
This will be addressed by the migration created for https://github.com/WikiWatershed/model-my-watershed/issues/1923
