### ISSUE TITLE
Precipitation slider jitters when toggled in Firefox and Safari

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2013]
Firefox 54.0.1:

![precip-jiggle](https://user-images.githubusercontent.com/12868342/27977294-05fa13ea-6338-11e7-8b0b-411e0ef125ab.gif)

Potentially related to the shift in the Save button area above when it switches from saving to saved?

**Comment by ajrobbins** [comment]
Safari 10.1.1: 
![safari_jitter](https://user-images.githubusercontent.com/12868342/28036266-ab234220-6585-11e7-81d2-d3283678d420.gif)

**Comment by kellyi** [comment]
Seems like this happens because the width of the control including the precipitation number value isn't fixed.
