### ISSUE TITLE
Implement climate overlay sliders from wireframes

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2018]
We've ingested monthly mean temperature and precipitation rasters for analysis in BiG CZ, and will be tiling them for visualization in #1976. This card is to wire up a slider that accompanies the new Temperature and Precipitation overlays in the layer selector. Each overlay actually has 12 overlays for display, one for each month. The slider enables the user to toggle between months, changing the overlay displayed.

See: https://marvelapp.com/5a66caa/screen/29342973

(slides 15-16)

**Comment by rajadain** [comment]
Depends on #1976

**Comment by mmcfarland** [comment]
Tiles are available via the azavea data-hub tile endpoint:

**Precipitation**
`https://{s}.tiles.azavea.com/climate/ppt_{month}/{z}/{x}/{y}.png`

**Temperature**
`https://{s}.tiles.azavea.com/climate/tmean_{month}/{z}/{x}/{y}.png`

`{month}` is a two digit, zero padded number 01-12.
