### ISSUE TITLE
Enable download of GMS file in Current Conditions (pre-scenario creation)

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2041]
[On staging, new UI] When a user selects the Watershed Multi-year model to run, they are brought to the Current Conditions view. At this point, no new scenarios have been created. The user has no option to download a GMS file here.

In the old version on production, selecting the multiyear model would automatically open a new scenario from which a gms file could be downloaded.

Users want to be able to download the gms file from the current conditions view - it's dependent only on GIS inputs, so it's available before scenarios are run. This will require some design work to figure out where this download should be made available in the UI.

**Comment by jfrankl** [comment]
Add "Download GMS" button next to "Current Conditions" in the Current Conditions toolbar.

When the user adds modifications, this special "Download GMS" button should disappear. Instead, the user would access Download GMS from the dropdown, the same way they'd access it for a new scenario.

https://github.com/WikiWatershed/model-my-watershed/issues/2041
