### ISSUE TITLE
Select boundary doesn't work if you activate it from a low zoom level

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2045]
### To Recreate:
- Zoom out to about a nation-level view
- Select by boundary --> HUC-08 (or another boundary of your choosing)
- Zoom in so that you can see the HUC boundaries
- You won't be able to select one until you've cleared and reactivated the tool

![b8hoqgg5qx](https://user-images.githubusercontent.com/7633670/28227233-0032dbc6-68a7-11e7-895b-271faa406956.gif)

**Comment by mmcfarland** [comment]
Closing in favor of #2217
