### ISSUE TITLE
Remove Header from Model View

### ISSUE THREAD

**Issue by ctaylo37** [WikiWatershed/model-my-watershed#205]
![screen shot 2015-05-22 at 9 54 13 am](https://cloud.githubusercontent.com/assets/5880793/7772120/36af1860-006a-11e5-8b07-f0e20da3d7aa.png)

**Comment by mmcfarland** [comment]
@caseypt and I weren't sure about this and decided to include it.  Without it, what are the actions for users to access their account navigation/log in & get to the homepage?

**Comment by mmcfarland** [comment]
There are some new design tasks in play to resolve general space issues, closing in favor of those.
