### ISSUE TITLE
BiGCZ shapes don't clear when you leave search

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2054]
- Draw an aoi that will garner WDC results (eg a philly huc-12)
- search "water" and view the WDC tab
- Click the "Critical Zone...." header link to the splash

![screen shot 2017-07-18 at 1 43 00 pm](https://user-images.githubusercontent.com/7633670/28331581-a1fd0916-6bbf-11e7-9405-cfaecfc07a23.png)

**Comment by rajadain** [comment]
Possibly another symptom of the same underlying problem #2053 has.
