### ISSUE TITLE
Compare view gets cut off on mobile safari

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2060]
Compare view doesn't calculate height properly for scrol

Perhaps related related to the `100vh`
https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/sass/pages/_compare.scss#L4

https://bugs.webkit.org/show_bug.cgi?id=141832

![20170719_173227](https://user-images.githubusercontent.com/7633670/28392578-837bd430-6cb0-11e7-87ae-7180e2e50b42.jpg)

Left two columns won't scroll any farther down.

**Comment by ajrobbins** [comment]
Closing due to in-progress Compare View Revamp.
