### ISSUE TITLE
Analyze tables show too few records in a single page

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2064]
When an analysis result has multiple pages of results, on Point Source/Water Quality, the record count per page is lower than expected, given the amount of space available (13" Chromebook).

![screenshot 2017-07-20 at 1 59 15 pm](https://user-images.githubusercontent.com/1014341/28431824-af0e2762-6d53-11e7-8357-f4a5d51178d2.png)

**Comment by ajrobbins** [comment]
This was a result of an attempt to get the pagination to work on tablets and a variety of desktop sizes, I think in this PR https://github.com/WikiWatershed/model-my-watershed/pull/1849

**Comment by mmcfarland** [comment]
> This was a result of an attempt to get the pagination to work on tablets and a variety of desktop sizes

I recall the issue, but the implementation which calculates the height leaves room for about a 100% increase in rows per page without over-consuming the whitespace (on a 13"), or half the number of pages needed to scroll through.  At other screen resolutions, the table makes use of the available whitespace before creating a smaller page size:

![screenshot from 2017-07-20 14 57 45](https://user-images.githubusercontent.com/1014341/28434064-16c69c56-6d5c-11e7-94b8-523ff6f92984.png)

**Comment by caseycesari** [comment]
This appears to be mostly driven by the "City" column. If the text in that column is long enough to wrap (and there are enough of rows with wrapping text, which seems to happen often), the table takes up about the right amount of space. However, if none of the column values wrap, there is extra space for more rows.

![screen shot 2017-08-18 at 1 13 51 pm](https://user-images.githubusercontent.com/1042475/29469630-26d6acd6-8417-11e7-9f96-f91228bd11be.png)

![screen shot 2017-08-18 at 1 14 03 pm](https://user-images.githubusercontent.com/1042475/29469646-3a21aebc-8417-11e7-8d87-011933b85669.png)

**Comment by caseycesari** [comment]
If we turn off text-wrapping for the "City" column, we could get a more consistent row height and fit more rows per page. The downside of that, is that it pushes the other columns further out of view.

![image](https://user-images.githubusercontent.com/1042475/29471212-252e2b4c-841d-11e7-82dd-705887111b96.png)

Is this acceptable?

**Comment by rajadain** [comment]
Wouldn't this make the City column have different widths in different pages? We exchange dynamic cell height for cell width ...

**Comment by arottersman** [comment]
> Wouldn't this make the City column have different widths in different pages? We exchange dynamic cell height for cell width ...

I think it would, but the dynamic cell width wouldn't cause the same issues. Those tables already had a width greater than the sidebar's, and scroll. I think the cell height issue comes from the pagination?

**Comment by caseycesari** [comment]
> Wouldn't this make the City column have different widths in different pages?

> I think it would, but the dynamic cell width wouldn't cause the same issues. Those tables already had a width greater than the sidebar's, and scroll. 

That is correct. We already allow for horizontal scrolling because the table doesn't fit within the sidebar.

**Comment by rajadain** [comment]
Alright. Doesn't seem like there is a way around it, and that is certainly the lesser of the two evils.

**Comment by arottersman** [comment]
Maybe we should let them open the tables in modals so they can see the whole row at once?

**Comment by ajrobbins** [comment]
I chatted with @jfrankl and we think that horizontally scrolling tables are preferable to the large amount of whitespace. So +1 to not wrapping city names.
