### ISSUE TITLE
Do not allow AoI outside CONUS

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2068]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/210/](https://rollbar.com/Azavea/MMW/items/210/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 283, in analyze_nlcd
    raise Exception('[analyze_nlcd] {}'.format(result['error']))
Exception: [analyze_nlcd] Job 0fd945eb-0f97-4c26-9f55-64afcc46a7a0 was ERROR (java.lang.Throwable: empty collection), deleted
```

**Comment by ajrobbins** [comment]
We should have a warning to the user when they draw an AoI outside the CONUS, and not permit that job to be submitted.

**Comment by rajadain** [comment]
This was the shape drawn for the error above:

![image](https://user-images.githubusercontent.com/1430060/28536306-31abbbf2-7075-11e7-9249-0190ba4872f0.png)

**Comment by jtarricone** [comment]
The approach that came most readily to mind is to simply use `turf` or something to check that the drawn shape is enclosed within a simplified GeoJSON polygon based on the perimeter of the continental US. Using a simplification algorithm via http://mapshaper.org I got a GeoJSON file that would be reasonably accurate and is only 35 kB.

@rajadain or @mmcfarland  Is this a reasonable avenue or is there a problem with this approach that I'm not seeing?

**Comment by mmcfarland** [comment]
Yep, sounds like the approach we are currently using for ensuring DRB and PA specific tasks are run within that perimeter:

https://github.com/WikiWatershed/model-my-watershed/blob/e794978f14c8fa56d2ba389856e885f7ddacd69b/src/mmw/mmw/settings/data/scripts/README.md
https://github.com/WikiWatershed/model-my-watershed/blob/e794978f14c8fa56d2ba389856e885f7ddacd69b/src/mmw/mmw/settings/data/scripts/bufferDRB.js
https://github.com/WikiWatershed/model-my-watershed/blob/ad79c3ad42cabbc8d6ddcf5ad02e3494a700c2a2/src/mmw/mmw/settings/layer_settings.py#L28-L34

**Comment by rajadain** [comment]
At first 35 additional kb sounded like a lot, but I think we're pushing 6 mb as it is, so that's a drop in the bucket. 👍

**Comment by mmcfarland** [comment]
Yeah, I would err on reduced size over increased accuracy.  Without it being extremely precise the borders will be wrong anyway, and I think we should consider them (literal) edge cases.

**Comment by jtarricone** [comment]
Once I get the actual check implemented I can see if I can get the same results with a simpler shape. All else equal, is there a target upper bound on file size?

**Comment by rajadain** [comment]
Looking at the DRB files:

```bash
$ ll (find . -name \*drb\*.json)
-rw-r--r--  1.8M Nov 10  2016 ./src/mmw/mmw/settings/data/drb_perimeter.json
-rw-r--r--  3.0K Nov 10  2016 ./src/mmw/mmw/settings/data/drb_simple_perimeter.json
```

So the simplified version is around 0.16% the file size. Let's try to achieve a similar ratio for the national one?

**Comment by jtarricone** [comment]
I have the intersection test working properly (and with a perimeter JSON file of about 7kb).

@ajrobbins or @mmcfarland What should happen if the AoI is outside the US? Is a simple alert or something good enough for now, in addition to not sending it to the API?

**Comment by rajadain** [comment]
Yeah I imagine something similar to the "too big" modal shown below:

![image](https://user-images.githubusercontent.com/1430060/28595642-b2b1aee4-7162-11e7-9148-252089ea5dc2.png)
