### ISSUE TITLE
Compare View Revamp: Add GWLF-E Hydrology Charts and Tables

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2073]
Consult mockups https://marvelapp.com/8hi9jg9/screen/30304099 for details

 - [ ] Create a set of `n` colors to be used for each scenario's line in the charts, and add a little dot next to the Scenario name in this view https://marvelapp.com/8hi9jg9/screen/30304103
 - [ ] 6 charts in GWLF-E Hydrology: Precipitation, ET, Surface Runoff, Subsurface Flow, Point Source Flow, Stream Flow. Precipitation should use a dashed line, the rest should use the assigned color

**Comment by kellyi** [comment]
Superseded by #2909 and #2915
