### ISSUE TITLE
Compare View Revamp: Wire Up Navigation

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2075]
Add the back and forward button functionality that slides scenarios in and out of view https://marvelapp.com/8hi9jg9/screen/29125397

**Comment by rajadain** [comment]
Depends on #2072

**Comment by jtarricone** [comment]
I recall there being some uncertainty about this behavior. Should the arrows just slide the oversized element around, or should they push/pop the last/first scenario to shift the lift itself?

**Comment by ajrobbins** [comment]
@jfrankl says that the arrows should just move you over one scenario. The compare-scenario-row-content class should move everything in a uniform way.

**Comment by jtarricone** [comment]
To it's just the *ordering* of scenarios and related stuff that changes? Such that the labels on the chart axis are always visible, for example?

**Comment by rajadain** [comment]
We basically just need to edit the `margin-left` value of the `.compare-scenario-row-content`, as shown here:

![2017-08-23 14 55 31](https://user-images.githubusercontent.com/1430060/29633106-2e96076e-8813-11e7-8891-8d6adc70d644.gif)

**Comment by rajadain** [comment]
The charts may need some more thought, as we'd like to keep the axis visible.

**Comment by kellyi** [comment]
I think @jtarricone mentioned this initially but I wonder whether it'd make sense to shift the list of visible scenario data rather than changing the CSS. The chart could then render a constant number of bars & we wouldn't have to worry about the y axes.

**Comment by rajadain** [comment]
It wouldn't communicate the "movement" though, achieved by something like this:

```css
transition: all 0.3s ease-in-out;
```

**Comment by rajadain** [comment]
The chart axis should always be visible.

**Comment by jtarricone** [comment]
I'm not sure how the chart axis could be visible if the chart if being moved. I was trying it out on a chart and the chart are doesn't seem to respond to just changing the left margin. There's probably some way of doing it but it could be pretty brittle.

**Comment by jtarricone** [comment]
I guess for this pass I'll just use the left margin, which will obscure the y-axis of the charts but otherwise should implement the desired effect.

**Comment by jtarricone** [comment]
One more question: should the directional shift be on a "per-click" basis, or should a continuous click stick?
