### ISSUE TITLE
Compare View Revamp: Add GWLF-E Water Quality Charts and Tables

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2077]
Mockup: https://marvelapp.com/8hi9jg9/screen/30304099

There are 57 charts in GWLF-E Water Quality total: 19 triplets of Sediments, Nitrogen, and Phosphorus, with dropdowns deciding which of the 19 to show at a time.

The table view should show either both tables, or only one and a dropdown to switch between them. Thoughts on this @jfrankl?

**Comment by kellyi** [comment]
Superseded by #2910 and #2916
