### ISSUE TITLE
Paged search results don't always fit within height of container

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2080]
When paged search results are displayed, they can be pushed lower than the on-screen container, making them invisible.  The problem is made more visible when the query filter box is expanded.

This is very similar to an issue we resolved in the GeositeFramework:
https://github.com/CoastalResilienceNetwork/GeositeFramework/pull/832
https://github.com/CoastalResilienceNetwork/regional-planning/pull/76

![screenshot from 2017-07-25 09 17 14](https://user-images.githubusercontent.com/1014341/28574053-b8459b7e-711a-11e7-8daa-feac08bd1f5a.png)

**Comment by rajadain** [comment]
Thanks for making a specific card for this with additional clues on fixing it. There is a general styling card, #1938, which calls for an overall cleanup. I added rudimentary scrolling in #2049, noting this drawback.

**Comment by mmcfarland** [comment]
Ah, sorry I missed that.

**Comment by rajadain** [comment]
Do with #2091

**Comment by rajadain** [comment]
Closing this since it has been fixed via #2087.
