### ISSUE TITLE
Cannot Duplicate Scenario with Modifications

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2084]
### Steps to Reproduce

Have a scenario with valid modifications that has had a proper run and has real results. Duplicate it.

### Expected Results

New scenario with same results. Or at least with the same inputs that succeeds after polling.

### Actual Results

New scenario with same inputs, but fails after polling.

### Demo

![2017-07-25 15 01 18](https://user-images.githubusercontent.com/1430060/28589018-5a574eb0-714a-11e7-90e6-91572fcc96bb.gif)

Also see related: #2083

**Comment by ajrobbins** [comment]
![screen shot 2017-07-25 at 3 13 32 pm](https://user-images.githubusercontent.com/12868342/28589373-dbd62672-714b-11e7-94b3-7458696cc6a6.png)

Duplicating just worked for me on staging with Mapshed modification. Testing on TR-55 now, then on prod.

**Comment by ajrobbins** [comment]
Didn't work for TR-55

**Comment by rajadain** [comment]
I think this'll be TR-55 only.

**Comment by ajrobbins** [comment]
Duplication works with TR-55 on production. https://app.wikiwatershed.org/project/17833/scenario/30562

**Comment by rajadain** [comment]
Test duplicating a scenario with modifications. That has none.

**Comment by ajrobbins** [comment]
Yikes, you're right. It doesn't work on production :(

**Comment by kellyi** [comment]
Reproduced this on staging:

https://staging.app.wikiwatershed.org/project/884/scenario/1706

Here's the corresponding Rollbar error:

https://rollbar.com/Azavea/MMW/items/194/occurrences/28175707041/

**Comment by kellyi** [comment]
Looks like duplicate scenarios with modifications are missing the `aoi_census` and the `modification_censuses` in the scenarios table: 
[missing_modifications.txt](https://github.com/WikiWatershed/model-my-watershed/files/1177370/missing_modifications.txt)

**Comment by rajadain** [comment]
Yes. We should add those fields when we duplicate a scenario here: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/models.js#L1003-L1008

**Comment by rajadain** [comment]
Honestly we should copy _all_ the fields, and only adjust `name` and `active`.

**Comment by kellyi** [comment]
That makes sense. I'll push two commits for this: one which just copies the aoi_census and modifications_hash, another which copies the entire object & updates the name field etc.
