### ISSUE TITLE
Handle differing AoI limits across catalogs

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2092]
We implemented AoI thresholds for each catalog, but they are not the same. This leads to the case in which a user searches with a larger AoI and gets CINERGI results (which appear first), then opens the WDC tab to get this error:
![screen shot 2017-07-27 at 10 45 05 am](https://user-images.githubusercontent.com/12868342/28676570-fe637fdc-72b8-11e7-9b43-d005bf1c8774.png)

This is jarrring and requires the user to create a new AoI. We should lower all thresholds to match the lowest, or investigate ways to tune performance to make HUC 8 searches viable for WDC.

Will need consult/recommendations from @jfrankl

**Comment by arottersman** [comment]
Related https://github.com/WikiWatershed/model-my-watershed/issues/2015
