### ISSUE TITLE
Allow Navigation between Search and Analyze

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2095]
Either a back button, or a switcher like MMW Model page has. Any ideas @jfrankl?

**Comment by jfrankl** [comment]
According to the wireframes, this should look like the MMW Model page:

https://marvelapp.com/5a66caa/

**Comment by caseycesari** [comment]
![image](https://user-images.githubusercontent.com/1042475/28921567-712fe6ca-7824-11e7-838e-04ab4d49634d.png)
