### ISSUE TITLE
Reduce specificity of date/time in search results

### ISSUE THREAD

**Issue by jfrankl** [WikiWatershed/model-my-watershed#2096]
Currently, we're displaying date, month, year, and time ranges in the search results. I'm wondering if it's common for the dates or even months to make a difference when a user is trying to figure out if a data set is relevant to their research. Users could more easily scan the dates if we provide less detail at this stage.

Whether or not we keep the days and months, I think we should remove the hours. This seems unlikely to be important when scanning the list of search results. 

I noticed that most hours are displayed as 7:00:00. Is that actually a popular time for collecting data or is that a default for when a time is not entered? Also, approximately 20% of the dates are 12/31, which seems peculiar.

Current app:

![image](https://user-images.githubusercontent.com/1809908/28696702-2d0d2aa8-7305-11e7-9abf-f8491353048e.png)

**Comment by ajrobbins** [comment]
Tagging @emiliom and @aufdenkampe to respond to this.

**Comment by rajadain** [comment]
In his most recent email, @emiliom said:

> For the date times, remember to just keep the date parts and drop the times.

So we can (and should) remove the hours.

We should take a look if the date discrepancy is something happening on our end or an artifact of the source data itself.

**Comment by aufdenkampe** [comment]
@rajadain, thanks for pasting in that part of the email from @emiliom. @jfrankl wasn't on that email thread, or on the call, where we also mentioned that we didn't want hours.  I fully agree with the recommendations in that email, so I'll paste it below. I'm also adding the things I would like to emphasize. 
- The first half of the location code (in front of the colon) should link to the Service, thus allowing the last line for Service to be dropped.
- I agree that Medium should be dropped, given that it seems is often redundant with info in the concept Keywords listed for Variables.
- I think Sitename could be appended to the first line, after Location, but perhaps not in bold. This may run into two lines at times, but I think that's OK. I think limiting this combined field to 1-2 lines is OK Thus the second line would end in ellipses.
- I'm leaning toward wanting to keep all lines for the list of variables, but it is verbose. I'm wondering if there is a clever way that we can figure out to abbreviate these.
- I now think it might be good to put SourceOrg right below Location + Sitename, and above Variables.
- Begin date and end date are VERY important to display, but not time.

Here's the email from Emilio.
> Overall, that's looking much nicer!
> 
> - For the date times, remember to just keep the date parts and drop the times.
> - The icons used for sample medium and variables are not intuitive or helpful. But frankly, I can't picture any icon that would. The other icons look great.
> 
> _From @ajrobbins: Each result is quite long and verbose. We have a couple of ideas to shorten and tighten up the content:
> 1. Move a line or two into the detail page - the result should be quickly scannable. If any of these variables are not crucial, they should live on the detail page that opens when the result is clicked.
> 2. Truncate the variables list so it's only one line, with ellipses at the end
> 3. Remove duplicate information: it seems like Location and Servcode are often the same (NWISUV in the example above), could that line be eliminated from the result?_
>
> Regarding #1 and #3: I don't think we can pull out any of this content. Except, indeed, the Location prefix and the Servcode string will always be identical; they are the same piece of information. Maybe the Servcode line could be removed, and the location prefix (always preceded by a colon) be turned into a link? It's possible that could be a bit confusing, though.
> 
> #2: I also think this is important. Would it be possible to truncate to one line, but expose the entire string on a mouse hover?
> 
> _From @ajrobbins: In the [Sample_WDC_Site_Record_BiGCZPortal_SearchResult](https://docs.google.com/document/d/11OzqHQSsJc-Cs2mY_yB2hixQ6D0gCV4KfJiZqiORlWs/edit) Google doc, you showed a more condensed template version. The downside to combining lines like that is that it's more difficult to scan. Ideally we'd have one isolated piece of information per line, and only 4-5 lines total. Any thoughts on how to reduce it?_
> 
> I agree with the goal. But I don't know what else to suggest to reduce the size. The site description (2nd line) could be put on the same line as the location code/string, but in many cases it's likely that the two pieces of information combined will still lead to two lines. Otherwise, if we had to drop anything, I'd drop the sample medium.
> Overall, that's looking much nicer!
> 
> - For the date times, remember to just keep the date parts and drop the times.
> - The icons used for sample medium and variables are not intuitive or helpful. But frankly, I can't picture any icon that would. The other icons look great.
> 
> Each result is quite long and verbose. We have a couple of ideas to shorten and tighten up the content:
> Move a line or two into the detail page - the result should be quickly scannable. If any of these variables are not crucial, they should live on the detail page that opens when the result is clicked.
> Truncate the variables list so it's only one line, with ellipses at the end
> Remove duplicate information: it seems like Location and Servcode are often the same (NWISUV in the example above), could that line be eliminated from the result?
> Regarding #1 and #3: I don't think we can pull out any of this content. Except, indeed, the Location prefix and the Servcode string will always be identical; they are the same piece of information. Maybe the Servcode line could be removed, and the location prefix (always preceded by a colon) be turned into a link? It's possible that could be a bit confusing, though.
> 
> #2: I also think this is important. Would it be possible to truncate to one line, but expose the entire string on a mouse hover?
> 
> 
> In the Google doc, you showed a more condensed template version. The downside to combining lines like that is that it's more difficult to scan. Ideally we'd have one isolated piece of information per line, and only 4-5 lines total. Any thoughts on how to reduce it?
> 
> I agree with the goal. But I don't know what else to suggest to reduce the size. The site description (2nd line) could be put on the same line as the location code/string, but in many cases it's likely that the two pieces of information combined will still lead to two lines. Otherwise, if we had to drop anything, I'd drop the sample medium.

**Comment by aufdenkampe** [comment]
Regarding the question of dates ending in 12/31. That is to be expected for many federal datasets that are quality controlled, such as NWISDV (daily values). These QC'ed datasets are often released for an entire year, about 3-6 months after the end of the year.

However, there some timestamps that are weird, however. These are most noticeable for NWISUV (unit values), which are near real time and should be updated at least hourly. The end date for many of those sites is in early June, but when we click on the SiteName link (for the NWISDV site of the same name), we can clearly see that the values there are completely up to date. Emilio and I noticed this and mentioned it on our last call. It could either be an error in our code or in the CUAHSI WDC web service.

**Comment by ajrobbins** [comment]
@jfrankl Is this enough info to rework the styling? We'll also have to do the work on the dev side to alter the info we're pulling in.

**Comment by ajrobbins** [comment]
Takeaways:
- Drop times, keep dates
- Remove Service part (everything *after the hyphen* in "From...webservice" and instead link it in the title.
- Move the Source org ("From Idaho State University") to be above variables
- Drop Medium (Observations on x,y,z)
- We could consider combining the first two lines, location and sitename.
- Is there a clever way we can abbreviate the list of variables?
- Another style idea: potentially make the variables look like tags, a la https://slack-imgs.com/?c=1&url=https%3A%2F%2Fkristarella.blog%2Fwp-content%2Fuploads%2Fclick-tags.png

@jfrankl

**Comment by aufdenkampe** [comment]
Arianna, thanks for that summary.

I like the idea of making the `conceptKeyword` (i.e. what we've called Variables), to look like tags. It would be very cool if clicking on one would add it to the free text search box.

One idea to make the terms shorter would be to drop everything after the comma. However, if we did that, we would likely want to re-introduce the Medium, for valuable context. So I'm not sure this makes sense. What do you think, @emiliom?

**Comment by aufdenkampe** [comment]
Arianna, thanks for that summary.

I like the idea of making the `conceptKeyword` (i.e. what we've called Variables), to look like tags. It would be very cool if clicking on one would add it to the free text search box.

One idea to make the terms shorter would be to drop everything after the comma. However, if we did that, we would likely want to re-introduce the Medium, for valuable context. So I'm not sure this makes sense. What do you think, @emiliom?

**Comment by emiliom** [comment]
Arianna's summary looks good to me -- thanks!

The tag idea for "variables" is visually nice, but I don't see how it would create compactness. Also, such tags are often links; I see the value of Anthony's idea (clicking on them refines the free text search box), but it could get tricky or confusing: should it issue a brand new request to the WDC catalog, or just refine the set of results already requested based on the previous criteria?

> One idea to make the terms shorter would be to drop everything after the comma. However, if we did that, we would likely want to re-introduce the Medium, for valuable context. So I'm not sure this makes sense. 

Yeah. Plus sample medium may be missing, and if the site measures on two different media (eg, air & water), the variable name w/o the medium suffix may be ambiguous.

A related possibility may be to do additional parsing on the variable strings, to pull out the medium suffix and use it as a new medium replacement and starting word for separated lists of variables, like this:
- `Stream:` temperature; dissolved oxygen; conductivity
- `Air:` temperature, barometric pressure, photosynthetically active radiation

I'm not positive that will work in every case, as I don't remember if every variable string (concept keyword) has a suffix. We'd need to assess these patterns first.

Regarding Jeff's comment:
> We'll also have to do the work on the dev side to alter the info we're pulling in.

Actually, I'm pretty sure all that work is already done. Terence is already pulling in all the necessary info.

**Comment by emiliom** [comment]
I realize this issue has been closed. But while the original narrow issue of reducing the specificity of date/time in WDC search results has been addressed, this github issue actually morphed into the broader topic of overall enhancements WDC search result presentation; see @ajrobbins [comment](2096#issuecomment-319114271), which I'm pasting here for convenience (and Anthony's comments prior to that, where he expanded the scope of the issue):

> Takeaways/Summary of the above:
> - Drop times, keep dates
> - Remove Service part (everything *after the hyphen* in "From...webservice" and instead link it in the title.
> - Move the Source org ("From Idaho State University") to be above variables
> - Drop Medium (Observations on x,y,z)
> - We could consider combining the first two lines, location and sitename.
> - Is there a clever way we can abbreviate the list of variables?
> - Another style idea: potentially make the variables look like tags, a la https://slack-imgs.com/?c=1&url=https%3A%2F%2Fkristarella.blog%2Fwp-content%2Fuploads%2Fclick-tags.png

Please see the comments from @aufdenkampe and me that followed up on Arianna's summary, specially regarding handling of variables and combining location and sitename. I'll refer to them below.

A week ago Arianna notified Anthony and I that the the WDC search result adjustments had been implemented on staging. I'm following up here rather than via that email.

> - We could consider combining the first two lines, location and sitename.

Anthony and I agreed this was a good idea. But it's not implemented on staging.

> - Is there a clever way we can abbreviate the list of variables?

We floated several possibilities, including Arianna's idea of a tag look. Anthony commented earlier "I'm leaning toward wanting to keep all lines for the list of variables, but it is verbose. I'm wondering if there is a clever way that we can figure out to abbreviate these." The last comment on this topic was mine, where I weighted pros and cons of some approaches. So, we didn't arrive at a definitive consensus about what to do to present variables more compactly; however, per Anthony's comment, we also did not agree that truncating the variables string to one line was the preferred path. But on staging the original Azavea mock-up idea of truncating variables was implemented. My opinion is that until we arrive at a happy consensus for compactness, the original, full variables string should be displayed. We don't want to hide from the results record any of the variables.

**Comment by emiliom** [comment]
I forgot to add this WDC result screenshot for illustration:

![selection_288](https://user-images.githubusercontent.com/742403/29434804-5bff56ec-8359-11e7-9146-ccbb231e8569.png)

**Comment by aufdenkampe** [comment]
I agree with Emilio's suggestions.
* Combine first two lines, Location and SiteName
* Implement full list of variables, even if it takes multiple lines

**Comment by emiliom** [comment]
> Implement full list of variables, even if it takes multiple lines

More specifically: revert to the original, verbose but complete presentation, *until* we come up with a consensus solution that preserves the listing of all variables but shown in a compact way.

**Comment by ajrobbins** [comment]
Thanks for circling back to this, @emiliom. I wasn't clear on the definitiveness of the responses to:
>We could consider combining the first two lines, location and sitename.
>Is there a clever way we can abbreviate the list of variables?

So we implemented what I thought was agreed upon. I've made new cards to track work/conversation on:
- Combining location + sitename https://github.com/WikiWatershed/model-my-watershed/issues/2163
- Revert variable list truncating https://github.com/WikiWatershed/model-my-watershed/issues/2164

**Comment by emiliom** [comment]
Thanks, @ajrobbins
