### ISSUE TITLE
Compare View Revamp: IE11 Flexbox Issues

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2098]
Due to a number of Flexbox issues in IE11 (see http://caniuse.com/#feat=flexbox and https://github.com/philipwalton/flexbugs), the new Compare View is unusable in it:

![image](https://user-images.githubusercontent.com/1430060/28732925-cfca32c0-73a7-11e7-884f-8122ce8c6b84.png)

vs

![image](https://user-images.githubusercontent.com/1430060/28732948-e1a91a60-73a7-11e7-97a9-19c945f10602.png)

Note the difference in horizontal alignment, missing sections view, and missing close button.

Fix these issues and make it work as it does in other browsers.

**Comment by rajadain** [comment]
A clue from @jfrankl https://github.com/WikiWatershed/model-my-watershed/pull/2094#issuecomment-318741483

> does this project use autoprefixer? If not, we'll need to manually run some kind of [autoprefixer script](https://autoprefixer.github.io/) once to handle all of that flexbox. In my experience, doing that, immediately fixes all problems with IE11.

**Comment by rajadain** [comment]
As of #2191, the issues still persist:

![image](https://user-images.githubusercontent.com/1430060/29716754-953a5304-897a-11e7-89eb-5635f74242ce.png)

Notably, the modal is not aligned left instead of being centered on the page, and the close button is missing.

**Comment by rajadain** [comment]
Also, the loading spinner from #2226 is not visible.

**Comment by ajrobbins** [comment]
I'm also not seeing the combined hydrology chart graphics in IE compare view:

![screen shot 2017-09-29 at 5 09 50 pm](https://user-images.githubusercontent.com/12868342/31036863-21a0f15e-a53c-11e7-8ec2-51581b5eadb5.png)

**Comment by caseycesari** [comment]
@arottersman My approach to this was to install the autoprefixer CLI and integrate it into our bundling process, and hope that this resolves the IE issues.
