### ISSUE TITLE
Change all geometry field names to "geometry" or similar.

### ISSUE THREAD

**Issue by lliss** [WikiWatershed/model-my-watershed#210]
In our db we use the column name "polygon" which is descriptive but may cause us headaches later. Windshaft can dynamically change table names to serve different tile data based on url but it can't change the shape data column name so they have to be consistent across all the tables. Since we may store other data than polygons it makes more sense to use a generic name for everything.

**Comment by kdeloach** [comment]
I think NYC uses the term `geom` (See: https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/apps/survey/models.py#L30)

**Comment by mmcfarland** [comment]
+1 to `geom` which is typical in PostGIS tables.

**Comment by jamesmcclain** [comment]
Okay, will-do.
