### ISSUE TITLE
Collections API: Install and Run Akka HTTP Service

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2101]
- [x] Update Ansible Provisioning to pull new JAR
 - [x] Update Upstart script to run new Akka HTTP Service

Depends on #2100 
Depends on https://github.com/WikiWatershed/mmw-geoprocessing/issues/48

**Comment by kellyi** [comment]
We'll also need to make an alpha release for the Akka Http version of the geoprocessing service.

**Comment by kellyi** [comment]
Also: we'll need to update the geoprocessing service's travis.yml file to pull the correct jar.

**Comment by kellyi** [comment]
https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image has instructions for testing travis ci builds locally using Docker images, to I'm going to try that while working on the travis.yml file

**Comment by kellyi** [comment]
We removed the Docker-based build and replaced it with TravisCI sbt/openjdk.

**Comment by kellyi** [comment]
Akka geoprocessing jar is here:

https://github.com/WikiWatershed/mmw-geoprocessing/releases/tag/3.0.0-alpha

**Comment by kellyi** [comment]
Tried `java -jar` running the api jar and both the /ping and /run endpoints worked.

**Comment by kellyi** [comment]
Upstart docs are here:

http://upstart.ubuntu.com/getting-started.html
