### ISSUE TITLE
Collections API: Convert Celery from Async to Sync

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2102]
Using the dummy Akka HTTP Service that always expects a single input and returns a single output (https://github.com/WikiWatershed/mmw-geoprocessing/issues/48), update the call from Celery to the service to act synchronously instead of asynchronously. This will involve:

 - [x] Remove `start`, `finish`, `sjs_submit`, and `sjs_retrieve` from [`geoprocessing.py`](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/geoprocessing.py)
 - [x] Add a `run` function that sends the static input to the Akka HTTP Service and consumes the response
 - [x] Replace all instances of `geoprocessing.start` and `geoprocessing.finish` tasks with that of `geoprocessing.run`

Depends on #2101

**Comment by kellyi** [comment]
This may be handled incidentally by this one, but we currently have a now-unnecessary check for whether SJS has a geoprocessing context set here:

https://github.com/WikiWatershed/model-my-watershed/blob/f4c6a4c0cdde099f0fb4ce82723e4c03ad53fce5/src/mmw/apps/modeling/geoprocessing.py#L167
