### ISSUE TITLE
Implement Hydroshare Bounding Box Filter

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2108]
Hydroshare needs `north`, `east`, `west`, `south` parameters, and additionally a `coverage_type=box` query parameter, to work. This currently fails in production, but development can be done against https://playground.hydroshare.org/ (which has a snapshot of production data). The failing bug has been identified and fixed, and will deployed to production in mid-August.

For details, see https://github.com/hydroshare/hydroshare/issues/2257

**Comment by rajadain** [comment]
Production deployment part of release [Hydroshare 1.12.0](https://github.com/hydroshare/hydroshare/milestone/47)

**Comment by rajadain** [comment]
We can probably just add the `coverage_type=box` parameter here: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/bigcz/clients/hydroshare/search.py#L63

Also, since it is a one-line change, consider removing the erroneously added date sort on CINERGI from here: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/bigcz/clients/cinergi/search.py#L121

**Comment by caseycesari** [comment]
Yeah, I was just looking into this. It seems we already send the coordinates.

**Comment by caseycesari** [comment]
> Also, since it is a one-line change, consider removing the erroneously added date sort on CINERGI from here: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/bigcz/clients/cinergi/search.py#L121

This is the change we made in the meeting this morning?

**Comment by rajadain** [comment]
Regarding:

> This currently fails in production, but development can be done against https://playground.hydroshare.org/ (which has a snapshot of production data).

I'm not sure if we should change our local endpoint to `playground` or keep it pointing at production and hope they do deploy v1.12 that has the fix mid-August. I'm leaning towards the latter.

**Comment by caseycesari** [comment]
Yeah, I was going to include testing instructions to update the URL, but leave it as is in the PR.
