### ISSUE TITLE
Compare View Revamp: Make Background Darken

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2120]
Currently because the Compare Window has no border, the white bleeds in to the background and it looks almost broken:

![image](https://user-images.githubusercontent.com/1430060/28988076-2b43f4bc-793c-11e7-9c22-10ed17b5b279.png)

The background should darken like it does for all other modals, as shown in the wireframe: https://marvelapp.com/8hi9jg9/screen/29166915

**Comment by jfrankl** [comment]
I was thinking we could use the same modal backdrop class as found in the login modal. But I'll leave it up to your judgement. Let me know if I can help.
