### ISSUE TITLE
Analyze results are cut-off when switching between BigCZ search results and analyze tab

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#2126]
![2017-08-07 11 27 29](https://user-images.githubusercontent.com/1430060/29033599-9088fc9a-7b63-11e7-9667-63614a99c5e1.gif)

**Comment by caseycesari** [comment]
I think it may be best to seek designer assistance on this issue. I tried to solve it with some basic CSS fixes, but ended up breaking the height of the tab in other views.

**Comment by ajrobbins** [comment]
OK, moving this back to the backlog. I don't see any points on it so our sprint points do not need to be adjusted.

**Comment by rajadain** [comment]
Fixed in #2459.
