### ISSUE TITLE
Analyze / Search Switcher Remains on Navigation to Home

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2129]
![2017-08-09 10 36 58](https://user-images.githubusercontent.com/1430060/29127424-073eb258-7cef-11e7-9c16-50ab8d6fc8ea.gif)

It should hide when the app is reset from clicking the top link.

**Comment by caseycesari** [comment]
Good catch. I think I can patch this up fairly quickly.
