### ISSUE TITLE
Compare View Revamp: Add loading indicator/spinner to compare view

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2134]
When precipitation is changed, the charts have to re-render. There is currently no indication to the user that anything is happening: https://github.com/WikiWatershed/model-my-watershed/pull/2123#issuecomment-321586095

**Comment by jfrankl** [comment]
Good catch. Let's model this after the proposed loading designs seen here: https://github.com/WikiWatershed/model-my-watershed/issues/1848

While model is running:

1. Add spinner
2. Change opacity of bars in bar graphs

Details in the screenshot below:

![mmw-model-running](https://user-images.githubusercontent.com/1809908/29282458-e09e085a-80f0-11e7-8765-6324dc090c34.png)
