### ISSUE TITLE
Move date filter control below text search bar

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2137]
Currently, the search pane looks like:
![screen shot 2017-08-10 at 1 18 34 pm](https://user-images.githubusercontent.com/12868342/29182858-74a6f3c0-7dce-11e7-914a-89da1bd0deb0.png)

This placement and labeling de-emphasizes the date filter considerably. Users will want to more easily and often access the date filter, and it is actually more of an additional filter (with the text search being the primary filter), not the only filter. In order to represent this visually, we should move the date filter below the free text search, and rename it to "More filters". Need @jfrankl consultation on this.

**Comment by rajadain** [comment]
Closing in favor of #2232 which would move the date filters into the filters sidebar.
