### ISSUE TITLE
Logging out should redirect user to homepage and open login prompt.

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#214]
We have a static log out page, made for #173, which needs to be designed. It will be available at [`/user/logout`](http://localhost:8000/user/logout).

**Comment by caseypt** [comment]
According to the latest mock ups by @ctaylo37, logging out redirects the user to the homepage. https://marvelapp.com/ih686e#6443208

**Comment by caseypt** [comment]
Sorry, wrong button. Updating title.

**Comment by ctaylo37** [comment]
Yes, logout should redirect to the homepage.

**Comment by rajadain** [comment]
Very well, I will make the changes once #225 is merged in.
