### ISSUE TITLE
WDC date ranges have zero-based days and months

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#2142]
The UTCDay and UTCMonth function return a 0-based index of the current day/month. We need to add one to both of these values to get the actual day/month.

**Comment by mmcfarland** [comment]
@caseycesari Could you add a quick description of where in the app we can see the months being wrong, so we can verify that it's fixed?

**Comment by caseycesari** [comment]
Yes, see the selected result below:

![image](https://user-images.githubusercontent.com/1042475/29931263-bcdd0d8e-8e3e-11e7-8815-9aaafdc6be84.png)
