### ISSUE TITLE
Which front-end pages require authentication?

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#215]
The issue #173 asks for users to be redirected to the home page if they are on a page which requires authentication. How do we figure out which ones are they? Or if the current page requires authentication?

**Comment by mmcfarland** [comment]
This is probably highly nuanced, but as a starting point:

* "My Projects" - listing of a users saved projects
* Private, saved project page
    * Either "model" or "compare"
    * It's further tricky because Public projects can be viewed without auth, but are read only and should have modification tools available.
* Account Profile pages (change password, details, etc)

It may be worth simply having an edict that logging out takes you to the root map page, perhaps retaining an area of interest.

**Comment by rajadain** [comment]
By "retaining an area of interest" do you mean that the polygon should still be there? That can be potentially problematic since there is no button that the user can press to go from having the polygon to the `analyze` view. This is done automatically in the usual case, when the user is forwarded to the `analyze` view as soon as the polygon is drawn. However, if the user is on the home page with a drawn polygon, the only way for them to get to the analyze page is to draw another polygon, thus losing the work they have currently.

**Comment by mmcfarland** [comment]
Correct, but we do have an issue for that already so it's in the works:
https://github.com/WikiWatershed/model-my-watershed/issues/121

**Comment by rajadain** [comment]
Added b3aa25f on #216 which uses the simple edict to redirect all logouts to the home page while retaining the area of interest. Thank you for the clarifications.
