### ISSUE TITLE
Indicate to user that select boundary AoI layers don't render at small scales

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#2160]
We should let the user know that they have to zoom in a bit for the layers to show up.

**Comment by mmcfarland** [comment]
Is this indicating the Layer Selector boundaries or the Draw boundaries?  For draw, zooming it won't allow it to work due to https://github.com/WikiWatershed/model-my-watershed/issues/2217.

**Comment by caseycesari** [comment]
This is for drawing. For example, at the country-wide zoom level, if you select HUC-8 boundaries, nothing renders until you zoom in a few levels.

**Comment by caseycesari** [comment]
The expected behavior in #2217 is what I'm advocating for. I'll close this since that has more details. Thanks.
