### ISSUE TITLE
Correct units on legend for Stream Layers from SRAT

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#2162]
Units are presently incorrect for the three stream layers showing mean annual water quality concentrations from SRAT. 

Presently, units are listed as "Kg/y". Units should be "mg/L".
@ajrobbins

**Comment by ajrobbins** [comment]
![screen shot 2017-08-17 at 4 15 54 pm](https://user-images.githubusercontent.com/12868342/29431830-5e380cca-8367-11e7-89af-271705dc1a4a.png)

**Comment by aufdenkampe** [comment]
Yes, exactly. Thanks.

**Comment by ajrobbins** [comment]
I've added this to our priority backlog of work. Thanks for creating the issue!
