### ISSUE TITLE
Combine Location and SiteName in WDC results

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2163]
Currently, WDC results look like:
![result](https://user-images.githubusercontent.com/12868342/29462999-205bc232-83ff-11e7-82f2-7093699e2d5f.png)

To reduce the length of the result, @emiliom and @aufdenkampe have recommended that we combine the Location (NWISDV 12101100) and Sitename (Lake Tapps...WA). @jfrankl what do you think of this idea, and how should we style it?

[WDC results key for reference](https://docs.google.com/document/d/11OzqHQSsJc-Cs2mY_yB2hixQ6D0gCV4KfJiZqiORlWs/edit)

**Comment by caseycesari** [comment]
@jfrankl FYI need your input here.

**Comment by jfrankl** [comment]
Something like this? 
![image](https://user-images.githubusercontent.com/1809908/29943871-2c4bc9ec-8e69-11e7-86b2-76a4fb47eed7.png)

In many cases, merging these two fields won't save space, because we'll just be pushing the title down to a new line (because both fields are very long).

**Comment by jfrankl** [comment]
Or 
![image](https://user-images.githubusercontent.com/1809908/29943970-8f22f158-8e69-11e7-9c54-c31b790f6185.png)

What's the is the Location or the Sitename going to be more helpful when the user is scanning through these results to try to find a dataset they want to explore?

**Comment by ajrobbins** [comment]
>is the Location or the Sitename going to be more helpful when the user is scanning through these results to try to find a dataset they want to explore?

@emiliom @aufdenkampe ^

**Comment by emiliom** [comment]
> In many cases, merging these two fields won't save space, because we'll just be pushing the title down to a new line

That is true.

> (because both fields are very long)

But this isn't always true. It's hard to say how often we'll save space. But with separate lines (current set up), the answer is never.

> is the Location or the Sitename going to be more helpful when the user is scanning through these results to try to find a dataset they want to explore?

It's not either or. It's a combination of the two. Depending on the service, the Sitename may not be as intelligible as the one in the example used (most Sitenames coming from the NWISUV service are intelligible). But the location the service provider, and its string length will also will be roughly identical across records. So I suggest we stick with the current scheme: location, then Sitename.

FYI, I believe @aufdenkampe will be offline until Monday.

**Comment by caseycesari** [comment]
Here's an implementation of the first option:

![image](https://user-images.githubusercontent.com/1042475/30064779-cc2311fe-9220-11e7-919e-a3d72a971d41.png)

**Comment by aufdenkampe** [comment]
I like the way this looks, with Location first, then SiteName.
I think we suggested moving all links off this "card" view and into the "details" view, but I can't remember if that idea was recorded or not.
Thanks!

**Comment by jfrankl** [comment]
Yes @aufdenkampe, we did agree to move links out of the list view. Not sure if there is a separate issue for that, but @caseycesari could you remove those as part of this work?

**Comment by caseycesari** [comment]
Yeah, sounds good.
