### ISSUE TITLE
Revert WDC result variable truncation

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2164]
Currently, WDC results look like this:
![result](https://user-images.githubusercontent.com/12868342/29463330-5340fa68-8400-11e7-9206-0a85764bc119.png)

At some point subsequent to https://github.com/WikiWatershed/model-my-watershed/pull/2049, we truncated the variables list to one line (second from last line in example above). Revert this change to show the full variable list.

**Comment by arottersman** [comment]
@jfrankl, should the text line up on its left margin or wrap underneath the icon?

(a)
<img width="462" alt="screen shot 2017-08-30 at 10 19 19 am" src="https://user-images.githubusercontent.com/7633670/29877154-d73bd296-8d6c-11e7-8f85-cefd426ac000.png">

(b)
<img width="469" alt="screen shot 2017-08-30 at 10 39 30 am" src="https://user-images.githubusercontent.com/7633670/29878110-9fea9ee6-8d6f-11e7-8e22-1262195960ff.png">

**Comment by ajrobbins** [comment]
I vote left margin

**Comment by jfrankl** [comment]
(b) is the way to go. Easier to scan.
