### ISSUE TITLE
Replace TR-55 Water Quality sideways bar chart with bullet chart

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2165]
Our current sideways bar graph is ineffective because TSS is always very large relatively. 
![screen shot 2017-08-18 at 12 04 54 pm](https://user-images.githubusercontent.com/12868342/29467181-813ef5b6-840d-11e7-95d2-2a55425d8ddf.png)

Replace with bullet chart as per wireframes: https://marvelapp.com/8hi9jg9/screen/29823519

**Comment by caseycesari** [comment]
We should consider using a graph type that represents parts-of-a-whole (the whole being "total loads"), illustrated here: http://www.datavizcatalogue.com/search/part_to_a_whole.html.

In the mock-ups, because of their alignment (even though the graphs are separate) and the different scales, a quick glance makes it look like phosphorus exceeds suspended solids. 

![image](https://user-images.githubusercontent.com/1042475/29467673-440b7334-840f-11e7-81eb-6bddca06e0ee.png)

**Comment by ajrobbins** [comment]
@jfrankl thoughts?

**Comment by jfrankl** [comment]
Hey @caseycesari, I see where you're coming from. A "part to the whole" graph does seem to be a natural fit for this. However, if you look at the sideways bar graph in Arianna's original post, one of the issues with this data is that the TSS is always so much higher than the other values that the graph ends up not being useful. Seems like all of the "part to the whole" graphs will run into this.

Multiple scales seems okay with the [bullet chart design specs](http://www.perceptualedge.com/articles/misc/Bullet_Graph_Design_Spec.pdf), so I don't think that part is necessarily a problem. Bullet charts are more difficult to read than some other types of charts, though.

What do you think? If there is a chart that you think would work well here and would address Arianna's original issue, I would love some help on this.

**Comment by caseycesari** [comment]
Looking at it again, I think the existing chart is workable if we add labels to the bars, like so:

![29467181-813ef5b6-840d-11e7-95d2-2a55425d8ddf](https://user-images.githubusercontent.com/1042475/29676556-60b33be6-88c6-11e7-99ac-80478d5100ac.png)

**Comment by ajrobbins** [comment]
@caseycesari I disagree - I think the existing chart is useful for comparing the three metrics to one another but that doesn't appear to be meaningful given the expected large differences among them.

**Comment by caseycesari** [comment]
Talked with Jeff. I'm happy with whatever design we move forward with.

**Comment by arottersman** [comment]
Is the conclusion of the discussion above that we should implement the bullet charts in the wireframes (https://marvelapp.com/8hi9jg9/screen/29823519)?

**Comment by ajrobbins** [comment]
@arottersman yes.

**Comment by rajadain** [comment]
What is the black bar in the mockup? 

![image](https://user-images.githubusercontent.com/1042475/29467673-440b7334-840f-11e7-81eb-6bddca06e0ee.png)

The blue rectangle corresponds to the loading rate (kg / ha), just like the current chart, I assume:

![image](https://user-images.githubusercontent.com/1430060/32574965-af005c8c-c4a0-11e7-89e2-3802eff62f6a.png)

The other two values have different units, thus can't be shown on the same graph.

**Comment by ajrobbins** [comment]
The black bar is a benchmark value that we don't have yet; ignore it in this iteration.

Loading rates just like the current graph is correct. The main difference is the styling and the fact that now each measure's chart will have it's own min and max
