### ISSUE TITLE
Compare View Revamp: Ensure ITSI Screenshots Still Work

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2166]
Ensure values shown on screen are faithfully shown in ITSI screenshots, which has been tricky in the past.

**Comment by kellyi** [comment]
Compare view isn't quite working in Chrome:

![screen shot 2017-09-26 at 2 58 13 pm](https://user-images.githubusercontent.com/4165523/30878625-33f67978-a2cb-11e7-887e-5b57c7a0d9ae.png)

**Comment by kellyi** [comment]
Identical problems in Firefox:

![image](https://user-images.githubusercontent.com/4165523/30878908-e2f1bcb2-a2cb-11e7-9ed8-e70fdb9a8fc0.png)

**Comment by kellyi** [comment]
Quick notes on how we got this set up to check locally:

- navigated to the ITSI portal here: https://authoring.concord.org/activities/5644/single_page/dec56c68-6170-4e59-b94a-82fb040e8d88
- used Requestly browser plugin to adjust the HTTP requests to replace app.wikiwatershed.org instance with an ngroked version I'd served from my local

**Comment by kellyi** [comment]
On the off chance that the compare screen was hidden behind the map & sidebar, I manually deleted all those elements from the DOM on my local then took a screenshot -- but then nothing showed up:

![screen shot 2017-09-27 at 11 49 55 am](https://user-images.githubusercontent.com/4165523/30923582-3e2d0be6-a37a-11e7-982a-4afe5c33b7d4.png)

Loading the .html version of that saved screenshot does show the compare view, so I'm assuming that some/all of these elements aren't getting rendered in time for the headless browser to capture them:

![screen shot 2017-09-27 at 11 52 22 am](https://user-images.githubusercontent.com/4165523/30923646-6fb71f94-a37a-11e7-9ffc-eb9e1a5778c1.png)

I'm going to see whether there's a way to force the screenshot to wait til everything's been rendered before making the image. I think I may also add some setup/teardown stuff to make it so the compare view takes up the entirety of the viewport in a screenshot -- as it does on iPads & other narrow screens -- then reset things once the screenshot's done.

**Comment by kellyi** [comment]
The missing compare view is related to something in the `.modal` class on `#compare-new`: with that class, the compare view doesn't appear at all in ITSI screenshots:

![screen shot 2017-10-04 at 5 39 47 pm](https://user-images.githubusercontent.com/4165523/31201043-34cf8cca-a92b-11e7-9ed8-d9dd31c8b76d.png)

Without it, the modal does show up -- albeit without some rules required to structure the scenario maps:

![screen shot 2017-10-04 at 5 40 09 pm](https://user-images.githubusercontent.com/4165523/31201063-4f5541d4-a92b-11e7-945d-00939b4e5936.png)

**Comment by kellyi** [comment]
Current strategy is to redo the CSS rules in the interval between the `saycheese` event and the `asyouwere` event:

![screen shot 2017-10-04 at 6 37 28 pm](https://user-images.githubusercontent.com/4165523/31203093-84614db6-a933-11e7-8e99-4d8160d81085.png)

Since the view spans multiple screens now, I *think* it might make sense to have a specific design for this screenshot depending on how much effort we'd like to spend on it.

**Comment by kellyi** [comment]
Turns out the remaining problems were flexbox related, so I'm creating an `itsi-compare-row` class to set things properly for PhantomJS:

![screen shot 2017-10-05 at 11 37 27 am](https://user-images.githubusercontent.com/4165523/31236311-bf3c26b6-a9c1-11e7-9b94-b58a44045c31.png)
