### ISSUE TITLE
Open water AoI area not reflected in Analysis

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2168]
I drew a 23 sq km AoI in open water, but the Analyze table shows 0 for open water (or any other type).

I thought initially I hadnt captured the centroid of a pixel, but 23 sq km is large enough that I should have.

![screen shot 2017-08-18 at 1 44 52 pm](https://user-images.githubusercontent.com/12868342/29470749-a363c12c-841b-11e7-9cf2-39df20267f86.png)

**Comment by rajadain** [comment]
If you were to turn on the NLCD layer for this AOI, would you see Open Water pixels, or nothing?

**Comment by ajrobbins** [comment]
Oh should have thought of that...nothing. Must be too far off the coast!
