### ISSUE TITLE
Geoprocessing API: Add Account Page For User To Manage API Tokens

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2188]
API tokens will be generated for every MMW user. Provide an account page where they manage their token (ie. [view it](http://www.django-rest-framework.org/api-guide/authentication/#by-exposing-an-api-endpoint
), invalidate it)

**Comment by arottersman** [comment]
@jfrankl has designs

**Comment by jfrankl** [comment]
![image](https://user-images.githubusercontent.com/1809908/30435735-7f28e5a8-9938-11e7-850e-29ebfa9f9fd8.png)

![image](https://user-images.githubusercontent.com/1809908/30435747-88fa1f7a-9938-11e7-975b-63203c31611a.png)

![image](https://user-images.githubusercontent.com/1809908/30435756-9085cbea-9938-11e7-8ef3-7135251b932c.png)

**Comment by ajrobbins** [comment]
Need another page or field for API key - talking to @jfrankl about this.

**Comment by mmcfarland** [comment]
> Need another page or field for API key

I think it can go on the Account page with Change Password.  We'd want a text box to copy the code (maybe a copy button like "share", and a button to generate the key.   A warning should be displayed that regenerating the key will invalidate any previous key.

**Comment by jfrankl** [comment]
@arottersman @ajrobbins @mmcfarland how does this look? The reset button would generate a new key and update the date. The user would see some warning after clicking the button to confirm they understand the consequences.

![image](https://user-images.githubusercontent.com/1809908/30438977-99c2f680-9940-11e7-850d-0a13d2260edf.png)

![image](https://user-images.githubusercontent.com/1809908/30438989-a26c660e-9940-11e7-9b3e-3ecb6f3a79c0.png)

**Comment by arottersman** [comment]
- For the confirmation/warning modal, the text should be something like "This will invalidate any previous requests..."

- The throttling message should be on the main page it — refers to the limit on the number of requests the user can make per minute with their API key.

- The "reset key" might be better as "regenerate key" or "get a new key"

**Comment by ajrobbins** [comment]
+1 to Alice's comments. I like "Regenerate API Key"

**Comment by jfrankl** [comment]
How about this?

![image](https://user-images.githubusercontent.com/1809908/30440198-d089f1c0-9943-11e7-889b-3ead0347c04c.png)

**Comment by ajrobbins** [comment]
LGTM

**Comment by arottersman** [comment]
This card includes the wireframes for the user profile page, but it looks like all the info on it is part of the hydroshare integration. Are the fields displayed in the wireframes finalized enough that they can be added, unpopulated, to the view for this issue? Or should it be moved to a separate card?

**Comment by mmcfarland** [comment]
I do believe these fields are finalized, but may not necessarily be part of the hydroshare integration.  Stroud is interested in capturing these additional details about users for reporting purposes.  I think if this card is directed towards just the managing of API tokens, the user profile portions should be its own task.  This will involve extending the user model.

**Comment by arottersman** [comment]
Thanks. I created this card for the API token management, but wasn't sure if it had been coopted for more. I've created #2365 for adding the profile section.
