### ISSUE TITLE
Develop legend for climate layers

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2204]
Develop legends for Mean Temp and Mean Precip which incorporate the normalization and non-linear ramping done in the creation of the visualizations.  Previous layers have discrete colors, and this is more of a true ramp.  We could either pluck out discrete values and have the scale inferred, or try to regenerate a corrected version of the one supplied from Nanoos.

![image](https://user-images.githubusercontent.com/1014341/29837847-62d0c2a4-8cc7-11e7-8b40-b5e98f0edadb.png)

@jfrankl @ajrobbins

**Comment by rajadain** [comment]
Taking the original color ramp from here: https://github.com/WikiWatershed/model-my-watershed/issues/2122#issuecomment-321374942

```python
colors = {
        "tmean": {
            "colors": [(46, 0, 103),
                       (141, 20, 255),
                       (165, 15, 245),
                       (189, 10, 235),
                       (213, 5, 225),
                       (238, 0, 215),
                       (178, 8, 225),
                       (119, 16, 235),
                       (59, 25, 245),
                       (0, 34, 255),
                       (0, 77, 199),
                       (0, 121, 143),
                       (0, 164, 86),
                       (0, 208, 31),
                       (59, 211, 23),
                       (117, 214, 15),
                       (176, 217, 7),
                       (236, 221, 0),
                       (240, 165, 0),
                       (245, 110, 2),
                       (250, 55, 2),
                       (255, 0, 4),
                       (87, 0, 16)],
            "position": [0., 0.16666667, 0.2, 0.23333333, 0.26666667,
                         0.3, 0.33333333, 0.36666667, 0.4, 0.43333333,
                         0.46666667, 0.5, 0.53333333, 0.56666667, 0.6,
                         0.63333333, 0.66666667, 0.7, 0.73333333, 0.76666667,
                         0.8, 0.83333333, 1.]
        },
        "ppt": {
            "colors": [(230, 111, 0),
                       (246, 155, 58),
                       (62, 178, 189),
                       (97, 212, 231),
                       (3, 116, 116),
                       (0, 49, 96)],
            "position": [0.0, 0.08, 0.16, 0.24, 0.32, 1.0]
        },
        "EVI": {
            "colors": [(229, 229, 229), (182, 165, 134), (160, 138, 91),
                       (138, 111, 49), (140, 127, 43), (142, 143, 37), (144, 159, 31),
                       (146, 175, 25), (138, 177, 21), (119, 165, 18), (99, 154, 15), (80, 142, 12),
                       (60, 131, 9), (41, 119, 6), (22, 108, 3), (3, 97, 0), (0, 23, 0)],
            "position": [0, 0.04, 0.08, 0.12, 0.16, 0.20, 0.24, 0.28, 0.32, 0.36, 0.40, 0.44, 0.48, 0.52, 0.56, 0.60, 1]
        }
}

tmean = zip(['#%02x%02x%02x' % c for c in colors['tmean']['colors']], [60 * p - 20 for p in colors['tmean']['position']])

ppt = zip(['#%02x%02x%02x' % c for c in colors['ppt']['colors']], [500 * p for p in colors['ppt']['position']])
```

Gives:

```python
tmean  # Values in °C
[('#2e0067', -20.0),
 ('#8d14ff', -9.999999800000001),
 ('#a50ff5', -8.0),
 ('#bd0aeb', -6.000000199999999),
 ('#d505e1', -3.999999800000001),
 ('#ee00d7', -2.0),
 ('#b208e1', -2.0000000233721948e-07),
 ('#7710eb', 2.000000199999999),
 ('#3b19f5', 4.0),
 ('#0022ff', 5.999999800000001),
 ('#004dc7', 8.000000199999999),
 ('#00798f', 10.0),
 ('#00a456', 11.999999800000005),
 ('#00d01f', 14.000000200000002),
 ('#3bd317', 16.0),
 ('#75d60f', 17.999999800000005),
 ('#b0d907', 20.000000200000002),
 ('#ecdd00', 22.0),
 ('#f0a500', 23.999999799999998),
 ('#f56e02', 26.000000200000002),
 ('#fa3702', 28.0),
 ('#ff0004', 29.999999799999998),
 ('#570010', 40.0)]
```

```python
ppt  # Values in mm
[('#e66f00', 0.0),
 ('#f69b3a', 40.0),
 ('#3eb2bd', 80.0),
 ('#61d4e7', 120.0),
 ('#037474', 160.0),
 ('#003160', 500.0)]
```

I think we should use the `ppt` colors as is in the legend. `tmean` values should be significantly curtailed, to show only 5-8.

**Comment by jfrankl** [comment]
I don't know if it makes more sense to do the discrete values or try to regenerate a corrected version. I think we should ask Stroud for their preference.

**Comment by jfrankl** [comment]
If we do a color ramp, can we use css gradients? Here's an example I made that uses the values tmean colors @rajadain posted above:

https://codepen.io/lknarf/pen/WZgjMV

**Comment by kellyi** [comment]
@jfrankl what do you think about making these legends run horizontally, as in the image pasted in the first comment?

<img width="236" alt="screen shot 2017-10-13 at 11 27 02 am" src="https://user-images.githubusercontent.com/4165523/31553754-78107118-b009-11e7-9ed0-2d74684f49b4.png">


https://codepen.io/anon/pen/EweXOd

Potentially that way we could try to have them appear above the "Mean Temp" slider here:

![screen shot 2017-10-13 at 11 25 53 am](https://user-images.githubusercontent.com/4165523/31553721-6330f902-b009-11e7-9ddf-7b76920ccf06.png)

**Comment by jfrankl** [comment]
I think we should keep the legend in the tooltip for consistency. Though, separate from that, I think it would have made sense above the mean temp.

**Comment by kellyi** [comment]
> I think we should keep the legend in the tooltip for consistency.

Sounds good. Just to clarify: I was thinking horizontal tooltip for these, with labels beneath the legend.

**Comment by kellyi** [comment]
Here's what the precipitation legend would look like if we use discrete values:

![screen shot 2017-10-13 at 1 11 16 pm](https://user-images.githubusercontent.com/4165523/31557745-0ac65866-b018-11e7-8b85-cd8a3c2bbed9.png)

Here's a version of the temperature legend using 7 discrete values, 10 degree steps:

![screen shot 2017-10-13 at 1 11 24 pm](https://user-images.githubusercontent.com/4165523/31557751-101f2748-b018-11e7-9b25-ad21eddc9ef2.png)

**Comment by kellyi** [comment]
Here's a vertical temperature tooltip with continuous values using the gradient:

![screen shot 2017-10-13 at 1 59 16 pm](https://user-images.githubusercontent.com/4165523/31559493-d131741c-b01e-11e7-853a-b1216211fc71.png)

Here's a horizontal temperature tooltip with the same gradient:

![screen shot 2017-10-13 at 1 56 22 pm](https://user-images.githubusercontent.com/4165523/31559513-e2f44788-b01e-11e7-9d52-c1a2141b12e0.png)

**Comment by rajadain** [comment]
For temperature, it looks like if we go discrete we'll need to include more values, because there is a lot of yellow on the map but no yellow in the legend. The continuous legend works better. If we can add labels to that, that'd be best.

**Comment by rajadain** [comment]
Since all our other legends are vertical, I'd be biased towards keeping this vertical too. We will have to figure out how to pad the bottom to ensure the month slider remains visible. The user should be able to look at the map, the legend, and the slider at once.

**Comment by kellyi** [comment]
I think I weakly prefer the horizontal gradients for these -- the other legends are vertical, but they also lack the month slider and display step values.

**Comment by kellyi** [comment]
This branch has the work for the gradient legends, plus a prior commit for the discrete legends shown above:

https://github.com/WikiWatershed/model-my-watershed/compare/ki/continuous-climate-legend


I think we need to determine which option to take before proceeding. @ajrobbins @jfrankl what do you think?

**Comment by ajrobbins** [comment]
I like the horizontal gradient with labels below - seems intuitive to the viewer and matches the original design in https://github.com/WikiWatershed/model-my-watershed/issues/2204#issue-253762446. We should include the units as well.
