### ISSUE TITLE
Overlapping WDC Results

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2210]
**Current Behavior**
- Draw an AOI around Mount Moriah Cemetary
_this general area_
![screen shot 2017-08-30 at 2 39 48 pm](https://user-images.githubusercontent.com/7633670/29889325-c8f3a3a6-8d91-11e7-8d19-90f87ffe11a5.png)

- The first result for searching "water" for WDC should be `NWISUV 01475548`.
- Hover over it and note which point highlights
![screen shot 2017-08-30 at 2 46 02 pm](https://user-images.githubusercontent.com/7633670/29889377-f85aa914-8d91-11e7-8c76-ca11ed109abc.png)

Open the popup for that point
![screen shot 2017-08-30 at 11 59 39 am](https://user-images.githubusercontent.com/7633670/29889391-02745878-8d92-11e7-8cd3-6d8840bb2cce.png)

- It's not the same. Instead of `NWISUV 01475548`, it's `UNH_Snow`

- It looks like there are two points overlapping (this point is a little darker than the others). We already group the WDC results by location, so this shouldn't happen

![screen shot 2017-08-30 at 11 59 31 am](https://user-images.githubusercontent.com/7633670/29888538-470c8260-8d8f-11e7-8b55-c0e5656be85a.png)

**Comment by rajadain** [comment]
Fixed in #2314.
