### ISSUE TITLE
Incorrect UTF-8 Grid Values

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2218]
For HUC-8s, there are some incorrect UTF-8 grid values. This is one example that shows hovering over the Lower Delaware HUC-8 shows Schuylkill in some areas.

![2017-08-31 15 15 23](https://user-images.githubusercontent.com/1430060/29941106-659c7552-8e5f-11e7-8629-f0024f105404.gif)

This does not happen if zoomed out further. This does not happen with HUC-12s. Not sure how isolated or systemic this is.

Clicking when it says Schuylkill selects the Schuylkill HUC-8 instead of Lower Delaware.

**Comment by mmcfarland** [comment]
Possible duplicate of #1168

**Comment by rajadain** [comment]
Ah right. Closing this in favor of that.
