### ISSUE TITLE
Add Climate Overlay Layer Legends

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2229]
Add legend for Temperature and Precipitation overlay layers, as NLCD and Soil currently do:

![image](https://user-images.githubusercontent.com/1430060/30174933-c351a5f8-93ca-11e7-9883-b0356abb4f49.png)

Make sure that the popup does not obscure the month slider:

![image](https://user-images.githubusercontent.com/1430060/30174968-e3041502-93ca-11e7-9bf2-5381637908a5.png)

So the user can see the map, the legend, and the slider all at once.

**Comment by mmcfarland** [comment]
Duplicate of #2204
