### ISSUE TITLE
Consider removing 'forgot username' option

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#223]
The wireframe for the "Retrieve account info" modal shows checkboxes for "Forgot username" and "Forgot Password". However, we are using the Django authorization module which only provides a password reset mechanism (which sends the username and allows the user to reset their password). For now, these checkboxes don't do anything, but we should either remove them, or modify the functionality so that it's possible to only email the user their username. The latter option doesn't seem like it would be very useful.

![screen shot 2015-05-26 at 3 59 22 pm](https://cloud.githubusercontent.com/assets/1896461/7821949/3b88ceb8-03c0-11e5-80ca-465e751c65a8.png)

**Comment by lewfish** [comment]
Wow, that's a big screenshot.

**Comment by mmcfarland** [comment]
You Mac users and your retina screens!

**Comment by caseypt** [comment]
I think we could remove both the checkboxes and just have a the email field.

**Comment by jfrankl** [comment]
Yeah let's remove the checkboxes.

**Comment by ajrobbins** [comment]
Addressed with redesign in #2254
