### ISSUE TITLE
BiG-CZ: Implement Filters Sidebar

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2232]
Implement filters sidebar which should contain date filters (which apply to all catalogs), and any catalog specific filters (such as "Include Gridded" for CUAHSI).

@jfrankl could you please add the mockups to this issue?

**Comment by jfrankl** [comment]
### Screen 1
![image](https://user-images.githubusercontent.com/1809908/30185291-d5a4556a-93ee-11e7-90bc-60b5f5af5ac7.png)

### Screen 2
![image](https://user-images.githubusercontent.com/1809908/30185315-f1a85be4-93ee-11e7-985b-8dbeeab9ffc4.png)
