### ISSUE TITLE
BiG-CZ: WDC Detail View

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2234]
Need template from @aufdenkampe / @emiliom for what to include.

If the service supports historical data, fetch and display one week's worth of it by default. We can expand on showing more after the user asks explicitly.

**Comment by rajadain** [comment]
The actual charting should be done as part of #2238.

**Comment by aufdenkampe** [comment]
@rajadain, @jfrankl & @emiliom.

I created a mockup in the [Sample_WDC_Site_Detail_BiGCZPortal_SearchResult](https://docs.google.com/document/d/1Kot_Toow6FPpI9FHImsx078W7Jn3UwMME4MOnersX2A/edit) Google Doc.

Here is a screenshot:
![screen shot 2017-09-08 at 4 05 11 pm](https://user-images.githubusercontent.com/5166036/30231238-9eb7f130-94af-11e7-8a05-97203c7ac4b5.png)

Please see the Google Doc for information on how it should be constructed from web service response fields, and comments on optional fields.

**Comment by aufdenkampe** [comment]
Here is the description of how to construct from web service responses, where: 
- we use Markdown syntax to indicate links
- A GetSeries request is implied for all fields, except...
- a GSERV prefix implies that the information comes from a cached GetServices request

---------
![screen shot 2017-09-08 at 4 09 28 pm](https://user-images.githubusercontent.com/5166036/30231368-2f9d06e0-94b0-11e7-99d0-d0102f1717bb.png)
---------

This image does not include comments that re in the Google Doc. Here is my best attempt at copying them
-  After Site, the <ServCode> prefix is removed after <location> in the title
-  After Source: (info) opens a Pop up tool tip, showing text from <GSERV:aabstract>
- for the buttons:
  - Change "Respository" to "Source Data". This is optional, and links or original sources constructed in patterns such as: https://waterdata.usgs.gov/nwis/uv/?site_no=01478120, when ServCode = "NWISDV" and location = "NWISDV:01478120"​
  - "Web services" links to the Service URL. Where:
    - The ServURL in from GetServicesInBox2 does not provide a web-friendly URL (e.g. for ServCode = "NWISDV", ServURL = "http://hydroportal.cuahsi.org/nwisdv/cuahsi_1_1.asmx"). However, a friendly URL can easily be constructed from ServiceID (which has a 1:1 map with ServCode) by following this pattern: http://hiscentral.cuahsi.org/pub_network.aspx?n=1
- If <Speciation> is "Not Applicable", then show nothing.
- Show most recent data value, from a Water One Flow (WOF) get values request.
- Fetch and show most recent week of data. We may eventually want to have options to view more than a week. Perhaps buttons for 1w (default), 1m, 3m.
