### ISSUE TITLE
Do not include catchments in Analyze which are not well contained in AoI

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2240]
The SRAT catchment water quality data comes from a different source than the RWD areas are derived from. This causes some discrepancies that lead to misleading results in the water quality tab for Analyze.

To replicate, delineate an area with RWD and observe that the SRAT catchments (hover over IDs) don't align. So we're capturing "intersecting" catchments that aren't truly intersecting.

![screen shot 2017-09-07 at 4 39 28 pm](https://user-images.githubusercontent.com/12868342/30184398-f802ba0a-93eb-11e7-91c8-40a94dfcf0cd.png)

Expected behavior: these not-really intersecting catchments are not included in the results.

We discussed potentially applying a buffer to the intersection query, so that catchments have to intersect with the AoI more significantly in order to be shown in the table.

**Comment by mmcfarland** [comment]
We're simplifying both the RWD shape and the catchment, so the intersection you see above most likely does not represent the true intersection.  A better visual check is an RWD + Catchment overlay:

![screenshot from 2017-09-21 10 59 16](https://user-images.githubusercontent.com/1014341/30702815-f73c87a6-9ebb-11e7-91b8-0520e80d988c.png)

Even with Contenental RWD, the borders align very well, but it looks like the shared borders count as an intersection.  We should probably adjust [the query](https://github.com/WikiWatershed/model-my-watershed/blob/ede8167ee26e860c19b692eb9ea135e41881cb32/src/mmw/apps/modeling/calcs.py#L108-L117) such that it only includes catchments whose intersection is something like > 1% of the area of the AoI.
