### ISSUE TITLE
Upgrade Celery

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2249]
There are numerous issues with Celery 3, which are no longer being addressed. The current version of Celery is 4, and can work with Django 1.8, thus we can upgrade to Celery 4 without first upgrading Django #2146.

Upgrade notes can be found here: http://docs.celeryproject.org/en/latest/whatsnew-4.0.html

Upgrade Celery to the latest version, and adjust related code to match.

**Comment by kellyi** [comment]
Started looking at this.

**Comment by kellyi** [comment]
Sounds good. Seems like everything cleanly upgrades to 3.1.25 -- the first suggest step in the upgrade guide above -- so I'll do that then this http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#step-2-update-your-configuration-with-the-new-setting-names and get that working before moving to 4.x

**Comment by kellyi** [comment]
Q: is there any reason we didn't add the `--purge` option to `debugcelery`'s command to start the Celery worker? Looks like it dumps previous messages on restarting.

Going to enable it while working on this on my local, but conceivably we could add it to the script checked in here, too.

**Comment by kellyi** [comment]
Relatedly, looks like we'll have to drop `--autoreload` from that script since...

> The --autoreload feature has been removed.
>
> This was an experimental feature, and not covered by our deprecation timeline guarantee. The flag is removed completely so the worker will crash at startup when present. Luckily this flag isn’t used in production systems.

http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#features-removed-for-lack-of-funding
