### ISSUE TITLE
BiG-CZ: No Climate Data for Small AoIs

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2253]
Because the size of the raster tiles for climate data (ppt and tmean rasters) are so large, if a small AoI does not intersect with their center, we get 0 values:

![image](https://user-images.githubusercontent.com/1430060/30395791-66565036-9895-11e7-8d56-583778bdae07.png)

To reproduce: draw a 1 sq km AoI anywhere and see that there is no climate data.

One potential way to fix this may be to treat the tiles as polygons rather than pixels. Another way may be to find the nearest tile and just use its values.

Implement such a fix, and describe how it addresses the problem.

**Comment by mmcfarland** [comment]
Rasterio has a flag for how to handle included cells, via centroid or intersection.  If GT exposes something similar, we should expose it as a flag based on what we know about each layer.  In practice, that would mean climate analysis would use intersection and the rest would continue to use centroid.

@echeipesh does GeoTrellis have the ability to specify the mechanism for determining which pixels to use on the fly, or is centroid baked in?

**Comment by echeipesh** [comment]
GeoTrellis has this concept of point vs area and it is already applied in the layer filter logic here: https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/LayerFilter.scala#L139

What is the context for this question? If there is a rasterizer that walks over the resulting tile it would have similar options available to it.
