### ISSUE TITLE
Update user onboarding/login modal styling

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2254]
Jeff has designed new user onboarding modals to update/replace the existing modals.

New login modal:
![login-1](https://user-images.githubusercontent.com/12868342/30433520-a657760e-9932-11e7-9c56-89517d44f9ff.jpg)

New password reset modal:
![login-2](https://user-images.githubusercontent.com/12868342/30433551-be293e7a-9932-11e7-8da2-c7abf9254821.jpg)

New account creation/register modal:
![login-3](https://user-images.githubusercontent.com/12868342/30433620-f7aa0e90-9932-11e7-99e2-4c2ebe0e9af3.jpg)

New confirm your email modal:
![login-4](https://user-images.githubusercontent.com/12868342/30433645-0349126e-9933-11e7-8e9c-27c0e21b3fea.jpg)

**Comment by caseycesari** [comment]
We'll also need mock-ups for when there is an error (ex. incorrect password, not a valid email, etc.)

**Comment by jfrankl** [comment]
When there is an error related to a specific field, display error message under that field.
![2](https://user-images.githubusercontent.com/1809908/30560124-e9479e94-9c84-11e7-8c76-8deb453a3b82.png)

When an error is not related to a specific field (general error, multiple fields), display at top.
![1](https://user-images.githubusercontent.com/1809908/30560125-e94ef8ba-9c84-11e7-81f3-8ca72c314f07.png)

@ajrobbins & @caseycesari let me know if you have feedback.

**Comment by ajrobbins** [comment]
LGTM!

**Comment by arottersman** [comment]
Should we match the styling for the inputs in the wireframes? Currently most of our text inputs look like this:
<img width="411" alt="screen shot 2017-10-26 at 9 44 24 am" src="https://user-images.githubusercontent.com/7633670/32056463-ba074366-ba32-11e7-8cfb-d54bb3600b30.png">

**Comment by ajrobbins** [comment]
The styling should match the wireframes posted in the issue. Also apply the new styling to the new modal created in https://github.com/WikiWatershed/model-my-watershed/pull/2432
