### ISSUE TITLE
Extend user model fields and create UI to populate them on sign up

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2255]
Stroud would like to capture some more user information for tracking and reporting purposes, so we are adding a user "survey" during the onboarding workflow. This is a new modal that should appear after the user registers for a new account and confirms their email address (so, the first time they log in after confirming their email):

![profile](https://user-images.githubusercontent.com/12868342/30434068-3aab6b70-9934-11e7-8f8f-3af7fa9025d3.jpg)

First name, last name, Organization, and ZIP should just be text fields for now. User type should be a dropdown menu of the following options: 
![screen shot 2017-09-14 at 10 10 17 am](https://user-images.githubusercontent.com/12868342/30434313-f746b816-9934-11e7-9b1a-8b89196ea643.png)

Country should be pre-filled with United States, but offer all countries as options.

This survey is optional, so clicking "I'll do this later" at the bottom should dismiss the modal.

If the survey fields are completed, we should save the information with the user record in the database.

**Comment by caseycesari** [comment]
This will require updating the database and applying a migration.

**Comment by mmcfarland** [comment]
Some of these user model attributes are choices as listed above, and all are optional.

**Comment by jwalgran** [comment]
I have a question about this workflow. If the user clicks "I'll do this later" should the form be shown the next time they log in, or should it never be shown?

**Comment by ajrobbins** [comment]
They should be shown a notification/alert the next time they log in, as described in https://github.com/WikiWatershed/model-my-watershed/issues/2256
