### ISSUE TITLE
Create notification for incomplete user profile

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2256]
In #2255 we're adding a user survey/profile to the user onboarding workflow. The survey is optional, so the user can dismiss it without completing it. This information is important for user tracking/reporting, so we want to encourage the user to complete this information anytime they are signed in, without being too aggressive.

When they dismiss the survey without completing it, we show this blue dot with tooltip and cover the screen with a semitransparent black overlay. Clicking "okay" dismisses the tooltip and the overlay.

![profile-bump-1](https://user-images.githubusercontent.com/12868342/30434913-6ebe20c2-9936-11e7-9aeb-24a4fcdfca58.jpg)

All subsequent times they are logged in with an incomplete profile, we show the blue dot next to their username:
![profile-bump-2](https://user-images.githubusercontent.com/12868342/30434925-761ade28-9936-11e7-940f-808d07685053.jpg)

Clicking the blue dot takes the user to their profile page, part of our new account page design (first screenshot on https://github.com/WikiWatershed/model-my-watershed/issues/2188#issuecomment-329502327)

Depends on #2255 and #2188

**Comment by caseycesari** [comment]
Will require logic to determine if a user has completed the additional profile fields. We may consider adding a field that tracks if a user has completed these steps, rather than rerunning the logic on every page visit.

**Comment by jwalgran** [comment]
`was_skipped` and `is_complete` status fields added in 2432
