### ISSUE TITLE
Save on Edit for projects and scenarios

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#226]
Initial auto-save functionality should be to save project/scenarios on attribute changes.  Keep the update as narrow as possible, ie, when a scenario name is changed, don't update all project scenarios or the project.  This workflow applies only to logged in users.

**Comment by caseypt** [comment]
- Remove controls for public projects that don't belong to the user.
- Don't try to fire save requests when non-owner is viewing project.

**Comment by lliss** [comment]
- if logged in - wait until a project attribute is changed or a scenario is added
 - if logged out, the login should trigger a save, probably immediately
