### ISSUE TITLE
Search WDC with date parameters results in error

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2277]
Search WDC with a keyword and it returns an expected result.  Add a date filter and the status code is `400`.

To reproduce:
1. Draw an area around John Heinz
2. Search for Water, click WDC
3. Open the filter panel and add a date

![screenshot from 2017-09-21 10 24 44](https://user-images.githubusercontent.com/1014341/30701009-3cdd205e-9eb7-11e7-9821-1977aed8101e.png)

**Comment by rajadain** [comment]
Can't seem to reproduce it on staging right now:

![image](https://user-images.githubusercontent.com/1430060/32345982-3a003122-bfe2-11e7-945e-06b29df169b5.png)

so closing this until it is reported again.
