### ISSUE TITLE
Compare View Revamp: Chart Tooltip Improvements

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2278]
Following #2158 and #2245, we now have chart tooltips. However, there are two issues:

 * Tooltips for very high values are cropped out:

    ![image](https://user-images.githubusercontent.com/1430060/30705702-31e51744-9ec4-11e7-9a99-18b3038ef569.png)

 * Tooltips are shown for 0 value elements in a stacked chart:

    ![image](https://user-images.githubusercontent.com/1430060/30705739-4dd2241a-9ec4-11e7-8133-6661d1abbc05.png)

Make it so that:

 - [ ] Tooltips are always visible, no matter their position in the chart
 - [ ] 0 value tooltips are shown for single value bar charts, but not for stacked value bar charts

**Comment by arottersman** [comment]
![Screen Shot 2017-10-02 at 1.58.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57b31ed59131fe0e00a15844/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236454f16b7191a379f117234f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ee8833c5771c13811aabc8349ed05be208b4bd1b0edd919d2f42f67b6d5db1063474f4dcbed5727a19041c95df64de84b52a51b326ae1702431.png)

When there are many scenarios and you pan over with the arrows, tooltips still appear for the bars on the left.

Should this issue be addressed with this card or is it lower priority?

**Comment by rajadain** [comment]
Depends on the difficulty. If it can be easily done, it should be included. Else offloaded.

**Comment by arottersman** [comment]
> If it can be easily done
I was going to comment laughing at this, but then the bug turned out to be related to the underlying cutoff tooltip issue, and I was able to "easily" add in a fix for this.
