### ISSUE TITLE
BiG-CZ: Implement Multiple Overlapping Popup

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2282]
For when there are multiple overlapping boxes (in CINERGI), or points (in WDC), clicking the geometry on the map should not open a popup for just the top one. Instead, it should open a popup listing all the shapes, in a paginated format.

@jfrankl to provide wireframes here.

**Comment by jfrankl** [comment]
![screen shot 2017-09-25 at 4 07 10 pm](https://user-images.githubusercontent.com/1809908/30828442-b23f7066-a20b-11e7-8a64-c1370ee9458c.png)
![screen shot 2017-09-25 at 4 07 16 pm](https://user-images.githubusercontent.com/1809908/30828441-b23ca908-a20b-11e7-868f-eb64388e817b.png)

**Comment by arottersman** [comment]
@jfrankl should there be a way to navigate back to the list popup from the regular popup?

**Comment by jfrankl** [comment]
Good idea. Could you drop a back button on the top of the popup? 
![image](https://user-images.githubusercontent.com/1809908/30985519-6bc84144-a45e-11e7-9720-2bc064cef76f.png)
