### ISSUE TITLE
Add user account pages

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2283]
With features incoming to add user profile fields and expose an API key to users, we need an account page for users to manage their account, login, and API key. Wireframes attached.
[2017_09_14_mmw_account_v1.pdf](https://github.com/WikiWatershed/model-my-watershed/files/1322610/2017_09_14_mmw_account_v1.pdf)

**Comment by caseycesari** [comment]
This will require updating the database and applying a migration.

**Comment by ajrobbins** [comment]
Not to be included in upcoming release.

**Comment by ajrobbins** [comment]
Closing in favor of #2188
