### ISSUE TITLE
Allow multiple "Untitled Projects"

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#229]
When creating a new project, the default name should read "Untitled Project" a la Google Docs.  We don't force the user to rename a project, but a project must be unique within a user account.  We should make accommodations for multiple untitled projects, presumably by not storing that actual name, but otherwise indicating on the model that it is yet unnamed and having the displayed name be a UI consideration only.

**Comment by caseypt** [comment]
Instead, remove the unique constraint from project name per user
