### ISSUE TITLE
Base Flow Index incorrectly calculated for MapShed

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2293]
The bfi48grd GeoTiff has values which range from 0-91.  When calculating Groundwater Recession Coefficient, the average BFI is calculated over the AoI.  This value is then used to calculate the GRC value, thusly:

```
GRC = BFI * -0.0015 + 0.1103
GRC = GRC if GRC >= 0 else 0.01
```

In practice, we are writing out `0.01` for the value in the GMS too frequently, which indicates that GRC is less than 0, which happens only when BFI > ~74.  These are non-typical values, the normal range for GRC is `0.02` - `0.06`.

Upon inspection, it looks like the geoprocessing service is returning average values of > 100, which will result in `0.01` for a GRC, since its original value is negative.  The average of BFI is somehow too large.  Check that either the ingested raster has not had its values shifted, or that the averaging function is not deficient.  The original GeoTiff on the fileshare appears accurate.

```
> gdalinfo -mm bfigrd48
STATISTICS_MAXIMUM=91
STATISTICS_MEAN=42.691618734836
STATISTICS_MINIMUM=0
STATISTICS_STDDEV=19.46358279968
```

### Sample HUC
Name: City of Philadelphia-Schuylkill River, HUC-12 Subwatershed
WKAoI: `huc12__55174`
[RasterGroupedAverage value](https://github.com/WikiWatershed/model-my-watershed/blob/ac2f981f95736bac2edcfeb9f11bfc95dc88c5a6/src/mmw/apps/modeling/mapshed/tasks.py#L350-L353) (BFI): `152.222222222`

This average value is seemingly higher than even the maximum value in the source raster.  A crude check against the tif shows the expected values to be in the mid-40s range.

**Comment by mmcfarland** [comment]
One additional data point, it seems like the Averaging job is correct, but that the raster has inflated values.  A RasterGroupedCount of the same HUC from above counts a single cell of `152`.  A grouped count of the containing HUC 10 shows:

```
{
u'List(163)': 3, 
u'List(171)': 5,
u'List(133)': 1, 
u'List(197)': 1,
u'List(178)': 2,
u'List(152)': 3,
u'List(159)': 2,
u'List(186)': 1,
u'List(148)': 3,
u'List(167)': 6, 
u'List(175)': 5,
u'List(156)': 1, 
u'List(182)': 3, 
u'List(140)': 1
}

```

**Comment by arottersman** [comment]
Something got messed up while/before chunking the tif for ingest. The mean is greater than the original tifs max value.

```bash
> gdalinfo ../civicapps-etl/raw/bfi48grd_chunks/bfi48grd_5070_1_1.tif -stats -mm
...
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=223.89266967773
    STATISTICS_MINIMUM=19
    STATISTICS_STDDEV=43.48303401102
```

I'm going to rechunk from the fileshare tif, check the values, and then ingest again.

**Comment by arottersman** [comment]
Issue was the way I had exported the ArcGIS-formatted originals to `.tif`. The `soilpalland2` was also incorrect: should be
```
  Minimum=35.000, Maximum=7788.000, Mean=596.992, StdDev=318.515
```
But instead exported as
```
  Minimum=70.000, Maximum=2232.000, Mean=662.625, StdDev=283.983
```

(SoilN was fine.)

I've created new ingests at `bfi48grd-epsg5070-09262017` and `soilpallland2-epsg5070-09262017`. Will put up a PR to have the tasks use them.

**Comment by arottersman** [comment]
On a branch that uses the corrected ingests, the values now seem to fall within the bounds of the original rasters (as @mmcfarland noted, the `bfi48grd` values hover around 40).

To be sure, I wanted to test the whole, national raster, so I modified `mapshed.tasks.geoprocessing_chains()`:

```python
# bounding box around the country I drew in geojson.io
    national_aoi = """
    {"type": "MultiPolygon", "coordinates": [[[
            [
              -130.78125,
              22.59372606392931
            ],
            [
              -61.17187499999999,
              22.59372606392931
            ],
            [
              -61.17187499999999,
              51.83577752045248
            ],
            [
              -130.78125,
              51.83577752045248
            ],
            [
              -130.78125,
              22.59372606392931
            ]
          ]]]}
    """
    task_defs = [
        ('nlcd_soil',    nlcd_soil,    {'polygon': [aoi]}),
        ('soiln',        soiln,        {'polygon': [aoi]}),
        ('soilp',        soilp,        {'polygon': [national_aoi]}),
        ('recess_coef',  recess_coef,  {'polygon': [national_aoi]}),
        ('gwn',          gwn,          {'polygon': [aoi]}),
        ('avg_awc',      avg_awc,      {'polygon': [aoi]}),
        ('nlcd_slope',   nlcd_slope,   {'polygon': [aoi]}),
        ('slope',        slope,        {'polygon': [aoi]}),
        ('nlcd_kfactor', nlcd_kfactor, {'polygon': [aoi]}),
        ('nlcd_streams', nlcd_streams, {'polygon': [aoi],
                                        'vector': streams_from_geojson(aoi)}),
    ]

```

I logged the resulting GroupedAverage values.`soilpallland2` was `371.74858052`, and`bfi48grd` was `26.5200593167`. These are almost half the mean-values given by the `gdalinfo` stats on the original tifs. Are the ingests still bad or is there something wrong with the way I'm testing?

/cc @rajadain @mmcfarland

**Comment by arottersman** [comment]
Branch is [here](https://github.com/WikiWatershed/model-my-watershed/tree/arr/mapshed-layer-corrections)

**Comment by mmcfarland** [comment]
Speculation, but it could be a difference in `NODATA` values.  You've got substantial area in the oceans that may be getting interpreted as `0`, which would depress the overall mean value.  GDAL may be treating those as NODATA (or, as likely, not including that area at all) and thus not included them in the mean.  If you want to triple check, try a more complex shape that adheres to the CONUS boundary and see if that has a substantial increase in mean values.

**Comment by arottersman** [comment]
That's probably it. Ran a check in the ocean and it output `0` for those jobs. Will update the test.

**Comment by arottersman** [comment]
Drew a shape more form-fitted to the CONUS and the values are much closer:`569.380416422`
`40.71185983` for `soilpallland2` and `bfi48grd` respectively.
