### ISSUE TITLE
Add catalog name on detail page

### ISSUE THREAD

**Issue by jfrankl** [WikiWatershed/model-my-watershed#2295]
Add catalog name (Water Data Center, etc.) on detail page.

![image](https://user-images.githubusercontent.com/1809908/30871787-f95f2e14-a2b5-11e7-9c61-f178da766c58.png)

**Comment by ajrobbins** [comment]
Snuck into a previous PR:
![Screen Shot 2017-10-05 at 1.41.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5685332b20438e130091808c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236454f66b7191a379f1162a4f5e595ecc3c4a4356bcbbd671f3e57862804e0ee8833c5771c13811aabc8349ed05be208b4bd1b0edd919d2f42f67b6d5db1063474f4dcbed5727a19041c95df64ce34f50a7163165e17f2431.png)
