### ISSUE TITLE
Document Collections API Geoprocessing Service Requirements

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2300]
Update the README to indicate that:

 * The developer must have `~/.aws` folder locally
 * The `default` credentials must be setup to access `azavea-datahub`
 * The `~/.aws` directory must have permissions of 755
 * The `~/.aws/credentials` and `~/.aws/config` must have permissions of 644

**Comment by rajadain** [comment]
Or bypass all that by switching provisioning to this: https://github.com/azavea/usace-levee-safety-api/blob/develop/Vagrantfile#L10

**Comment by caseycesari** [comment]
I'm not sure if it's possible, but I don't think the provisioning should dictate what each user has as their `default` aws profile. Ideally, we could specify in the provisioning to use the `datahub` profile.

**Comment by rajadain** [comment]
It is possible. We just need an `AWS_PROFILE` environment variable declaration in the worker VM, and it should pick up the correct credentials.
