### ISSUE TITLE
Map interaction broken after modeling

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2303]
### Problem
All map interactivity, including zooming and panning is broken after running through a model and returning to the main screen.  Observed on staging @ f4ee3ee7f9c8aa5ccb58a4139a0f7c0557662e29.

#### Steps to reproduce
1. Select an area to analyze
1. Select Multi-Year model
1. When the model completes, click "New Project"
1. You are returned to the select AoI screen, and the map cannot be interacted with.

There don't appear to be JS errors in the console.

**Comment by mmcfarland** [comment]
Looks like similar behavior can happen from just going to Analyze, then Change Area.

**Comment by arottersman** [comment]
When going from Analyze -> Change Area -> Sq Kilometer -> Analyze, it freezes, and I see this error in the console:
```
vendor.js:76085 Uncaught TypeError: Cannot read property 'getLatLng' of undefined
    at NewClass._fireCreatedEvent (vendor.js:76085)
    at NewClass._onClick (vendor.js:76085)
    at NewClass.fireEvent (vendor.js:77268)
    at NewClass._fireMouseEvent (vendor.js:79019)
    at NewClass._onMouseClick (vendor.js:78999)
    at HTMLDivElement.handler [as _leaflet_click1] (vendor.js:83198)
_fireCreatedEvent @ vendor.js:76085
_onClick @ vendor.js:76085
fireEvent @ vendor.js:77268
_fireMouseEvent @ vendor.js:79019
_onMouseClick @ vendor.js:78999
handler @ vendor.js:83198
```

I don't notice the same for free draw.

**Comment by ajrobbins** [comment]
I'm observing the freezing behavior when I simply select an AoI via any method, and proceed to Analyze the first time.

**Comment by arottersman** [comment]
Related (?) Base map gets stuck in big cz, but zooming still works for feature group:
![artgalt5r5](https://user-images.githubusercontent.com/7633670/30970869-4a9e90b0-a434-11e7-8b08-88f9dddedc07.gif)
