### ISSUE TITLE
Reset button should only appear when filters are selected

### ISSUE THREAD

**Issue by jfrankl** [WikiWatershed/model-my-watershed#2317]
When there are no filters selected in BiG CZ, we should hide the "Reset" button. The "Reset" button should appear when a filter is selected. That way, the button will never be visible to the user when clicking on it doesn't perform any action.

**Comment by rajadain** [comment]
Should the Reset button clear all filters, or restore all filters to the default state? I'd think the latter. WDC for example has "Exclude Gridded" checked by default:

![image](https://user-images.githubusercontent.com/1430060/31740576-c7302b48-b41f-11e7-9b7a-a51c1b4f18e4.png)

**Comment by ajrobbins** [comment]
I think default
