### ISSUE TITLE
Site storm results are identical for 100% forest and current conditions

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2322]
Observed:
100% forest results = current conditions results for runoff and water quality:
![screen shot 2017-10-03 at 2 33 41 pm](https://user-images.githubusercontent.com/12868342/31142445-502d3a0a-a848-11e7-808a-13501cf2f302.png)
![screen shot 2017-10-03 at 2 34 40 pm](https://user-images.githubusercontent.com/12868342/31142446-512282a8-a848-11e7-90c8-52b49e2179e7.png)

Expected:
Results should be different, especially in urban areas. This was previously addressed, for water quality at least, in https://github.com/WikiWatershed/model-my-watershed/pull/1802.

**Comment by arottersman** [comment]
We aren't parsing the results for the compare view correctly: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/compare/models.js#L67

We're always accessing the value in the `modified`key, but there are 3 values:
`modified`, `unmodified` and `pc_unmodified`. `pc_unmodified` corresponds to the value of the model run under precolumbian/100% forest conditions.
