### ISSUE TITLE
Upgrade node and npm

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#2323]
The versions of node ([0.10.32](https://github.com/azavea/ansible-nodejs/blob/develop/CHANGELOG.md#011)) and npm ([2.1.17](https://github.com/WikiWatershed/model-my-watershed/blob/2b17268dc31e6dd07e50c4d8b1cf349ca6fb0a1b/deployment/ansible/group_vars/all#L33)) the project utilizes are no longer supported.

We should upgrade to recent versions with LTS plans.

Node LTS plan: https://github.com/nodejs/Release#release-schedule1
npm LTS plan: https://github.com/npm/npm/wiki/LTS#historical-note

**Comment by rajadain** [comment]
Having attempted many versions of this, I have been unable to upgrade `node` / `npm` without breaking the current build process. I do not think we can upgrade `node` without also moving away from Browserify. We may have to investigate if something like Webpack can be used to build the MMW front-end.

For the purposes of PA DEP, I recommend going with a Docker approach, akin to Beekeepers.
