### ISSUE TITLE
Replace placeholder text in Compare View mini-map tooltips

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2325]
![screen shot 2017-10-04 at 4 49 52 pm](https://user-images.githubusercontent.com/12868342/31199019-234c5da4-a924-11e7-94ef-266f255da3e0.png)
![screen shot 2017-10-04 at 4 49 57 pm](https://user-images.githubusercontent.com/12868342/31199023-247751f2-a924-11e7-9afa-9a1fa65764b1.png)

@aufdenkampe @SRGDamia1 Can you provide text for the current conditions and 100% forest column headers?

**Comment by SRGDamia1** [comment]
100% Forest Cover -
        Title should read, "Predominantly Forested"
        ​This scenario shows the Site Storm Model results ​for this area of interest after replacing all "non-natural" (agricultural and urban) land use types with deciduous forest.  Natural land-use types (such as wetland) remain unchanged.

​Current Conditions​ -
        ​Title should read, "Current Conditions"
        ​This scenario shows the Site Storm Model results ​for this area of interest based on national data from the 2011 National Land Cover Database (NLCD) and 2016 Gridded Soil Survey Geographic (gSSURGO) Database.

**Comment by aufdenkampe** [comment]
Here's an attempt to shorten it up to about 12-15 words (based on my count of the mockup)

100% Forest Cover -
* Title should read, "Predominantly Forested"
* ​Model simulation of a pre-development landscape, where forest replaces all agricultural and urban landcover.

​Current Conditions​ -
* ​Title should read, "Current Conditions"
​* Model results based on 2011 NLCD land and 2016 gSSURGO soil datasets.

@mmcfarland, let us know if these needs to shortened further.

We'll put the lengthier descriptions in our Tech Docs.
