### ISSUE TITLE
What does read-only mode on a project look like?

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#233]
If a project isn't private, anyone can view the project.

- Does a user still have to be logged into view a public project?
- Is the interface the same for a public project?
- Can a user run scenarios and make modification, just not save anything?

**Comment by mmcfarland** [comment]
> Does a user still have to be logged into view a public project?

No, I think anyone with a link to a public project can view

> Is the interface the same for a public project?

Yes, except no modification/input tools.  i.e., no way to re-run the models, we use the saved results of last run.

> Can a user run scenarios and make modification, just not save anything?

Good question.  I was anticipating "no", but that would be an interesting feature.  Maybe a low cost/time compromise is being able to "copy" the project into your own account, and then do a normal modification workflow.

**Comment by mmcfarland** [comment]
These questions are largely resolved and implemented.  I think further changes will be address from user feedback.
