### ISSUE TITLE
ITSI Screenshots: Fix New Modeling View

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2331]
Because of PhantomJS Flexbox issues similar to those discussed in #2326, the new Modeling view does not screenshot correctly:

![83ae940a64430723177b6ae062436e62c62e8577](https://user-images.githubusercontent.com/1430060/31242225-52fc0062-a9d4-11e7-92c4-0a400708c121.png)

Apply similar fixes to ensure it does.

**Comment by kellyi** [comment]
Just to have it ready at hand here's the ITSI portal link:

https://authoring.concord.org/activities/5644/single_page/dec56c68-6170-4e59-b94a-82fb040e8d88
