### ISSUE TITLE
Update RWD Version

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2339]
Update the app to use the new version of RWD created [here](https://github.com/WikiWatershed/rapid-watershed-delineation/issues/77)

**Comment by kellyi** [comment]
Shares a point with https://github.com/WikiWatershed/rapid-watershed-delineation/issues/77

**Comment by kellyi** [comment]
Release 1.2.3 is here: https://github.com/WikiWatershed/rapid-watershed-delineation/releases/tag/1.2.3

Going to make a PR on `develop` to match.
