### ISSUE TITLE
Run reload_dev_data during 'vagrant provision app'

### ISSUE THREAD

**Issue by lliss** [WikiWatershed/model-my-watershed#234]
To reduce the number of steps needed to get to a working state, running ```vagrant provision app``` should run ```reload_dev_data```.

**Comment by mmcfarland** [comment]
I'm not sure this is a good idea.  At the very least, it should be associated with provisioning `services`, not app - since it's loaded to the database.  I think we want to maintain control about how data is loaded in production, which is why it's dev_data and a manual step right now.

**Comment by rajadain** [comment]
I was just thinking that. I remember asking you a while ago why don't we run migrations automatically. My approach here is to run `manage.py migrate` and `manage.py reload_dev_data` automatically only in `development` and `test` environments, which I think is slightly more acceptable, but even there I can imagine developers wanting some control over weather or not they are run immediately.

Should I proceed with that or abandon this for now?

**Comment by mmcfarland** [comment]
Given that it didn't make it into the sprint and we still have cards in Queue, I don't think we should have it in as a `+` card yet.

**Comment by kdeloach** [comment]
Once the project stabilizes we should scarcely have to run `reload_dev_data`.

**Comment by lliss** [comment]
Seems like no one else is in to this. I felt that if starting up an application from nothing and running ```vagrant up``` it would be nice to have a fully working app at the end and this seems to add an extra step.

**Comment by mmcfarland** [comment]
Closing, the command in question has been removed.
