### ISSUE TITLE
Geoprocessing API: Validate Shape Does Not Self Intersect

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2342]
We already check for self-intersections on the frontend via `leaflet-draw` and `turf-kink`, but we now have to guard against bad input from API users. Add a check on AOIs submitted to the analyze endpoints.

**Comment by kellyi** [comment]
Django gis GEOSGeometry has a `.valid` method which we can use to validate these, but it will probably catch more than just the self-intersecting. Here's the list of GEOS error messages:

https://github.com/OSGeo/geos/blob/master/src/operation/valid/TopologyValidationError.cpp

```cpp
const char* TopologyValidationError::errMsg[]={
	"Topology Validation Error",
	"Repeated Point",
	"Hole lies outside shell",
	"Holes are nested",
	"Interior is disconnected",
	"Self-intersection",
	"Ring Self-intersection",
	"Nested shells",
	"Duplicate Rings",
	"Too few points in geometry component",
	"Invalid Coordinate",
	"Ring is not closed"
};
```
