### ISSUE TITLE
Ingest elevation raster

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2347]
In order to support terrain analysis and visualization (https://github.com/WikiWatershed/model-my-watershed/issues/2346), ingest a 30m national-extent elevation raster into GeoTrellis. The cells should line up with our % slope raster and other 30m rasters.

Use the 30m NED elevation raster - we have the NED on the fileshare under Stroud MMW/downloads/NED.

**Comment by arottersman** [comment]
@rajadain can hook you up with https://github.com/rajadain/trelliscope to visually verify the ingest.

**Comment by jwalgran** [comment]
Blocked because Anthony may want us to use a different elevation raster.

Geotrellis has national NED data, but it is not the datahub.

**Comment by jwalgran** [comment]
Under the geotrellis AWS account in the `raw` subdirectory there are some NED directories

```
$ aws s3 ls s3://azavea-datahub/raw/ned
                           PRE ned-13arcsec-geotiff/
                           PRE ned-13arcsec/
```

**Comment by ajrobbins** [comment]
Rescoping this card for now to: figure out the provenance and resolution of any national elevation rasters in the GT AWS account, so we can know whether we have to ingest a new one or not.

**Comment by kellyi** [comment]
Both `ned-13arcsec-geotiff` and `ned-13arcsec` dirs contain geotiffs.

The `ned-13arcsec/` dir listed above has a README.txt file the geotiff images indicating the images there were downloaded from a USGS site "sometime around the summer of 2014."  It also has an `extent.geojson` file which has linestring boxes + points which seem to represent the extent and central point of each tile.

Loaded it up in geojson.io and it looks like it covers the Continental US plus some parts of Alaska, Hawaii, and Puerto Rico:

<img width="832" alt="screen shot 2017-11-28 at 11 31 49 am" src="https://user-images.githubusercontent.com/4165523/33331991-15ac4c76-d431-11e7-8fee-c59e0148a4ae.png">

Here's what they look like at a higher zoom level:

<img width="781" alt="screen shot 2017-11-28 at 11 42 11 am" src="https://user-images.githubusercontent.com/4165523/33332153-7ac665e2-d431-11e7-809e-133825d02600.png">

And here's the json for one point & one tile:

```json
{
            "geometry": {
                "coordinates": [
                    [
                        161.99944444440004,
                        6.000555555559518
                    ],
                    [
                        161.99944444440004,
                        4.999444444444001
                    ],
                    [
                        163.00055555551555,
                        4.999444444444001
                    ],
                    [
                        163.00055555551555,
                        6.000555555559518
                    ],
                    [
                        161.99944444440004,
                        6.000555555559518
                    ]
                ],
                "type": "LineString"
            },
            "properties": {
                "driver": "HFA/Erdas Imagine Images (.img)",
                "filename": "/storage/NED_1_3/imgn06e162_13.img",
                "projection": "GEOGCS[\"GCS_North_American_1983\",DATUM[\"North_American_Datum_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.017453292519943295],VERTCS[\"Unknown VCS\",VDATUM[\"Unknown\"],PARAMETER[\"Vertical_Shift\",0.0],PARAMETER[\"Direction\",1.0],UNIT[\"Meter\",1.0]]]",
                "size": "10812x10812"
            },
            "type": "Feature"
        },
        {
            "geometry": {
                "coordinates": [
                    162.4999999999578,
                    5.5000000000017595
                ],
                "type": "Point"
            },
            "properties": {
                "driver": "HFA/Erdas Imagine Images (.img)",
                "filename": "/storage/NED_1_3/imgn06e162_13.img",
                "projection": "GEOGCS[\"GCS_North_American_1983\",DATUM[\"North_American_Datum_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.017453292519943295],VERTCS[\"Unknown VCS\",VDATUM[\"Unknown\"],PARAMETER[\"Vertical_Shift\",0.0],PARAMETER[\"Direction\",1.0],UNIT[\"Meter\",1.0]]]",
                "size": "10812x10812"
            },
            "type": "Feature"
        },
```

**Comment by kellyi** [comment]
`ned-13arcsec-geotiff/` doesn't contain a README or extent.json file, btw.

`ned-13arcsec/`s files are dated 2016-03-17
`ned-13arcsec-geotiff/`s files are dated 2016-03-26

**Comment by ajrobbins** [comment]
From the names, looks like those are 10m resolution

**Comment by kellyi** [comment]
Asked @lossyrob whether GT has 30m NED data. If we anticipate this dataset being used in concert with existing datasets for geoprocessing operations, I believe we may want to ingest it ourselves regardless to force the extents to match these:

https://github.com/WikiWatershed/model-my-watershed/pull/2252

**Comment by kellyi** [comment]
Asked GT in Slack and this is the existing NED data is `us-ned-tms-epsg3857`, a 10m NED in 3857 on the Azavea datahub. It covers the continental US, and has a few tile-shaped holes:

![pasted_image_at_2017_05_24_07_00_am](https://user-images.githubusercontent.com/4165523/33338806-29efaeee-d445-11e7-83e4-2bfc44cf38fd.png)

**Comment by jwalgran** [comment]
Does the `tms` in the name mean that they are PNG tiles instead of data?

**Comment by kellyi** [comment]
> figure out the provenance and resolution of any national elevation rasters in the GT AWS account, so we can know whether we have to ingest a new one or not

According to discussion in the GT Slack channel:

- that's GT's NED data
- it's 10m resolution, which is apparently standard resolution for the NED
- source was a possibly-requester-pays S3 bucket and the full dataset was about 230gb

It seems like we're probably going to have to perform some kind of ingest for the 30m/5070 NED.

**Comment by kellyi** [comment]
Putting this back in the queue. The re-scoped work for this card has been done here: https://github.com/WikiWatershed/model-my-watershed/issues/2347#issuecomment-347639764

I believe the outcome's that we still need to ingest an elevation raster. The original comment on this issue mentions one possible data source; https://github.com/WikiWatershed/model-my-watershed/issues/2347#issuecomment-347338670 mentions the possibility of using another.

**Comment by ajrobbins** [comment]
Confirmed that we should use the elevation raster from the NED

**Comment by arottersman** [comment]
This card is to create the ingest only, or should the tile painting get rolled with it?

**Comment by arottersman** [comment]
## Final output

Tiles are in the datahub bucket under the name `ned-nhdplus-30m-epsg5070`. Ingest PR [here](https://github.com/azavea/civic-apps-etl/pull/2)

I verified them using [trelliscope](https://github.com/rajadain/trelliscope). Here you can see that they line up with the NLCD layer. I've also written out sever tiles to geotiff, and confirmed they contain meaningful data.
![screen shot 2017-12-21 at 12 26 54 pm](https://user-images.githubusercontent.com/7633670/34274209-9c27a3ae-e665-11e7-934f-bd9226cce502.png)

## Sourcing the data
Downloaded the NED_Snapshots for each region from [NHDPlus V2](http://www.horizon-systems.com/NHDPlus/NHDPlusV2_data.php)

<details>

<summary>
I used this rather patched together script to gather it
</summary>

```python
import requests


ROOT_URL='http://www.horizon-systems.com/NHDPlusData/NHDPlusV21/Data'

regions={
"01"   : { 'drainage_id': 'NE', 'rpus': ['01a'], },
"02"   : { 'drainage_id': 'MA', 'rpus': ['02a','02b'], },
"03N"  : { 'drainage_id': 'SA', 'rpus': ['03a','03b'], },
"03S"  : { 'drainage_id': 'SA', 'rpus': ['03c','03d'], },
"03W"  : { 'drainage_id': 'SA', 'rpus': ['03e','03f'], },
"04"   : { 'drainage_id': 'GL', 'rpus': ['04a','04b','04c','04d'], 'ned_version': '03'},
"05"   : { 'drainage_id': 'MS', 'rpus': ['05a','05b','05c','05d'], },
"06"   : { 'drainage_id': 'MS', 'rpus': ['06a'], },
"07"   : { 'drainage_id': 'MS', 'rpus': ['07a','07b','07c'], },
"08"   : { 'drainage_id': 'MS', 'rpus': ['08a','08b','03g'], },
"09"   : { 'drainage_id': 'SR', 'rpus': ['09a'], },
"10U"  : { 'drainage_id': 'MS', 'rpus': ['10e','10f','10g','10h', '10i'], 'ned_version': '03' },
"10L"  : { 'drainage_id': 'MS', 'rpus': ['10a','10b','10c','10d'], },
"11"   : { 'drainage_id': 'MS', 'rpus': ['11a','11b','11c','11d'], 'ned_version': '02' },
"12"   : { 'drainage_id': 'TX', 'rpus': ['12a','12b','12c','12d'], },
"13"   : { 'drainage_id': 'RG', 'rpus': ['13a','13b','13c','13d'], },
"14"   : { 'drainage_id': 'CO', 'rpus': ['14a','14b'], },
"15"   : { 'drainage_id': 'CO', 'rpus': ['15a','15b'], },
"16"   : { 'drainage_id': 'GB', 'rpus': ['16a','16b'], },
"17"   : { 'drainage_id': 'PN', 'rpus': ['17a','17b', '17c', '17d'], },
"18"   : { 'drainage_id': 'CA', 'rpus': ['18a','18b', '18c'] },
}

regions_without_subdir = [
    '01',
    '02',
    '04',
    '09',
    '12',
    '13',
    '16',
    '17',
    '18',
]

for vpu, val in regions.items():
    drainage_id = val['drainage_id']
    for rpu in val['rpus']:
        subdir = '' if vpu in regions_without_subdir \
                        else 'NHDPlus{vpu}'.format(vpu=vpu)
        version = '01' if 'ned_version' not in val \
                        else val['ned_version']
        url = '{root}/NHDPlus{drainage_id}/{subdir}/NHDPlusV21_{drainage_id}_{vpu}_{rpu}_NEDSnapshot_{v}.7z'.format(root=ROOT_URL,
             vpu=vpu,
             drainage_id=drainage_id,
             rpu=rpu,
             subdir=subdir,
             v=version).strip()
        print("getting ", url)
        filename = 'NHDPlusV21_{drainage_id}_{vpu}_{rpu}_NEDSnapshot_{vpu}.7z'.format(vpu=vpu, drainage_id=drainage_id, rpu=rpu)
        r = requests.get(url, stream=True)
        with open(filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=1024): 
                if chunk:
                    f.write(chunk)
```

</details>

The files download as [`.7z` archives](http://www.7-zip.org/7z.html), and need to be unzipped.

```
7za e *.7z
```

All regions except `03g` and `03d` were `Int32`s. `03g` and `03d` were `Int16`s, and converted to `Int32` like this:

```bash
# convert type
gdalwarp -ot Int32 \
         -of GTiff \
         -dstnodata -2147483647 \
         -srcnodata -32768 \
         NHDPlusSA/NHDPlus03S/NEDSnapshot/Ned03d/elev_cm/ 
         NHDPlusSA/NHDPlus03S/NEDSnapshot/Ned03d/elev_cm_int32.tif

# write old min(int16) data value to new min(int32) no data value
gdal_calc.py -A NHDPlusSA/NHDPlus03S/NEDSnapshot/Ned03d/elev_cm_int32.tif \
             --outfile=ned_03sd.tif
             --calc="A*(A>-32767)" 
             --NoDataValue=-2147483647
```

Next, all files were converted to lzw-compressed geotiffs:
```bash
find -name "elev_cm" -type d -execdir gdalwarp -of GTiff {} elev_cm_int32.tif \;
 
find . -name "elev_cm_int32.tif" -execdir gdal_translate -of GTiff -co "COMPRESS=LZW" {} elev_cm_int32_lzw.tif \;
```

Finally, each region's geotiff was uploaded to the datahub so they could be read for ingest:
```
find . -name "elev_cm_int32_lzw.tif" \
       -execdir bash -c \
  'grealpath ./elev_cm_int32_lzw.tif | sed -n -e "s/^.*\(NEDSnapshot\)/\1/p" | (echo -n s3://datahub-rawdata-us-east-1/ && cat) | xargs aws s3 cp --profile arottersman ./elev_cm_int32_lzw.tif' \;
```
