### ISSUE TITLE
Create visual tiles for % slope

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2348]
Using either GeoTrellis or the gdal script Matt's used previously, create visual tiles for % slope and store on S3 as we do for other overlays. Add the applicable layers to the layer selector and enable visualization in the app, under the coverage grid category.

**Comment by arottersman** [comment]
Just to get the color ramp thread going here — is there already a color ramp out for approval/coming from client or do we need to make one? If we need to make one, are stats needed for the layer?

If we'd like to start this work without it, we can write a class in `civic-apps-etl` using a built-in GT color ramp, confirm a local test works, and then be ready to go for the national scale when the final color ramp comes in.

**Comment by arottersman** [comment]
Layer in catalog is called `us-percent-slope-30m-epsg5070-512`

**Comment by ajrobbins** [comment]
We need to make one; there isn't one out for approval yet. If you could provide the summary stats for the layer, that would be great.

**Comment by arottersman** [comment]
Calculated stats on `us-percent-slope-30m-epsg5070-512` via the GT `Histogram[Double]` statistics. Class is [here](https://github.com/azavea/civic-apps-etl/blob/arr/paint-pct-slope/mmw-ingest/src/main/scala/GetStats.scala)

```
---- STATISTICS ----
Mean: 8.854093957743567
StdDev: 14.561038278135415
Min: 0.0
Max: 951.4365844726562
```

**Comment by arottersman** [comment]
The ocean, which I would expect to contain a NoData value, has a value of 0 instead. This makes sense in that it's "flat", but means our tiles will be as ugly as the NLCD with a big green box around the country.  

* Anybody remember if the original set had no data outside the country's boundary? Did the ingest go awry? 
* If not, should we crop the tiles before painting like Rob does [here](https://github.com/lossyrob/geotrellis-ned-example/blob/master/src/main/scala/elevation/Main.scala)? The implementation is easy enough, but we'll have to decide how detailed of a boundary shape we'll want to use.

**Comment by arottersman** [comment]
On further inspection, it seems the data does have NoData values farther out from the land:
<img width="326" alt="screen shot 2018-01-18 at 2 21 05 pm" src="https://user-images.githubusercontent.com/7633670/35116887-dc684fb2-fc5a-11e7-94ea-ec65b0b323d8.png">

**Comment by ajrobbins** [comment]
Color ramp has been approved! Here are the RGB values and the raster values they should be associated with, on a stretched color ramp:

* 171,63,0 - 951.437 (max)
* 250,0,0 - 50
* 255,85,0 - 30
* 255,153,0 - 20
* 255,184,77 - 15
* 255,213,0 - 10
* 251,255,0 - 6
* 252,255,179 - 4
* 252, 255, 235 - 2
* 227,230,204 - 1
* 208,209,207 - 0

Image examples:
![boulder_opaque.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5685332b20438e130091808c/125516c66e82c728ace21e0d46ea9b8f2f8686bbb0e6af42b548f5d665043761260ea62864c7b96aea177900575a49a9415e5b45aaab8d2fa6b638248c0d58b8c3714d36976345f3e5db55ea43a82a994e8dbcbd8f4dc6e13c21ef8b884e39181755.png)
![delaware_opaque.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5685332b20438e130091808c/125516c66e82c728ace21e0d46ec9196229582bb8ad6b053a54ce5916b0a65633b0ba92e7391a172fd172e030e574bab44585940fdafdb2fa2b63c74de5a5abe847f4366846c4ff8e7df46f554f832815d84beb68b49c1ee3424e3838e4e371e010ac4.png)

**Comment by ajrobbins** [comment]
Color ramp:
![ramp_bottom.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5685332b20438e130091808c/125516c66e82c728ace21e0d46fa959733bd81a69bfdb04ee611b2843b492d762a10e17132d0b62abe1a2e565a5f48a8400e0d40f8f9892ff2b06d23df4e17ff933c0120996048e6edc00db513bb27814e80b7ba834dc4e03923ef8d8c5d73.png)

![ramp_top.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5685332b20438e130091808c/125516c66e82c728ace21e0d46fa959733bd97a69fabf301b44fff9e2c4533317346f67e7284bb7de8172b575b5e18fe455c5f44f8ad8f7af5e32e6c981e5ab38532022d8c6853beb2901eb80bbb258a498cb7b88249c7ea3525f5c6.png)

**Comment by arottersman** [comment]
There are some small discrepancies at higher % slope values, but I think this is close enough to move forward with the national. I'm unsure what ArcMap does to spread the uppermost quartile — I had to add in an additional step pulled from the boulder screencap, `51 -> RBG(162, 72, 29)`, to get the results below.
 
![screen shot 2018-01-29 at 12 59 52 pm](https://user-images.githubusercontent.com/7633670/35526129-77f14672-04f4-11e8-941c-8c8203536923.png)

![screen shot 2018-01-29 at 12 58 31 pm](https://user-images.githubusercontent.com/7633670/35526128-77e5f92a-04f4-11e8-947c-57f67ddbbab4.png)

**Comment by ajrobbins** [comment]
Never seen something so beautiful in my life!

**Comment by arottersman** [comment]
The tiles are in `s3://tiles.us-east-1.azavea.com/us-percent-slope-30m`. @ajrobbins, what should the layer be called in the layer picker?

**Comment by ajrobbins** [comment]
"Slope (Percent)"

**Comment by ajrobbins** [comment]
Note that we should be incorporating the legend in the layer picker in the style of mean monthly precip:
![screen shot 2018-01-29 at 2 39 27 pm](https://user-images.githubusercontent.com/12868342/35530502-3ba1915a-0502-11e8-826eca089d61b39a.png)

If that's out of scope for this card, we can make a new one.
