### ISSUE TITLE
Climate analyze tab cut off in IE11 + FF

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2360]
The analyze climate view is too tall in IE11 and FF; you can't scroll to the bottom

![screen shot 2017-10-10 at 4 46 15 pm](https://user-images.githubusercontent.com/7633670/31409759-f16f1f7c-adda-11e7-8e73-81b77ab74244.png)

**Comment by aufdenkampe** [comment]
Also in cut off in Chrome. Works in Safari.
