### ISSUE TITLE
BiG-CZ: Browser back button doesn't clear detail geom

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2366]
If you use the browser back button while a detail view is open in the data catalog, the detail geom will remain on the map:

<img width="959" alt="screen shot 2017-10-12 at 2 31 05 pm" src="https://user-images.githubusercontent.com/7633670/31513520-97d3aed2-af5c-11e7-805d-2bc78deafa6a.png">

**Comment by kellyi** [comment]
Trying to replicate this and it seems like BigCZ has the same behavior as MMW, viz:

Clicking back from the "Analyze" tab will leave the AOI on the map, but with the aoi rendered differently:

<img width="773" alt="screen shot 2017-10-16 at 3 41 25 pm" src="https://user-images.githubusercontent.com/4165523/31631714-8983ebe2-b288-11e7-9514-c06cbdfce57d.png">

->

![screen shot 2017-10-16 at 3 41 31 pm](https://user-images.githubusercontent.com/4165523/31631717-8d68ac2a-b288-11e7-90aa-49ce66986501.png)

The AOI will then clears on trying to select a new AOI.

Assuming I've replicated this correctly, is the desired behavior here that no shape is visible on the map immediately after clicking the back button (and before selecting a new AOI)?

**Comment by mmcfarland** [comment]
The issue references "the detail geom", and there is a small circle in the screenshot.  I think it may be referring to a selected result's geometry, not the AoI shape.  @arottersman ?

**Comment by kellyi** [comment]
> I think it may be referring to a selected result's geometry, not the AoI shape

Ah, that makes sense. I was able to replicate this locally by searching for results in the data catalog for an aoi, then clicking back. Looks like it remains on the map both for the Analyze tab and on returning to the "Select Area" view:

![screen shot 2017-10-16 at 4 01 41 pm](https://user-images.githubusercontent.com/4165523/31632556-5ff87dd0-b28b-11e7-9b05-960d87c087f7.png)

->

![screen shot 2017-10-16 at 4 02 55 pm](https://user-images.githubusercontent.com/4165523/31632593-7fac719a-b28b-11e7-9d56-ae6bef898523.png)

**Comment by kellyi** [comment]
Out of curiosity I checked whether this was happening on the branch from #2371 and it seems like it may not be? Going to investigate a bit more but may have been the same root cause.
