### ISSUE TITLE
BiG-CZ: Browser back button breaks filter sidebar

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2367]
- Go to the data catalog, search for something and open the filter panel
- Hit the browser back button
- Go to the data catalog again
- Try to open the filter again, and it will be blank
<img width="960" alt="screen shot 2017-10-12 at 2 37 12 pm" src="https://user-images.githubusercontent.com/7633670/31513558-b4d2c96e-af5c-11e7-8d02-8b2264348826.png">

**Comment by kellyi** [comment]
This element lives in #secondary-sidebar > #secondary-sidebar-content divs as the `.data-catalog-filter-window` div element.

Clicking the back button when this is open doesn't unmount the `.data-catalog-filter-window` component. On clicking "Search data sources" again, the element's still on the DOM.

At that point, clicking "Filters" again removes it from the DOM.
