### ISSUE TITLE
Expand staging hours through 11/31/17

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2378]
Currently, we limit staging hours to save money on AWS. Members of the project team, including west coast folks, will be testing the site more extensively as we wrap up the BiG CZ contract. They've requested that we extend staging's active hours to be up until 1am PST/8AM UTC on all days, including weekends (currently staging is down on weekends, afaik). The existing start time is fine to keep.

**Comment by rajadain** [comment]
+1 inspected in Staging environment, configuration looks good:

![image](https://user-images.githubusercontent.com/1430060/31726927-40e8cdd4-b3f6-11e7-88b4-a1dcd4238a73.png)

**Comment by hectcastro** [comment]
Thanks, @rajadain. These changes were captured in the configuration file used for deployment on staging. Changes should persist across stack deployments.
