### ISSUE TITLE
Implement client-side free text search for WDC (4 pts)

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2389]
The WDC API, unlike the other two APIs we integrate with for the BiG CZ data catalog search, does not support free text search. One of the core ideas of the BiG CZ project is that the user can seamlessly search across multiple catalog and expect the same search mechanisms to be supplied, and the design (large text search box) reinforces that.

We can implement our own free-text search for WDC by:
- making the API call for all results in the AoI
- searching over all of the returned results (every field shown on the result details page + the description we put in the info button popup + the citation) for the inputted search terms

**Comment by emiliom** [comment]
attributes being searched: title, id, site name, description, location; service citation & abstract & title; variables (concept keywords)

**Comment by emiliom** [comment]
Request from @aufdenkampe and I: **exclude** `service citation` and `service abstract` from the free text search.
