### ISSUE TITLE
Implement revised Hydroshare result card

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2390]
Currently looks like:
![screen shot 2017-10-19 at 10 56 16 am](https://user-images.githubusercontent.com/12868342/31777492-2d0ddd6a-b4bc-11e7-9f2b-0da5c5380af9.png)

Waiting for mockup from Anthony + Emilio.

**Comment by ajrobbins** [comment]
Mockup here: https://docs.google.com/document/d/1nsSV6Cl_BwETraKrMnB9bP5fYYRyUtt4zXrliq3Int8/edit

**Comment by ajrobbins** [comment]
Notes are in the doc. Also here:

- Author First, Date Second
- Date should show Coverage Start and End instead of Creation Date
- If not Coverage Dates are available, sort to end of list and show N/A or similar
- If a record does not have spatial information, don’t show it
- If a resource is “private”, it should be filtered out by default, like Gridded Services in WDC (low priority)
-

**Comment by rajadain** [comment]
The date filters wire up to the `from_date` and `to_date` request parameters in the HydroShare API that filters over `created_at` date, which will no longer be shown in the UI:

![image](https://user-images.githubusercontent.com/1430060/31836940-05fb82ce-b5a5-11e7-82bc-9e8d88c924e8.png)

This may be a reason to keep that date in the results. Any feedback on this, @aufdenkampe / @emiliom ?

**Comment by emiliom** [comment]
HydroShare is not my thing, but I *think* I follow what you're asking, so I'll chime in.

The start and end dates that @aufdenkampe specified in the mockup ("coverage dates" something or other) really are the ones that are meaningful in the context of a search, but as we've said, they're also not commonly populated in HydroShare records. It's misleading, and therefore not helpful to users, to enable date filtering on dates other than these dates.

So, the Filters would need to be rewired for HydroShare. And if a user chooses to apply a date filter, all records that have no "coverage dates" will have to drop out, b/c its relevant dates are unknown.

@aufdenkampe, what do you think?

**Comment by aufdenkampe** [comment]
I agree with Emilio.

Sent from my iPhone

On Oct 20, 2017, at 2:35 PM, Emilio Mayorga <notifications@github.com<mailto:notifications@github.com>> wrote:


HydroShare is not my thing, but I think I follow what you're asking, so I'll chime in.

The start and end dates that @aufdenkampe<https://github.com/aufdenkampe> specified in the mockup ("coverage dates" something or other) really are the ones that are meaningful in the context of a search, but as we've said, they're also not commonly populated in HydroShare records. It's misleading, and therefore not helpful to users, to enable date filtering on dates other than these dates.

So, the Filters would need to be rewired for HydroShare. And if a user chooses to apply a date filter, all records that have no "coverage dates" will have to drop out, b/c its relevant dates are unknown.

@aufdenkampe<https://github.com/aufdenkampe>, what do you think?

-

**Comment by ajrobbins** [comment]
Created https://github.com/WikiWatershed/model-my-watershed/issues/2431 to handle rewiring the filter to use coverage period.
