### ISSUE TITLE
Implement revised Hydroshare detail view

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2391]
Currently looks like:

![screen shot 2017-10-19 at 10 57 14 am](https://user-images.githubusercontent.com/12868342/31777547-4898fbc8-b4bc-11e7-912e-21d33732ca4b.png)

Mockup here: https://docs.google.com/document/d/1rrrgZYYH_Jc5LN-vYP3sj3YoLcyXOdgfMcEb6v8Mtdg/edit but not finalized

**Comment by ajrobbins** [comment]
- Mockup in Gdoc, also see comments on discarding and reordering results
- Fetch data from /scimeta endpoint
- Abstract and Content sections should be tabs, like Chart / Table for WDC
- Content Tab should have “Last Updated” field from the list endpoint data
- Source Data link should go to detail page in HydroShare
- Web Services link should go to Swagger UI (may change in future)

**Comment by emiliom** [comment]
> Web Services link should go to Swagger UI (may change in future)

@aufdenkampe, what do you think about using this link instead?: https://github.com/hydroshare/hydroshare/wiki/HydroShare-REST-API

**Comment by aufdenkampe** [comment]
@rajadain, I've completed documentation of all the API requests and response fields for the mockup in the [Sample_HydroShare_Resource_Detail_BiGCZPortal_SearchResult](https://docs.google.com/document/d/1rrrgZYYH_Jc5LN-vYP3sj3YoLcyXOdgfMcEb6v8Mtdg/edit) Google Doc.

@emiliom, thanks for that suggestion. Unfortunately, that page hasn't been edited since April. For that reason, I still suggest we point the "Web Services link to https://www.hydroshare.org/hsapi/#/hsapi

**Comment by emiliom** [comment]
> @emiliom, thanks for that suggestion. Unfortunately, that page hasn't been edited since April. For that reason, I still suggest we point the "Web Services link to https://www.hydroshare.org/hsapi/#/hsapi

Normally a documentation page wouldn't need to be updated frequently. But in my mind it's a toss up between my suggestion (advantage: has background information, links to the API, etc) and yours (advantage: to the point, and guaranteed to be updated b/c it is the API!)

Anyway, I'm fine with that choice.

**Comment by rajadain** [comment]
Hi @aufdenkampe, I had one implementation note: the mockup asks for the abstract section to be scrollable in case of long abstracts, but that puts a scrollable div inside another scrollable div, which can be hard to navigate and doesn't look good on platforms that don't have vanishing scrollbars (like Windows):

![image](https://user-images.githubusercontent.com/1430060/31913373-0992846a-b815-11e7-9ef9-bae98b4ed613.png)

Choosing an appropriate height is further complicated by the table in Contents having a different number of rows for each result. Thus I elected to let the abstract flow freely, allowing the users to scroll to the bottom of the page if they need the citation, like this:

![2017-10-23 16 53 18](https://user-images.githubusercontent.com/1430060/31912761-fbce1ca6-b812-11e7-8d55-eeb33a52b39c.gif)

**Comment by emiliom** [comment]
This is a reasonable decision, and it's consistent with our decision not prioritize #2399

**Comment by aufdenkampe** [comment]
Agreed

Sent from my iPhone

On Oct 23, 2017, at 4:46 PM, Emilio Mayorga <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a reasonable decision, and it's consistent with our decision not prioritize #2399<https://github.com/WikiWatershed/model-my-watershed/issues/2399>

-
