### ISSUE TITLE
Branding and text changes

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2394]
From https://github.com/BiG-CZ/BiG-CZ-Portal/issues/3:

  - Change the front-page branding to refer to BiGCZ specifically (not MMW). Start thinking about appropriate logos, instead of just Stround and WikiWatershed
  - Add BiGCZ prefix to the "Critical Zone Data Explorer" application label at upper left
- In the first page, list item # 3 says "Model". But that's not relevant to BiGCZ portal. It should be replaced with the tab used later in the workflow, "Data"
- Unify labeling of buttons in detail views; currently using "Web Services", "Repository", and "Source" across catalogs
- Move logos on landing page below the Get Started button
- Remove "Open project" link at bottom of landing page sidebar:
![screen shot 2017-10-19 at 11 06 31 am](https://user-images.githubusercontent.com/12868342/31778074-bb3f29bc-b4bd-11e7-99ed-ee12519d38b0.png)

Also, change the "About" link in the top right of the page to direct to: https://bigcz.org/

**Comment by ajrobbins** [comment]
@aufdenkampe @emiliom What BiG CZ logos if any should be added to the existing Stroud and wikiwatershed ones (and moved below Get Started)? Should we remove the Wikiwatershed logo?

**Comment by emiliom** [comment]
We have a BiGCZ logo at https://bigcz.org. Anthony probably has a collection of logo images.

@aufdenkampe, I'm not sure I like having WikiWatershed so prominently (as opposed to a less prominent "About" page that credits the WW/MMW work that supported the development of the platform). Also, if Stroud is going to be up front, I'd like to see APL there too. But it raises the question of whether that's an area for only institutions that contributed very directly to the portal, or for all BiGCZ core partners ....

**Comment by aufdenkampe** [comment]
Thanks for setting this up. I'll take on the task early next week to provide all of this branding, in a separate Google Doc mockup.

**Comment by emiliom** [comment]
Thanks @aufdenkampe. I'll just add that the text changes should include:
- Using a lot less text in the "start page". What's there is more than is needed (it gets in the way, IMHO), and the focus is not quite right for BiG CZ:  "Explore, analyze and model human impacts on your watershed .... Analyze real geo-data, model storms, and compare potential impact of conservation and development scenarios in a watershed."
- The intro text under "Select Area" should also be trimmed substantially.

**Comment by aufdenkampe** [comment]
Yes, I agree.

**Comment by aufdenkampe** [comment]
Note to explicitly add AoI size limits, to allow a delay in #2388 to later in November.

**Comment by ajrobbins** [comment]
@aufdenkampe when do you anticipate the google doc branding mockup will be available? We will need it by Wednesday morning at the latest in order to get it into this sprint.

**Comment by aufdenkampe** [comment]
Arianna. Thanks for the nudge and deadline.  I'll get it done by close of business tomorrow, or preferably sooner.

Sent from my iPhone

On Oct 30, 2017, at 10:00 AM, Arianna Robbins <notifications@github.com<mailto:notifications@github.com>> wrote:


@aufdenkampe<https://github.com/aufdenkampe> when do you anticipate the google doc branding mockup will be available? We will need it by Wednesday morning at the latest in order to get it into this sprint.

-

**Comment by ajrobbins** [comment]
@aufdenkampe Any updates on this content? Thanks!

**Comment by aufdenkampe** [comment]
Sorry! I'll get to it this afternoon. I just submitted a proposal, which took more time than expected (as is usual, I guess!).

**Comment by aufdenkampe** [comment]
@ajrobbins, I have completed the [Branding Text for BiG CZ Portal](https://docs.google.com/document/d/1oaS6YidSgJPsREBQcGgh70Q__aj56lBMQE4i5GbbdBU/edit#heading=h.ogbr6n6wefv3) Google Doc. It should be ready to go!

Note that some of the suggestions address #2079 and can be simultaneously and equally applied to MMW using WPF funds.

@emiliom, feel free to review and comment, but I think its all good.

**Comment by aufdenkampe** [comment]
@kellyi & @ajrobbins, I just made some minor changes to the Splash page text. See Google Doc.
In brief, to "3. Search Data", I would like to list the 3 catalogs and have a tooltip associated with each (the same tooltip used for "Catalog" in the record detail page view).
