### ISSUE TITLE
Remove DRB-specific layers from BiG CZ layer selector

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2395]
@emiliom to provide list of layers to keep.

**Comment by emiliom** [comment]
From the Layers widget/selector (as opposed to AOI selector), **keep**:

### Streams
- Continental US Medium Resolution Stream Network

### Coverage Grid
- National Land Cover
- Hydrologic Soil Groups from gSSURGO
- Mean Monthly Precip
- Mean Monthly Temperature

### Boundary
- USGS * HUC layers
- County Lines

**Comment by ajrobbins** [comment]
Thanks, @emiliom . I just created https://github.com/WikiWatershed/model-my-watershed/issues/2400 for removing non-applicable area selection options for BiG CZ, and added it to our November milestone.

**Comment by emiliom** [comment]
> I just created #2400 for removing non-applicable area selection options for BiG CZ, and added it to our November milestone.

Great, thanks.
