### ISSUE TITLE
Add user to scenario

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#240]
See https://github.com/caseypt/model-my-watershed/commit/b70d977b36a5457d6a8fe019c02fac9ef70f5a4e#commitcomment-11394907

**Comment by caseypt** [comment]
In case the comment is lost:

![selection_030](https://cloud.githubusercontent.com/assets/1042475/7871787/28d8ef86-0560-11e5-8ae0-23c632e81ff2.png)

**Comment by kdeloach** [comment]
Alternatively, `Scenario.objects.filter(id=..., project__user=request.user)`.

**Comment by caseypt** [comment]
Took @kdeloach's approach here when implementing #301

**Comment by caseypt** [comment]
As noted above, this wasn't need. It's just as easy to use the Django ORM methods.
