### ISSUE TITLE
Add Source Data direct link to WDC Unit Values and Groundwater search results

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2403]
For WDC Daily Values search results (NWISDV), we include a "Source Data" direct link in the details page to the sensor page. Add this for Unit Values (NWISUV) results as well; Anthony says the URL path should be parallel.

**Comment by emiliom** [comment]
> Add this for Unit Values (NWISUV) results as well; Anthony says the URL path should be parallel.

Indeed. For example: https://waterdata.usgs.gov/nwis/dv/?site_no=12102075

Likewise, it looks like "Source Data" direct links can also be added for **NWISGW** can search results. For example: https://nwis.waterdata.usgs.gov/usa/nwis/gwlevels/?site_no=471018122143302
@aufdenkampe, do you want to look further into that, or do we tell Azavea to go ahead and implement this too?

**Comment by aufdenkampe** [comment]
Yes, I agree with the priority for also adding "Source Data" links for NWISGW sites. I just tried some tests, and that pattern worked for me.

**Comment by emiliom** [comment]
It looks like the Data Source urls for NWISUV and NWISDV are flipped. NWISUV results have a "dv" in the url (should be uv), and NWISDV have a "uv" (should be dv).

**Comment by ajrobbins** [comment]
Created https://github.com/WikiWatershed/model-my-watershed/issues/2456 for this, thanks @emiliom
