### ISSUE TITLE
Revise WDC sensor detail presentation

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2406]
Some WDC results, specifically daily values, return mean/min/max results for each variable, as well as C and F:
![screen shot 2017-10-19 at 2 50 34 pm](https://user-images.githubusercontent.com/12868342/31788536-021ed6b0-b4dd-11e7-8cf5-d6f8e709bc5c.png)

- Remove all Fahrenheit results by default
- Keep the mean.min/max/other options, but append the qualifier to the variable name in the table

**Comment by aufdenkampe** [comment]
One minor modification, let's not yet remove all Temperature in "deg F" by default, as I just found a record that didn't have the equivalent in "deg C". (Site: 05331000 MISSISSIPPI RIVER AT ST. PAUL, MN).
