### ISSUE TITLE
High latency for /mapshed endpoint for large features using wkaoi

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2426]
Large watersheds, at around the HUC8 size, start to incur high latencies for requests to submit jobs to the `/mapshed` endpoint.  This was previously noted and due to Celery worker polling that has since been removed.  This does not seem to depend on the actual _payload_ size, but the area (or perhaps complexity) of the AoI, as the effect is demonstrated when using `wkaoi` ids, not posting large geojson shapes.  Interestingly, when you do post the shape of the equivalent HUC8, it is considerably faster (though still a few seconds).  

It seems to have something to do with parsing the geometry out of a `wkaoi` id.  Note that RWD shapes have been simplified, so they are likely much less complex than their equivalent HUC8 straight from PostGIS.  Although they look the same visually, they are likely pretty different in terms of vertices.

Here are three mapshed submissions, a HUC12 then a HUC8, both using `wkaoi` - the third is the same HUC08, but generated via RWD such that it posts the shape and does not use `wkaoi`.  The byte size is approximately the same, the duration extremely divergent (reported as TTFB)

![screenshot from 2017-10-24 13 45 56](https://user-images.githubusercontent.com/1014341/31959225-1ba58dac-b8c2-11e7-8669-d5e128c6ee1a.png)

These were recording using staging.

**Comment by rajadain** [comment]
For this exercise I used the Schuylkill HUC-08.

I first downloaded the exact HUC-08 used in the database and constructed a JSON payload for it:
 [huc08-schuylkill.json.txt](https://github.com/WikiWatershed/model-my-watershed/files/1451611/huc08-schuylkill.json.txt). I then created an RWD shape akin to the Schuylkill HUC-08, and did the same for that: [rwd-schuylkill.json.txt](https://github.com/WikiWatershed/model-my-watershed/files/1451615/rwd-schuylkill.json.txt).

The difference between these files is immense:

```

**Comment by rajadain** [comment]
It is worth noting that WKAoI's _do_ take ~3 times longer to parse than inline shapes, but in both cases that time is so diminutive that it has no perceptible effect on the overall wait:

```
Inline

==> Parsed input in 0.0155169963837
==> Parsed input in 0.0165300369263
==> Parsed input in 0.0164260864258

WKAoI

==> Parsed input in 0.0452678203583
==> Parsed input in 0.0468440055847
==> Parsed input in 0.0413160324097
```

**Comment by rajadain** [comment]
Created #2502 for following up with stream fetch optimization.
