### ISSUE TITLE
Rewire date filter for Hydroshare

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2431]
From https://github.com/WikiWatershed/model-my-watershed/issues/2390#issuecomment-338302728

Rewire the filter implementation for the Hydroshare catalog only, so that we're filtering on `<coverages:period:start> - <coverages:period:end>`, not what we are currently using ("creation date"?)

**Comment by rajadain** [comment]
This has been done in #2416 here: https://github.com/WikiWatershed/model-my-watershed/pull/2416/commits/3821b99efba54ebba9abe108847fcd2a7605838f
