### ISSUE TITLE
Delaware Hi-Res RWD Failures

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2454]
The Delaware High-Resolution version of RWD is failing repeatedly on staging. To reproduce, try dropping a point at the Philadelphia zoo. The shape works on production but I get an immediate error on staging:

![screen shot 2017-10-31 at 6 08 45 pm](https://user-images.githubusercontent.com/12868342/32251252-953e83cc-be66-11e7-8cdf-272af79f2c61.png)

**Comment by mmcfarland** [comment]
This is not reproducible on the staging workers that were booted this morning.  It's likely a result of the intermittent drive mount / service start race condition we periodically see.  The quick fix is to restart the `mmw-rwd` service, but it's happening regularly enough that we should spend some time getting a more robust fix in.  I'm going to close this and make an issue.
