### ISSUE TITLE
Change "WDC" tab string on Data Sources page

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#2470]
@ajrobbins, Hopefully this is a quick bug fix.

We would like to change the tab label string for the WDC from "WDC" to "CUAHSI WDC".
This is important because CUAHSI is changing it's branding away form WDC, and more people recognize the organization CUAHSI anyways.

**Comment by rajadain** [comment]
Shares a point with #2468
