### ISSUE TITLE
Change "Water Data Center" Catalog name in Details page

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#2471]
@ajrobbins, Hopefully this is a quick bug fix.

We would like to change the Catalog label string in the WDC record detail page from "Water Data Center" to "CUAHSI Water Data Center (WDC)".

This is important because CUAHSI is changing it's branding away form WDC, and more people recognize the organization CUAHSI anyways.

**Comment by rajadain** [comment]
Shares a point with #2468
