### ISSUE TITLE
Add tooltip for WDC catalog

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#2473]
In the details view for each record, we have info tooltips the CINERGI and HydroShare catalogs, but not one for WDC.

Anthony will develop the tooltip text.

All tooltips should also go next to the catalog names on the splash page, as described in https://github.com/WikiWatershed/model-my-watershed/issues/2394#issuecomment-341525899.

**Comment by rajadain** [comment]
Shares a point with #2468

**Comment by aufdenkampe** [comment]
Tooltip text and link:

The Consortium of Universities for the Advancement of Hydrologic Science, Inc. (CUAHSI) Water Data Center (WDC) provides tools for data access, analysis and collaboration, including a Catalog of hydrological time series data available as Water One Flow (WOF) and WaterML web services. 
See https://www.cuahsi.org/data-models/discovery-and-analysis/.

cc. @rajadain & @ajrobbins
