### ISSUE TITLE
Upload GeoJSON shape only allows FeatureCollection

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2481]
The upload code expects the geojson file to contain a feature collection, [from which it plucks the first](https://github.com/WikiWatershed/model-my-watershed/blob/2dc52e9b704dee29a29401d290b31a29c04e0251/src/mmw/js/src/draw/views.js#L416) value.  This is good behavior _if_ the shape is a feature collection, but single multipolygons should also be valid.

Additionally, when the upload fails on a feature geojson, no error is displayed and the screen retains the opaque overlay.

Fails
[feature.geojson.txt](https://github.com/WikiWatershed/model-my-watershed/files/1446627/feature.geojson.txt)

Succeeds
[featurecollection.geojson.txt](https://github.com/WikiWatershed/model-my-watershed/files/1446628/featurecollection.geojson.txt)

I think the code should check for the `features` property, and grab the first feature.  Otherwise, if it has a `coordinates` property, it should treat it as the single feature.

**Comment by rajadain** [comment]
Shares points with #2426
