### ISSUE TITLE
Upload GeoJSON prevents analyze on seemingly valid shape

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2483]
In trying to produce a shape to test #2472, I produce a valid geojson file (though had to convert to FeatureCollection due to #2481).  This shape renders but then displays a confused error about being too large to analyze (it's not).  This is a geojson representation of the Middle Delaware-Mongaup-Brodhead, HUC-8 Subbasin.

[aoi-fail-catchment.geojson.txt](https://github.com/WikiWatershed/model-my-watershed/files/1446704/aoi-fail-catchment.geojson.txt)

Note the shape is rendered but the error message claims it is 0km2, which is larger than 75km2:
![screenshot from 2017-11-06 10 15 13](https://user-images.githubusercontent.com/1014341/32447987-a86bc2c4-c2db-11e7-8598-5d4a62fdd7bb.png)

**Comment by rajadain** [comment]
Shares points with #2426
