### ISSUE TITLE
MMW AWS Staging: Confirm it's safe to delete excessive Snapshots

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2492]
There are about 800GB of snapshots for app, worker and tilers in the MMW staging account, plus an additional 2.2TB of snapshots that appear to be unused storage for RWD data files (I believe there is a single 512MB snapshot that is actually used).  

I know the cost of snapshot storage is based off incremental changes, but there are likely savings to be had by clearing up some of the ~3TB of data.

(Note: there are no snapshots in the production account, as AMIs are shared from staging)

**Comment by hectcastro** [comment]
I cleaned up the `Environment: Production` tagged AMIs with the following commands:

```bash
$ ./mmw_stack.py prune-ami --aws-profile mmw-stg --mmw-profile production \
                           --keep 3 --machine-type mmw-app
$ ./mmw_stack.py prune-ami --aws-profile mmw-stg --mmw-profile production \
                           --keep 3 --machine-type mmw-tiler
$ ./mmw_stack.py prune-ami --aws-profile mmw-stg --mmw-profile production \
                           --keep 3 --machine-type mmw-worker
```

This removed all but the last 3 AMIs for each instance type (goes back to release 1.20.0). In addition, I removed all of the RWD snapshots that weren't associated with any of the worker AMIs, which left `snap-0211cbbff8a81266f`.

**Comment by mmcfarland** [comment]
Looks great, thanks for clearing those out.
