### ISSUE TITLE
Already Fetched WDC Variables Are Blank

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2495]
1. Search for something with WDC results, like "water" in the philly area
1. Open the details for a result with a date. Mark down its name, and let the variables load
1. Go back to the list and open the date filter. Choose a date that will include the result for which you just opened the details
1. Open the same result's details again and it will have no variables

![screen shot 2017-11-08 at 8 40 45 am](https://user-images.githubusercontent.com/7633670/32552397-cfc68fde-c461-11e7-89aa-1de84eaf45f4.png)

/cc @rajadain

**Comment by rajadain** [comment]
This can be fixed by:

```diff
diff --git a/src/mmw/js/src/data_catalog/models.js b/src/mmw/js/src/data_catalog/models.js
index a065e7d1..3500d680 100644
--- a/src/mmw/js/src/data_catalog/models.js
+++ b/src/mmw/js/src/data_catalog/models.js
@@ -421,6 +421,7 @@ var Result = Backbone.Model.extend({
             if (variables instanceof CuahsiVariables) {
                 variables.reset(response.variables);
                 delete response.variables;
+                delete this.fetchPromise;
             }
         }
```
