### ISSUE TITLE
Prepare HUC-12 boundaries for sub-basin modeling

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2519]
* De-deduplicate `boundary_huc12` on its `huc12` column. If there are duplicates with different geometries, merge them
* Create an index on the `huc12` column so we can efficiently look up HUC-12s that are contained within HUC-10s and HUC-8s based on their huc-ids.

**Comment by arottersman** [comment]
#### Checking for duplicates
```sql
mmw=# select huc12, count(*) from boundary_huc12 group by huc12 having count(*) > 1;
    huc12     | count
--------------+-------
 040201010102 |     2
 040201030108 |     2
 040201050608 |     4
 150801031203 |     2
(4 rows)
```

<details>
<summary>
IDs of the duplicates

</summary

```sql
mmw=# select id from boundary_huc12 where huc12='040201010102';
  id
-------
 81556
 81575
(2 rows)

mmw=# select id from boundary_huc12 where huc12='040201030108';
  id
-------
 81651
 81650
(2 rows)

mmw=# select id from boundary_huc12 where huc12='040201050608';
  id
-------
 81626
 81643
 81647
 81623
(4 rows)

mmw=# select id from boundary_huc12 where huc12='150801031203';
  id
-------
 80468
 80119
(2 rows)
```

</details>

#### How duplicate are they?
Scott's email said he found some to be true duplicates, but I found all had different geometries. From the `geom` column:
<img width="572" alt="screen shot 2017-11-20 at 2 07 54 pm" src="https://user-images.githubusercontent.com/7633670/33036664-1dbf7468-cdfd-11e7-9f2c-61356a7ae55b.png">
<img width="768" alt="screen shot 2017-11-20 at 2 07 06 pm" src="https://user-images.githubusercontent.com/7633670/33036665-1dcf2d22-cdfd-11e7-86ec-37393c347add.png">
<img width="772" alt="screen shot 2017-11-20 at 2 06 29 pm" src="https://user-images.githubusercontent.com/7633670/33036666-1ddca448-cdfd-11e7-8cff-ed730ed845be.png">
<img width="584" alt="screen shot 2017-11-20 at 2 05 17 pm" src="https://user-images.githubusercontent.com/7633670/33036667-1deb30ee-cdfd-11e7-8a42-00a6e5e60ae6.png">

These are all in the great lakes region, except for the last one which is in Mexico.

Planning to merge all as MultiPolygons.

/cc @mmcfarland

**Comment by mmcfarland** [comment]
Seems unusual, but verified using another source viewer:
![screenshot from 2017-11-20 14 31 00](https://user-images.githubusercontent.com/1014341/33037420-7c41a810-cdff-11e7-89a8-2e6ae50a4ccb.png)
