### ISSUE TITLE
Add slope pct data to Streams Analysis

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#2532]
Per https://github.com/WikiWatershed/model-my-watershed/issues/2334#issuecomment-345734852 slope is not currently available as an attribute on the `nhdflowline` table.

We implemented the streams analysis tab with 0 values for stream order slope percentages. The tasks for this card are to:

- [ ] get slope data into nhdflowline (or figure out how to calculate it somehow)
- [ ] adjust the streams analysis job to return slope percentage data per stream order
- [ ] display the slope percentage data per stream order in the client-side app

**Comment by kellyi** [comment]
https://github.com/WikiWatershed/model-my-watershed/pull/2524 added the streams task & tab

**Comment by arottersman** [comment]
It seems like we need another NHD table `ElevSlope` which has the `ComId` of the stream and `Slope`. 

@mmcfarland, have we ever received this table, and if not would stroud be able to send us a dump of it (if it is what we need)?

**Comment by mmcfarland** [comment]
That looks like the right dataset to me, using the `slope` attribute.

![screenshot from 2017-12-01 12 38 18](https://user-images.githubusercontent.com/1014341/33495447-85641804-d694-11e7-83bd-a15832dd3667.png)

via [User Docs](https://s3.amazonaws.com/nhdplus/NHDPlusV21/Documentation/NHDPlusV2_User_Guide.pdf)

We have previously used the `NHDPlusAttributes` data sets to extract `stream_order` via `comid` and I still have all the attributes dbfs for all NHD Regions on an external drive, so we should be able to script the extraction.

@ajrobbins can you confirm with @aufdenkampe that this attribute is appropriate for the new stream analysis slope tab?  Note that the NHD dataset is slope in *meters* and the referenced issue indicates that a mean *percentage* is desired.  We'll need to see if a conversion is necessary (or possible) and if so if we should pre-process that per reach or simply load up meters and do adjustments based on AoI.

**Comment by ajrobbins** [comment]
Just emailed Anthony the Q.

**Comment by aufdenkampe** [comment]
@mmcfarland, yes, the `Slope` attribute in that table is exactly what we want. The unit for those values is actually in meter of elevation drop divided by meters of flowline length (meters/meters), which turns into a unitless floating point number, usually between 0.01 and 1.00, and therefore commonly expressed as a percent. Therefore, just multiply the value by 100 to express as a percent. Note that in locations that are steeper than 45 degrees from flat, that slope can be >100%, so such outliers are OK but extremely rare for stream segments, even in mountains.
