### ISSUE TITLE
Unable to select boundary for analysis if HUC Search is used previously

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2533]
### Overview
When using the search box to select a HUC boundary, it adds the selected vector shape to the map for display.  If the user does not utilize the "Select" button in the search box, and instead adds a boundary layer for selection, the "search" shape prevents clicking on the UTF8 grid layer for the boundary.

### To reproduce
1. Search for `Brandywine` in the search box
2. Select the `Brandywine-Christina` result under the HUC8 header
3. Observe the HUC has been added to the map
4. Under the `Select Boundary` option on `/draw`, add the HUC8 layer
5. The shapes should overlap the Brandywine HUC selected previously
6. Note you cannot click on the Brandywine HUC to analyze, presumably the click events are being absorbed by the reference shape.

**Comment by caseycesari** [comment]
In the test case described above, is it preferable that the initial HUC added to the map from searching is removed when the HUC8 layer is added?

**Comment by ajrobbins** [comment]
I believe the desired behavior should be:
- User selects HUC from search box
- HUC displays on map
- User selects HUC8 option from boundary selector from the sidebar tools
- Displayed HUC is removed from the map, and clickable boundary viz/UTF8 grid appears. Clicking on a boundary selects it for analysis
