### ISSUE TITLE
For release: load deduplicated HUC-12s and clear .grid.json HUC-12s from tile cache

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2535]
#For whatever release the subbasin modeling will be part of, we need to load the deduplicated HUC-12 table:
```sh
cd /opt/model-my-watershed
./scripts/aws/setupdb.sh -f boundary_huc12_deduped.sql.gz
```

And clear their utf8grids from the tile cache

For staging we did:
```bash
> aws s3 rm --recursive s3://tile-cache.staging.app.wikiwatershed.org --profile mmw-stg --exclude "*" --include "huc12/*.grid.json"
```

**Comment by rajadain** [comment]
As of #2563 we need to update the `ms_weather_station` table:

```bash
$ ./scripts/aws/setupdb.sh -f ms_weather_station.sql.gz
```

and clear the GEOP cache:

```bash
$ redis-cli -n 1 --raw KEYS ":1:geop*" | xargs redis-cli -n 1 DEL
```

**Comment by arottersman** [comment]
We will also need to load the new catchment table (#2548) 
```sh
$ cd /opt/model-my-watershed && ./scripts/aws/setupdb.sh -c
```

and reload the streams table (#2532) 

```sh
$ cd /opt/model-my-watershed && ./scripts/aws/setupdb.sh -s
```

**Comment by rajadain** [comment]
![21fewe](https://user-images.githubusercontent.com/1430060/34223542-b39abebe-e58d-11e7-9c04-6552d1ee9022.jpg)

**Comment by rajadain** [comment]
Closing this card as the instructions were completed as part of #2644.
