### ISSUE TITLE
Scenario Share Dialog

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2538]
In #2511 we changed the Project Share modal to be more comprehensive and allow integration with third parties such as HydroShare. This makes sense at the project level, but not so much at the scenario level. Currently Scenarios can also be shared, and are still using the old share dialog:

![image](https://user-images.githubusercontent.com/1430060/33438539-27f5a114-d5b9-11e7-8968-d98a56f13e3d.png)

Is this inconsistent? Should this be changed? How should this be done?

/cc @ajrobbins @jfrankl @mmcfarland

**Comment by jfrankl** [comment]
It is inconsistent, but I think it's okay to leave it for now. By my estimation, it will take a significant amount of design time to resolve this.
