### ISSUE TITLE
Handle large subbasin gwlf-e payloads

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2543]
When submitting the GMS output for all huc12s in a large huc8 the payload sometimes exceeds the `5MB` limit on the nginx server.

- Send the job id instead + any BMPs
- The BMP application that currently happens on the frontend will now have to happen on the server after we've looked up the result via the job id
- The implementation of the point above will be dependent on #2542

**Comment by arottersman** [comment]
@rajadain, we chatted at RRP about using the project's `gis_data` attribute instead of the job table's results. Anonymous users, however, don't create stored projects.

In practice we've never deleted the jobs table, and even though it feels impermanent it's not the cache or anything. Any strong concerns if we use it for the mapshed results?

**Comment by rajadain** [comment]
re: Anonymous users, good point, that is true. I suppose the front-end does have the job id, and we don't make a habit of clearing out the jobs table, and even in this case we're using its data in a relatively temporary fashion (will not persist between user sessions if they log out / back in). Okay I approve this methodology ✅
