### ISSUE TITLE
Investigate HydroShare API, Project Export Format

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2544]
Investigate the HydroShare API and hs_restclient to delineate techniques for exporting data to HydroShare.

Investigate and Evaluate different techniques (JSON, CSV, XML, GeoJSON, etc) of generating files from a project and exporting to HydroShare, and define a file list to be generated when a project is exported to HydroShare.

**Comment by rajadain** [comment]
The export should have:

1. `area-of-interest.geojson`: A GeoJSON of the Area of Interest, with total area, name, and WKAoI id as properties
2. `scenario_{{ name }}.geojson`: A GeoJSON for every scenario with all the modifications, with modification type details as properties on the polygons
3. `analyze_{{ name }}.csv` A CSV for every Analyze tab
4. `scenario_{{ name }}_{{ tab }}_{{ table }}.csv` A CSV for every Model tab for every Scenario

For example, a TR-55 Project with 2 scenarios can have:

```
area-of-interest.geosjon
analyze_land.csv
analyze_soil.csv
analyze_animals.csv
analyze_water-quality.csv
analyze_streams.csv
scenario_current-conditions.geojson
scenario_current-conditions_runoff.csv
scenario_current-conditions_water-quality.csv
scenario_new-scenario.geojson
scenario_new-scenario_runoff.csv
scenario_new-scenario_water-quality.csv
```

**Comment by rajadain** [comment]
Does the list above look good @ajrobbins @mmcfarland ? Should we include a `readme.txt` file that will always be identical, but will introduce this scheme to any one downloading a whole zip?

**Comment by mmcfarland** [comment]
Consider a `gms` file for each scenario of a Multi Year project.

**Comment by rajadain** [comment]
Update:

* We should do `.shp` in addition to `.geojson` for the area of interest
* We should not do any scenario exports for TR-55, as we await advice on how to format them from Stroud
* For MapShed projects, we should include the GMS file for every scenario

**Comment by rajadain** [comment]
(Question for Stroud)

* What resource type should an MMW project be exported as? These are the available options:
  - `CollectionResource`
  - `CompositeResource`
  - `GenericResource`
  - `GeographicFeatureResource`
  - `ModelInstanceResource`
  - `ModelProgramResource`
  - `MODFLOWModelInstanceResource`
  - `NetcdfResource`
  - `RasterResource`
  - `RefTimeSeriesResource`
  - `ScriptResource`
  - `SWATModelInstanceResource`
  - `TimeSeriesResource`
  - `ToolResource`
* Should we get a new type made for us? `ModelMyWatershedResource`?

**Comment by rajadain** [comment]
(I'm going with `GenericResource` until I hear otherwise)

**Comment by ajrobbins** [comment]
I'm checking this with the Hydroshare folks.

**Comment by ajrobbins** [comment]
Verdict from David: 
>You should be using the composite resource.  That allows the most flexibility and can hold shapefiles as well as geographic rasters and time series all together.   You will not need all of these immediately, but may in the future.
