### ISSUE TITLE
Describe HydroShare Project / Resource Interaction

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2545]
- [x] How are repeat exports handled?
  - [x] Do we always re-export, or manually when prompted?
      > The project is set to auto-export on every change by default, but there is a checkbox in the multi-share menu that can be turned off. When it is turned off there is a button to manually export it. See wireframes for details.
  - [x] Do we re-export to the same resource in HydroShare? Or do we create a new resource every time? Is there a mechanism to link different versions of an export with each other in HydroShare?
      > We create a new resource the first time, and then export to the same resource every time. There will always be a one-to-one correspondence between an MMW project and a HydroShare resource.
- [x] Should there be a place in the MMW UI where we can see all linked HydroShare resources?
  > There will be only one resource attached to an MMW project, and a link to it will be present in the multi share modal.
- [x] Should we be allowed to delete HydroShare resources from the MMW UI?
  > If the HydroShare slider is turned off then we switch the HydroShare resource to be private so it is no longer shared. At that point, we can prompt the user if they want to delete the project complete. If they agree, then the project is deleted. If they don't, it is still saved, and whenever sharing for this project is turned back on the existing resource will be made public. If it had been deleted in the past, we will make a new one.
- [x] On/Off
  - [x] If, after publishing a resource, they turn "Publish on HydroShare" off, does that delete the resource in HydroShare?
    > That turns the resource private in HydroShare, with an option to delete it.
  - [x] If they turn it off and back on again, do we make a new resource or still continue pushing to the same old one?
    > If they deleted it then we make a new one, otherwise we keep pushing to the existing one.

**Comment by ajrobbins** [comment]
> Do we always re-export, or manually when prompted?
I assume this is referring to the case when changes are made to the MMW project. Using this modal:
![screen shot 2017-12-04 at 2 46 28 pm](https://user-images.githubusercontent.com/12868342/33572800-051363f6-d902-11e7-85d3-3953e159c1c2.png)
The user will be specifying whether they want project changes to trigger an automatic export to HS, or whether they want to handle it manually. So, it depends on which they choose.

> Do we re-export to the same resource in HydroShare? Or do we create a new resource every time? Is there a mechanism to link different versions of an export with each other in HydroShare?
I think we decided to overwrite the resource each time, and not deal with keeping old versions (at least in a way that they'd be accessible to the user). Tagging @mmcfarland for input.

> Should there be a place in the MMW UI where we can see all linked HydroShare resources?
The above pictured modal has a link where a user can view the resource on Hydroshare - we should link that back to the resource page on HS, and not do anything else in the MMW UI.

>Should we be allowed to delete HydroShare resources from the MMW UI?
The user should be exposed to particular resource files from within the UI, just the link to the resource on HS. So I think the answer is no. However, I'm not sure if deleting a project should delete it's associated resource in HS automatically. @mmcfarland @jfrankl thoughts?

**Comment by rajadain** [comment]
If, after publishing a resource, they turn "Publish on HydroShare" off, does that delete the resource in HydroShare?

If they turn it off and back on again, do we make a new resource or still continue pushing to the same old one?

**Comment by jfrankl** [comment]
I am posting what I think should happen. That being said, I think we should get more feedback from Stroud. I could see some of these going a couple of ways that would all be fine.

> Do we re-export to the same resource in HydroShare? Or do we create a new resource every time? Is there a mechanism to link different versions of an export with each other in HydroShare?

Yes, same resource. I think there is a way to update a resource with new versions. If that's true, that's our best option.

>> Should we be allowed to delete HydroShare resources from the MMW UI?
> The user should not be exposed to particular resource files from within the UI, just the link to the resource on HS. So I think the answer is no. However, I'm not sure if deleting a project should delete it's associated resource in HS automatically. @mmcfarland @jfrankl thoughts?
I think the most important part is to communicate with the user about what is happening. If we are going to delete the resource on Hydroshare when we delete the project on MMW, we should warn them when they begin to delete the project ("Deleting this project will remove the shared content from Hydroshare. Are you sure you want to do this."). If we are not going to delete the resource, we should warn them that they can delete it by going to the Hydroshare website.

With that being said, my inclination is to delete the file from Hydroshare.

> If, after publishing a resource, they turn "Publish on HydroShare" off, does that delete the resource in HydroShare?

We could: a.) give the user a warning their file will be deleted and delete the file if they accept; b.) give the user the option to delete the file; if they don't, their project will remain on hydroshare, no longer connected to MMW; c.) if possible, we could hide the project on Hydroshare so other users can't see it (I don't know if this is an option in their API)

C seems like the best option, if available. If not, I'd want to know what others think regarding the other options.

> If they turn it off and back on again, do we make a new resource or still continue pushing to the same old one?

If it's possible to retain the old resource, that seems ideal. It would preserve the link. That being said, would be good to get Stroud or Hydroshare's thoughts.

**Comment by rajadain** [comment]
I updated the description with answers for each question. Thanks for all your input!
