### ISSUE TITLE
Change link for about button in upper black bar

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#2550]
Re-address from https://wikiwatershed.org/ to https://wikiwatershed.org/about/

![capture](https://user-images.githubusercontent.com/5374350/33629300-854359a8-d9d1-11e7-8d05-5a617dd69f1d.JPG)

**Comment by ajrobbins** [comment]
Thanks for submitting this! It's actually covered in #2534, so I'm closing this issue in favor of that one.
