### ISSUE TITLE
Add Ability to Open MMW Project From HydroShare

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2558]
HydroShare has some "blessed" apps whose names and logos are shown in a dropdown in the top right corner of a resource's detail page. These apps differ by resource.

_TODO_ Insert screenshot when HydroShare is back up

Investigate how MMW can be added to that menu (this may involve collaborating with HydroShare folks) and ensure that clicking it opens the correct project link.

**Comment by rajadain** [comment]
Blocked awaiting documentation for this from HydroShare folks /cc @ajrobbins

**Comment by ajrobbins** [comment]
Just emailed requesting documentation.

**Comment by ajrobbins** [comment]
HydroShare folks devised a proposed integration plan here: https://docs.google.com/document/d/1CjctGQRIdAC0OxY2S6MhpN7ETaEWSmbESMfNdVzujfA/edit?ts=5a87092b#
