### ISSUE TITLE
Investigate slow streams tab

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#2560]
The streams tab is currently slow; we should investigate why & make a fix.

**Comment by arottersman** [comment]
Query on `nhdflowline` was taking almost 9 sec:
![screen shot 2017-12-19 at 2 23 19 pm](https://user-images.githubusercontent.com/7633670/34174803-39551f5c-e4c8-11e7-963f-40805b7ca27d.png)

Add a spatial query on the geom, and now takes 242.3ms

![screen shot 2017-12-19 at 2 23 06 pm](https://user-images.githubusercontent.com/7633670/34174804-396226e8-e4c8-11e7-8b44-865b4dc468c3.png)


```sql
CREATE INDEX  nhdflowline_gix ON nhdflowline USING GIST (geom);
```

Going to upload table with index to s3.
