### ISSUE TITLE
Aggregate Precipitation Data

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2561]
Currently, when querying temperature data for multiple weather stations, the results are averaged:

https://github.com/WikiWatershed/model-my-watershed/blob/586efe5c8454af386a5ba151b7ba876598d2bebd/src/mmw/apps/modeling/mapshed/calcs.py#L392-L411

However, the same is not done for precipitation, leading in non-averaged, non-aggregated data:

https://github.com/WikiWatershed/model-my-watershed/blob/586efe5c8454af386a5ba151b7ba876598d2bebd/src/mmw/apps/modeling/mapshed/calcs.py#L412-L423

It is unclear why this difference exists, as both were added in the same commit https://github.com/WikiWatershed/model-my-watershed/commit/fc1a41c3171072110bd0fbdada13a1ab1cb277c3 in the same PR #1241. But on the surface it looks wrong.

Add the same averaging aggregation to precipitation as exists for temperature.

**Comment by rajadain** [comment]
Note: the previous version of `ms_weather_station.sql.gz` (now available at [`ms_weather_station_backup.sql.gz`](https://s3.amazonaws.com/data.mmw.azavea.com/ms_weather_station_backup.sql.gz)) had two rows for each weather station. Since we match for the [top 2](https://github.com/WikiWatershed/model-my-watershed/blob/bf593766a4300610a14cdbe65c746e919d4d3c98/src/mmw/mmw/settings/gwlfe_settings.py#L463) [closest stations](https://github.com/WikiWatershed/model-my-watershed/blob/586efe5c8454af386a5ba151b7ba876598d2bebd/src/mmw/apps/modeling/mapshed/calcs.py#L56-L61). Thus, for precipitation, the two resulting rows would have had identical values, thus discarding one had no real effect. However, as of #2549, we now fetch two actually different weather stations, and do need to average the values, else lose data.

**Comment by rajadain** [comment]
Blocked until @ajrobbins confirms with subject matter experts.

**Comment by ajrobbins** [comment]
Addressed in #2737
