### ISSUE TITLE
Intermittent Mapshed timeouts on staging + prod

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2567]
While working in the app today, Matt and I noticed that Mapshed runs on multiple different sizes of AoIs (all three HUC types) were failing due to timeouts about 80% of the time. We observed this on both staging and production. Analyze and Site Storm model runs were working fine.

**Comment by rajadain** [comment]
Wonder if one or more workers was down. Both staging and production are running very smoothly right now.

**Comment by ajrobbins** [comment]
@mmcfarland didn't you check the workers at the time?

**Comment by ajrobbins** [comment]
I just tried several HUC 10s and 8s on staging and didn't see a timeout. If you haven't hit any (in uncached areas), I think we can chalk this up to an intermittent failure.
