### ISSUE TITLE
HydroShare Export Design Issues

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2579]
### Language Review

* Is "unsynchronize" the best term? Should we use "desynchronize" or "disconnect" instead?
* ???

### Interaction Review

* Add error message if trying to export project without filling in Title and Abstract
* ~~If modal is closed after export is started but not finished, we get a JavaScript error:~~

    ![image](https://user-images.githubusercontent.com/1430060/34530388-07257ee4-f07d-11e7-997a-d3532a02814e.png)

* Add a "Share" button to the secondary nav as shown here: https://share.goabstract.com/1bd9e502-5ef5-40d8-aba0-868134986fb5 and remove it from the project dropdown.
  - While HydroShare is autosyncing, add a special class to that button, which will be used to style it later.

**Comment by jfrankl** [comment]
>Is "unsynchronize" the best term? Should we use "desynchronize" or "disconnect" instead?

I agree, it's clunky. When someone accepts, we remove their project from HydroShare, correct? What if we use language that involves "removing"?

![image](https://user-images.githubusercontent.com/1809908/34539341-18ef3efa-f09e-11e7-9781-047f4aefdaa6.png)

>Add error message if trying to export project without filling in Title and Abstract

Yes, please refer to the design pattern used in the login modal for the validation. https://share.goabstract.com/01ead2a3-57f8-493d-bd74-0df6d445ec5d
