### ISSUE TITLE
Purchase Reserved Instances

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2582]
Implement proposal in https://github.com/WikiWatershed/model-my-watershed/issues/2370

**Comment by hectcastro** [comment]
The full complement of RIs was purchased for staging. On the production account 18/24 T2 RIs were purchased due to account limits; 2/2 R4 RIs were purchased. Following-up with support to have the limit increased.

**Comment by ajrobbins** [comment]
Production RIs were purchased.
