### ISSUE TITLE
HydroShare Backend Refactor

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2584]
Refactor backend to group all HydroShare related entities under the `export/hydroshare` namespace.

**Comment by arottersman** [comment]
Migrations have already been applied to staging, and will have to be rolled back to move the models under the `export` namespace.

**Comment by rajadain** [comment]
Refactor `HydroShareClient.add_files` to have a binary option, where `contents` would  be a file-like object instead of a string.
