### ISSUE TITLE
Add MMW Version to About Modal

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2591]
To implement this: https://github.com/WikiWatershed/model-my-watershed/issues/2534#issuecomment-355130115 we need the current MMW Version Number available in the UI. This is currently stored in the production settings file (according to @hectcastro).

Make this version number available to the frontend via [`clientSettings`](https://github.com/WikiWatershed/model-my-watershed/blob/cda398667de5012cdcd8699fd74d70914863f2d2/src/mmw/apps/home/views.py#L142) and add it to the About modal made for #2534, linking to the release page on GitHub.

Alternatively, update `version.txt` to include the tag name in addition to the SHA, fetch it when loading the modal, and display it then.

Or something else if it's easier.

**Comment by hectcastro** [comment]
Actually, the version number (`1.0.0`) is not available; only the first 7 characters of the Git revision SHA. To get the version number into the deployment pipeline, I think that we'd have to make modifications to the Packer configuration and parse the version number out of the release/hotfix branch name:

- https://github.com/WikiWatershed/model-my-watershed/blob/develop/deployment/packer/template.js#L116
- https://github.com/WikiWatershed/model-my-watershed/blob/develop/deployment/packer/driver.py#L122-L123
- https://github.com/WikiWatershed/model-my-watershed/blob/develop/deployment/packer/driver.py#L72-L77

**Comment by rajadain** [comment]
See @jfrankl's mockup for what the version number should look like here:

![image](https://user-images.githubusercontent.com/1809908/34581506-a150e300-f15e-11e7-8aaf-af0cf6759fb4.png)

Source: https://github.com/WikiWatershed/model-my-watershed/issues/2534#issuecomment-355382167

**Comment by rajadain** [comment]
Curiously, here it seems like we are using the `version` variable to populate `version.txt`:

https://github.com/WikiWatershed/model-my-watershed/blob/a02c1762e398c859703f22b8881af441975450fe/deployment/packer/template.js#L116

And here we are populating `version` with `get_git_sha`:

https://github.com/WikiWatershed/model-my-watershed/blob/a02c1762e398c859703f22b8881af441975450fe/deployment/packer/driver.py#L120-L121

which is defined as:

https://github.com/WikiWatershed/model-my-watershed/blob/a02c1762e398c859703f22b8881af441975450fe/deployment/packer/driver.py#L60-L69

which when run locally gives a far more informative string:

```bash
$ git describe --tags --always --dirty --abbrev=40
1.21.0-126-ga02c1762e398c859703f22b8881af441975450fe
```

I think we should change `driver.py` to always use `get_git_sha` rather than the `GIT_COMMIT` environment variable.

I will make that change, and then add parsing code in the UI.

**Comment by hectcastro** [comment]
A concern I have with using that command to populate the thing we want to parse to extract the version, is that I don't think it'll include anything about the upcoming version (e.g., for a release branch). When the release branch is being created, the corresponding tag does not exist. At that point the upcoming version only exists in the name of the release branch itself.

**Comment by rajadain** [comment]
Ah good point. I still think we should switch to that for `version.txt` for our own informational purposes.

I'll add a line that also exports the current branch to `/srv/version.txt` and parse that.
