### ISSUE TITLE
saving for guest users

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#260]
I'm not sure I completely understand this, but quoting @mmcfarland in https://github.com/WikiWatershed/model-my-watershed/pull/225

"For redirecting, we're supporting a workflow for anonymous users who have work in progress and decide to register at that point. We should leave the register window completion modal up with a button for login available (or flip directly to the login) and in the activation tab, there should be instructions similar to "if you had work in progress, visit the previous tab to continue and save your work". Activating an account should not log you in."

**Comment by rajadain** [comment]
Shares a point with #356
