### ISSUE TITLE
Add explanatory tooltips to streams tab

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2600]
- Next to "other" - add a tooltip that reads: "Contains canals, artificial paths, coastlines, and other flowlines without a flow direction"
- Add tooltip next to the length in X areas lines that reads: "Derived using a uniform one-pixel (30m) riparian width for flowlines"

**Comment by rajadain** [comment]
Is this also blocked awaiting further instruction?

> need to ascertain what features
> (cell size?)
> riparian buffer

**Comment by ajrobbins** [comment]
I need to clarify the riparian buffer comment, but the "other" one needs to be done by us - As implemented in the streams tab, determine which water feature/stream types are included in the "other" row in the tables.

**Comment by rajadain** [comment]
The code for generating that table is here:



So we group all 0 or empty stream orders into the "Other" field. If we check to see how many of each type there are in the table:

```sql
SELECT COUNT(*) FROM nhdflowline; -- 2993515

SELECT stream_order, COUNT(*) AS count, ROUND(100.0 * COUNT(*) / 2993515, 5) AS percent
FROM nhdflowline
GROUP BY stream_order
ORDER BY stream_order;
```

we get the following results:

| stream_order | count   | percent     |
|--------------|---------|-------------|
| **0**       | **101**     | **0.00337396**  |
| 1            | 1352677 | 45.18691238 |
| 2            | 602309  | 20.1204604  |
| 3            | 323143  | 10.79476802 |
| 4            | 182916  | 6.110408667 |
| 5            | 103278  | 3.450057875 |
| 6            | 59909   | 2.001292795 |
| 7            | 29097   | 0.972001142 |
| 8            | 10403   | 0.347517884 |
| 9            | 3417    | 0.114146747 |
| 10           | 603     | 0.020143544 |
| **NULL**     | **325662**  | **10.87891659** |

From the above, **0** and **NULL** values are grouped under "Other". I'm not sure what that signifies. Maybe @arottersman has a better idea, having touched that table last.

**Comment by kellyi** [comment]
I used Other as a catch all for the 0 and Null values; Null are there because the data was unavailable. 0 initially seemed like bad or missing data, too, but it may signal small streams which aren't connected to any others: https://en.wikipedia.org/wiki/Strahler_number

If 0 is meaningful enough we can add a row for it to the table.

**Comment by ajrobbins** [comment]
Thanks for looking into that! For this card, let's add a tooltip next to the 0 that says "Contains streams with 0 or Null values".

**Comment by arottersman** [comment]
We figured this out; 0 and null ordered streams are all of certain feature types like canals, artificial paths, and coastlines. See https://github.com/WikiWatershed/model-my-watershed/issues/2334#issuecomment-349394240

**Comment by rajadain** [comment]
Regarding the cell size of the riparian buffer, after doing some digging, here’s what I found:

1. We don’t treat NLCD pixels as areas, just as pixels (we’ve done this elsewhere and I was confused)
2. A stream vector line is rasterized to 1 pixel, which is the same size as an NLCD pixel (which is 30m)
3. Under the hood, GeoTrellis uses Bresenham’s Line Drawing algorithm to rasterize a line to pixels:

   - GeoTrellis code: https://github.com/locationtech/geotrellis/blob/4a718f2b64e02d2f05f0be6627fd76ec3b9b8d14/raster/src/main/scala/geotrellis/raster/rasterize/Rasterizer.scala#L281-L328
   - Wikipedia Article on Bresenham’s Line Drawing Algorithm https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm

To answer the question that if we add a buffer of any kind after we rasterize a line: the answer is no. The line is rasterized to a 1-pixel string, where each pixel is the same size as NLCD. So the cell size of the riparian buffer should be 30m.

**Comment by ajrobbins** [comment]
OK, I'm updating the original comment with the appropriate tooltip text. Thanks for the investigation, folks!
