### ISSUE TITLE
Exclude "export" app from swagger docs

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2604]
We should add `export` to the excluded namespaces in the [swagger settings](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/base.py#L323)

<img width="1073" alt="screen shot 2018-01-12 at 6 57 25 am" src="https://user-images.githubusercontent.com/7633670/34874155-ddfdafb0-f765-11e7-8f72-229184d408ea.png">

**Comment by rajadain** [comment]
Shares points with #2576
