### ISSUE TITLE
Splash Page and Header Updates

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2623]
Mockup: 

![image](https://user-images.githubusercontent.com/1430060/35345051-9ba98aee-00fc-11e8-8915-de224871e782.png)

- [x] Update Step 2 to read "Analyze & Monitor"
- [x] Remove "Stroud" Logo from the center
- [x] Replace "Model My Watershed" text with "WikiWatershed" logo. Clicking it should behave identically to now.
- [x] Add "Projects" button to the top right
  - [x] Clicking this should take the user to their "My Projects" page
  - [x] If the user is not logged in, it should open the login modal
  - [x] Remove the "My Projects" option from the user dropdown in the top right

**Comment by rajadain** [comment]
Maybe we should consider making the WikiWatershed logo in the top left not-clickable. I remember it not being clickable originally, and us adding it on purpose, but given this new design:

![image](https://user-images.githubusercontent.com/1430060/36263471-4f7a057a-1238-11e8-86b2-8d0129fbeeff.png)

users can accidentally click the title and go home when in fact they mean to click Analyze or Monitor, losing their work. I've done that at least once.

Thoughts @ajrobbins @jfrankl?

**Comment by ajrobbins** [comment]
I think it's a common pattern to have a home/webpage name link in the top left, and users are used to that. Though I could see now a mistake could be make, I think the new logo there (as opposed to more unstyled text_ will hopefully make that less likely. So, I'm in favor of keeping it as a link.
