### ISSUE TITLE
Add warning text to Hydroshare modal

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2626]
Before the user shares to Hydroshare, they should be warned that the project is being made public. Add text to the share modal, below the current HydroShare text, that reads "When you export to HydroShare, your project will be made public under a [Creative Commons 4.0](https://creativecommons.org/licenses/by/4.0/) license."

![screen shot 2018-01-25 at 2 44 46 pm](https://user-images.githubusercontent.com/12868342/35409088-3992e8ee-01df-11e8-84b9-3ad7e0f6b54d.png)

**Comment by rajadain** [comment]
Shares points with #2613
