### ISSUE TITLE
Allow opening project via Hydroshare resource ID

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2637]
* Create a new web app resource for each of the Hydroshare environments (beta, staging, prod) and have it submitted for CUAHSI approval 
<details>

<summary>instructions on creating web app resource from chris calloway </summary>

The first step is to create an MMW “web  app resource” in Hydroshare. It is the fourth choice on the “create new” dropdown when you create a HydroShare resource. A web app resource is a sort of HydroShare meta-type resource which specifies both which other Hydroshare resource types can be opened with your application and a URL pattern for opening the resource. The rather sparse documentation is here:

https://help.hydroshare.org/hydroshare-resource-types/web-app/

with an example web app resource type here:

https://www.hydroshare.org/resource/9674a0af9f30410e9e02397c91284f54/

If you look toward the bottom of the example web app resource, you will see a ab for “resource specific” metadata. Clicking on this tab show the information needed to open the web app: home page, URL pattern, supported resource types (chosen from a list of all HydroShare resource types), support resource statuses (combinations of public, published, or private), and an app icon

The URL pattern language is documented here:

https://www.hydroshare.org/terms/#AppURLPattern

Notice also that the example web app resource itself is in the public status. This will be important if you want other users to be able to use your web app.

</details>

* Add a new route to open a public MMW project via Hydroshare resource id or create a new project if one doesn't exist

**Comment by rajadain** [comment]
> or create a new project if one doesn't exist

Meaning to import the shape from the HydroShare resource?

**Comment by mmcfarland** [comment]
> Add a new route to open a public MMW project via Hydroshare resource id or create a new project if one doesn't exist

This makes sense if the resource id is internally translatable to a mmw project id.  I believe the supported design for this was going to use an internal project copy mechanism and not actually import any files from the HS resource.

**Comment by rajadain** [comment]
We can translate the resource id to an MMW project id, but only if it exists. Not sure what the second point implies.
