### ISSUE TITLE
Remove "Search Data" button on BiG CZ

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2639]
After the Monitor tab has been integrated in to MMW, run through BiG-CZ and ensure that the workflow fits well there.

Discuss what it should be before removing the MMW specific parts from the UI.

**Comment by ajrobbins** [comment]
I just ran through BCZ- the only issue I can spot (and it is breaking the site), are the Change Area | Search Data buttons at the bottom. Clicking Search Data breaks the site. For this card, let's remove the "Search Data" button on BiG CZ and make the Change Area button full-width, operating the same as it does now. Tagging @jfrankl for confirmation on this approach design-wise.
