### ISSUE TITLE
Production Release 3.13

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2644]
Aiming for Tuesday 3.13 release of MMW to include HydroShare integration, Monitor My Watershed, and new streams/terrain analysis + viz

**Comment by rajadain** [comment]
#2627 Update `ms_weather_station` data post-deployment:

```shell
$ cd /opt/model-my-watershed/
$ ./scripts/aws/setupdb.sh -f ms_weather_station.sql.gz
```

**Comment by hectcastro** [comment]
Some questions I had while going through the release diff:

- Do we have a value for `SRATCatchmentAPIKey` that can be used in production?
- When the streams table is reloaded, do we only need to purge the stale grid JSON files, or do all the tiles need to be purged as well? (The script will purge all as is, but also that'll take a lot longer than just the grid JSON)
- The boundary file was updated as well, does that need updating too?
- Looks like migrations are backwards compatible, except maybe one of the HydroShare ones where it is being moved to a different project? Was that feature already active in production prior to this release?

**Comment by rajadain** [comment]
Just checked on production:

```sql
SELECT * FROM django_migrations WHERE app = 'modeling' ORDER BY applied DESC LIMIT 5;

 id |   app    |              name               |            applied
----+----------+---------------------------------+-------------------------------
 43 | modeling | 0024_fix_gwlfe_gis_data         | 2017-11-09 21:20:20.614223+00
 39 | modeling | 0023_fix_gis_data_serialization | 2017-10-17 14:24:29.238865+00
 38 | modeling | 0022_project_wkaoi              | 2017-10-17 14:24:28.521937+00
 34 | modeling | 0021_old_scenarios              | 2017-07-20 17:28:40.674298+00
 33 | modeling | 0020_old_scenarios              | 2016-12-07 15:46:40.953567+00
(5 rows)
```

And the git diff for this release:

```bash
$ git diff --name-only master..release/1.22.0 | grep migrations

src/mmw/apps/core/migrations/0003_requestlog_api_referrer.py
src/mmw/apps/export/migrations/0001_hydroshareresource.py
src/mmw/apps/export/migrations/__init__.py
src/mmw/apps/modeling/migrations/0025_hydroshareresource.py
src/mmw/apps/modeling/migrations/0026_delete_hydroshareresource.py
src/mmw/apps/user/migrations/0005_hydrosharetoken.py
```

The `hydroshareresource` migration was added and removed from the `modeling` app in this release, and is not on production. It's a separate migration because it was up on staging for a while, but will essentially be a no-op as `modeling/0026` undoes `modeling/0025`. `export/0001` will be used by executing code.

@arottersman should be able to answer the other questions.

**Comment by arottersman** [comment]
> Do we have a value for SRATCatchmentAPIKey that can be used in production?
No, we have only that single key that's in last pass (there's currently only one instance of that API). We're going to reach out to Drexel to see if they'll be making a production version of the API, but doubt that will be ready for tomorrow. This work isn't part of the release though, and is feature flagged. Should be okay to leave blank or insert the same staging key. 

> When the streams table is reloaded, do we only need to purge the stale grid JSON files, or do all the tiles need to be purged as well? (The script will purge all as is, but also that'll take a lot longer than just the grid JSON)

Only the utf8grids

> The boundary file was updated as well, does that need updating too?
Yes, there's a new huc12 boundary file `boundary_huc12_deduped.sql.gz`

**Comment by rajadain** [comment]
List of PRs in this release:

```bash
$ git log --oneline --graph --no-color master..release/1.22.0 --grep Merge
```

* 29a8ae2d Merge pull request #2712 from WikiWatershed/tt/fix-version-number
* 6484badc Merge pull request #2710 from WikiWatershed/tt/monitor-throttle-envirodiy
* f20ce1cd Merge pull request #2700 from WikiWatershed/tt/hydroshare-export-model-tables-2
* f8b34563 Merge pull request #2701 from WikiWatershed/tt/ui-cleanup
* f846e1cd Merge pull request #2704 from WikiWatershed/tt/bigcz-hide-search-navigation-button
* cc483d3e Merge pull request #2696 from WikiWatershed/arr/elevate-your-life
* 8acdfa6d Merge pull request #2705 from WikiWatershed/ki/clear-analyze-results-on-selecting-geocoder-shape
* 1e21a180 Merge pull request #2698 from WikiWatershed/arr/safari-hydroshare-link
* 19bd0ae3 Merge pull request #2694 from WikiWatershed/arr/pq-version
* 53169366 Merge pull request #2693 from WikiWatershed/tt/monitor-search-fixes
* 81ef5335 Merge pull request #2691 from WikiWatershed/tt/fix-reopening-modification-dropdown
* 7e86ce78 Merge pull request #2686 from WikiWatershed/tt/fix-overlapping-chart-ticks
* 2c20f0de Merge pull request #2685 from WikiWatershed/tt/monitor-hide-modifications
* 5b295d7d Merge pull request #2674 from WikiWatershed/jcw/read-only-project
* aaede34e Merge pull request #2675 from WikiWatershed/tt/monitor-modeling-stage-interaction
* ec6b8b25 Merge pull request #2672 from WikiWatershed/arr/csv-namechanges
* 986f51fa Merge pull request #2663 from WikiWatershed/tt/monitor-add-bigcz-search
* aa356c03 Merge pull request #2665 from WikiWatershed/mjm/splashy-changes
* 69c94fb0 Merge pull request #2664 from WikiWatershed/tt/hydroshare-export-mmw-extended-metadata
* a415b619 Merge pull request #2661 from WikiWatershed/tt/hydroshare-export-resource-redirect
* 33f1038c Merge pull request #2658 from WikiWatershed/tt/hydroshare-export-mandatory-public
* 2251abab Merge pull request #2659 from WikiWatershed/mjm/analysis-reorders
* 2a9b1f48 Merge pull request #2645 from WikiWatershed/arr/subbasin-srat-catchment-api
* 2afb3324 Merge pull request #2642 from WikiWatershed/tt/upgrade-jquery
* 405d258c Merge pull request #2633 from WikiWatershed/tt/subbasin-geoprocessing-multioperation-adr
* 1d0e74dd Merge pull request #2653 from WikiWatershed/tt/upgrade-libpq-dev
* 853571a1 Merge pull request #2634 from WikiWatershed/jdf/center-header
* fb9127f2 Merge pull request #2632 from WikiWatershed/tt/monitor-add-monitor-tab
* 3ec450ad Merge pull request #2630 from WikiWatershed/arr/pct-slope-tiles
* 54ca3064 Merge pull request #2628 from WikiWatershed/tt/hydroshare-export-add-license-text
* 949d01d5 Merge pull request #2625 from WikiWatershed/tt/aoi-download
* ed0eeca2 Merge pull request #2618 from WikiWatershed/mjm/stream-tips
* c7a3aed6 Merge pull request #2617 from WikiWatershed/tt/hydroshare-export-shapefile-folder
* 039740c9 Merge pull request #2616 from WikiWatershed/tt/hydroshare-export-handle-timeout
* 37944269 Merge pull request #2614 from WikiWatershed/tt/hydroshare-export-listing-modal
* 08285da2 Merge pull request #2610 from WikiWatershed/tt/hydroshare-export-keyword-bubbles
* 7889e513 Merge pull request #2608 from WikiWatershed/tt/analyze-tabs-ui-fixes
* c61361eb Merge pull request #2609 from WikiWatershed/tt/hydroshare-export-details-2
* 35b101bf Merge pull request #2605 from WikiWatershed/arr/deleted-hydroshare
* eeca6bdf Merge pull request #2607 from WikiWatershed/tt/hydroshare-export-user-profile
* fad05746 Merge pull request #2606 from WikiWatershed/arr/geocoder-text-selection
* 7eba3610 Merge pull request #2598 from WikiWatershed/tt/hydroshare-export-validation
* e601d52a Merge pull request #2594 from WikiWatershed/tt/version-number
* b9544522 Merge pull request #2595 from WikiWatershed/tt/geoprocessing-api-capture-mmw-users
* a02c1762 Merge pull request #2593 from WikiWatershed/tt/branding-updates
* ffdb4826 Merge pull request #2566 from WikiWatershed/arr/pg_dump
* bb1e51a6 Merge pull request #2590 from WikiWatershed/tt/hydroshare-export-autosync
* 4dc83d21 Merge pull request #2587 from WikiWatershed/tt/hydroshare-export-backend-refactor
* 5bade6d5 Merge pull request #2586 from WikiWatershed/tt/analyze-terrain
* 2e03597e Merge pull request #2585 from WikiWatershed/arr/hydroshare-gms
* 9fa18147 Merge pull request #2580 from WikiWatershed/tt/hydroshare-export-update-resource
* b4b59a42 Merge pull request #2581 from WikiWatershed/arr/no-more-spots
* 9b108461 Merge pull request #2570 from WikiWatershed/tt/hydroshare-export-project
* 003fe265 Merge pull request #2562 from WikiWatershed/arr/slow-streams
* b83bdb8d Merge pull request #2564 from WikiWatershed/cpc/fix-search-and-select
* 2d4ca155 Merge pull request #2563 from WikiWatershed/tt/mapshed-update-et
* 9c4b43e2 Merge pull request #2548 from WikiWatershed/arr/import-nhdplus-catchments
* 055cd392 Merge pull request #2556 from WikiWatershed/tt/hydroshare-export-login-frontend
* 47341a7b Merge pull request #2551 from WikiWatershed/arr/slope
* 81a36baa Merge pull request #2552 from WikiWatershed/mjm/statsite-upgrade
* cda39866 Merge pull request #2537 from WikiWatershed/arr/split-mapshed-hucs
* 1ed425f4 Merge pull request #2547 from WikiWatershed/tt/stream-analysis-ag-length
* 611e3084 Merge pull request #2546 from WikiWatershed/tt/fix-null-streams
* abe90765 Merge pull request #2539 from WikiWatershed/tt/hydroshare-export-sharing-modal
* 8f5b359a Merge pull request #2536 from WikiWatershed/arr/fix-dedupe-script
* 4e0cc1cb Merge pull request #2525 from WikiWatershed/arr/dedupe-huc12
* 4fa4fb82 Merge pull request #2531 from WikiWatershed/tt/update-momentjs
* c3888fb2 Merge pull request #2527 from WikiWatershed/tt/hydroshare-export-login-backend
* edc583ca Merge pull request #2524 from WikiWatershed/ki/add-streams-tab
* c9f899ae Merge pull request #2517 from WikiWatershed/tt/make-climate-analyze-common
* 182df07d Merge branch 'hotfix/1.21.1' into develop
* 457cfb1b Merge pull request #2516 from WikiWatershed/feature/hmc/set-geop-aws-creds
* 586efe5c Merge pull request #2506 from WikiWatershed/tt/mapshed-optimize-stream-fetch
* e4572fdf Merge pull request #2508 from WikiWatershed/feature/hmc/fix-geop-beaver-config
* 4de82bdd Merge pull request #2505 from WikiWatershed/arr/analyze-rwd-results
* 8cfba6c4 Merge pull request #2503 from WikiWatershed/tt/tr55-water-quality-bullet-charts
* 70bd542b Merge branch 'release/1.21.0' into develop
* cc5a7490 Merge pull request #2500 from WikiWatershed/tt/geojson-upload-fixes
* fb7ab24d Merge pull request #2501 from WikiWatershed/tt/drb-users-list
* 806e2a9a Merge pull request #2479 from WikiWatershed/tt/geop-api-cors-allow-all

**Comment by rajadain** [comment]
Release complete: https://app.wikiwatershed.org/ and https://github.com/WikiWatershed/model-my-watershed/releases/tag/1.22.0

**Comment by rajadain** [comment]
Moving this back to "Verified" so it can be counted in the Civic Apps sprint.

**Comment by rajadain** [comment]
We missed deploying the Runoff site changes to Production, where the text still says "Micro Site" rather than "Runoff":

![image](https://user-images.githubusercontent.com/1430060/37875221-d6b5e0e2-3059-11e8-86af-00a044fb12c9.png)

Pushing that should be really simple given it's a static site. /cc @ajrobbins @tnation14

**Comment by ajrobbins** [comment]
Ah, that's unfortunate. For efficiency, let's just do it in the 1.23 release. I'll add a comment to that release card.
