### ISSUE TITLE
Add "Hotspot View" Toggle

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2647]
Add a "Hotspot View" toggle switch to the Water Quality tab of the Mapshed model. Toggling this switch should kick off a subbasin model run. Currently the subbasin modeling is set up to run as an either/or situation with regular mapshed/gwlfe. Make it so both results can coexist (this will likely mean adding a `subbasin_results` attribute the scenario model).

<img width="220" alt="screen shot 2018-03-13 at 3 55 31 pm" src="https://user-images.githubusercontent.com/7633670/37368188-df7ac3c8-26db-11e8-87d2-625795b44682.png">

* While polling a spinner should appear at the top right of the sidebar, as it does when fetching CUAHSI variables in Monitor.
* When polling completes, just show a new blank view

~Potentially re-run the model in sub-basin mode, depending if we're doing this by default for all eligible shapes or only by user opt-in (/cc @ajrobbins)~

**Comment by ajrobbins** [comment]
We won't be running subbasin mode until a user clicks on the link, so as to preserve performance for the majority of users who won't use subbasin mode.

**Comment by kellyi** [comment]
`window.clientSettings.enabled_features=["subbasin"];`

**Comment by kellyi** [comment]
https://github.com/WikiWatershed/model-my-watershed/blob/0c301ee281b8967e2596b123ea9907557b324776/src/mmw/js/src/modeling/models.js#L253

**Comment by kellyi** [comment]
> While polling a spinner should appear at the top right of the sidebar, as it does when fetching CUAHSI variables in Monitor.

I spoke with @jfrankl about the desired behavior for this and since subbasin may take > 5-10 seconds to run we decided to show the spinner in the center of the new view, the way that it's currently done with the other modeling tasks.

**Comment by arottersman** [comment]
Kelly and I chatted about this on slack, but:
> since subbasin may take > 5-10 seconds

is more like 10-80sec
