### ISSUE TITLE
Sub-basin: Add Sub-basin HUC-12 Level Container

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2650]
When first entering subbasin mode display:
- a back button to exit subbasin mode
- the same AOI aggregate info (name + model description)
- two sub-container tabs "detail" and "huc-12s"

For the purpose of this card, do _not_ add:
- tables
- "related layers"

<img width="219" alt="screen shot 2018-03-13 at 3 50 10 pm" src="https://user-images.githubusercontent.com/7633670/37368048-71cd732a-26db-11e8-8d7a-c29b3b118659.png">

**Comment by kellyi** [comment]
Blocked by #2647
