### ISSUE TITLE
Sub-basin: Add "Related Layers" To HUC-12 View 

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2655]
At the HUC-12 level of hotspot mode, display a "related layer" toggle like we do on analyze. Selecting a water quality metric should render a visualization of that metric on the map via colored catchment polygons and colored streams. Use the same color breaks we use for the DRB water quality streams and coverage layers.

NB: Rendering so many polygons might not be performant, and might fail. Hopefully only doing this at the HUC-12 level will keep the number down, but we should point this card accordingly.

Mimic the water quality related layer:
![screen shot 2018-02-07 at 4 01 10 pm](https://user-images.githubusercontent.com/7633670/35980639-3ab155be-0cb9-11e8-92f4-035e22de43a2.png)

![screen shot 2018-02-07 at 4 01 13 pm](https://user-images.githubusercontent.com/7633670/35980619-30aeedd8-0cb9-11e8-94f4-54e7133e161a.png)

[Wireframes](https://app.goabstract.com/projects/76ed1390-dea8-11e7-a27c-0f868efbc56f/branches/master/commits/c97f50abf47968d7ccb1679a20b6af9b2b0e7ff3/files/7F4A25A6-1E0D-48A0-B999-8629B42E4E23/layers/F356B552-990A-446E-B648-D891E255F8C8)

**Comment by rajadain** [comment]
Comparing the breaks used in DRB Water Quality rasters vs the values in subbasin:

![image](https://user-images.githubusercontent.com/1430060/39775783-e673554c-52cc-11e8-95de-413113b6bb42.png)

TotalP is always going to be more than 1.20 kg/y, so it'll all be the same black. Is that expected / desired? Should we be using other breaks? /cc @ajrobbins

**Comment by rajadain** [comment]
Also, any suggestions for where the legend will go once we have the colors in?
