### ISSUE TITLE
Add Mapshed model output to HS export

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2666]
As reported by @aufdenkampe , the HydroShare export currently does not include MapShed model output (hydrology table and water quality tables). Add csv's for those tables to the [HS export](https://github.com/WikiWatershed/model-my-watershed/commit/7b2b1125d158f7287c81ac6e497c5141f7aa1052).

**Comment by rajadain** [comment]
There are more items in the results view than just the tables, such as summary statistics:

![image](https://user-images.githubusercontent.com/1430060/36681829-ad4f6c46-1ae7-11e8-9d2a-29380785f3ef.png)

Should these also be included, or just the tables?

**Comment by ajrobbins** [comment]
@aufdenkampe thoughts?

**Comment by ajrobbins** [comment]
Filename should be: model_multiyear_<scenarioname>_hydrology | waterquality
Should output as a csv exactly matching the UI

**Comment by aufdenkampe** [comment]
@rajadain, regarding additional summary statistics, can you append those to the CSVs, as extra columns, but with blanks for all the rows except the Total / Entire Watershed row?

**Comment by rajadain** [comment]
Like this:

| Sources                            |     Sediment | Total Nitrogen | Total Phosphorus | Mean Flow (m3/year) | Mean Flow (m3/s) |
|------------------------------------|-------------:|---------------:|-----------------:|---------------------:|------------------:|
| Total Loads (kg)                   | 10,842,816.7 |      299,694.8 |         45,412.5 |          115,777,006 |              3.67 |
| Loading Rates (kg/ha)              |     1,320.94 |          36.51 |             5.53 |                      |                   |
| Mean Annual Concentration (mg/l)   |        93.65 |           2.59 |             0.39 |                      |                   |
| Mean Low-Flow Concentration (mg/l) |        99.41 |           2.05 |             0.48 |                      |                   |

?
