### ISSUE TITLE
Cross-account issue with HydroShare export

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2671]
Scenario:
- Did not log out of Hydroshare as UserA.
- Registered new UserB in MMW
- Made new model as UserB
- Model saved to UserA's hydroshare account

User B is not prompted to make HS account, and can save projects to User A's account. 

Desired: User B should be prompted to make an HS account/link their account, and should not be able to sync to HS (User A's account)

**Comment by arottersman** [comment]
We tried to replicate this and found that the project isn't automatically shared to the current Hydroshare account on clicking "Share" — you still have to authorize the  link to UserB's MMW account. If there's a currently active Hydroshare session in your browser, the authorization iframe will use it.
