### ISSUE TITLE
Pre-release Bug Fix Blackbox

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2678]
- [ ] Modification Dropdown Does Not Re-Open #2684 
- [ ] Boundary overlays persist on map when home button is clicked #2680

**Comment by ajrobbins** [comment]
Originally 2 points.

**Comment by rajadain** [comment]
-1 to #2684

**Comment by arottersman** [comment]
-1 to #2687

**Comment by rajadain** [comment]
Closing this as all points have been exhausted.
