### ISSUE TITLE
Use non-breaking space on AoI size

### ISSUE THREAD

**Issue by jfrankl** [WikiWatershed/model-my-watershed#2682]
Currently, it's possible for the area of interest size to be split into two lines, which looks confusing. Example:

![image](https://user-images.githubusercontent.com/1809908/36683219-ff2f6d60-1aea-11e8-80ec-4805afcab26c.png)

Use a `&nbsp;` between the number and the unit of measurement to keep them on the same line. That will look like:

![image](https://user-images.githubusercontent.com/1809908/36683273-2caeb50c-1aeb-11e8-80c3-8ebc7b686647.png)

**Comment by rajadain** [comment]
Shares points with #2660.
