### ISSUE TITLE
Modification Dropdown Does Not Re-Open

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2684]
Clicking "Land Cover" or "Conversation Practice" works the first time, but not subsequently:

![2018-02-26 17 12 18](https://user-images.githubusercontent.com/1430060/36698690-809b0b5c-1b18-11e8-8a12-490ef260240e.gif)

It should work every time.

**Comment by ajrobbins** [comment]
I'm not able to replicate this - was this opened via HydroShare or are there any other special steps to replicate?

**Comment by rajadain** [comment]
Confirmed on staging. Added to sprint.
