### ISSUE TITLE
Monitor search button doesn't do anything

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2687]
![screen shot 2018-02-27 at 3 47 23 pm](https://user-images.githubusercontent.com/7633670/36754026-ea633150-1bd5-11e8-9a7c-74999da1139f.png)

Clicking the search icon on the monitor tab doesn't do anything. You have to hit enter to initiate search.

/cc @ajrobbins is this worthy of the bug black box?

**Comment by ajrobbins** [comment]
yes, let's take a point from the bb and fix it
