### ISSUE TITLE
Handle large areas of interest for Monitor

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2689]
In BiG-CZ, the area of interest is limited to 1500 sq km because CUAHSI search fails for larger areas. In MMW, the limit is larger (~5000 sq km). How should we handle larger areas in the Monitor tab?

Should we have text explaining search might fail?

Should we not enable it for AoIs beyond a certain size?

Should we just show an error when search fails, without any other preamble?

/cc @ajrobbins @aufdenkampe

**Comment by rajadain** [comment]
It may be best to just not search CUAHSI for AoIs beyond 1500 sq km and have text there explaining this. CINERGI and HydroShare work fine.

**Comment by aufdenkampe** [comment]
I think that idea makes sense.

**Comment by rajadain** [comment]
Shares points with #2687.
