### ISSUE TITLE
Analyze Results Don't Clear When Selecting Shape from Search

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2699]
## Steps to Reproduce

* Select a shape and proceed to Analyze. Wait for the analyses to finish.
* Click "Change Area" and type in something in the search bar.
* Select a suggested HUC. Click "Select" in the search bar to proceed to Analyze.
* See analyze results from previous shape.

### Observed Behavior

Analyze results from prior shape are shown.

### Expected Behavior

Analyze results for new shape are kicked off.

## Demo

![2018-03-02 17 37 36](https://user-images.githubusercontent.com/1430060/36925483-23535b94-1e41-11e8-8edb-379f3f4ac46c.gif)

**Comment by ajrobbins** [comment]
Good catch! I was able to replicate this just now.
