### ISSUE TITLE
Display holes in AOI

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2703]
EDIT FROM ALICE:
Holes in a polygon are valid, but are not displayed on the map when the AOI mask is applied. Users can upload their own shapes, and might be thrown off that they appear hole-less. Make it so internal holes in an AOI are masked out.

[test shape with holes](https://github.com/WikiWatershed/model-my-watershed/files/1786265/saltLakeCityRwd.json.txt)

original issue
-----------

From David Tarboten:

>
![image](https://user-images.githubusercontent.com/12868342/36997560-03004ba6-2088-11e8-92ac-7376cb2c7218.png)

![watershed1](https://user-images.githubusercontent.com/12868342/36997590-1eef500a-2088-11e8-854b-9ec48fe6411b.png)

>
![image](https://user-images.githubusercontent.com/12868342/36997586-18af9ac4-2088-11e8-9916-53017ef5d7d0.png)
![watershed2](https://user-images.githubusercontent.com/12868342/36997604-2d3a075e-2088-11e8-8346-3aee27b1b5bd.png)
![image](https://user-images.githubusercontent.com/12868342/36997608-2e56faf2-2088-11e8-9100-2b403505e2be.png)

**Comment by arottersman** [comment]
Here is approximately the shape shown above to be used for testing.
[saltLakeCityRwd.json.txt](https://github.com/WikiWatershed/model-my-watershed/files/1782503/saltLakeCityRwd.json.txt)

**Comment by arottersman** [comment]
I think this is two issues. 

One should be opened in https://github.com/WikiWatershed/rapid-watershed-delineation for the holes that shouldn't exist. Likely an issue with something like [this](https://github.com/WikiWatershed/rapid-watershed-delineation/blob/master/rwd_nhd/NHD_Rapid_Watershed_Delineation.py#L182)

Another for the our AOIs not displaying rings/holes which may be an bug for users uploading geojson/shapefiles with them.

**Comment by rajadain** [comment]
We've decided not to pursue this at this time. Future enhancements may make it so that shapes with holes have the holes discarded completely, rather than be preserved in the GeoJSON.

For historical purposes, this was an attempt at showing the holes on the map:

```diff
commit d14567e1e533ca71ef264aae2a168d4477c54f8b
Author: Terence Tuhinanshu <ttuhinanshu@azavea.com>
Date:   Wed Mar 7 11:32:59 2018 -0500

    Show holes in area of interest on the map
    
    Previously, if an area of interest had holes in it, they
    would not be rendered. This was because of the way we style
    the map, by shading the "outside" and leaving the "inside"
    see through.
    
    The way this is done in ce884f6e and #221, is by creating a
    rectangle spanning the entire world and shading it grey, then
    cutting a hole in the rectangle in the shape of the area of
    interest, thus making it see-through. Unfortunately, this did
    not account for holes within the area of interest itself.
    
    Now we go through the area of interest and gather all the
    holes, and make a MultiPolygon, in the same style as the
    "outside" world, and add it to the _areaOfInterestLayer.
    This makes it look like there are holes to the user, even
    though the holes are a separate layer.
    
    None of this should affect any data handling or processing,
    since the GeoJSON of the shape is stored directly on the
    Backbone model of the map: App.map.get('areaOfInterest').
    This edit is for purely visuals.

diff --git a/src/mmw/js/src/core/views.js b/src/mmw/js/src/core/views.js
index b2be2441..068ec31f 100644
--- a/src/mmw/js/src/core/views.js
+++ b/src/mmw/js/src/core/views.js
@@ -1037,10 +1037,15 @@ function applyMask(featureGroup, shapeLayer) {
             return acc.concat(hole);
         }, [outerRing]),
 
-        maskLayer = L.polygon(latlngs, polygonOptions);
+        maskLayer = L.polygon(latlngs, polygonOptions),
+
+        // Add holes in the original polygon as its own layer styled
+        // the same as the "outside".
+        holeLayer = L.multiPolygon(getHolesAsLatLngs(shapeLayer), polygonOptions);
 
     featureGroup.clearLayers();
     featureGroup.addLayer(maskLayer);
+    featureGroup.addLayer(holeLayer);
 }
 
 // Return 2D array of LatLng objects.
@@ -1071,6 +1076,23 @@ function getLatLngs(boundsOrShape) {
     throw 'Unable to extract latlngs from boundsOrShape argument';
 }
 
+// Returns 2D array of LatLngs of holes in all features in a group
+function getHolesAsLatLngs (featureGroup) {
+    var holes = [];
+
+    _.each(featureGroup.getLayers(), function(layer) {
+        if (layer instanceof L.Polygon) {
+            holes.push(layer._holes);
+        } else if (layer instanceof L.MultiPolygon) {
+            layer.eachLayer(function(subLayer) {
+                holes.push(subLayer._holes);
+            });
+        }
+    });
+
+    return holes;
+}
+
 var ModificationPopupView = Marionette.ItemView.extend({
     template: modificationPopupTmpl,
 
```
