### ISSUE TITLE
Sub-basin: Add List table for huc-12 results

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2726]
Under the "HUC-12" tab in the sub-basin view, show the total loads per huc-12:

<img width="219" alt="screen shot 2018-03-13 at 3 50 10 pm" src="https://user-images.githubusercontent.com/7633670/37370364-582ad08c-26e2-11e8-9694-4792eb053da2.png">

No need to add map or row interaction for this card.
https://app.goabstract.com/projects/76ed1390-dea8-11e7-a27c-0f868efbc56f/branches/master/commits/a49748bccbdf373c6c9c88eae15b2ee1a73d5e71/files/7F4A25A6-1E0D-48A0-B999-8629B42E4E23/layers/DB560561-C085-4BB7-9830-6B0A1B80173E

**Comment by aufdenkampe** [comment]
For the "HUC-12 List" tab (formerly "HUC-12") when viewing **_AoI-level model results_** for Water Quality, please mimic the following table, which has extra columns to the one shown above. The live mockup can be found in the [AoI or HUC12 Source Details Table](https://docs.google.com/spreadsheets/d/1OzuN-3SV3_CHrVDoHSRd7ukGMCvVrWpUnnMVik_ZpT8/edit#gid=0) Google Sheet.

NOTE: 
* this table is _nearly identical to the NHD+ Catchment list table_ referenced in #2730, except for the first few columns.
* this table mimics the AoI-level and HUC-12-level Sources tables_ referenced in #2724 & #2729 respectively.

<img width="911" alt="screen shot 2018-04-04 at 11 37 19 am" src="https://user-images.githubusercontent.com/5166036/38321240-954cbbe4-37fc-11e8-957d-4e9016fd77b9.png">
