### ISSUE TITLE
Sub-basin: Add Source Details Table for HUC-12

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2729]
Add a table displaying the active HUC-12 results under the "Details" tab of the view
![screen shot 2018-03-19 at 4 56 53 pm](https://user-images.githubusercontent.com/12868342/37621867-99317578-2b96-11e8-8460-3f9cf56ca89b.png)

https://app.goabstract.com/projects/76ed1390-dea8-11e7-a27c-0f868efbc56f/branches/master/commits/a49748bccbdf373c6c9c88eae15b2ee1a73d5e71/files/7F4A25A6-1E0D-48A0-B999-8629B42E4E23/layers/C853BCBA-EDF7-42F1-B4EC-2F10D1908CED

<img width="483" alt="screen shot 2018-03-13 at 3 56 55 pm" src="https://user-images.githubusercontent.com/7633670/37371066-8918d656-26e4-11e8-84e5-3714576c966e.png">

**Comment by aufdenkampe** [comment]
For the "Sources" tab (formerly "Details) when viewing **_HUC-12-level_** model results for Water Quality, please mimic the following table, which has different column headers and units than the one shown above (which has errors). The live mockup can be found in the [AoI or HUC12 Source Details Table](https://docs.google.com/spreadsheets/d/1OzuN-3SV3_CHrVDoHSRd7ukGMCvVrWpUnnMVik_ZpT8/edit#gid=0) Google Sheet.

NOTE that this table is _identical to the AoI-level Sources table_ referenced in #2724.

<img width="812" alt="screen shot 2018-04-04 at 11 28 23 am" src="https://user-images.githubusercontent.com/5166036/38320849-55ddca8a-37fb-11e8-8142-4362e8d9f904.png">
