### ISSUE TITLE
Production Release 1.23 / Subbasin

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2732]
Notes for production release in April 2018 featuring Subbasin modeling.

**Comment by ajrobbins** [comment]
Needs to include pushing microsite changes to production; see https://github.com/WikiWatershed/model-my-watershed/issues/2644#issuecomment-375968503

**Comment by ajrobbins** [comment]
Now targeting early May for this release.

**Comment by arottersman** [comment]
We need to reload the mapshed data to get the `EtAdj` values from #2773:

```sh
./scripts/aws/setupdb.sh -m
```

**Comment by rajadain** [comment]
If we know the other values haven't changed, it would be preferable to do

```
./scripts/aws/setupdb.sh -f ms_weather_station_1523624744.sql.gz
```

instead, which skips the large `ms_weather.sql.gz` dump.

**Comment by rajadain** [comment]
Remove the `core_job_uuid` index from production before running migrations. This index was manually added to improve performance, but conflicts with [this migration](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/core/migrations/0004_job_uuid_unique_constraint.py) which does the same thing.

**Comment by rajadain** [comment]
Now targeting a mid-June release.

**Comment by hectcastro** [comment]
- [x] Push microsite changes to production
- [ ] Remove `core_job_uuid` before applying migrations
- [ ] Execute migrations
  - `ALTER TABLE` on large `core_job` table
  - Clear of mapshed results using Python
- [ ] Reload mapshed `ms_weather_station_1523624744.sql.gz` (does this impact tiles?)

```bash
./scripts/aws/setupdb.sh -f ms_weather_station_1523624744.sql.gz
```

**Comment by rajadain** [comment]
The weather station table refresh does not impact tiles, only the MapShed results which we are clearing.
