### ISSUE TITLE
Later Scenarios with Long Names are Uneditable

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#274]
If there are many scenarios with long names, while the later ones can be accessed via the dropdown, they cannot be edited since their ▼ button is not visible:

![image](https://cloud.githubusercontent.com/assets/1430060/7961061/0f5394b8-09d3-11e5-84d8-854a5a0530fa.png)

The dropdown menu that allows selecting tabs should also include the ▼ button for each tab so that they can be edited.

**Comment by kdeloach** [comment]
This would be a hack, but we could always just move the active tab to the front (right of Current Conditions, which should always be the first tab).

**Comment by rajadain** [comment]
Jumping tabs ordering around would be disruptive to the user experience. A big part of a user's ability to relate to an interface is though spatial recognition: if the thing that was on the top right jumps to the top left, it is very disruptive.

Also, this would require us to have limits on scenario name lengths. If we had a really long scenario name, it won't work with even one:

![image](https://cloud.githubusercontent.com/assets/1430060/7963599/9432709c-09e1-11e5-85a4-03c739561e3f.png)

**Comment by mmcfarland** [comment]
I think we should consider truncating the display name area of a tab to keep them to a maximum size, with an ellipsis and a tooltip displaying the full name in the cases where they go over.

**Comment by mmcfarland** [comment]
Closing as new design as dispensed with using tabs.
