### ISSUE TITLE
More extensive branding to "WikiWatershed" and away from "Model My Watershed"?

### ISSUE THREAD

**Issue by emiliom** [WikiWatershed/model-my-watershed#2741]
I think a current goal is to transition the branding of the application towards WikiWatershed, and not just Model My Watershed, now that it incorporates a strong Monitor My Watershed component. But there are a number of places where Model My Watershed is still central:
- In the start page, under "Analyze & Monitor" on the instructions on the left, none of the text indicates clearly that there's monitoring datasets available ("See land cover, soil groups, point sources and other factors impacting water.")
- The HTML "title" (the name that is shown on a browser tab, and bookmarked)
- Everywhere in the About pop-up
- The content and presentation of the Help link page

Pinging @aufdenkampe for him to think about whether this comment is worth pursuing and prioritizing (I don't know David Arscott's github handle)

**Comment by aufdenkampe** [comment]
@ajrobbins, these seem to be easy updates that we want to implement.
We'll have to provide you with updated content.

**Comment by aufdenkampe** [comment]
The WikiWatershed Outreach team met today, and we had a lengthy discussion of rebranding issues. See today's notes in our [2017-2019_Wikiwatershed_OutreachNotes-Cumulative](https://docs.google.com/document/d/14ZOGs80rQehmbMMJsx2cIpc29UEox7nNwFPn2xc0tzk/edit#bookmark=kix.1pozzdyrca5t) Google Doc.

We re-thought a number of branding elements across the WikiWatershed / Model My Watershed / Monitor My Watershed system, many of which are also relevant to https://github.com/ODM2/ODM2DataSharingPortal/issues/171.

We're still working on final decisions. I'll summarize soon, and provide clear recommendations/instructions.

**Comment by aufdenkampe** [comment]
Part of this is a likely update of our logos. See our [WikiWatershed Toolkit Branding Ideas](https://docs.google.com/document/d/14QO72Oj5Tb_ATWHc_3cJuJcih0x8y9I3VHXD5BQWKsU/edit#) Google Doc for some of the things we're considering. No decisions on logos have been finalized.

**Comment by aufdenkampe** [comment]
@ajrobbins, @emiliom and @SRGDamia1.

I've revised the Splash page text. 
The draft text is currently is in the [v1.23_SplashPage-Mockup](https://docs.google.com/document/d/10ukwnUruZu6z6FU5VxL1pNJGkKn8w4cFKXKWzHmU2Z8/edit#heading=h.g0skqbe34bzo) Google Doc. 

I would like Dave Arscott to also review before we finalize.

Here is the current draft:

> ## Explore human impacts on your watershed
> Use the WikiWatershed™ web app to analyze mapped watershed data, visualize monitoring data and run model simulations of human impacts.
> - Select Area & Analyze
>   - Explore map layers and select your area of interest. 
>   - Analyze land cover, soil groups, point sources and other factors impacting water.
> - Monitor My Watershed
>   - Search for monitoring data from hundreds of sources. 
>   - Share your monitoring data.
> - Model My Watershed
>   - Use one of two models to compare impacts of different conservation and development scenarios.

**Comment by aufdenkampe** [comment]
Note that in topic 5c of our [2018-04-10 Biweekly Meeting Outreach team notes​](https://docs.google.com/document/d/14ZOGs80rQehmbMMJsx2cIpc29UEox7nNwFPn2xc0tzk/edit#bookmark=kix.1pozzdyrca5t), we decided that the three bullets would eventually become our small square logos for WikiWatershed, Monitor My Watershed and Model My Watershed respectively. However, we don't yet have those.

@HeatherBrooks, is there any chance that we would have those logos in the next week?

**Comment by darscott** [comment]
I've edited the splash screen text. Please see my edits...willing to discuss further changes

**Comment by aufdenkampe** [comment]
@darscott, thanks for your edits. I just accepted them, and made a few other tweaks.

@ajrobbins, here is the text is now final in the [v1.23_SplashPage-Mockup](https://docs.google.com/document/d/10ukwnUruZu6z6FU5VxL1pNJGkKn8w4cFKXKWzHmU2Z8/edit#heading=h.g0skqbe34bzo) Google Doc. Here it is for convenience (but note that the second level of bullets are optional).


## Explore human impacts on your watershed
Use the WikiWatershedⓇ web app to analyze mapped watershed data, visualize monitoring data and run model simulations of human impacts on water quality.

- Select Area & Analyze
  - Explore map layers and select your area of interest. 
  - Analyze land cover, hydrologic soil groups, permitted point source discharges and other natural and human influenced features.
- Monitor My WatershedⓇ
  - Search for monitoring data submitted to various data repositories. 
  - Share your monitoring data to view in WikiWatershed.
- Model My WatershedⓇ
  - Run one of two models to compare impacts of different conservation and development scenarios on water quality.
  - Share your modeling results for others to edit in WikiWatershed.

**Comment by HeatherBrooks** [comment]
@aufdenkampe @darscott I haven't made edits to the Google Doc yet. I thought you said we had until tomorrow?

**Comment by aufdenkampe** [comment]
@HeatherBrooks, thanks for offering to make edits. You definitely have until tomorrow if you would like to contribute. Thanks.

**Comment by HeatherBrooks** [comment]
@aufdenkampe, thanks for the extra time. RE: logos, I spoke with Diane Huskinson and she hasn't had time to work on them yet.

**Comment by aufdenkampe** [comment]
@ajrobbins, 

We now have what should be final text, after one more round of edits based on suggestions from @HeatherBrooks, in the [v1.23_SplashPage-Mockup](https://docs.google.com/document/d/10ukwnUruZu6z6FU5VxL1pNJGkKn8w4cFKXKWzHmU2Z8/edit#heading=h.g0skqbe34bzo) Google Doc. 

Here it is for convenience (but note we are replacing numbers with bullets, and that the second level of bullets are optional):

## Explore Human Impacts on Your Watershed
Use this web app to analyze mapped watershed data, visualize monitoring data, and run model simulations of human impacts on water quality.

- Select Area and Analyze
  - Explore map layers and select your area of interest. 
  - Analyze land cover, hydrologic soil groups, permitted point source discharges and other natural and human influenced features.
- Monitor My WatershedⓇ
  - Search for monitoring data in various data repositories. 
  - Share your monitoring data to view in WikiWatershed.
- Model My WatershedⓇ
  - Run one of two models to compare impacts of different conservation and development scenarios on water quality.
  - Share your modeling results for others to find, copy and edit.

**Comment by aufdenkampe** [comment]
@ajrobbins, I like the change. Thanks.

**Comment by rajadain** [comment]
Are these text changes final and ready to go? /cc @aufdenkampe

**Comment by aufdenkampe** [comment]
@rajadain and @ajrobbins, Yes!
For this release, we'll use the version presently in the in the [v1.23_SplashPage-Mockup](https://docs.google.com/document/d/10ukwnUruZu6z6FU5VxL1pNJGkKn8w4cFKXKWzHmU2Z8/edit#heading=h.g0skqbe34bzo) Google Doc, which includes the suggestion from @ajrobbins. The Outreach team hasn't completed our discussion on larger branding issues, so there's a chance we'll revise this with the last release.

Here it is for convenience (but note we are replacing numbers with bullets, and that the second level of bullets are optional):

## Explore Human Impacts on Your Watershed
Analyze mapped watershed data, visualize monitoring data, and run model simulations of human impacts on water quality.
- **Select Area and Analyze**
  - Explore map layers and select your area of interest. 
  - Analyze land cover, hydrologic soil groups, permitted point source discharges and other natural and human influenced features.
- **Monitor My WatershedⓇ**
  - Search for monitoring data in various data repositories. 
  - Share your monitoring data to view in WikiWatershed.
- **Model My WatershedⓇ**
  - Run one of two models to compare impacts of different conservation and development scenarios on water quality.
  - Share your modeling results for others to find, copy, and edit.
