### ISSUE TITLE
Model Output window toggles

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#275]
The amount of controls and windows in the `/model` view leaves little room for the map, even on large screens, and makes drawing details difficult:

![image](https://cloud.githubusercontent.com/assets/1430060/7961242/44411d2a-09d4-11e5-82c1-7498a91b174a.png)

Consider ways to make the map bigger when users are drawing modifications, by minimizing other panels.

**Comment by mmcfarland** [comment]
There is some workflow with the model output.  It's meant to start out minimized and icons on the output tabs indicate that models are running or complete.  The user can then toggle the pane up or down.  We've also got plans to consolidate the top app header with the project/scenario header.

**Comment by rajadain** [comment]
Oh! Good to know. Should I close this issue or leave it open until those tasks are done?

**Comment by mmcfarland** [comment]
Nope, it's good to leave, we can use it as a waffle to implement the feature when we are ready for it.

**Comment by caseypt** [comment]
I think we should update the title `Model Output` to be `{{ active scenario }} Model Output`

**Comment by caseypt** [comment]
Add an arrow
