### ISSUE TITLE
Make scenario tabs re-orderable in /model view

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#276]
Duplicates, even of earlier scenarios, are always added to the very end:

![image](https://cloud.githubusercontent.com/assets/1430060/7961334/e0b1428e-09d4-11e5-8aae-c29f62970ef3.png)

Consider the use case:
- Start with original scenario "Test Scenario 5", which has X modifications.
- Duplicate the original scenario "Copy of Test Scenario 5", and add Y modifications.
- Duplicate the copy to make "Copy of Copy of Test Scenario 5", and add Z modifications.
- Duplicate the original scenario to make "Copy of Test Scenario 5 1", and add W modifications.

At this point, the state is as follows:
- Test Scenario 5 = X
- Copy of Test Scenario 5 = X+Y
- Copy of Copy of Test Scenario 5 = X+Y+Z
- Copy of Test Scenario 5 1 = X+W

Now, if one wants to compare X+Y to X+W, it would be helpful to have them side by side. Unfortunately, since one cannot re-order tabs, one is unable to do this.

**Comment by kdeloach** [comment]
This isn't a bad idea, but I think there will be a separate view for comparing scenarios.

**Comment by mmcfarland** [comment]
Closing as new design as dispensed with using tabs.
