### ISSUE TITLE
Replace Python suds dependency with suds-jurko

### ISSUE THREAD

**Issue by emiliom** [WikiWatershed/model-my-watershed#2760]
The app seems to be using the very old and deprecated `suds` package:  
https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/requirements/base.txt#L23
suds is used for SOAP implementation, for CUAHSI HIS interactions. As mentioned in #2756, this particular package stopped being developed many years ago, and is known to have memory problems. Its use should be replaced with [`suds-jurko`](https://bitbucket.org/jurko/suds), a fork that's maintained more actively. 

It's a simple, drop-in replacement, with no changes to code needed.

Note that `ulmo` already lists `suds-jurko` in its [requirements.txt](https://github.com/emiliom/ulmo/blob/wml_values_md/requirements.txt) file, and ulmo is already listed in the app `requirements/base.txt` file, so suds-jurko might already be installed but not used when doing `import suds`. It may be that removing the `suds==0.4` line is all that's needed.

cc @aufdenkampe @ajrobbins @rajadain

**Comment by aufdenkampe** [comment]
@ajrobbins & @rajadain, this seems to be an easy update that has a lot of potential to increase performance with minimal effort. Please implement.

**Comment by aufdenkampe** [comment]
@rajadain just reported during today's meeting that using `suds-jurko` does indeed substantially improve performance, and that 5000 to 8000 km2 could be reasonable. Yay!
