### ISSUE TITLE
Layers > Observations: Is Historical Data time series plotting disabled?

### ISSUE THREAD

**Issue by emiliom** [WikiWatershed/model-my-watershed#2761]
At the 3/20 Monitor MW call we discussed the problems with displaying historical time series plots available through Layers > Observations. 

It appears that the functionality is currently disabled on the App -- as opposed to the problem being solely on the UW server end, where requests for very long time series are not working.

@rajadain and/or @arottersman can you confirm that's the case? If so, please reenable it on the test app so we can run some tests.

I've confirmed that the UW web service is functioning normally for a request for a relatively short time series, such as this one (about 65 days): http://www.wikiwatershed-vs.org/services/get_asset_info.php?opt=data&asset_type=siso&asset_id=USGS_01408168&var_id=H1_RiverStage&units_mode=v2

Once our tests confirm that we can make this work with shorter time series, I'll make changes on the UW end so that all time series are short enough.

cc @aufdenkampe @ajrobbins

**Comment by aufdenkampe** [comment]
Decided on today's meeting that @mmcfarland & @rajadain will investigate

**Comment by aufdenkampe** [comment]
From our discussion today, it sounds like Azavea has done what they need to do on their end, and now it's back to Emilio to set up auto trimming of datasets on his end to contain < 1 year of data.

**Comment by emiliom** [comment]
> and now it's back to Emilio to set up auto trimming of datasets on his end to contain < 1 year of data.

I've trimmed the data on my end and did a bunch of spot testing on the staging app. With 1 year, the USGS data was fine, but the other two data sources (NOAA NOS and DEOS) were not. So I trimmed everything to 6 months, and now all sites seem to be able to generate complete "historical" time series plots.

**Comment by aufdenkampe** [comment]
@emiliom, thanks!

**Comment by ajrobbins** [comment]
I just spot checked several sites in the staging app, and it's looking good! Closing this issue.

**Comment by emiliom** [comment]
Final note: I've set up our database cache to automatically trim data that's a little over 6 months (190 days). This happens daily.
