### ISSUE TITLE
Add new loading indicator messaging for subbasin

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2764]
Due to the large number of subbasins in some HUCs, total execution times for subbasin modeling may range from 30-90 seconds. Since this is farily long loading time for a web app, we should implement some more helpful messaging for the loading indicator, including:
- fraction of steps complete
- name of step in process that's currently running
- up-front warning about likely time range

mockup (note that the loading indicator styling itself should not change):
![image 15](https://user-images.githubusercontent.com/12868342/38316588-11d6924c-37f9-11e8-9332-b7efdc3aae3c.png)

**Comment by arottersman** [comment]
If we need to get the in-flight progress for a celery task, we can use something like this: http://docs.celeryproject.org/en/latest/userguide/calling.html#on-message

**Comment by rajadain** [comment]
Another alternative may be to simply report the polling stage, allowing the user to see how far along the process is. In some cases the process may finish before polling times out, and when it doesn't we'll be more transparent regarding the wait.

@jfrankl Do you have any suggestions for a progress bar library or something that could support ~150 ticks? I suppose it could be done with simple CSS too.

**Comment by arottersman** [comment]
Here's the bootstrap 3 progress bars if they're of interest https://getbootstrap.com/docs/3.3/components/#progress
