### ISSUE TITLE
"Elm Fork Red" HUC 8 fails to model with Multi-year model on staging

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2765]
Reported by BME, the Elm Fork Red HUC 8 (TX/OK border) fails in modeling on staging once it reaches about the GWLF-E stage.

![screen shot 2018-04-04 at 4 55 22 pm](https://user-images.githubusercontent.com/12868342/38334460-66801f22-3829-11e8-9540-2647907d7e05.png)

Works fine on production, so this is likely something introduced since the release.

**Comment by ajrobbins** [comment]
Another failed project: https://staging.app.wikiwatershed.org/project/1251/
Not sure if related

**Comment by arottersman** [comment]
On staging elm fork fails from double_scalar underflow (this issue/rollbar error #2763). I haven't yet been able to reproduce this locally — I can model Elm Fork Red when on `develop`.

The project  linked above that also fails is a case of #2767
