### ISSUE TITLE
Determine cause or solution to removal of Ubuntu HVM AMIs from public listing

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#2766]
Our CI build process depends on the Ubuntu AMI listing on http://cloud-images.ubuntu.com/query/trusty/server/released.current.txt to select the most up-to-date Ubuntu Trusty HVM release AMI. It appears that all HVM AMIs have been removed from the list, leaving only paravirtualized AMIs.

This could be a temporary issue, but if it isn't, we need to determine an alternate way to find the most recent Ubuntu Trusty HVM AMI.

At the time of issue creation, there appear to be no HVM AMIs for Ubuntu Trusty for `us-east-1` at https://cloud-images.ubuntu.com/locator/ec2/ either.

**Comment by tnation14** [comment]
https://cloud-images.ubuntu.com/locator/ec2/ was intermittently showing images, but they're still not showing up in  http://cloud-images.ubuntu.com/query/trusty/server/released.current.txt at all. If we switch to using Boto to look up AMIs [here](https://github.com/WikiWatershed/model-my-watershed/blob/develop/deployment/packer/driver.py#L21), we won't have to rely on an external resource anymore.
