### ISSUE TITLE
Missing Required streamLines

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2767]
https://rollbar.com/Azavea/MMW/items/302/

We assume all shapes will have streams
https://github.com/WikiWatershed/model-my-watershed/blob/46b52479e211e3b6ac03ecff271439c5a757feb8/src/mmw/apps/modeling/geoprocessing.py#L172

To recreate, draw a small shape that doesn't intersect any streams. Try to model it with mapshed.

**Comment by ajrobbins** [comment]
Another failing project: https://staging.app.wikiwatershed.org/project/1251/, not sure if related
