### ISSUE TITLE
Incorporate PA municipalities boundary with PA urbanized areas overlay

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2769]
PA DEP has a need to view the PA urbanized areas overlay and the PA municipalities boundary overlay at the same time in the same "coverage grid" layer, so they can turn on the HUC 12 overlay as well for a digitization workflow. We can move the muncipalities overlay to the urban areas layer, and change the red color to something that will contrast with the red HUC12 lines when they are viewed together.

**Comment by ajrobbins** [comment]
To be clear, the desired new behavior is that when the user turns on the PA urbanized areas layer in the "coverage grid" section of the layer selector, the PA municipalities overlay also appears (not activated in boundary menu, but is actually merged into this one layer). The municipality lines should be a different color than red. The urbanized areas layer would then be renamed "PA Municipalities and Urbanized Areas", and I believe that the existing Municipalities layer can be removed from the boundaries section of the layer selector.

**Comment by rajadain** [comment]
I have the paired layers working now:

![2018-06-26 13 28 02](https://user-images.githubusercontent.com/1430060/41929005-f689a10e-7944-11e8-9dd0-5a7d622a7d24.gif)

Any recommendations on what color these boundary lines should be so they don't conflict with actual boundary layers (such as HUC-12) when they are turned on too:

![image](https://user-images.githubusercontent.com/1430060/41929056-1518d54a-7945-11e8-9f4f-0bc8f4829267.png)

/cc @ajrobbins @jfrankl

**Comment by rajadain** [comment]
Current color scheme is defined here:

https://github.com/WikiWatershed/model-my-watershed/blob/7e7fd74a0b24df8589f00cbc721666c388e32244/src/tiler/styles.mss#L5-L26

**Comment by ajrobbins** [comment]
Chatted with @jfrankl about this - he recommends using the black we use in subbasin hover mode instead of the red for the municipalities line color.

![screen shot 2018-06-26 at 1 58 03 pm](https://user-images.githubusercontent.com/12868342/41930460-1e2a3800-7949-11e8-9c28-341a145655af.png)

It looks like there's a thin white stroke around the red now, which we should keep with the black.

**Comment by rajadain** [comment]
The color used there is a very dark green #1d3331 ![1d3331](https://via.placeholder.com/16/1d3331?text=%20). Here's what that looks like:

![image](https://user-images.githubusercontent.com/1430060/41931171-437420ec-794b-11e8-9f96-105a0742ee7c.png)

Is this alright?

**Comment by ajrobbins** [comment]
Checking with BME.

**Comment by ajrobbins** [comment]
Got a +1 from Barry, @rajadain !!

**Comment by rajadain** [comment]
Great. The PR is ready #2879
