### ISSUE TITLE
Update unit for DRB/SRAT layer legend items

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2776]
The three SRAT/DRB coverage water quality legends are using incorrect units.  Currently they are `kg/yr`, but should be `kg/ha`.

![screenshot from 2018-04-16 11 29 29](https://user-images.githubusercontent.com/1014341/38819519-9fe65580-4169-11e8-9a7c-9aca5aa3569a.png)

**Comment by caseycesari** [comment]
Is this just a copy issue, or are other code changes also required?

**Comment by mmcfarland** [comment]
Yes, just a unit label problem, not a unit conversion.

**Comment by rajadain** [comment]
Shares points with #2714
