### ISSUE TITLE
Subbasin Hover Only Works First Time

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2791]
The hover interaction works very well the first time the subbasin mode is loaded. But if the user goes back to MapShed and then back to Subbasin, it doesn't work:

![2018-04-20 14 08 55](https://user-images.githubusercontent.com/1430060/39066896-b81a58ca-44a4-11e8-90ca-3cee1dd6f163.gif)

The failure happens in `bringToBack` and `bringToFront` invocations here:

https://github.com/WikiWatershed/model-my-watershed/blob/02661b382408ac9d3498f4231c8de312db1d625b/src/mmw/js/src/core/views.js#L1048-L1060

Also see related https://github.com/Leaflet/Leaflet/issues/2439 and https://github.com/Leaflet/Leaflet/issues/2200.

Make it so the interaction always works and doesn't error out.

**Comment by arottersman** [comment]
Shares a point #2730

**Comment by rajadain** [comment]
Not done yet. Still happening in some cases.

**Comment by rajadain** [comment]
Shares points with #2655.
