### ISSUE TITLE
Default StreamLength to 10 for Streamless AoIs

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2799]
According to BME, Mapshed can't be performed for areas without streams. Instead of the workaround we implemented in https://github.com/WikiWatershed/model-my-watershed/pull/2790, which enables Mapshed to operate on streamless areas, show an error message in an alert modal saying "The watershed multi-year model cannot be run on the area of interest you have delineated, because it does not contain any streams. Please select a different area of interest or a different model."

**Comment by rajadain** [comment]
What should be done in cases like this (Upper Wolf HUC-8, Texas):

![image](https://user-images.githubusercontent.com/1430060/40124757-40d714b2-58f7-11e8-91b2-3cdd0acfb5d8.png)

where the parent HUC-8 has streams, but one or more child HUC-12s do not have any (the westward ones above)? In this case, do we let the user run MapShed but not Subbasin?

**Comment by rajadain** [comment]
From BME:

Set StreamLength to 10m in cases when there are no streams. This will not affect results significantly, while allowing MapShed desktop to process the GMS files (which would crash if StreamLength is 0).

This change should be made here:

https://github.com/WikiWatershed/model-my-watershed/blob/390d2220a51601d28a550443b89a047325446446/src/mmw/apps/modeling/mapshed/tasks.py#L94
