### ISSUE TITLE
Staging tiles get intermittent 503

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2809]
A substantial number of tile requests to the current staging tiler endpoints fail with 503.  Layer type does not seem to be important.

> https://blue-tiles.staging.app.wikiwatershed.org/huc8/7/34/46.png 503 (Service Unavailable: Back-end server is at capacity)

![screenshot from 2018-04-27 10 46 30](https://user-images.githubusercontent.com/1014341/39368706-51956acc-4a08-11e8-9ecf-997b0f687876.png)

**Comment by mmcfarland** [comment]
Looks like the Tiler ASG has been cycling these out for health check failures for a day or two.

**Comment by mmcfarland** [comment]
Tiler logs show
> envdir: fatal: unable to switch to directory /etc/mmw.d/env: access denied

Must be related to #2808, will likely self resolve when that PR is merged.

**Comment by hectcastro** [comment]
I shepherded this PR into staging and confirmed the tile server is operating as expected now.
