### ISSUE TITLE
Ingest Shippensburg future land use data to GeoTrellis for visualization

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2810]
These rasters are for visualization only, and are drawn from the Shippensburg 2050 future land use projection data. They should be added to the "coverage grid" tab in the layer selector.

Extent: DRB
Cell size: 30m
Range of values: 0-100
Color ramp: TBD

Three rasters, available [here](https://drive.google.com/file/d/1Tkhib5uzY3l5QZuuze5QwaVb-9OEBJnf/view?usp=sharing):
1. BaseLine_Sum2050.tif
2. Scenario1_Sum2050.tif
3. Scenario2_Sum2050.tif

**Comment by rajadain** [comment]
Confirming that the color ramp should be white to red?

**Comment by ajrobbins** [comment]
That is correct. Per @aufdenkampe:

>The 2050 layer without the 2011 footprint doesn't convey to me what things will look like in 2050, which I think could be quite confusing to users.

>I would like to have us visualize the 2050 layers with the 2011 footprint, to make it really clear that this is what things might look like in the future. For these visualizations, the 2012 footprint will get a value of 100 (percent probability), and we'll want to make the color ramp show 2011(100%) distinctly from everything else.


>The user can also toggle back and forth to the 2011 layer to see clearly the difference, and to highlight the locations of future urban vs current urban.
