### ISSUE TITLE
Adjust Subbasin map styling

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2821]
Several styling elements on the subbasin mode map implementation were placeholder, and should be reviewed/updated by a designer:

![image 16](https://user-images.githubusercontent.com/12868342/39883911-2aa87b68-5456-11e8-9c8e-5d1b8b6ba755.png)

- yellow HUC-12 outline
- grey subbasin outlines
- black outline + extra opacity (0.4 instead of 0.3) that indicates hover

**Comment by rajadain** [comment]
Also, any idea where we should put the legend?

**Comment by rajadain** [comment]
For the legend, we can use this pattern:

![image](https://user-images.githubusercontent.com/1430060/40126224-d293b592-58fa-11e8-8a64-b43849459121.png)

In the area same as the slider here:

![image](https://user-images.githubusercontent.com/1430060/40126250-e0ecb2c4-58fa-11e8-8f94-77af14fe295e.png)

**Comment by rajadain** [comment]
Also see if these comments can be addressed: https://github.com/WikiWatershed/model-my-watershed/pull/2829#issuecomment-389629926
