### ISSUE TITLE
Update SedNitr and SedAAdjust multipliers in Mapshed

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2824]
**SedNitr change**
From BME:

>Back in March of 2017, I sent a document to you and Matt describing how some new GIS layers should be used to calculate various model parameters (see attached). I was wondering - would it be possible to make a slight change in the value used to multiply the derived "SedNitr" value by (i.e., 6.0 instead of 4.0)? Based on my recent calibration work, I'm finding that the nitrogen loads are being calculated slightly lower than they should be, and this slight change would help correct that problem. Thanks.

See routines descriptions in https://drive.google.com/open?id=0B0hs2mX4ApaLYnNkdThNZXppWUN2dE1USUp2X1hqZG9sekM0

**SedAAdjust Change**
From BME:
>Last summer, we made a change in a default value that was being written to the gms file. Specifically, the default value for the Sediment adjustment factor (SedAAdjust, the 7th value on line 36 of the gms file) was changed from "1" to "1.4". Based on my calibration work, I think this value should now be changed to ~"2.1"~ 1.5. [edited 6.20]

**Comment by rajadain** [comment]
Since `SedNitr` had already been set to `7.0` in #2563, I asked BME what we should and this is what he said:

> I guess I forgot that we had changed it to 7.0. So I guess the easiest way to answer this is to say, if it's currently 7.0, change it to 8.0. However, if it is still 4.0 (which I know would be easy enough to check), change it to 6.0. Thanks for your help.

So we should change it to `8.0`.

**Comment by rajadain** [comment]
Update from BME:

> Sorry, I changed my mind. If the multiplication factor for SedNitr is already at 7.0, please change it to 9.0 instead to make the resultant change in load significant enough. I promise this will be my last request for this factor!

We need to set it to `9.0`.
