### ISSUE TITLE
HUC-10 search is slow

### ISSUE THREAD

**Issue by jfrankl** [WikiWatershed/model-my-watershed#2833]
Searching for "Lower Sch" takes ~15 seconds to complete. There is a spinner visible, but because there are already results listed under the HUC headings, it seems like the search has already completed and failed.

We should either speed up the search, if possible, or find a way to make it more clear that the results under HUC-8, HUC-10, and HUC-12 are in progress.

![xgpscdkmtk](https://user-images.githubusercontent.com/1809908/40136985-587ef45c-5917-11e8-8a24-3ca5c9080345.gif)

**Comment by lossyrob** [comment]
I'm noticing that modelmywatershed.org is not exhibiting this behavior.

For the development environment, if I run the following SQL in the vagrant app through `psql`,

```
mmw=# CREATE EXTENSION pg_trgm;
CREATE EXTENSION
mmw=# CREATE INDEX trgm_idx_boundary_huc08_name ON boundary_huc08 USING gin (name gin_trgm_ops);
CREATE INDEX
mmw=# CREATE INDEX trgm_idx_boundary_huc10_name ON boundary_huc10 USING gin (name gin_trgm_ops);
CREATE INDEX
mmw=# CREATE INDEX trgm_idx_boundary_huc12_name ON boundary_huc12 USING gin (name gin_trgm_ops);
CREATE INDEX
```

The speed issue goes away. I'll look to where this index creation will best fit into the dev environment setup to solve on the dev side.
