### ISSUE TITLE
Add Water Quality Portal (WQP) catalog to Monitor search

### ISSUE THREAD

**Issue by emiliom** [WikiWatershed/model-my-watershed#2837]
This issue is really just an after-the-fact book keeping entry to give PR #2813 a clearer reference point, so that this new capability can be better accounted for in prioritizations and [Monitor issue labeling](https://github.com/WikiWatershed/model-my-watershed/issues?q=is%3Aopen+is%3Aissue+label%3AMonitor). Maybe it's completely unnecessary at this point, but I'm adding it just in case. We had not created an issue for it yet.

WQP implementation discussions were first tracked externally, at https://github.com/BiG-CZ/BiG-CZ-Portal/issues/8. More work (important refinements) will be done at some future date (months from now); preparatory discussions for that work will probably take place there.

Great to see that this initial WQP implementation is now close to arriving on staging!

@aufdenkampe @ajrobbins @rajadain

**Comment by rajadain** [comment]
In order to get this on staging quickly, but still shielding the next release of MMW from code that hasn't been tested on staging, would we be open to the idea of feature flagging this so that WQP is available on BiG-CZ URLs (https://staging.portal.bigcz.org/ and eventually https://portal.bigcz.org/) but not WikiWatershed URLs until we re-enable it?

**Comment by emiliom** [comment]
That seems like a good strategy to me. I'm all for it.

**Comment by rajadain** [comment]
Shares points with #2846

**Comment by rajadain** [comment]
Water Quality catalog is now available on BiG-CZ Staging https://staging.portal.bigcz.org/ /cc @emiliom @aufdenkampe @lsetiawan @ajrobbins 

Note that we're having some issues with EnviroDIY (#2859), so please refrain from looking those up.

**Comment by emiliom** [comment]
Nice! It seems to be working just fine. Thanks, @rajadain 

Now, @aufdenkampe myself and others can use this to propose fine tuning the behavior and appearance of the WQP catalog

**Comment by lsetiawan** [comment]
THIS IS SO COOL! Thanks @rajadain! It has been great working with you :smile:
