### ISSUE TITLE
Feature flag new Monitor catalog, cut release branch

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2846]
Feature flag the new Monitor catalog added by Emilio & Don (https://github.com/WikiWatershed/model-my-watershed/pull/2813), so that it deploys to BiG CZ for this release. This will enable us to test it on production without introducing it to MMW prematurely. 

Also, cut a release branch for 1.23.

**Comment by rajadain** [comment]
Release branch has been cut: https://github.com/WikiWatershed/model-my-watershed/tree/release/1.23.0
