### ISSUE TITLE
Fix links in Contribute Data modal

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2851]
A couple of the links in the Contribute Data modal have https when the sites don't support it. Revise to use http and ensure that all links in the modal open pages properly.

**Comment by rajadain** [comment]
Shares points with #2815

**Comment by rajadain** [comment]
Some more background about the upcoming changes in Google Chrome that will mark HTTP pages that have form fields as "Not Secure" https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html /cc @aufdenkampe
