### ISSUE TITLE
Monitor: Limit /values/ to 5s

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2859]
When searching for some EnviroDIY values (such as _SHPK3S Pickering Creek Eastern Trib at Bryn Coed Lane_), the EnviroDIY server responds with 504s:

![image](https://user-images.githubusercontent.com/1430060/40746842-7fb9e032-6429-11e8-99ee-349928ded5aa.png)

This is tolerated and managed locally. However, on staging, it causes all the `gunicorn` processes to restart. Additionally, we start getting 503s from the server, and it is eventually cycled out.

Find out why this is happening and make it so that handling this is just as graceful on staging as it is on local.

**Comment by rajadain** [comment]
Paired on this with @hectcastro and @tnation14. This is what we observed:

* Staging has 3 worker processes, evaluated based on how many CPUs are on a platform (see #1724). Since Staging is a `t2.small` which has 1 CPU, the formula `2n + 1` yields 3, where `n` is the number of CPUs.
* When the client fires off 4 EnviroDIY requests, 3 of those are given to the 3 worker processes. The 4th is enqueued.
* These requests take ~ 60s, at which point the EnviroDIY server returns a 504 timeout.
* Because these requests each take 60s, and all workers are busy, other requests are enqueued and not responded to.
* These other requests include health check requests by the ELB, which are fired every 30s.
* If the health check fails twice, the app VM is recycled.
* Since the workers are busy for >60s, the health check fails twice, and the app VM is recycled.

Proposed ideas for solving this:

* Add a timeout to the `/values/` Ulmo calls of 3-10s (the lower the better. This seems to be enough for the other data providers). If Ulmo does not support timeouts natively, wrap it in something that will kill it after the timeout.
* Increase workers on Staging. (Dev has 2 CPUs so 5 workers. Dev also doesn't have the ELB kill switch for 60s of inactivity.) Since each worker process has the full app in memory, we may run in to RAM issues.
* Switch to `gevent` and aynschronous workers. This allows us to have far more worker threads, instead of the processes that we currently have. This _should not_ have ill consequences, since most of our requests are IO bound rather than CPU, with the exception of the `/details/` for CUAHSI which require a lot of CPU for parsing the data.

Other notes:

* Update local dev timeout to be the same as staging here:

    https://github.com/WikiWatershed/model-my-watershed/blob/ea6467447137d32e6cc1a171e4f40e5eabfb1f01/deployment/ansible/roles/model-my-watershed.app/templates/gunicorn.py.j2#L12

* We should talk to Stroud about placing the time limit of 3-10s so that their endpoints can be updated to run faster and finish within the limit.

---

My recommendation:

Place the time limit on just the `/values/` endpoint of 3-10s. This is fast enough for >90% of all CUAHSI endpoints in testing. This will also lead to quicker failures and lower wait times for the user. Hopefully incentivize EnviroDIY and others to improve their service.

While increasing the workers, and changing the worker types, are promising, especially because they don't involve any changes to code, only configuration, I feel they are risky because

* They affect the entire app
* They may surface concurrency bugs by adding a level of parallelism we have so far avoided
* We are 1 week from releasing to production, which doesn't give us enough time to test and iterate

/cc @ajrobbins

**Comment by mmcfarland** [comment]
I like this recommendation as well, nice job tracking it down.

**Comment by rajadain** [comment]
Repurposing this card to:

* Limit the `/values/` endpoint to timeout after 3s and test. Up to 5s, 8s, and a max of 10s to get most endpoints to work.
* Set local timeout to be 60s instead of 1800 for a request.

**Comment by aufdenkampe** [comment]
@rajadain, thanks for this detailed report.

@horsburgh, @Maurier and @jcaraballo17, can you help figure this out.
I created this related issue in the relevant EnviroDIY Data Portal repo: https://github.com/ODM2/ODM2DataSharingPortal/issues/258
