### ISSUE TITLE
Create reclassified NLCD 2011 raster

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2864]
In order to provide a baseline for 2050 land use projections, we'll be including a "2011 urban land cover" raster for visualization, from the layer selector. We already have the NLCD 2011 raster ingested, so in order to derive urban land cover we need to reclassify it to combine the urbanized categories.

The new raster should only have two classes, urbanized and nonurbanized land cover. Urbanized consists of the four developed land categories, values 21, 22, 23, 24.

**Comment by rajadain** [comment]
Should the non-urbanized be "no data" or "non-urbanized"? (i.e. showing one color and empty map vs showing two colors on the map)

**Comment by ajrobbins** [comment]
Not sure - @aufdenkampe what do you think?

The applicable Shippensburg product appears to have white or no data for non-urbanized:
![screen shot 2018-06-01 at 12 48 21 pm](https://user-images.githubusercontent.com/12868342/40852933-30866b62-659a-11e8-9631-73f3ae414475.png)

**Comment by aufdenkampe** [comment]
I think "not developed" should be white for all four datasets. Read below.

The Shippensburg 2050 products from Scott should be byte rasters, with values ranging from 0 to 100, right?

These were intended to indicate the probability of being urbanized in 2050, with 0 representing 0% probability of being urbanized and 100 representing 100% probability of being urbanized, which should also equal the 2011 urban classes (assumption is that if urbanized now, it will still be urbanized in 2050). We didn't complete our discussion of the visualization color ramp, but one good option would be to to continuously grade from White (=0) to Red (=100). Given our opacity slider, I think having 0 equal clear/transparent might make it tricky to clearly see those location with 0% probability of urbanizing. Seeing this is important.

The idea was that the 2011 Urban layer dataset would be set up identically, except that it would only have values of 0 and 100 (or 1 for efficiency, as long as it is visualized as 100), and only 2 colors (i.e. white and red).

For reference, see Notes from [Topic 3a Data layers for visualization and analysis](https://docs.google.com/document/d/1mG6m6wxxJjoSxK4SyYrNRaUTHZujSHYz5B7aXmCJWsQ/edit#bookmark=id.k1hfurf8t5he) notes for [2018-03-20 Bi-Weekly MMW2 Tech Meeting](https://docs.google.com/document/d/1mG6m6wxxJjoSxK4SyYrNRaUTHZujSHYz5B7aXmCJWsQ/edit#bookmark=kix.avcs8loa5wtd).

**Comment by kellyi** [comment]
I created the tiles for reclassified NLCD locally and I'm getting set to push them to S3.

For reference, I set up tilejson.io to display the new tiles adjacent to the existing tiles:

*left: reclassified; right: nlcd 2011*

![screen shot 2018-07-25 at 1 21 12 pm](https://user-images.githubusercontent.com/4165523/43218267-e6f3a45e-9011-11e8-9d75-4931341e5d3b.png)

*left: reclassified; right: Shippensburg 2050 baseline*

![screen shot 2018-07-25 at 1 21 22 pm](https://user-images.githubusercontent.com/4165523/43218321-12c321fe-9012-11e8-9d2e-c666d5677282.png)

*left: reclassified; right: Shippensburg 2050 baseline (zoomed out to show matching extents)*

![screen shot 2018-07-25 at 1 21 42 pm](https://user-images.githubusercontent.com/4165523/43218347-2437fd1a-9012-11e8-8e27-93de1d86cc96.png)

**Comment by kellyi** [comment]
Also for future reference: I used this Python script to get the bbox of the Shippensburg source geotiff for using to crop & mask the NLCD RDD data before reclassifying and tiling:

```
import json
import rasterio
import rasterio.features
import rasterio.warp

with rasterio.open("shippensburg.tif") as dataset:
    mask = dataset.dataset_mask()

    for geom, val in rasterio.features.shapes(
            mask, transform=dataset.transform):
        geom = rasterio.warp.transform_geom(
            dataset.crs, 'EPSG:4326', geom, precision=6)

        print(json.dumps(geom, indent=4))
```

That's basically the Rasterio "hello world", adjusted so the output polygon was actual GeoJSON: https://rasterio.readthedocs.io/en/latest/#rasterio-access-to-geospatial-raster-data

**Comment by kellyi** [comment]
Here they are in my local MMW

![screen shot 2018-07-25 at 4 41 27 pm](https://user-images.githubusercontent.com/4165523/43226458-f2f28f50-9029-11e8-805f-fd1fdd11d452.png)

Uploading to S3 now
