### ISSUE TITLE
Fix typos for links in Contribute Data modal

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#2865]
Somehow the last sentence in the Contribute Data modal got changed to:
> Learn these protocols at http://data.envirodiy.org and https://leafpacknetwork.org.

As shown here, https://github.com/WikiWatershed/model-my-watershed/pull/2843#issuecomment-392813577, the first link was supposed to be to https://www.envirodiy.org, which has the protocols.

I think there was confusion by my comment about pointing to http://data.wikiwatershed.org, rather than http://data.envirodiy.org, or perhaps by the https issue referenced and fixed with https://github.com/WikiWatershed/model-my-watershed/issues/2851.

Please change the text back to the intended text:
> Learn these protocols at http://data.envirodiy.org and https://leafpacknetwork.org.

Similarly, the EnviroDIY logo should point to http://data.envirodiy.org

Thanks!
cc: @rajadain and @ajrobbins

**Comment by rajadain** [comment]
Hi @aufdenkampe,

In the issue description above, both quoted blocks read identical. Should the second one say https://www.envirodiy.org instead of http://data.envirodiy.org?

Here's my take away, would be great if you could confirm it:

- The Contribute button should go to http://data.envirodiy.org
- The text and the logo should go to https://www.envirodiy.org

Correct?

**Comment by rajadain** [comment]
Hi @aufdenkampe, if you could confirm the above I'll get this up on staging today.

**Comment by aufdenkampe** [comment]
@rajadain, yes! Your take is correct.
- The Contribute button should go to http://data.envirodiy.org
- The text and the logo should go to https://www.envirodiy.org

I'm sorry for adding confusion rather than clarifying.
Is there still time to fix this?

**Comment by rajadain** [comment]
I put up #2872 with the above assumption. Will get that merged soon. Thanks for confirming.

**Comment by rajadain** [comment]
Would you prefer it if the Contribute button went to http://data.wikiwatershed.org ?

**Comment by aufdenkampe** [comment]
Yes! Contribute button should point to http://data.wikiwatershed.org!
Thanks for catching all those mistakes. I guess that what happens to me when I'm multi-tasking too much!
- The Contribute button should go to http://data.wikiwatershed.org
- The text and the logo should go to https://www.envirodiy.org
