### ISSUE TITLE
Make the Download GMS Button Always Visible

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2882]
Currently, once the user proceeds to add modifications to an area with the Multi Year model, their ability to download a gms file for current conditions goes away:

![screen shot 2018-07-09 at 12 17 36 pm](https://user-images.githubusercontent.com/12868342/42463026-f911678a-8372-11e8-8012-633c88899fed.png)

Add a similar "..." control next to Current Conditions in the scenario dropdown with only the "export GMS" option in it, and enable GMS download.

**Comment by rajadain** [comment]
Instead of the above, make it so the "Download GMS" button is always available in the top bar, as it is for Current Conditions before new scenarios are added. Will have to see how that changes the positioning of the "Add New Scenario" button. Discuss with @jfrankl.
