### ISSUE TITLE
Resolve HydroShare Export timeout

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#2885]
@darscott and I have both experienced issues exporting MMW projects to HydroShare.

For example, when I export this project, https://app.wikiwatershed.org/project/24728/, I get this response after waiting quite a while for the ball to spin:

![screen shot 2018-07-10 at 3 49 19 pm](https://user-images.githubusercontent.com/5166036/42536858-d9eb841c-8458-11e8-949e-e3024ef47287.png)

I followed the suggestion of @rajadain to try multiple times, but I just got multiple new resources on HydroShare:

![screen shot 2018-07-10 at 3 50 29 pm](https://user-images.githubusercontent.com/5166036/42536942-1af8264a-8459-11e8-99a8-eda639c9f4ec.png)

Each resource has .csv files for Analyze and Model outputs, plus the AoI geoJSON. However, I also don't see a GMS file.

@dtarb, @rayi113 and @horsburgh, Could there have been a change on HydroShare?

**Comment by sblack-usu** [comment]
Assuming the first project uploaded to hydroshare is missing the GSM file and timed out like the others, I don't believe we can blame this on the release downtime (The first one happened on July 6th, the others on July 10th).

If someone can give me the call to hydroshare that is made by model my watershed, then I can help troubleshoot.  It'd also be helpful to get a copy of the file set to be uploaded to a resource.

**Comment by aufdenkampe** [comment]
Is this on staging yet?
@darscott and I were presenting MMW today for the DRWI and this issue cropped up again when we tested it on staging. It seems that Beta.HydroShare.org is up, so that's not the issue.

**Comment by rajadain** [comment]
Hi @aufdenkampe,

After coming back, beta.hydroshare.org may have returned as a new clone of production. In which case, any existing OAuth permissions saved with MMW have expired, leading to the issues above. They can be solved by going to your account, unlinking and relinking to HydroShare, and then exporting the projects. This will not happen on production, because the production HydroShare database isn't refreshed like the beta is.

Thanks.

**Comment by aufdenkampe** [comment]
Update: it just worked for me on staging / beta. I linked and unlinked the accounts, but it still took 2 tries to complete.

**Comment by aufdenkampe** [comment]
@rajadain, thanks for explaining that a bit more clearly. It is now definitely working better now.

Another problem, that should be put in a separate issue, is that clicking on the "Open with..." "Model My Watershed" app in Hydroshare does not succeed in opening the project in Model My Watershed. I suspect this might be a problem on Hydroshare's side. 

For example:
This project https://staging.app.wikiwatershed.org/project/1371/scenario/2434
Was exported to this resource https://beta.hydroshare.org/resource/c85a2c98d7b64192910d0c008dcaa069/
Which tries to open this project https://app.wikiwatershed.org/project/via/hydroshare/c85a2c98d7b64192910d0c008dcaa069/

Is this the expected behavior?

@dtarb, we might need help from your team on this.

**Comment by aufdenkampe** [comment]
I now see why that didn't work on Staging (because the app pointed back to production), but the same was happening on Production. I can't provide examples, because I unlinked & relinked my accounts and I can't get a new MMW project to export to HydroShare.

@darscott was having similar issues (but at least some success), especially when trying to open up a project that was created & exported by another person, copied in Hydroshare, and opened by Dave. This kind of sharing functionality really needs to work seamlessly. We need to fix all this and test it carefully for the next release.

**Comment by rajadain** [comment]
Again, because the beta site had its database overwritten from production, the "Model My Watershed" resource was pointing to production. I just updated it:

![image](https://user-images.githubusercontent.com/1430060/45233268-29c3a800-b2a0-11e8-9117-dd91b1e77ef0.png)

And it should work correctly now.

**Comment by rajadain** [comment]
If you could find an example of this not working on production, I can open a new issue for that.
