### ISSUE TITLE
Modify geocoder placeholder text to clarify coordinate search

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2895]
We got feedback from Stroud that people are confused about what format of coordinates to enter in the geocoder if they want to search by lat/lon. For example, Google Maps both displays and searches by coordinates like this: 39°57'44.9"N 75°09'16.2"W, while our geocoder only accepts x,y or y,x.

Determine the best approach to surface this requirement with @jfrankl - potentially adding some placeholder text, which may necessitate resizing the geocoder element:

![screen shot 2018-07-25 at 5 04 10 pm](https://user-images.githubusercontent.com/12868342/43227446-c5da6b7a-902c-11e8-864b-e80bdcd25e7c.png)

**Comment by rajadain** [comment]
Follow up from Slack discussion @jfrankl, the approach here will be to have a tooltip that shows up after a small delay (~500ms), recommending the format, like:

> Enter coordinates as **Lat,Lng** (e.g. **32.95,-75.16**)
