### ISSUE TITLE
Reorder MultiYear model Hydrology chart dropdown list and table column order

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2903]
From Stroud:

>Order should be:
Stream Flow
Surface Runoff
Subsurface Flow
Point Source Flow
Evapotranspiration
Precipitation

That should be the order from top to bottom in dropdown, and left to right in tabular results. Current:
![screen shot 2018-08-08 at 4 59 02 pm](https://user-images.githubusercontent.com/12868342/43863989-62915cda-9b2c-11e8-9b9a-9cec44f19a98.png)

**Comment by aufdenkampe** [comment]
@darscott, does that order make sense, with runoff second after stream flow?

1. Stream Flow
2. Surface Runoff
3. Subsurface Flow
4. Point Source Flow
5. Evapotranspiration
6. Precipitation

**Comment by darscott** [comment]
sounds good. I know Barry has always called it subsurface flow, but it
would be nice to have the terms between the two models the same...any
thoughts on appropriateness of calling subsurface flow "infiltration"?
Dave

___________________________________________________________________________________

Dave B. Arscott, Ph.D. - Executive Director, Research Scientist

Stroud Water Research Center -  Avondale, PA 19311 USA
Phone: (office) 610-268-2153 x 278, (mobile) 484-885-5225

_____________________________________________________________________________________

Advancing knowledge and stewardship of fresh water through global research,
education, and restoration


Sign up for e-news <http://www.stroudcenter.org/subscribe/> about our
science, education, restoration and events.
