### ISSUE TITLE
MapShed Compare View: Add Water Quality chart

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/model-my-watershed#2910]
Per the wireframes...

<img width="578" alt="screen shot 2018-08-10 at 4 14 35 pm" src="https://user-images.githubusercontent.com/4165523/43979367-835e0f52-9cb8-11e8-9b06-8fdecefa664e.png">

... add the Water Quality Chart.

It should:
    - have two dropdowns for selecting which chart to show
    - allow using the first dropdown to select between summary and land cover tables
    - allow using the second dropdown to select row of selected table
    - have one bar chart per column (Sediment, Total Nitrogen, Total Phosphorus), which includes all scenarios color appropriately

Note:
    * Need to talk to Matt / Client to confirm dropdowns

**Comment by rajadain** [comment]
May also need to talk to someone to figure out how subbasin fits into this.
