### ISSUE TITLE
MapShed Compare: Pick Scenario Colors

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2912]
Pick a set of colors to be used for scenarios in the MapShed Compare View. This can be a static list, of at least 15 colors. These will be used to differentiate scenarios in the Compare View:

<img width="568" alt="screen shot 2018-08-10 at 4 12 37 pm" src="https://user-images.githubusercontent.com/4165523/43979285-3b4fa5cc-9cb8-11e8-8179-a63b7743fd19.png">

Work with @jfrankl on this.

**Comment by rajadain** [comment]
Relatedly, found [this great blog post](https://blog.graphiq.com/finding-the-right-color-palettes-for-data-visualizations-fcd4e707a283) for picking colors for visualizations.

If we need to go with a different scheme, I recommend picking some from the [Material Color tool](https://material.io/tools/color/).

I also took a look at [ColorBrewer2](http://colorbrewer2.org/), but that only supported schemes up to 9 categories, and we needed more than that.

**Comment by jfrankl** [comment]
@rajadain those colors look good to me. Interested in how they look in the actual application.

**Comment by rajadain** [comment]
Screenshots from Staging:

![image](https://user-images.githubusercontent.com/1430060/44588120-dec77200-a782-11e8-91fd-9f96bbe58e11.png)

![image](https://user-images.githubusercontent.com/1430060/44588127-e6871680-a782-11e8-8586-3e913e849c5e.png)

You can take a look here: https://staging.app.wikiwatershed.org/project/1366/

**Comment by rajadain** [comment]
If you find any design issues that need fixing, please add them here: https://github.com/WikiWatershed/model-my-watershed/issues/2929
