### ISSUE TITLE
Fix Worker VM Failure in Jenkins

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2919]
The `worker` VM issues started happening after #2902 was merged. None of that seems like it would affect `vboxsf` or file mounting of any sort. Currently we’ve been destroying and rebuilding the `worker` on every build. May have to look for a more permanent solution.

http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-pull-requests/3863/console
http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-pull-requests/3862/console

http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-develop/1035/console

```
==> worker: Mounting shared folders...
    worker: /opt/app => /var/lib/jenkins/workspace/model-my-watershed-pull-requests/src/mmw
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 opt_app_ /opt/app

The error output from the command was:

: No such device
+ exitCode=1
+ set -e
+ [[ 1 == 0 ]]
+ echo ''

+ echo 'Failure detected; waiting 20 seconds...'
Failure detected; waiting 20 seconds...
+ echo ''

+ sleep 20
+ attempt=3
+ timeout=40
+ [[ 3 < 3 ]]
+ [[ 1 != 0 ]]
+ echo 'Vagrant has failed the provisioning process 3 times.'
Vagrant has failed the provisioning process 3 times.
+ echo 'Please inspect the failures manually and retry the build.'
Please inspect the failures manually and retry the build.
+ return 1
Build step 'Execute shell' marked build as failure
```

**Comment by hectcastro** [comment]
The following builds all completed successfully after upgrading Vagrant (2.1.2) on CivicCI:

- http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-pull-requests/3867/
- http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-pull-requests/3866/
- http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-pull-requests/3865/
- http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-develop/1037/
- http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-develop/1038/
