### ISSUE TITLE
MapShed Compare: Design Pass

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2929]
Once the functionality is mostly implemented, do a design review and iron out any final issues.

Also use this card to collect design issues as they are seen.

## Issues

- [x] Remove download button from top right. It can be brought back in #2911 if necessary
- [x] Left align scenario names

**Comment by kellyi** [comment]
- [ ] Water Quality chart data y value tick marks are sometimes long enough to occlude the y-axis label:

![screen shot 2018-08-27 at 4 03 01 pm](https://user-images.githubusercontent.com/4165523/44682954-d08f8500-aa12-11e8-9b19-e9798e894ec9.png)

**Comment by rajadain** [comment]
- [ ] Make the active tab bottom line touch the border for TR-55:

![image](https://user-images.githubusercontent.com/1430060/44736945-a5626f80-aabe-11e8-9e26-7ddefe581e54.png)

- [ ] Add units (in parens) to the y-axis label for Water Quality Charts, as done for all other charts:

![image](https://user-images.githubusercontent.com/1430060/44737014-d93d9500-aabe-11e8-81b6-075088a4d932.png)
