### ISSUE TITLE
Rebranding back to Model My Watershed; update to new logos

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#3011]
@darscott reminded me yesterday of another priority issue for this upcoming release, which comes from recent and final branding decisions by the WikiWatershed Outreach Team (see [2017-2019_Wikiwatershed_OutreachNotes-Cumulative](https://docs.google.com/document/d/14ZOGs80rQehmbMMJsx2cIpc29UEox7nNwFPn2xc0tzk/edit#) Google Doc) after a several month process mentioned in https://github.com/WikiWatershed/model-my-watershed/issues/2741#issuecomment-380243646. We just implemented this rebranding at https://wikiwatershed.org if you want to take a look.

We therefore need to:
- Rebrand https://app.wikiwatershed.org to "Model My Watershed", 
- by replacing the "WikiWatershed" logo that always appears in the upper left with the new "Model My Watershed" logo available in the  [WikiWatershed Branding Identity](https://drive.google.com/drive/folders/1MiPT4DBrtUaFxUiTf3CRYNVBl0X_pj0U?usp=sharing) Google Drive folder and its sub-folders.

@chitchens & @rajadain, please contact @HeatherBrooks if you need any additional information regarding the logos or branding.

**Comment by mmcfarland** [comment]
We should update the favicon as well, as it's represented on the main wikiwatershed site

![screenshot 2018-11-01 at 2 46 46 pm](https://user-images.githubusercontent.com/1014341/47872534-33234980-dde5-11e8-9d50-85a50fb0de51.png)

**Comment by darscott** [comment]
We also have an image file that is just the wave feature if needed...
https://drive.google.com/open?id=1bnTDcJGvXEko665Mcnbab73OYTi_Vyj7
