### ISSUE TITLE
Finalize WQP text fields

### ISSUE THREAD

**Issue by aufdenkampe** [WikiWatershed/model-my-watershed#3012]
As suggested by @emiliom, these tasks remain to finalize text fields for the Monitor search results for the Water Quality Portal (WQP):

- [ ] @aufdenkampe will review the mapping of metadata to the WQP results list and details pages, and suggest edits.
- [ ] Replace placeholder text for "Citation" in the record details page:
  - from "We thank the water quality portal."
  - to this template, where bold text is generated from fetching today's date:
    - National Water Quality Monitoring Council, **2016**. Water Quality Portal. **Accessed 23 August 2016**. http://www.waterqualitydata.us/ 

cc: @chitchens & @rajadain

**Comment by emiliom** [comment]
Thanks @aufdenkampe. Regarding this citation template:

> National Water Quality Monitoring Council, 2016. Water Quality Portal. Accessed 23 August 2016. http://www.waterqualitydata.us/

Just wanted to add that for USGS NWIS results from CUAHSI WDC, currently we use a template that doesn't take the extra step of filling in "today's" year and date of access; instead, it uses static placeholders:

> U.S. Geological Survey, [YEAR], National Water Information System data, accessed [DATE ACCESSED] via HIS Central (http://hiscentral.cuahsi.org)

I believe that comes straight from the CUAHSI WDC, as is. So, my 2 cents: if it saves significant dev time, I think we can do exactly the same thing, using static placeholders.

**Comment by rajadain** [comment]
Shares points with #2918

**Comment by rajadain** [comment]
In accordance with the instructions above, I'll replace the details text with:

> National Water Quality Monitoring Council, [YEAR]. Water Quality Portal. Accessed [DATE ACCESSED]. http://www.waterqualitydata.us
