### ISSUE TITLE
Fix Worker VM Issues

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3026]
On macOS Mojave, the VM does not boot after shutting down. It must always be destroyed and rebuilt, which takes a long time. All other VMs behave correctly.

Figure out how to get it to the point where it loads correctly.

**Comment by rbreslow** [comment]
Information from Terence's workstation:

```bash
$ vboxmanage --version
5.2.22r126460
```

```bash
$ vagrant --version
Vagrant 2.2.0
```

```bash
$ ansible --version
ansible 2.7.2
  config file = /Users/ttuhinanshu/dev/bees/ansible.cfg
  configured module search path = ['/Users/ttuhinanshu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov  6 2018, 18:46:03) [Clang 10.0.0 (clang-1000.11.45.5)]
```

>When I try to turn it on, it freezes on the “updating Vagrant Guest Additions” step. That happens because I have the vagrant vbguest plugin installed. If I uninstall it, it freezes on mounting the folders from my local.
>This does not happen the very first time I create a VM, but if I halt and start it
>This does not happen on #bees (which is a fork of #mmw from long ago) or on any of the other VMs in #mmw

I was getting this:

![image](https://user-images.githubusercontent.com/1774125/49162255-7b585d80-f2f8-11e8-9c93-d7286d78a908.png)

Terrence said:

>Correct! That’s what I used to get (many months, perhaps years ago). Then I found this plugin: https://github.com/dotless-de/vagrant-vbguest which automatically upgrades the VirtualBox Guest Additions of a VM if it is outdated, and for a long time that worked. Then I upgraded to Mojave and now it crashes at the Guest Additions update stage
>When I uninstalled that plugin I got the same error as above

**Comment by rajadain** [comment]
This is the stage I get to on my machine, which has the `vagrant-vbguest` plugin installed that tries to upgrade the VirtualBox Guest Additions:

![image](https://user-images.githubusercontent.com/1430060/49164834-ec4e4400-f2fd-11e8-8d7e-1b993fdb47b3.png)

At this point, it just stalls forever, and there is no CPU or RAM usage in the VM. This used to work before Mojave.

**Comment by rbreslow** [comment]
I don't think this is related to Mojave. I am experiencing the same issues on High Sierra.

I was able to make some progress. If you do `CTL + C` to get back to your host OS while it's stuck on `VirtualBox Guest Additions: Starting.`, and then run `$ vagrant reload`, then `up` and `halt` work as they should.

**Comment by caseycesari** [comment]
I ran into this issue again this morning, and tried the above workaround. However, it didn't work for me. I basically got into a loop of `vagrant up`, `ctrl + c`, `vagrant reload`, `ctrl+c`, etc. It seems to get stuck in the same place on both `reload` and `up`. I'm on Mojave.

**Comment by rbreslow** [comment]
Roger that @caseycesari. I'm going to continue looking into this.

**Comment by rbreslow** [comment]
I think we're experiencing an issue related to https://github.com/hashicorp/vagrant/issues/1657#issuecomment-20589841. 

>This is usually a result of the guest’s package manager upgrading the kernel without rebuilding the VirtualBox Guest Additions

This seems to work:

On the host OS, run:

```bash
$ vagrant plugin uninstall vagrant-vbguest
```

Within the VM:

```bash
vagrant@worker:~$ sudo apt-get purge virtualbox*
vagrant@worker:~$ sudo apt-get install linux-generic linux-image-generic linux-headers-generic linux-signed-generic
vagrant@worker:~$ sudo apt-get install virtualbox-guest-utils virtualbox-guest-x11 virtualbox-guest-dkms
```

Then, on the host OS, run:

```bash
$ vagrant halt worker; vagrant up worker
==> worker: Attempting graceful shutdown of VM...

Bringing machine 'worker' up with 'virtualbox' provider...
==> worker: Checking if box 'ubuntu/trusty64' is up to date...
==> worker: Clearing any previously set forwarded ports...
==> worker: Clearing any previously set network interfaces...
==> worker: Preparing network interfaces based on configuration...
    worker: Adapter 1: nat
    worker: Adapter 2: hostonly
==> worker: Forwarding ports...
    worker: 2375 (guest) => 2375 (host) (adapter 1)
    worker: 8090 (guest) => 8090 (host) (adapter 1)
    worker: 22 (guest) => 2222 (host) (adapter 1)
==> worker: Running 'pre-boot' VM customizations...
==> worker: Booting VM...
==> worker: Waiting for machine to boot. This may take a few minutes...
    worker: SSH address: 127.0.0.1:2222
    worker: SSH username: vagrant
    worker: SSH auth method: private key
==> worker: Machine booted and ready!
==> worker: Checking for guest additions in VM...
    worker: The guest additions on this VM do not match the installed version of
    worker: VirtualBox! In most cases this is fine, but in rare cases it can
    worker: prevent things such as shared folders from working properly. If you see
    worker: shared folder errors, please make sure the guest additions within the
    worker: virtual machine match the version of VirtualBox you have installed on
    worker: your host and reload your VM.
    worker:
    worker: Guest Additions Version: 4.3.36
    worker: VirtualBox Version: 5.2
==> worker: Setting hostname...
==> worker: Configuring and enabling network interfaces...
==> worker: Mounting shared folders...
    worker: /opt/app => /Users/rbreslow/Projects/model-my-watershed/src/mmw
    worker: /vagrant => /Users/rbreslow/Projects/model-my-watershed
    worker: /var/lib/mmw/.aws => /Users/rbreslow/.aws
==> worker: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> worker: flag to force provisioning. Provisioners marked to run always will still run.
==> worker: Running provisioner: shell...
    worker: Running: inline script
```

**Comment by rajadain** [comment]
That seems to have worked! Great find!

Is there any way this can be recorded so it is easily used? Not sure if an ansible command or a script or something else is the best thing, since this only happens in certain environments.

And while this does work, I still don't understand why we don't see the same issue in `app` or `tiler`.
