### ISSUE TITLE
Use cached area of interest when running model

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#303]
Instead of sending the area of interest (which can be big) as part of the post data when starting a TR55 job, just send the ID of the area of interest which is stored in the database. 

This will require storing drawn area of interests in the DB, and allowing guests to save drawn areas of interest, which each probably merit being solved in separate issues/PRs.

**Comment by caseypt** [comment]
Have you run into problems with this when working on #200?

**Comment by lewfish** [comment]
I'm not sure if it's a problem yet, but we suspect it will be.

**Comment by lewfish** [comment]
It takes about one second for the POST to start_tr55 when sending over one of the congressional districts.

**Comment by mmcfarland** [comment]
Implemented based on #1484
