### ISSUE TITLE
Add ToS, Policy Info

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3038]
From @aufdenkampe:

> The long-requested [Terms of Use](https://docs.google.com/document/d/1wU9sTJBXeFA-_haRFt_pZnkbGTIEOHMrab6flrrF2UI/edit) are ready to be added, along with the [Privacy Policy](https://docs.google.com/document/d/1Cof0xLH7kuld4v8y3zE2HErxm3Jov5BvuFED4yAPWRs/edit), and the [Cookie Policy](https://docs.google.com/document/d/1KOdYGH8KHoK9U9JlkqQ3BZ8hQ99upeAv4lsczcgqTt8/edit) if they are setting cookies. 
> 
> The Terms of Use should be accepted on the registration page. And maybe all three can be linked into the "About" modal?

The current Register Modal looks like this:

![image](https://user-images.githubusercontent.com/1430060/49244601-2ee74d80-f3de-11e8-93ea-55369df97cff.png)

and the About modal looks like this:

![image](https://user-images.githubusercontent.com/1430060/49244631-3e669680-f3de-11e8-8035-821b1d50f277.png)

Figure out where to add these items, and then add them to the site.

**Comment by HeatherBrooks** [comment]
Unfortunately, the email address at the very end of the Privacy Policy needs to be changed from privacy@modelmywatershed.org to webmaster@stroudcenter.org. With the DNS changes I no longer have email forwarding set up with our domain registrar.

**Comment by rajadain** [comment]
Thanks @HeatherBrooks, I'll make that change.

**Comment by rajadain** [comment]
Also, should this link: https://modelmywatershed.org/dmca/ be changed to https://wikiwatershed.org/dmca/?

**Comment by HeatherBrooks** [comment]
Sorry, looks like we didn't mention the DMCA policy in the email excerpt at the beginning of this thread. It can be found on [Google Drive](https://docs.google.com/document/d/1ExTwDwEnWgpbkdh1BFFWFNdydo86UmbmiFUoI4JoyDc/edit#) and should be added to modelmywatershed.org in the same manner as the other policies, and linked into the Terms of Use.
