### ISSUE TITLE
Upgrade to Postgres 9.6

### ISSUE THREAD

**Issue by jeancochrane** [WikiWatershed/model-my-watershed#3044]
In order to support PostGIS 2.2 on RDS, we'll need to bump Postgres to 9.5.

See:

- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html
- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html

Connects #3031.

**Comment by rajadain** [comment]
Remember to remove deprecated functionality after the upgrade #3049
