### ISSUE TITLE
Cannot Analyze Schuylkill HUC-8

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3058]
![image](https://user-images.githubusercontent.com/1430060/50109497-ffba4400-0205-11e9-9af5-ab542477cfbb.png)

Something may be up with unit conversions.

**Comment by mmcfarland** [comment]
Prior to the unit scheme, the Schuylkill HUC-8 comparison was:
```
> area
12388.307404707883
> MAX_AREA
75000
```
then on `release`
```
> area
12388307404.707882
> maxArea
7500000000
```
in

https://github.com/WikiWatershed/model-my-watershed/blob/6a6a8bbe2ca854cd1272b12542e6297e46017766/src/mmw/js/src/draw/utils.js#L183-L187
