### ISSUE TITLE
Syncing hydroshare project fails

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#3066]
On modelmywatershed.org I created a new Multi-Year project, synced my account with Hydroshare and attempted to export the project.  The export failed with the following error.  Notably, it looks like it's attempting to sync with the beta Hydroshare site and not the production one.  The account I synced with was the production HS site.

![screenshot from 2018-12-26 11 13 24](https://user-images.githubusercontent.com/1014341/50451039-899d9780-08ff-11e9-81d4-c468584dc346.png)

**Comment by rajadain** [comment]
Fixed in #3070.
