### ISSUE TITLE
Migrate to a non-Azavea Rollbar account

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#3074]
Currently, MMW is a tenant of the Azavea Rollbar account. It would be preferred if there was a WikiWatershed specific Rollbar account with MMW as a project.

**Comment by jeancochrane** [comment]
I set up the new Rollbar account as `WikiWatershed` and copied over all of the settings from the existing project in the `Azavea` org. Once the account was set up, I updated the tokens on the Fileshare and in Jenkins.

## Notes

* I used my own GitHub/Slack tokens to set up those integrations, so I updated https://github.com/azavea/operations/issues/285 to make sure we remember to change those soon.
* The only remaining step is to set up billing for the account. We have 14 days until the free trial runs out.

## Testing instructions

* Grab the Rollbar token from the `default.yml` file on the Fileshare 
* Run a Django shell:

```console
# Run this on the host
$ /scripts/manage.sh shell
```

* Test the Rollbar access token:

```python
import rollbar
rollbar.init(access_token, os.environ['MMW_STACK_TYPE'])
rollbar.report_message('Testing access token for new Rollbar account.')
```

* Log into the new Rollbar account at https://rollbar.com/WikiWatershed/ModelMyWatershed/ and make sure your message shows up as an Event

**Comment by hectcastro** [comment]
I was able update the Slack and GitHub integrations with Rollbar. I also updated the account tier to `Free`. 👍 

cc: @rajadain @mmcfarland so that you're aware that we are swapping the underlying Rollbar account to disassociate MMW from the core Azavea Rollbar account.

**Comment by rajadain** [comment]
I like that issues created by previous Rollbar account (e.g. #3073) still have their details accessible.

**Comment by jeancochrane** [comment]
Remote credentials are updated, so this change should get swapped in on the next deployment.
