### ISSUE TITLE
Upgrade Ubuntu operating system in development

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3075]
`ubuntu/trusty64` is out of date, has trouble with SNI validation at times.

**Comment by hectcastro** [comment]
We should increase the scope of this issue to account for upgrading the Ubuntu operating system across all environments (development, staging, and production).

**Comment by hectcastro** [comment]
- [ ] Upgrading the basebox to a Bento based basebox
- [ ] Remove ELK stack components
- [ ] Open issues for logical tasks that come out of the upgrade process.
