### ISSUE TITLE
Model timing out even on small areas of interest

### ISSUE THREAD

**Issue by HeatherBrooks** [WikiWatershed/model-my-watershed#3084]
Reports have been coming in for several days:
- February 15: "I have tried analyzing my school's data at Wilson High School and the middle school's several times and keep getting an error that's says "operation took too long, considering trying a smaller area. I have tried areas that include our whole school district as well as our school property and gone down to small sections of a stream that are only 40,000 square meters and it gives me the same error."
- February 16: "The application for Model My Watershed does not appear to be working. I have tried several times to model and analyze a small catchment area, and the process times out. Error message: Operation took too long Consider trying a smaller area of interest. This happens no matter what size catchment I try. I have several saved projects and cannot access the information under the 'Analyze' tab."
- February 18: replicated by Charlie Dow at Stroud Center, "I was able replicate the issue; tried several different methods of defining an area - freehand drawing, selecting various boundaries (from school district up to HUC10); attempted in the Wilson High School area (Reading PA area) as well as in the White Clay Creek area; same results everywhere - operation times out. I did try to work with an existing project; was able to open it, create a new scenario, but when going to 'Compare', operation timed out again - same message "Operation took too long, Consider trying a smaller area of interest.
![image](https://user-images.githubusercontent.com/9368629/52963004-ab9a2000-336c-11e9-8d5f-12e1011ee4fd.png)

@aufdenkampe @darscott

**Comment by rajadain** [comment]
Hi Heather, this has been fixed on production for now. We're working on a preventative measure in #3085 which should be deployed soon, hopefully preventing these issues from happening in the future.

**Comment by HeatherBrooks** [comment]
Looks great, thanks!

**Comment by rajadain** [comment]
Thanks for confirming.
