### ISSUE TITLE
Upgrade NumPy based on GWLF-E and Ulmo dependencies

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#3093]
As part of https://github.com/WikiWatershed/model-my-watershed/pull/3090, we navigated around transitive dependency installation issues by pushing NumPy installation into Ansible vs. `requirements.txt`.

This issue is to undo that, while upgrading NumPy to a current version that works with the GWLE-E and Ulmo libraries.

**Comment by rajadain** [comment]
Blocked until we have the green light from @dboyer that this can be worked on within the NSF contract.

**Comment by dboyer** [comment]
Unblocked as work has been approved.

**Comment by rajadain** [comment]
@caseycesari we can use the **Testing Instructions** of #3090 to test the NumPy upgrade as part of this card. We don't use Ulmo in a manner that does any math, we just use it to query data from 3rd party APIs, so no need to test that functionality. The [celery-segfault.zip](https://github.com/WikiWatershed/model-my-watershed/files/2894563/celery-segfault.zip) file has a test script and an expected value which can be used to test new values.

Let me know if you have any further questions.
