### ISSUE TITLE
Draw tools still visible after selecting area

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#314]
To reproduce:

 * Go to [http://localhost:8000/analyze](http://localhost:8000/analyze) or [http://localhost:8000/model](http://localhost:8000/model)
 * You will be redirected to the home view [http://localhost:8000/](http://localhost:8000/)
 * Draw an area using "Draw". You will be moved forward to the analyze view.

Observed behavior:

 * Draw tools are still visible. Selecting a new area using these tools does not update the analyze panel:

![image](https://cloud.githubusercontent.com/assets/1430060/8036532/6851dc36-0dc6-11e5-9454-582a9c2c4360.png)

Expected behavior:

 * Draw tools are hidden after area is selected

Other notes:

 * This does not happen if one starts the session at the home view, only if they start at the analyze or model view and then are redirected to home.
 * A fix might either hide the draw tools, or add code to always update the analyze view whenever new area is drawn, whichever is more appropriate.
 * If one moves forward from analyze to model, and then comes back, if the draw tools were visible before in the analyze view they still are. If they were not visible before then they still aren't.

**Comment by mmcfarland** [comment]
Thanks for tracking this down, we'd seen it pop up occasionally during demos but not figured out the cause.
