### ISSUE TITLE
Observations Tab Isn't Loading

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3183]
![image](https://user-images.githubusercontent.com/1430060/66949922-5d394000-f025-11e9-8eec-e858c7f26687.png)

**Comment by dboyer** [comment]
From conversation with Stroud:

Based on what used to be under "observations" tab, listed here (https://wikiwatershed.org/help/model-help/mmw-tech/#overlays-tab-observations), it would be best to try to keep the EPA Permitted Point Sources (would be best if we could expose this for the entire country on this tab (perhaps limiting the viewing to some zoom scale if this is too much to view at national scale), and the USGS NWIS sites. We should talk about also making that layer available nationwide, as there are REST services available...https://waterservices.usgs.gov/rest/. I think we can let the NOAA and DEOS site go at this point.

**Comment by rajadain** [comment]
There's two datasets that are already in the database:

`ms_pointsource`:

![image](https://user-images.githubusercontent.com/1430060/71929747-50317600-3168-11ea-96ce-b314a695af5f.png)
![image](https://user-images.githubusercontent.com/1430060/71929988-c7ffa080-3168-11ea-9d9c-94a04a7f0a22.png)

There is a further set, `ms_pointsource_drb`, which has more detail for the Delaware River Basin:

![image](https://user-images.githubusercontent.com/1430060/71930071-eb2a5000-3168-11ea-87f3-57594aaa9356.png)
![image](https://user-images.githubusercontent.com/1430060/71930099-f7aea880-3168-11ea-94e4-5033df16dc52.png)

The available metadata is this:

```sql
SELECT * FROM ms_pointsource LIMIT 5;

 ogc_fid |                        geom                        | npdes_id  |     city     | state |  latitude  |  longitude   |   huc_12_cod    | avg_n_conc |   lbsn_yr   |  mgd   | avgpconc  |     lbsp_yr     |  kgn_yr  | kgp_yr 
---------+----------------------------------------------------+-----------+--------------+-------+------------+--------------+-----------------+------------+-------------+--------+-----------+-----------------+----------+--------
   23070 | 0101000020E610000015C5ABAC6D1454C038A0A52BD8A24340 | WV0005363 | CLARKSBURG   | WV    | 39.2722220 |  -80.3191940 |  50200020204.00 |       21.6 | 50005660.00 | 1100.0 |           |                 | 22702570 |       
   23071 | 0101000020E6100000C425C79DD2D358C06EA6423C12ED4340 | KS0100749 | PHILLIPSBURG | KS    | 39.8521190 |  -99.3097300 |                 |       90.1 | 17474523.00 |   19.2 | 0.0180000 |    1953.0000000 |  7933433 |    887
   23072 | 0101000020E6100000ACADD85F76F155C03E5C72DC29E94440 | IL0028053 | CICERO       | IL    | 41.8215900 |  -87.7728500 |  71200040705.00 |        7.8 | 15774767.00 |  680.0 | 0.9300000 | 1879062.0000000 |  7161744 | 853094
   23073 | 0101000020E6100000E50B5A48C04F5DC0A9DA6E826F564040 | CA0107409 | SAN DIEGO    | CA    | 32.6752780 | -117.2461110 | 181000000000.00 |       37.4 | 14942084.00 |  131.0 |           |                 |  6783706 |       
   23074 | 0101000020E61000004D4BAC8C469857C08FC2F5285C934240 | MO0002402 | CARTHAGE     | MO    | 37.1512500 |  -94.3793060 | 111000000000.00 |       93.0 | 10453958.00 |   11.8 |           |                 |  4746097 |       
```

These can somewhat readily be added to the front-end.

Getting the USGS NWIS sites may take further investigation. There is currently a step in Monitor that pulls those dots on demand:

![image](https://user-images.githubusercontent.com/1430060/71930461-b36fd800-3169-11ea-989e-0a673ad24119.png)

However, these are numerous and limited to small shapes. Furthermore, figuring out how to use these as a Leaflet layer may take some work, as the REST API they are fetched from is designed for data, not a tile layer,  requests.

**Comment by rajadain** [comment]
Made #3227 for adding a layer for EPA Point Sources.

**Comment by rajadain** [comment]
The Observations Tab now only shows Weather Stations, which do load correctly:

![image](https://user-images.githubusercontent.com/1430060/83055228-9147fb00-a021-11ea-92ae-f9e9725b54bd.png)
