### ISSUE TITLE
Site Storm Model: Unable to view all modifications on a project with a very large number of modifications

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#3198]
There's no scroll in the modifications drop down, so once the number of modifications exceeds the screen length they become un-viewable.

![image](https://user-images.githubusercontent.com/5374350/68241030-f41d6a80-ffdb-11e9-9cb1-18b46df3cdc3.png)

**Comment by rajadain** [comment]
This was fixed in #3232 and is now available on production.

**Comment by SRGDamia1** [comment]
Thank you!
