### ISSUE TITLE
Add Front-end for Analyzing Protected Areas

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3203]
Add Protected Areas to the front-end, within the Land tab. Waiting on @designmatty to provide a design on how to handle that. There will likely be some sort of drop-down. Also add the "Related Layer" link to turn on Protected Areas. Use the table in #2951 to relate raster values to names of categories.

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/1430060/68496700-ee649680-0220-11ea-9951-cde37505c83c.png">

**Comment by rajadain** [comment]
If adding a chart, use this legend: https://github.com/WikiWatershed/model-my-watershed/issues/2950#issuecomment-418813271

**Comment by designmatty** [comment]
Abstract link: https://share.goabstract.com/c89fd997-2405-4f74-a6e7-90c2c48339be?collectionLayerId=87b7a2de-1136-40ad-b0c1-994efc55d00b&mode=design

**Comment by rajadain** [comment]
I have a working version with an extra tab row:

![image](https://user-images.githubusercontent.com/1430060/72287297-c45e9480-3614-11ea-96f8-b6c7bf4d9636.png)

This is the simplest implementation, and doing one where we override the Land tab requires either changing the established public API on the back-end (which we are discouraged to do), or refactoring the front-end to not have one-tab-one-endpoint relationship it currently does, which is also non-trivial.

Given the above constraints, I wonder if we should take a quick shot at seeing how best to manage the tab-overflow, and if we have a simple enough implementation that may be preferable. Else, we'll fall back to the front-end refactor to one-tab-many-endpoints.

**Comment by rajadain** [comment]
The above work is in the [`tt/protected-lands-analyze-backend-2`](https://github.com/WikiWatershed/model-my-watershed/tree/tt/protected-lands-analyze-backend-2) branch. /cc @lossyrob

**Comment by lossyrob** [comment]
@rajadain will protected lands have to be disabled for BiG-CZ?

This issue restricted the tabs that are available: https://github.com/WikiWatershed/model-my-watershed/issues/1978

For the decoupling, we could do this restriction on a per-tab or per-task basis. 

If per-tab, then protected_lands would be available as part of the Lands tab.

**Comment by rajadain** [comment]
The Protected Lands visual layer is not available in BiG-CZ, as evidenced by the absence of the `big_cz: true` key in the layer definition:

https://github.com/WikiWatershed/model-my-watershed/blob/780eddae7a695f4e38f0e6eb0ba21ec1bcf7ed10/src/mmw/mmw/settings/layer_settings.py#L209-L234

Thus, we shouldn't have the Protected Lands analysis available there either. Looks like we'll need per-task decoupling.
