### ISSUE TITLE
Switch to MapBox Static Tiles API for basemap

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#3204]
Documentation: https://docs.mapbox.com/help/glossary/static-tiles-api/

Sample code: https://codepen.io/ccazavea/full/XWWypPz

**Comment by designmatty** [comment]
@rajadain could you take a look at my adapted [MapBox Studio Style](https://api.mapbox.com/styles/v1/mwilliamsazavea/ck41mg8zu1dcx1cnwxbng7ifl.html?fresh=true&title=view&access_token=pk.eyJ1IjoibXdpbGxpYW1zYXphdmVhIiwiYSI6ImNpZ21oMmMzZzAyMmV1bmx6a20zbjllOHMifQ.JsUVaCRdxK16APj3-M1xDQ#3.1/40.612372/-90.943141/0). Let me know what you think. It's not a perfect one to one representation but it's fairly close.

If you don't have any changes, I'll copy the styles over to the Stroudcenter mapbox account.

**Comment by rajadain** [comment]
The new styles have really tiny labels, can we make them bigger? Also, the default zoom seems to be different. Haven't changed anything on the Leaflet end.

Before:

![image](https://user-images.githubusercontent.com/1430060/70650853-d87e3300-1c1d-11ea-84f3-db302c1d1c2d.png)

After:

![image](https://user-images.githubusercontent.com/1430060/70650866-dd42e700-1c1d-11ea-98df-1be2c5698d3d.png)

The labels remain tiny regardless of zoom level:

![2019-12-11 13 55 27](https://user-images.githubusercontent.com/1430060/70650920-f64b9800-1c1d-11ea-837b-7008d6a88b41.gif)

**Comment by rajadain** [comment]
Once the styles were transferred to the `stroudcenter` Mapbox account, I had to go in to the Share and Develop dialog and get CARTO style URL to work with Leaflet:

![image](https://user-images.githubusercontent.com/1430060/70652164-2136eb80-1c20-11ea-8e38-080cd7274464.png)

**Comment by rajadain** [comment]
It's much closer now:

![2019-12-11 14 12 20](https://user-images.githubusercontent.com/1430060/70652266-54797a80-1c20-11ea-91d0-25de0476c3b6.gif)

The one missing piece is state boundaries. How difficult do you think it would be to add those?

**Comment by designmatty** [comment]
That's a small tweak. The data is there but gets hidden at that zoom level. I'll fix it.

**Comment by designmatty** [comment]
Okay, I lied about that being a small tweak. The admin (state) boundaries are there, however, mapbox no longer displays boundaries in the middle of water. So if a river splits the boundary between two states (PA/NJ) there will be no state line. The line will only display if the states are connected via land.

**Comment by rajadain** [comment]
Ah interesting. Well, I think we can live with that for now. Thanks for looking in to it.
