### ISSUE TITLE
Cleanup Model tools

### ISSUE THREAD

**Issue by ctaylo37** [WikiWatershed/model-my-watershed#321]
![image](https://cloud.githubusercontent.com/assets/5880793/8043513/a154c06a-0df4-11e5-8c6f-fefc2776517f.png)

**Comment by kdeloach** [comment]
Here's what it looks like presently. I'm updating the slider to match the wireframes as best as I can right now.
![image](https://cloud.githubusercontent.com/assets/43062/8043940/3b885b54-0df7-11e5-983e-581598c6076c.png)
