### ISSUE TITLE
Investigate Significantly Increased Mapbox Charges

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3246]
Despite the basemap upgrade, our MapBox billing has gone up significantly. When reaching out to MapBox support, they responded:

> Thanks for writing in. I see what you're saying with your most [recent invoice](https://account.mapbox.com/invoices/1580242027/). The increase in price here was due to our new pricing model. There are a few things that you might be able to do on your end to change your mapping implementation to 1) be faster and more performant and 2) be more cost effective for you. 
> 
> Before diving in, I added a 3-month 100% off coupon to your account to give you a bit of time to update your maps if you see fit. I'm also curious to know if you've reached out to our [Community team](https://www.mapbox.com/community/)? Your watershed map is awesome and seems very aligned with types of maps our Community team supports -- especially since you're an environmental nonprofit. 
> 
> Now for some more technical details regarding your map. 
> 
> Most folks using the our tile-based Maps APIs either change their implementation to call fewer tiles (making the invoices cheaper) or consider whether or not switching to GL JS is a feasible option for their implementation. Very large interactive maps like this watershed map usually are perfect candidates for GL JS. 
> 
> The latest version of GL JS is configured with map load pricing that will come with unlimited tile requests - check out [our demo](https://docs.mapbox.com/help/interactive-tools/gl-js-usage/). If you want to opt into map load billing, upgrade all your mapping implementations to use our web renderer [GL JS](https://docs.mapbox.com/mapbox-gl-js/overview/).
> 
> **Only maps using GL JS v1.0.0 (or greater) will be billed on map loads instead of individual tile requests.**
> 
> Map loads will closely align with your current website page view metrics (you can find this using your own web analytics tool). To estimate what your invoices might be under map load billing, you can input your current page load metrics in the [map load pricing calculator](https://www.mapbox.com/pricing/#maploads) on our pricing page.
> 
> If you have any questions about that, check out our [pricing page](https://www.mapbox.com/pricing/) and [pricing documentation](https://docs.mapbox.com/help/account/pricing/). If you still have questions, let me know. I'm happy to help.

- [x] See if it is possible to have Map Load billing with Leaflet
- [ ] See if there are other, non-Mapbox basemaps that we could use instead, which are cheaper to use

**Comment by mmcfarland** [comment]
A quick thought on this - we didn't release to production until 1/21, so perhaps all or a majority of the billing period in question was using the old mapbox tiles. If we could request that actual bill, we might be able to evaluate the costs incurred before/after -  or even potentially from production vs staging domains (where it has been deployed since mid December).

**Comment by rajadain** [comment]
That's a good point and we should investigate, although it should be noted that the basemap upgrade was deployed on 12/18/2019 in [1.25.2](https://github.com/WikiWatershed/model-my-watershed/releases/tag/1.25.2): https://github.com/WikiWatershed/model-my-watershed/compare/1.25.1...1.25.2

**Comment by rajadain** [comment]
The [most recent invoice}(https://account.mapbox.com/invoices/1580242027) is for the period of 12/28/2019–1/27/2020, and mentions 633,277 static tile requests. This is consistent with [tile request statistics](https://account.mapbox.com/statistics/?from=12-28-2019&to=01-27-2020) for the same period:

![image](https://user-images.githubusercontent.com/1430060/73481325-9e9df300-4369-11ea-9f22-ede41423c5b5.png)

Looking at requests from [November to January](https://account.mapbox.com/statistics/?from=11-01-2019&to=01-27-2020), we see that over the course of the last month we switched from previously using Raster Tiles API to the newer Static Tiles API:

![image](https://user-images.githubusercontent.com/1430060/73481536-05231100-436a-11ea-938d-fbd32a518c0e.png)

However, looking at [the pricing page](https://www.mapbox.com/pricing/), it looks like Raster Tiles API actually costs less than Static Tiles:

![image](https://user-images.githubusercontent.com/1430060/73481638-38fe3680-436a-11ea-8114-21459c559b58.png)

So we may have moved to a more expensive API.

I'd like a second set of eyes to confirm this, and if so, by switching back we should be on the more affordable tier again.

**Comment by rajadain** [comment]
It should be noted that the classic style basemap that we were using in the Raster Tiles API is [no longer being updated](https://docs.mapbox.com/accounts/overview/pricing/#raster-tiles-from-raster-tilesets), and will get more and more outdated with time. Mapbox is strongly pushing for upgrading to Mapbox GL JS. That will likely be a _very_ big lift, which should be planned and prioritized separately.

**Comment by rajadain** [comment]
And to answer one of the questions in the main issue:

- No, map load billing can only be done via Mapbox GL JS, not Leaflet
