### ISSUE TITLE
Globally configure nunjucks filters

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#326]
Currently all view modules import the `filters` module so that the filters are available for templates used by those views.  It appears that when templates are required, if the filter is not also required in the same module, the filter is unavailable in a way that returns `[object object]` for any or no value returned from the filter function.  It was attempted to configure the environment globally in main.js, but the initial attempt was unsuccessful.

**Comment by caseypt** [comment]
@kdeloach got this to work in #407
