### ISSUE TITLE
Custom Weather: Add Boto3, Django Storages for S3 Uploads

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3274]
After discussing with @hectcastro, the conclusion was reached that it is better to store the user-uploaded Custom Weather Data as objects on S3 rather than in the database. S3 is preferable so as not to unnecessarily complicate the database (large number of rows may have an impact on database snapshots, etc).

Add Boto3 and Django Storages, as done elsewhere, and configure it e.g.:

```python
# django-storages
if os.getenv('DJANGO_DEFAULT_FILE_STORAGE'):
    DEFAULT_FILE_STORAGE = os.getenv('DJANGO_DEFAULT_FILE_STORAGE')
    AWS_ACCESS_KEY_ID = os.getenv('DJANGO_STORAGES_AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('DJANGO_STORAGES_AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv(
        'DJANGO_STORAGES_AWS_STORAGE_BUCKET_NAME')
    AWS_DEFAULT_ACL = os.getenv('DJANGO_STORAGES_AWS_DEFAULT_ACL')
    AWS_S3_FILE_OVERWRITE = bool_getenv(
        'DJANGO_STORAGES_AWS_S3_FILE_OVERWRITE', False)
    AWS_LOCATION = os.getenv('DJANGO_STORAGES_AWS_LOCATION', '')
    AWS_S3_REGION_NAME = os.getenv('DJANGO_STORAGES_AWS_S3_REGION_NAME',
                                   'us-east-1')
```

to prepare for adding support to write to S3.

From the operations side of things, we need:

- [ ] Accounts and credentials for the app to upload files
- [ ] Naming and creating the bucket for dev, staging, and production environments

**Comment by rajadain** [comment]
The [`django-storages` README](https://github.com/jschneier/django-storages) recommends setting this:

```python
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
```

Currently, we have these in place:

https://github.com/WikiWatershed/model-my-watershed/blob/7e8cc32f4324f4a555940b3e42d8a2ae29c8cd4f/src/mmw/mmw/settings/base.py#L59-L61

https://github.com/WikiWatershed/model-my-watershed/blob/7e8cc32f4324f4a555940b3e42d8a2ae29c8cd4f/src/mmw/mmw/settings/production.py#L80

Presumably we would only change the `production.py` one, which would apply to staging and production. We'd use local storage in the `app` VM during development, which is what `FileSystemStorage` seems to imply. I have been unable to find any leads on where `PublicS3BotoStorage` is used, and what implications changing it would have.

**Comment by hectcastro** [comment]
> I have been unable to find any leads on where `PublicS3BotoStorage` is used, and what implications changing it would have.

I feel like this got carried over from another project and is dead code in MMW. We had to override the `django-storages` functionality in Treescount, which was done via a `PublicS3BotoStorage` class.

**Comment by rajadain** [comment]
I pushed up my changes to [`tt+hmc/custom-weather-s3-backend`](https://github.com/WikiWatershed/model-my-watershed/tree/tt%2Bhmc/custom-weather-s3-backend), feel free to add to that.

**Comment by rajadain** [comment]
Re-opening to count in Civic Apps board.
