### ISSUE TITLE
Add Papertrail alert on Celery Worker SIGKILL

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3278]
In certain cases (see #3277), the Celery Worker can die with the following message:

```
[2020-03-29 14:08:09,264: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:2587 exited with 'signal 9 (SIGKILL)'
```

Add a rollbar alert for when this happens.

**Comment by hectcastro** [comment]
This may be tricky to support via code additions to the project. One potentially cheap way to do it would be to look for a similar message in Papertrail, and drop an alert in Slack when it is found.

**Comment by rbreslow** [comment]
I saved the following search and created an alert to notify Slack:

![image](https://user-images.githubusercontent.com/1774125/81610766-066fcb00-93a8-11ea-9b78-184b1b85b09a.png)

This required adding an additional Papertrail integration for the `#mmw` channel.

I connected to a staging app server and appended the following to the syslog:

```bash
ubuntu@ip-10-0-3-91:~$ logger [2020-03-29 14:08:09,264: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:2587 exited with 'signal 9 (SIGKILL)'
```

And, voila:

![image](https://user-images.githubusercontent.com/1774125/81610887-328b4c00-93a8-11ea-88a0-391576b69bd2.png)

@rajadain Can you verify my approach is sound?

**Comment by rajadain** [comment]
The query and Slack integration look good. The only thing is that we need to be monitoring the Celery processes which execute on the `worker` VM, not the `app` VM. Will this capture those? They live in `/var/log/celery/[Blue|Green]-worker[0|1].log`

**Comment by rbreslow** [comment]
Yes, this should capture those messages. We have an rsyslog configuration in place to read the worker logs and send them to the syslog tagged as `celery-worker-n`.

https://github.com/WikiWatershed/model-my-watershed/blob/develop/deployment/ansible/roles/model-my-watershed.celery-worker/templates/celery-syslog.j2

If you do a search for `celery-worker-` in Papertrail, you'll find log output similar to what you shared in the beginning of the issue.

**Comment by rajadain** [comment]
Excellent, thank you!
