### ISSUE TITLE
Fix Celery Restart Script

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3279]
We should have a cron task to restart Celery every night (see #3085 and #3086). However, recent logging shows that Celery is not restarted at night, sometimes going days without being restarted, as evidenced in the logs in #3277.

Investigate and fix the script so that Celery is restarted every day, in all cases.

**Comment by hectcastro** [comment]
Might be worth looking to make this an explicit `stop` and `start` vs. `restart`. That should hopefully account for a scenario where `restart` doesn't lead to the outcome we desire. It may also be worth testing the modification after killing the Celery processes out-of-band with `kill`.
