### ISSUE TITLE
Scenarios assume modifcations are present

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#331]
`ToolBarTabConentView` assumes that a scenario has modifications which causes exceptions when switching between tabs under certain conditions (like switching between empty tabs on a saved project):

https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/views.js#L419-L428

**Comment by kdeloach** [comment]
I would review the logic in the constructor (See https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/models.js#L139). Scenario modifications should never be null. If there are no modifications, this attribute should be an empty collection.

**Comment by mmcfarland** [comment]
Interesting, in practice, I'm seeing the empty value be a serialized array:  `"[]"` which obviously doesn't implement `filter` and throws an exception.
