### ISSUE TITLE
Custom Weather: Deploy to Production

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3311]
Once all the [Custom Weather](https://github.com/WikiWatershed/model-my-watershed/issues?q=label%3A%22Custom+Weather+Data%22+) work is done, deploy to production.

Full comparison can be seen here: https://github.com/WikiWatershed/model-my-watershed/compare/master...release/1.29.0

**Comment by ColeKettler** [comment]
@hectcastro We're targeting a release sometime during the week of 5/25.

**Comment by hectcastro** [comment]
- [ ] Ensure `mmw-production-data-us-east-1` S3 bucket exists
- [ ] Skip migration `0030_custom_weather_dataset` and `0032_project_remove_weather_fields`

```
envdir /etc/mmw.d/env /opt/app/manage.py migrate modeling 0030 --fake
envdir /etc/mmw.d/env /opt/app/manage.py migrate modeling 0031
envdir /etc/mmw.d/env /opt/app/manage.py migrate modeling 0032 --fake
```
