### ISSUE TITLE
Custom Weather: Bugfixes

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3312]
* Seeing a strange `AWSAccessKey` suffix on staging:
  ![Screen Shot 2020-05-14 at 2 36 30 PM](https://user-images.githubusercontent.com/1430060/81973317-f9461c80-95f1-11ea-82cf-c462095f54cb.png)
  ![image](https://user-images.githubusercontent.com/1430060/82226561-a53e7f00-98f4-11ea-9015-7ec1fe6b727e.png)

**Comment by mmcfarland** [comment]
This workflow can provide unexpected results:

1. Upload valid weather data file & save
2. Open CWD panel, delete/confirm the custom data
3. Without closing the panel, upload an invalid data file and receive error
4. Hit Cancel to close the panel
5. Open the panel again, the deleted data file is still listed 

Having confirmed delete, I would not expect the original file to still be associated with scenario.

![mmw-cdw-1](https://user-images.githubusercontent.com/1014341/82153452-7c0ae980-9835-11ea-84b8-5a0ad155cb03.gif)

**Comment by rajadain** [comment]
The above is similar to the "cancel after delete" workflow error noted in #3309. My approach to fixing this is to remove the Save / Cancel button, replace it with a Done which simply closes the dialog, and always save on switching weather type and successful upload. Will implement for #3309.

**Comment by rajadain** [comment]
All the above was handled in other PRs. No bugs were reported by the clients during testing on staging. Closing.
