### ISSUE TITLE
Determine preferred database backup and maintenance windows

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#335]
The `PreferredBackupWindow` is a block of at least 30 minutes for RDS to snapshot the PostgreSQL database. The `PreferredMaintenanceWindow` is a block of at least 60 minutes along with a day of the week that RDS reserves for routine maintenance.

**Comment by hectcastro** [comment]
@mmcfarland Do you have any sense for what these time windows would be? I assume anything outside of the school day, but that has to take into account all timezones in the US, right?

**Comment by mmcfarland** [comment]
Yeah, at a guess, outside of school/business hours.  Midnight EST seems arbitrary and acceptable.  A weekend night for the `PreferredMaintenanceWindow` seems right as well.  Outside of that broad spectrum, I don't think the particular times are important.
