### ISSUE TITLE
SSO and cookie issue

### ISSUE THREAD

**Issue by dboyer** [WikiWatershed/model-my-watershed#3358]
Reported by Concord Consortium:

We discovered an issue logging in to MMW when it is embedded in LARA and Chrome's new SameSite cookie policy is enabled.

You can learn more about the SameSite cookie policy change here: https://www.chromium.org/updates/same-site
This article might be a better read: https://blog.heroku.com/chrome-changes-samesite-cookie

The gist is that Chrome is gradually rolling out a more strict cookie policy. By default this policy prevents cookies from "3rd party" sites.
When MMW is embedded in LARA, MMW is considered a 3rd party site because it is in an iframe of a different domain.
Because MMW doesn't include properties in it cookies to override this default, chrome will not store cookies sent by MMW when it is in an iframe.

**Comment by rajadain** [comment]
Timeframe:

**July 14, 2020**: SameSite cookie enforcement has resumed, with a gradual rollout starting today (July 14) and ramping up over the next several weeks as we continue to monitor overall ecosystem readiness and engage with websites and services to ensure they are prepared for the SameSite labeling policy. The SameSite features are being enabled for Chrome Stable channel users on versions 80 and 81 (who should update Chrome!), 83, as well as the newly released 84.

So we may need to work on this sooner than later.

**Comment by rajadain** [comment]
Use this site to test: http://concord-consortium.github.io/lara-interactive-api/
