### ISSUE TITLE
Update TR-55 Colors to be more Accessible

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3359]
Using color recommendations decided in https://github.com/WikiWatershed/mmw-micro/issues/18

**Comment by designmatty** [comment]
Infiltration: #f2cf46;
    Evapotranspiration: #2d8bff;
    Runoff: #ed3b3b;

**Comment by rajadain** [comment]
Should be noted that the colors look different between Firefox and Chrome:

![image](https://user-images.githubusercontent.com/1430060/88565404-8bab6900-d002-11ea-8d78-2c514299b1c2.png)

This is a well known issue in the industry.
