### ISSUE TITLE
Geocoding no longer works

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#336]
Attempting a geocode produces this (somewhat gracefully handled) error:

```
XMLHttpRequest cannot load 
https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/suggest?f=json&searchExtent=-127.17,24.76,-66.53,50.4575&text=340. 
Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers.
```

**Comment by mmcfarland** [comment]
Same error is reported in the testem console, but geocoder tests are all passing.

**Comment by caseypt** [comment]
That is the correct behavior for the JS tests. They are isolated from integration problems because they are using a fake server. The python geocode tests, however, should fail.

I'm seeing this error in the console log when running the geocode tests. Looks like requests aren't be captured in this test for some reason: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/geocode/tests.js#L105

**Comment by caseypt** [comment]
I take part of that back. The python tests won't catch this either because the problem is with calls to the suggestion service, and not the geocoder (which is proxied through Django).

If this is a real problem (and not a temporary network issue), we should find a way to test it out.

**Comment by caseypt** [comment]
If you comment out this line, geocoding works: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/setup.js#L20

**Comment by mmcfarland** [comment]
That makes sense, I was worried we were too expansive in targeting all `ajax` requests with that.  We'll have to narrow our scope somehow.

**Comment by kdeloach** [comment]
Whoops. Should definitely not be adding csrf to ajax requests on external domains.

**Comment by rajadain** [comment]
It's actually this line which is preventing Cross Domain AJAX calls: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/csrf.js#L31

That was added so we don't expose our CSRF token to third parties, but instead it  has locked down all outside AJAX requests. We should remove that and add a different way of checking if a request is local or not, and only then attach the `X-CSRFToken` header.

**Comment by kdeloach** [comment]
We could also override `Backbone.ajax` in the shim and add the csrf there instead of globally.

**Comment by rajadain** [comment]
That sounds reasonable.

**Comment by caseypt** [comment]
Overriding `Backbone.ajax` wouldn't help here because the call to the ArcGIS server is made through a Backbone Model.

**Comment by rajadain** [comment]
Using an `isExternal(url)` method which might be defined in one of many ways: http://stackoverflow.com/questions/6238351/fastest-way-to-detect-external-urls, we might refactor to this:

```javascript
exports.jqueryAjaxSetupOptions = {
    beforeSend: function(xhr, settings) {
        var csrftoken = getCookie('csrftoken');
        if (!csrfSafeMethod(settings.type) && !isExternal(settings.url)) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
}
```

**Comment by kdeloach** [comment]
Just throwing this out there... We don't have to make all ajax requests via Backbone models. If we use just $.ajax for the geocoder then this becomes a little easier to solve.

**Comment by caseypt** [comment]
In this case, I think @rajadain's approach is best. 

The related code is utilizing Backbone quite a bit: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/geocode/models.js#L25-L65
