### ISSUE TITLE
Release 1.31.0 to Production

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3369]
- [x] Disable Recent Weather, as was done in #3362
- [x] Release 1.31.0 to Production
- [x] Enable Recent Weather on Staging, as was done in #3363

**Comment by hectcastro** [comment]
Recent weather was enabled again on `develop` in https://github.com/WikiWatershed/model-my-watershed/commit/eddec64e45f5236a638f142927e41a66379bc39d.
