### ISSUE TITLE
Setup read replica for ElastiCache

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#337]
This is to help protect against a Redis master failure.

**Comment by hectcastro** [comment]
This should probably happen along with https://github.com/WikiWatershed/model-my-watershed/issues/339.

**Comment by hectcastro** [comment]
`t2.*` instances aren't supported for setting up an ElastiCache replica set. The next cheapest instance is an `m1.small`. We'd be going from $0.018 to $0.075 per hour.

**Comment by mmcfarland** [comment]
Is this resolved by #533?

**Comment by hectcastro** [comment]
Yes!
