### ISSUE TITLE
Add Multi Layer Support to Projects

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3400]
## Overview

* [x] Add a `layers` JSON field to `modeling_project` which will contain a dictionary of layer names to be overwritten
* [x] Initialize the above field to `{"__LAND__": "nlcd-2011-30m-epsg5070-512-int8"}` for all existing rows, but use `{"__LAND__": "nlcd-2019-30m-epsg5070-512-byte"}` as the default value going forward
* [x] Add this to the project serializer and send it to the front-end
* [x] In the front-end, include this in all `model_input` parameters given to TR-55 and MapShed jobs
* [x] Modify [TR-55](https://github.com/WikiWatershed/model-my-watershed/blob/d78510a7f31c71389b8bea6aad502f8ce5d3622b/src/mmw/apps/modeling/views.py#L599) and [MapShed](https://github.com/WikiWatershed/model-my-watershed/blob/d78510a7f31c71389b8bea6aad502f8ce5d3622b/src/mmw/apps/modeling/views.py#L539) to read this dictionary from the `model_input`

## Previously

Currently, the data layers queried for a project are hardcoded into the system. As of #3397 we now have multiple NLCD layers to pick from. We must now add a mechanism to specify which layers a project is using, and adjust the geoprocessing to get the layer name from the project before querying it. We must also set all existing projects to use the 2011 (NLCD11) layer, and all new projects to default to 2019 (NLCD19) layer.

When there is only one layer for a project, the design is simple. If folks want to compare different layers per scenario, then it gets more complicated:

- We could have scenario level layers, that would have to be sandwiched between project level base data, and the scenario-specific modifications
- We could handle different layers as modifications
  - This is easier in Mapshed, where we already have a Land Cover Modification dialog
  - Harder in TR-55, where modifications are spatially relevant, can't just use aggregations

**Comment by rajadain** [comment]
At first I thought that TR-55 would be the exceptional case, but since we run the entire TR-55 model on every run, it's pretty simple to provide it with a different input layer.

The harder question may be how this is handled for MapShed. Currently, Land Cover changes are applied as modifications, but this is not perfect, as it leads to issues like #3346 and #3347. If we were to change the land cover changes from being applied as modifications, that may require a larger refactor.

**Comment by rajadain** [comment]
Since the current contract has been budgeted and scoped with the simplest, most immediate solution in mind, that is all we can implement at this time. We will have to defer addressing the related issues above to a later time.

The implementation for this card should follow this workflow:

* [ ] Add a `layer_land` field to `modeling_project` which only allows `2019_2019` - `2011_2011` as valid values
* [ ] Initialize the above field to `2011_2011` for all existing rows, but use `2019_2019` as the default value going forward
* [ ] Add this to the project serializer and send it to the front-end
* [ ] In the front-end, include this in all `model_input` parameters given to TR-55 and MapShed jobs
* [ ] Modify [TR-55](https://github.com/WikiWatershed/model-my-watershed/blob/d78510a7f31c71389b8bea6aad502f8ce5d3622b/src/mmw/apps/modeling/views.py#L599) and [MapShed](https://github.com/WikiWatershed/model-my-watershed/blob/d78510a7f31c71389b8bea6aad502f8ce5d3622b/src/mmw/apps/modeling/views.py#L539) to read the `land_layer` value from the `model_input`
* [ ] Modify geoprocessing tasks `run` and `multi` to take a `layers` dictionary and replace certain tokens in a configuration with the values from the dictionary
  - For example, a configuration may look like this:
    ```python
    {
        'name': 'RasterGroupedCount',
        'label': 'nlcd_soil',
        'rasters': [
            'LAND_LAYER',
            'SOIL_LAYER'
        ]
    }
    ```
    and a `layers` dictionary may look like this:
    ```python
    layers = {
        'LAND_LAYER': 'nlcd-2011-30m-epsg5070-512-int8',
        'SOIL_LAYER': 'ssurgo-hydro-groups-30m-epsg5070-512-int8',
    }
    ```
    Make it so that the tokens in `rasters` are replaced with their values from the `layers` dict.

**Comment by rajadain** [comment]
The final point above could be a big enough refactor to belong in its own issue.

**Comment by rajadain** [comment]
The geoprocessing refactor was done in #3406.

**Comment by rajadain** [comment]
We spoke with Dave A and BME and Lin P about the issues around Land Cover dialog modeling deficiencies, which are covered here: https://docs.google.com/document/d/1xAEcinQ0zfYFPyjA579tMVcjOFihD-TSoBD5xoUMCGc/edit?usp=sharing. They understood and they are aware of the deficiencies, they agree to proceeding with our original implementation.

**Comment by SRGDamia1** [comment]
Can the Shippensburg 2100 centers/corridors predictions be used as a layer override?  If so, what is the proper `__LAND__` value to use?

**Comment by rajadain** [comment]
Hi @SRGDamia1,

The Shippensburg layers were ingested for visualization in #3320, but not for analysis. Their analysis is implemented by the Drexel Fast Zonal API in #3334. Because it was not ingested via GeoTrellis, it cannot be spatially intersected with other layers.

The analysis is part of the MMW API:

![image](https://user-images.githubusercontent.com/1430060/144144993-79bc84c3-4e0c-41bc-9213-398625da465e.png)

For MapShed projects, the Shippensburg predictions can be selected via the Land Cover dialog:

![image](https://user-images.githubusercontent.com/1430060/144144853-a9c71646-5467-4374-bffe-12bdac1ef30a.png)

This was implemented in #3344.

What is your use case?

**Comment by SRGDamia1** [comment]
@rajadain No, actually I'm running the  the model via web requests from python. And I want to run tr-55 on the layers so I need the full geoprocessing to get the soil type / land use intersection census.

**Comment by rajadain** [comment]
Ah unfortunately the Shippensburg projections are only supported for Analysis and MapShed, not for TR-55. If we'd like to support them for TR-55, we can ingest them for data processing ourselves. That work was not done before in favor of the Drexel Fast Zonal API, but could be done in the future.

**Comment by SRGDamia1** [comment]
Oh, Ok. Thanks!
