### ISSUE TITLE
Saving the project more than once has no effect

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#341]
Saving a project the first time will save the project and all scenarios. Saving a second time, will only save the project, even if there were changes to the scenario.

1. Create a new project or load an existing one
2. Add scenario
3. Change the precipitation level
4. Save
5. Change the precipitation level again
6. Save
7. Reload

Expected:
Scenario should have precip value from step 5.

Actual:
Scenario has old precip value from step 3.

**Comment by mmcfarland** [comment]
Resolved in #348
