### ISSUE TITLE
Upgrade base box to at least Ubuntu 18.04

### ISSUE THREAD

**Issue by colekettler** [WikiWatershed/model-my-watershed#3416]
We are currently on Ubuntu 16.04 which recently transitioned to Extended Security Maintenance (ESM). This requires an Ubuntu Advantage subscription and valid token to continue to access its apt repositories. This is currently causing CI to fail.

We should target an upgrade to at least Ubuntu 18.04 to get back onto an LTS release under active support.

Ideally we could target an upgrade to 20.04, but it's worth noting that this is the first release to use Python 3 as the default interpreter. We would need to install Python 2 and switch to it as the default interpreter ourselves. This may be prohibitive until we complete #3165. If this does prove to be prohibitive, we should target 18.04 and create an issue to upgrade to 20.04 after #3165 is completed.

We have previously completed a similar upgrade in https://github.com/azavea/cicero/pull/2206. This could serve as an example for implementation.

**Comment by rajadain** [comment]
(I'm going to keep a running log of notes as I work through this here.)

I've been trying to upgrade to Ubuntu 20.04 and have a branch [`tt/upgrade-ubuntu-20.04`](https://github.com/WikiWatershed/model-my-watershed/compare/tt/upgrade-ubuntu-20.04) where I'm adding commits, very rough, just to get things in a working state.

I've been able to get through most things, but this seems like a blocker: https://code.djangoproject.com/ticket/31838

Seemingly Django 1.11 is not supported in Ubuntu 20.04?

A Django upgrade can be evaluated, but I'm hesitant to entangle that with this effort. Will revisit this tomorrow.

**Comment by rajadain** [comment]
Setting points from 5️⃣ to 0️⃣ for tracking purposes.
