### ISSUE TITLE
Investigate Incorrect Area Calculation on Staging

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3431]
Post Ubuntu Upgrade, on staging and local, the area calculation seems to be off. For the Lower Schuylkill HUC-10, the correct value is ~698 km²:

![image](https://user-images.githubusercontent.com/1430060/141045351-ff3232b5-6be1-4b53-a7c4-d1efc067a4fe.png)

This is reflected when operating directly in the database:

```sql
SELECT ST_Area(ST_Transform(ST_SetSRID(geom, 4326), 5070))
FROM boundary_huc10
WHERE huc10 = '0204020310';

     st_area
-----------------
 696717334.86354
(1 row)
```

However, in Python this gives a different value:

```python
>>> sql = "SELECT ST_AsGeoJSON(geom) FROM boundary_huc10 WHERE huc10 = '0204020310'"
>>> with connection.cursor() as cursor:
       cursor.execute(sql)
       row = cursor.fetchone()
       geojson = row[0]
>>> geom = GEOSGeometry(geojson, srid=4326)
>>> geom.transform(5070, clone=True).area
<<< 230633144.86478913
```

This is not happening on production.

---

Figure out why this is happening and fix it.

**Comment by rajadain** [comment]
Further details: https://code.djangoproject.com/ticket/30645 and https://github.com/OSGeo/gdal/blob/9e9f8b294418e5f2670dacd5cacb5d6cdeabb797/MIGRATION_GUIDE.TXT#L67-L72

**Comment by rajadain** [comment]
Apparently, previously GDAL always treated the order of coordinates as the first one being X, and the second one being Y. As of GDAL 3.0.0, it prefers the order defined by the projection scheme: https://code.djangoproject.com/ticket/30645

A fix for this was added in Django in https://github.com/django/django/pull/12878 and is released as part of Django 3.1. It has not been backported.

It does not seem possible to install GDAL < 3.0.0 on Ubuntu Focal. It is not available in any of the main repositories, and there does not seem to be an archive / legacy repository for GDAL like there is for Postgres.

Installing from source takes upwards of an hour, which is not practical for VMs / CI / deployments, where the VMs are frequently built.

Replacing calls to this functionality in our code with PostGIS equivalents also does not seem viable, since it occurs in many places.

Manually adding these lines to the relevant files also seems to not have an effect:

https://github.com/django/django/blob/8d9827c06ce1592cca111e7eafb9ebe0153104ef/django/contrib/gis/gdal/prototypes/srs.py#L35
https://github.com/django/django/blob/8d9827c06ce1592cca111e7eafb9ebe0153104ef/django/contrib/gis/gdal/srs.py#L68

(I deleted the corresponding `*.pyc` files, restarted the `celeryd` service and the entire VM, still no effect)

This may imply that the Python and Django upgrades are inevitable.

**Comment by aufdenkampe** [comment]
@rajadain, thanks for that detailed explanation!

It looks like we'll need to deal with these tech-debt upgrades at a minimum:
- #3165
- #3419

**Comment by rajadain** [comment]
Those two should be enough. Will be done in that order, since Django 1.11 (what we are currently on) supports both Python 2 and 3. Once the Python 3 upgrade is complete, then we can upgrade to Django 3.2, which is the current latest version and will calculate area correctly.
