### ISSUE TITLE
Upgrade Deployment Code to Python 3

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3437]
Much of our deployment code is in Python 2, and does not work with the new Python 3 application:

```
mmw-worker: TASK [model-my-watershed.rwd : Configure RWD service definition] ***************
mmw-worker: fatal: [mmw-worker]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: module 'six' has no attribute 'ensure_text'"}
```

http://civicci01.internal.azavea.com/view/mmw/job/model-my-watershed-packer-app-and-worker/1355/console

Upgrade the deployment code to Python 3 to fix this.

**Comment by SRGDamia1** [comment]
Any guesses on when staging might be live again?

**Comment by rajadain** [comment]
Still working on this, sorry! Is there anything I can do on my locally running instance to help you in the interim?
