### ISSUE TITLE
Early creation of a Project, persist in navigation

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#346]
Right now, Projects are only created once the user navigates through to the `/model` page.  We should consider creating the Project earlier in the sequence in order to reduce the number of places we persist the area of interest shape and also to be able to navigate back and forth more consistently.  Currently, if you got to a `/model/id` page, navigate back to `/analyze` then forward again, you are looking a new project for the same area of interest.  This may or may not be what the user wanted, but it's pretty confusing.

**Comment by ajrobbins** [comment]
We now save the project so that if you navigate back to analyze and then forward again, the user is back at the initial project.
