### ISSUE TITLE
Only allow sharing if project is public

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#347]
I think there are two potential workflows:

1. Project is private: "Share" menu items are not available for project or scenario
2. "Share" items always available, but if the project is private, the modal presents the option to make public in order to view the share link.

I like option 2 because I don't think people will intuitively know to make a project public to share it, though they will probably try to share it.  Not sure what to do about just copying a link from the URL bar, right now they'll get a 404, which from a security perspective is best, but from a sharing perspective makes it seem broken if you don't understand public/private projects.

**Comment by caseypt** [comment]
Agree that option 2 is better. As you suggested in #328, we probably need to prominently display the current privacy setting in the UI.

**Comment by caseypt** [comment]
@ctaylo37 Any ideas for where/how to show the privacy setting in the UI? It's currently just a menu item in the project menu.

![selection_005](https://cloud.githubusercontent.com/assets/1042475/8194005/b519d0b0-1446-11e5-8c68-a27c1ab52ea8.png)
