### ISSUE TITLE
Increase Worker VM EBS Volume Size on EC2

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3515]
The Worker VMs on EC2 are full as soon as they start:

```
System load:  0.0               Users logged in:                  0
Usage of /:   99.2% of 7.69GB   IPv4 address for br-68637d7cab34: 172.18.0.1
Memory usage: 29%               IPv4 address for docker0:         172.17.0.1
Swap usage:   0%                IPv4 address for ens3:            10.0.1.229
Processes:    138
```

This leads to runtime issues, including extraneous SIGKILLs to `snapd.service`.

Most of this is Docker. But as logs get bigger, they also take up room.

Make it so the Worker VMs are provisioned with 10GB of default space.

**Comment by rajadain** [comment]
For more context see: https://azavea.slack.com/archives/C044CG212/p1649176958355409

**Comment by rajadain** [comment]
For an example of where this was done previously, see:

https://github.com/azavea/cac-tripplanner/blob/20d0f66ad2b6af23e1f08cc900de5b003c098db5/deployment/packer/cac.json#L46-L70

**Comment by rajadain** [comment]
Getting these messages again, going to remake them.

**Comment by rajadain** [comment]
Also consider adding log rotation so that the disk does not fill up as fast.

**Comment by JN-Hernandez** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Apps-62c5ba9ee84ced001f5b5d00/issues/WikiWatershed/model-my-watershed/3515?planning-poker) with Zenhub @JN-Hernandez

**Comment by JN-Hernandez** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Apps-62c5ba9ee84ced001f5b5d00/issues/WikiWatershed/model-my-watershed/3515?planning-poker) with Zenhub @caseycesari

**Comment by rajadain** [comment]
This is now happening roughly weekly. Going to address this in this sprint.
