### ISSUE TITLE
Include entire GWLF-E result for each HUC-12 subbasin in the subbasin run outputs

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#3537]
The areas, flows, and monthly loads from the individual HUC-12's are lost when the subbasin results are combined with SRAT results and formatted for output in https://github.com/WikiWatershed/model-my-watershed/blob/31566fefbb91055c96a32a6279dac5598ba7fc10/src/mmw/apps/modeling/tasks.py#L99

**Comment by SRGDamia1** [comment]
After talking with Barry and others today I realized I was misunderstanding the chain and what is coming back in the sub-basin result.  **_None_** of the raw GWLF-E outputs are returned with the sub-basin results, only the attenuated totals.

**Comment by rajadain** [comment]
Completed in #3545
