### ISSUE TITLE
Question:  How long are jobs persisted?

### ISSUE THREAD

**Issue by SRGDamia1** [WikiWatershed/model-my-watershed#3541]
How long after running a job can I still look up the results from that job using the job's UUID?

**Comment by rajadain** [comment]
We don't have a hard policy in place for this. Jobs are meant to be ephemeral, and should be treated as such. In the past, when we ran out of space, we've deleted all jobs unattached to projects older than 1 month. This has only been done once or twice though.

Given that, I would say 1 month is a reasonable expectation, even though in most cases they'll be around much longer.

**Comment by SRGDamia1** [comment]
Ok.  I had been assuming the persistence was on the order of an hour and re-running after that.  Then I tried to use a MapShed job from two weeks ago as input for a new GWLF-E run and was surprised it worked.

I'll continue to generally work as if jobs are short-lived, but for this DRWI stuff, I'm happy to have older jobs still available and will use them.
