### ISSUE TITLE
DRWI API Improvements Black Box 2️⃣

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3543]
- [ ] #3542
- [ ] #3540

**Comment by rajadain** [comment]
@SRGDamia1 I've chosen 2 cards from those you've made which seem high priority. Under this task we have bandwidth for 1 more. Which one would you recommend?

**Comment by SRGDamia1** [comment]
I think #3540 would be cleaner and easier to implement.  I would be afraid #3542 might become a bit of a rabbit hole.

**Comment by rajadain** [comment]
Closing this black box in favor of #3540

**Comment by aufdenkampe** [comment]
@rajadain, from my perspective for the PA2 work, the constraining issue is that if missing COMID catchment results when running HUC-12s through sub-basin modeling, as described in #3542. In the last week, this has become an issue for us with compiling PA2 results.

That said, if implementing #3540 solves the null catchment values issue, then that would be a win-win.

@SRGDamia1, is that what you were thinking when you said  #3540 would be more straightforward?

**Comment by SRGDamia1** [comment]
@aufdenkampe - I don't think allowing the GMS import would fix the missing catchment problem. Since Azavea's time is so limited, I thought it would be easier to add the feature than to chase down a bug.
