### ISSUE TITLE
Add New Boundary for Recent Weather

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3547]
The DRWI team would like to enable Recent Weather on staging and production. They would like to limit it to the Full DRWI Extent, which is slightly larger than the DRB Boundary:

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/1430060/172990093-4b945d28-3e21-4e37-a935-1dcaa38132a4.png">

Unfortunately, the DRWI Extent shape does not line up with HUC-12s (since it is derived by aquifers, not elevation). Since so many AoIs in MMW center around HUCs, here's a union of the Full DRWI Extent and all its intersecting HUC-12s:

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/1430060/172990231-e5ea6d6c-9b69-49ce-9bd2-f933670106a3.png">

The geojson of the shape is here: [20220609-drwi-huc12-boundary.geojson.zip](https://github.com/WikiWatershed/model-my-watershed/files/8875730/20220609-drwi-huc12-boundary.geojson.zip)

This shape was created using the following query: [20220609-drwi-huc12-boundary.sql.zip](https://github.com/WikiWatershed/model-my-watershed/files/8875750/20220609-drwi-huc12-boundary.sql.zip)

Add that boundary to MMW and enable Recent Weather for AoIs that fall within it.

**Comment by aufdenkampe** [comment]
@rajadain, thank you for extending this area for recent weather.

Can you extend it slightly further, to include all those pink NJ coastal HUC-12s? There are upcoming "coastal resiliency" use-cases that would benefit from having that new data available for those HUC-12s, and the weather stations that we're currently using clearly cover those locations.

The pink HUC12's in Delaware should be excluded, as you have proposed, as we would need to add additional weather stations to properly estimate their recent weather.

**Comment by rajadain** [comment]
Is this an accurate representation of the shape you would like? It's the DRB + all coastal HUC-12s within New Jersey:

![image](https://user-images.githubusercontent.com/1430060/173062387-21259e2e-d14b-4626-982a-bf7996830ec2.png)

These HUC-12s fall under the Mullica-Torns 02040301 and Great Egg Harbor 02040302 HUC-8s.

**Comment by rajadain** [comment]
Going with this shape: [20220610-drwi-nj-coastal-huc12s.geojson.zip](https://github.com/WikiWatershed/model-my-watershed/files/8879175/20220610-drwi-nj-coastal-huc12s.geojson.zip)


![image](https://user-images.githubusercontent.com/1430060/173075421-4619c608-c678-4e49-b3b1-af0ce5e829a0.png)

Made using:

```sql
SELECT ST_AsGeoJSON(ST_Union(geom))
FROM boundary_huc08
WHERE huc08 LIKE '0204%'
  AND huc08 NOT IN ('02040303', '02040304');
```

**Comment by SRGDamia1** [comment]
@aufdenkampe @darscott Is there a reason not to enable recent weather nationally? If it's available nationwide, why not provide it nationwide or for the full extent that it is available?

**Comment by aufdenkampe** [comment]
@SRGDamia1, we wold definitely like to go nationally ASAP with recent weather data. That said, Azavea is at the end of their budget for this project, so I think right now we go with what is immediately necessary for PA2.

Fortunately, we have the UPWINS project coming down the pipe, with a start date of Sept. 1, so we'll want to go national with the recent weather as a high priority at that time.

**Comment by darscott** [comment]
Also...we have not compiled recent weather for any other stations
