### ISSUE TITLE
Replace Google Analytics UA tag with new GA4 tag

### ISSUE THREAD

**Issue by HeatherBrooks** [WikiWatershed/model-my-watershed#3581]
Google Analytics is requiring a switch from UA to GA4 tracking; UA will stop collecting data in July 2023. The process of creating a GA4 tag using the existing UA tag didn't work for this property, so unfortunately we'll need to replace the currently active UA tag with this: [model-my-watershed-ga4-tag.txt](https://github.com/WikiWatershed/model-my-watershed/files/9922100/model-my-watershed-ga4-tag.txt). Thank you!

**Comment by HeatherBrooks** [comment]
It looks like the old Google Analytics tag (UA-47047573-15) is still in place and the GA4 tag isn't collecting data. I hope it won't take much of your time to drop in the new snippet so we can continue tracking site usage after Google turns off the old tag on July 1. Thanks!

**Comment by rajadain** [comment]
Hi Heather,

We've opened #3598 which adds Google Analytics 4 support. I'll let you know once that's been deployed to production.

Once it is, from what I understand, Google Tag Manager will have to be configured to receive the custom events MMW used to send to Google Analytics. All MMW events will be sent as `event: 'mmw'` to Google Tag Manager. More information can be found here: https://developers.google.com/analytics/devguides/collection/ga4/events?client_type=gtm&sjid=2114022881004196404-NA.

I am not a Google Tag Manager expert, so may be able to offer limited support. Please let me know if you'd like any code in the app changed to better supply the analytics.

Thanks.

**Comment by HeatherBrooks** [comment]
Hi Terence, 
I know Google Tag Manager can be super useful but I haven't set it up yet. However, if I'm reading [this](https://support.google.com/analytics/answer/9234069) correctly, GA4 will collect basic interactions like pageview without GTM. Adding gtag.js seems to be all that is required?

**Comment by rajadain** [comment]
Alright, if we're not actively tracking the custom events so far, then the new `gtag.js` should do all we want. We can defer the GTM configuration to a later date.

I'll let you know once this is deployed to staging, and we can check if the data is flowing through correctly.

**Comment by rajadain** [comment]
Hi Heather,

The GA4 deployment is now live on https://staging.modelmywatershed.org/. Can you play around with that site and see if the data is flowing through to Google Analytics?

**Comment by HeatherBrooks** [comment]
Hi Terence, 
I can see that data is flowing to the new GA4 property. Thanks!

**Comment by rajadain** [comment]
Great, thanks for confirming!
