### ISSUE TITLE
Client stuck, creating jobs in a loop

### ISSUE THREAD

**Issue by Benjamin-L** [WikiWatershed/model-my-watershed#3593]
![image](https://user-images.githubusercontent.com/6504174/220010473-2882a4dd-a96d-4c58-ad32-c4a5d167fc2c.png)

After selecting a region in the web UI, the client gets stuck indefinitely. It looks like it's hitting the "create a new side job" endpoint about every 100ms, which I'm guessing can't be good for the server :)

**Comment by rajadain** [comment]
Can you try again please? It's working at the moment:

![image](https://user-images.githubusercontent.com/1430060/220388091-f4973df3-b580-4ae4-88b7-1af52bf05cc2.png)

Also, those requests are not creating new jobs, but inspecting the status of the job that was created. We create a new job with a POST request, and all subsequent GETs are fetching the status of that job.

**Comment by Benjamin-L** [comment]
Seems to be working for me now as well.

> Also, those requests are not creating new jobs, but inspecting the status of the job that was created. We create a new job with a POST request, and all subsequent GETs are fetching the status of that job.

Oh, that makes sense :) I think I just saw the `"status": "created"` field in the response body and jumped to a conclusion.

I'm assuming that this was some server-side problem then, and the client was working as expected. Gonna close the issue.
