### ISSUE TITLE
Location search not responding to input

### ISSUE THREAD

**Issue by HeatherBrooks** [WikiWatershed/model-my-watershed#3605]
I received the following bug report through the WikiWatershed contact form. Several staff members at the Stroud Center have confirmed that they are seeing the same issue. Issue confirmed in Firefox and Chrome on PCs and Safari on Mac.

> The 'jump to' box doesn't appear to be 'jumping to' and marking the location requested. Has something changed?

**Comment by HeatherBrooks** [comment]
More information, from Dave Arscott: 

> I've used it recently and the only search that works is if you have text matching a HUC8 or 12 and then you can select the geography after it finds it...all other addresses and search strings don't work...

**Comment by rajadain** [comment]
After some investigation, I've identified the underlying issue, likely a subtle change in ESRI Geocoding endpoints: https://github.com/azavea/python-omgeo/issues/67. Will address the issue there, cut a new release, and upgrade MMW to use that.

**Comment by rajadain** [comment]
Have a made a PR there demoing MMW working correctly with the fixed version: https://github.com/azavea/python-omgeo/pull/68
