### ISSUE TITLE
Initial extent should be determined from browser

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#367]
Attempt to geolocate the user via the browser and setCenter on it on app start, if no AoI or Project extent exists.

**Comment by rajadain** [comment]
It might also be useful to have a "locate me" button in the home page for the user to manually trigger this, a-la Google Maps.

**Comment by mmcfarland** [comment]
Yeah, we use a leaflet plugin for that on USACE nicely https://github.com/domoritz/leaflet-locatecontrol

**Comment by mmcfarland** [comment]
USACE Reference implementation:
https://github.com/azavea/usace-wisdm-symbolizer/blob/1640ddaa422917b83b70c95965e936dc567e1015/src/js/map.js#L704
