### ISSUE TITLE
Modifications drop down shows IDs instead of Names

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#369]
We switched to using internal IDs as part of #352 6c2ff6d8703502f9b8ff4f718977af6a69bcd9f6. As a side-effect, the modifications drop down now shows the internal IDs instead of names:

![image](https://cloud.githubusercontent.com/assets/1430060/8118929/fff68794-105f-11e5-9865-5969d495386d.png)

Figure out a way to store both Names and IDs in the model, which currently only saves one, and use the new Name field in all user-facing displays, including any devised for #252.

**Comment by kdeloach** [comment]
One way I solved this was to hard-code the names in the template (See https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/templates/scenarioToolbarTabContent.html#L21). We should also consider adding a label field on `ModificationModel`.

**Comment by rajadain** [comment]
Currently, in the Control thumbnail macro definition https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/templates/controls/utils.html, we use the `value` parameter to populate the `data-value` attribute. But the macro also has access to a `name` parameter which is the pretty name and is used in the thumbnail label. We should be able to easily add a `data-label` attribute to the control and populate that with the `name` parameter, and just pick it up along with `data-value` when initializing modifications.

```
        <div class="thumb" data-value="{{ value }}" data-label="{{ name }}">
            ...
        </div>
        ...
```

We might also consider renaming the `name` parameter to `label` since modification names currently refer to Land Use, Conservation Practice, or Precipitation.

**Comment by jamesmcclain** [comment]
Okay, thank you to everyone for the thoughts.
