### ISSUE TITLE
Clicking a Scenario context menu button ▾ should make scenario active

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#378]
While sharing the Project and current Scenario shows the correct URL in the Share Modal, sharing an inactive Scenario shows the incorrect URL of the active Scenario, instead of the one being shared:

![image](https://cloud.githubusercontent.com/assets/1430060/8119697/7b593788-1065-11e5-8047-542e998cb73a.png)

![image](https://cloud.githubusercontent.com/assets/1430060/8119709/8aa0e010-1065-11e5-8d21-127a10ebc589.png)

In this case, the URL should have been http://localhost:8000/model/7/scenario/**20**, not http://localhost:8000/model/7/scenario/**21**

Clicking the ▾ button should make that scenario active first, before opening the drop-down menu.

**Comment by kdeloach** [comment]
I think this is easy to remedy by using `cid` from the click event, to find the correct model in the collection, instead of always using the active scenario.

However, disabling the dropdown for non-active tabs would increase parity with Google Sheets, which isn't a bad thing.
