### ISSUE TITLE
Develop model package selection workflow

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#389]
Currently, we've only implemented a single model package, modified-TR55.  Eventually, we'll have multiple, mutually exclusive packages that are set on the project which should be determined before an scenario tabs are presented to the user (model package determines what inputs/modifications are available).

Keep in mind #346 for the workflow.

**Comment by caseypt** [comment]
This has been implemented.

![image](https://cloud.githubusercontent.com/assets/1042475/19931603/7b92646c-a0e3-11e6-8745-ef1d05779386.png)
