### ISSUE TITLE
Determine ITSI report page format and function

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#392]
ITSI teacher accounts will be evaluating student assignments by viewing a condensed view or static representation of the students work.  For design considerations, this output will be likely displayed in an iframe.

**Comment by rajadain** [comment]
Not sure if this is covered in the "determine function" part of this issue, but it should be noted that with the current OAuth data we're getting from ITSI, we cannot determine which users are students vs teachers, nor which students are under which teachers. I expect we'll get more APIs for this work.

**Comment by mmcfarland** [comment]
We are now using the `compare` view for such reporting.
