### ISSUE TITLE
Add JS tests around running models

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#393]
- Making a change to a scenario starts a model (add modification, change an input value)
- Test `TaskModel.reset`
- Test `TaskModel.start`
- Test `TaskModel.pollForResults`
- Test `ResultCollection.setPolling`
- Test `ResultCollection.setNullResults`
- Test `ScenarioModel.initialize`
- Test `ScenarioModel.getResults`

Depends on #345

**Comment by kdeloach** [comment]
Other candidates for testing:
  * Non-owners should not be able to see modification controls (input controls should still be visible).

**Comment by caseypt** [comment]
Add tests for `modificationConfigUtils`.

**Comment by lewfish** [comment]
Modify tests for saving projects/scenarios to account for their asynchrony.
