### ISSUE TITLE
Project is saved as soon as `/model` is loaded

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#396]
With #345, as soon as the `/model` route loads, the project is saved (or an attempted save is made).

Is this the behavior we want?

**Comment by rajadain** [comment]
Also see #348 and #385 for more auto-save discussion. The way it is currently setup is that any change to a project triggers a save. If #345 is changing the project model at all it is probably triggering an auto-save.

**Comment by caseypt** [comment]
Yeah, I think something is wrong in the current implementation. After testing for a few days, I now have a ton of "Untitled Projects" projects even though I didn't make any edits. If we had a "My Projects" view, the current behavior could clutter things up.

**Comment by lliss** [comment]
This should be addressed in https://github.com/WikiWatershed/model-my-watershed/pull/448

**Comment by mmcfarland** [comment]
Fixed in #448
