### ISSUE TITLE
Precipitation slider should display 0" if the slider is all the way to the left

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#397]
![selection_062](https://cloud.githubusercontent.com/assets/1042475/8166497/332ebc7c-1366-11e5-8734-7aa2acb3ca98.png)

**Comment by kdeloach** [comment]
This line needs to be updated: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/controls.js#L96.
