### ISSUE TITLE
Consider not fitting bounds on output panel resize

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#401]
If the user is zoomed to an extent of the AoI, minimizes the output panel, then restores it, we resize the zoom and center to fit the bounds in the new bbox.  This can be annoying if we are focused on a region and need to occasionally look at the results output.  I don't think we need to fit to bounds.

**Comment by lewfish** [comment]
So, we want minimizing and restoring to have no effect on the position and zoom level?

**Comment by mmcfarland** [comment]
That's my inclination - would be good to get other feedback from those of us who have been "using" the app.  Thoughts?

**Comment by caseypt** [comment]
+1

**Comment by rajadain** [comment]
I agree, the resize is disruptive.

This may have the effect of Leaflet attribution never being visible in the `/model` page. Created #497 for that.
