### ISSUE TITLE
Remember Active Model Output between Scenarios

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#414]
Currently if one selects "Water Quality", goes to another scenario, and returns to the original, "Runoff" is selected as the active model output:

![remember-model-output-issue](https://cloud.githubusercontent.com/assets/1430060/8192669/c60aa57e-143d-11e5-9de6-a1124b8f0cda.gif)

This happens even if "Water Quality" is also selected in the currently active scenario:

![remember-model-output-issue-2](https://cloud.githubusercontent.com/assets/1430060/8192674/d4467316-143d-11e5-8370-18c5883c7852.gif)

The ideal behavior would be either:
1. Remember the active model output for each scenario
2. Have the same model output be active for each scenario

For 2., if I select "Water Quality" as the active model output in one scenario, it should be active for each scenario.

**Comment by rajadain** [comment]
Can be worked on after #412 is merged.

**Comment by ajrobbins** [comment]
The compare view is the place to switch among scenarios and compare the metrics. The model or analyze views should show the same initial state when each scenario is viewed.
