### ISSUE TITLE
Allow Frame-Options to be open to multiple domains

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#415]
ITSI cannot display 'https://mmw.azavea.com/' in an iframe because its  'X-Frame-Options' are set to 'SAMEORIGIN'.  We'll need to make this more liberal for ITSI integration.  Initially, this may be easiest to open to all domains, but we could potentially limit it to ITSI based ones.  Not sure if the header supports wildcards.

**Comment by rajadain** [comment]
I think we will have to allow it for all domains by [removing the XFrameOptionsMiddleware from our config](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/base.py#L240). The `ALLOW-FROM` directive only supports a single URI, and moreover [is not supported by Chrome or Safari at all](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options).

**Comment by mmcfarland** [comment]
That's fine, since we're targeting a view for an iframe and have public projects, I think it may be a nice bonus feature to have embeddable iframes.
