### ISSUE TITLE
Boundary outlines do not appear locally

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/model-my-watershed#429]
Try loading the application, then clicking on `Select by Boundary` and then `Congressional Districts`.  The congressional district outlines will not appear, you will see something like this in the "network" part of the console:

```
GET http://localhost/0/10/298/388.png net::ERR_CONNECTION_REFUSED
GET http://localhost/0/10/297/387.png net::ERR_CONNECTION_REFUSED
GET http://localhost/0/10/299/387.png net::ERR_CONNECTION_REFUSED
```

I think it is because [this line](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/views.py#L234) no longer references the port that should be used.

**Comment by kdeloach** [comment]
We could update the default `TILER_HOST` setting https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/base.py#L254.

**Comment by mmcfarland** [comment]
These are working locally for me - I suspect your  tiler may need to get restarted.

**Comment by jamesmcclain** [comment]
`http://localhost/0/10/298/386.png` fails for me, but `http://localhost:4000/0/10/298/386.png` succeeds.  I think it is because the port number is no longer used to build the string on [line 234 of `modeling/views.py`](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/views.py#L234).

**Comment by mmcfarland** [comment]
http://33.33.34.35/0/11/595/774.png is the structure for tiler URLs that my setup is producing.  I'd try reprovisioning your app/tiler.

**Comment by jamesmcclain** [comment]
Probably so.
