### ISSUE TITLE
Error loading saved projects

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#443]
Stack trace:

Uncaught TypeError: Cannot read property 'get' of undefinedmain.js:6968 isEditablemain.js:6393 Marionette.LayoutView.extend.templateHelpersvendor.js:5070 Marionette._getValuevendor.js:6198 Marionette.View.Backbone.View.extend.mixinTemplateHelpersvendor.js:6602 Marionette.ItemView.Marionette.View.extend._renderTemplatevendor.js:6573 Marionette.ItemView.Marionette.View.extend.rendervendor.js:7464 Marionette.LayoutView.Marionette.ItemView.extend.rendervendor.js:5651 Marionette.Region.Marionette.Object.extend.showmain.js:6226 Marionette.LayoutView.extend.reRendermain.js:6238 Marionette.LayoutView.extend.onShowvendor.js:5200 (anonymous function)vendor.js:6423 Marionette.View.Backbone.View.extend.triggerMethodvendor.js:5236 Marionette.triggerMethodOnvendor.js:5695 Marionette.Region.Marionette.Object.extend.showmain.js:4439 initViewsmain.js:4369 (anonymous function)vendor.js:23945 jQuery.Callbacks.firevendor.js:24057 jQuery.Callbacks.self.fireWithvendor.js:29110 donevendor.js:29451 jQuery.ajaxTransport.send.callback

**Comment by caseypt** [comment]
When loading a project with one additional scenario from the default (so there are 3 total), the project loads, but some of the scenario tabs are missing.

**Comment by kdeloach** [comment]
Scenarios are saving with the incorrect project ID.
