### ISSUE TITLE
Animate DetailsView in Analyze

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#461]
In https://github.com/WikiWatershed/model-my-watershed/pull/456, we never got the animation of the DetailsView (containing the table and chart) to work as described in #80. There was a tricky bug involving CSS layout that we couldn't figure out. This will probably require extensive consultation with Design, although we did figure out how to do the sliding animation in principle using the transform and transition CSS keywords.

**Comment by ajrobbins** [comment]
We're no longer seeking to implement this animation.
