### ISSUE TITLE
DRF endpoints show GUI in production

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#471]
I had assumed that the DRF GUI was associated with the Django `DEBUG` settings.  If you are logged in, this will give you a nice screen of your projects:

https://mmw.azavea.com/api/modeling/projects/

Is this something we should turn off?  Presumably the endpoint would continue to give json output, and one can still get to it via the browser (https://mmw.azavea.com/api/modeling/projects/?format=json).

**Comment by rajadain** [comment]
Yeah we should definitely turn that off. Especially since it isn't just a read-only view, it actually allows users to submit POST requests in a form at the bottom.

**Comment by lewfish** [comment]
So, we just want to turn this off in production right, since it could be useful during development?

**Comment by mmcfarland** [comment]
Correct - and just the GUI part, it'll obviously still return whatever data it's meant to.
