### ISSUE TITLE
Geolocation error alert

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#475]
On my laptop, I get the following error when clicking the "locate me" button.  It may be some networking error, but we should find a better way to handle the error, even if it's coming from within the location plugin.
![screenshot from 2015-06-18 21 40 59](https://cloud.githubusercontent.com/assets/1014341/8245877/0e6e39ea-1603-11e5-8838-29209a02cf62.png)

**Comment by mmcfarland** [comment]
This must have been a transient network error, not repeated or reported by users.

**Comment by kdeloach** [comment]
I actually get this error for pretty much every application that asks for my location, on my workstation. Not sure why.
