### ISSUE TITLE
Turn off geolocation tracking

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#479]
The "geolocate me" feature should just provide and initial coordinate to set the initial extent of the map.  Currently, the site tracks the user location, and after about a minute of use, the page will re-navigate to the users location, disrupting the view they've constructed.

Should be considered with #460 (and may be the same fix).

**Comment by rajadain** [comment]
I can still reproduce this on Staging. Should I reopen and move this to the backlog?

**Comment by mmcfarland** [comment]
Yeah, could you reopen and list the steps you use to recreate it? I haven't been able to.

**Comment by rajadain** [comment]
The steps to reproduce are the following:

 1. Navigate to a far away place, like New York, and draw an area of interest
 2. Navigate to a different tab in Chrome and wait 30 - 60 seconds
 3. Navigate back to first tab, move mouse (but don't click), or hover over the navigation icon:  
  ![pasted_image_7_2_15__12_31_pm](https://cloud.githubusercontent.com/assets/1430060/8482263/8571703a-20b6-11e5-805a-444846aa6de7.png)
 4. You will be brought back to your own location

**Comment by lewfish** [comment]
We think this is being caused by leaflet.locatecontrol.

**Comment by mmcfarland** [comment]
Yeah, I've used the navigator function a bunch without experiencing this issue, suspecting the leaflet plugin seems reasonable.

**Comment by lewfish** [comment]
I can't reproduce this, so moving on to another task for now.

**Comment by rajadain** [comment]
I can reproduce this on my machine, will take a stab at it after I finish my current task.
