### ISSUE TITLE
Leaflet attribution not visible in /model view when results panel minimized

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#497]
Because of the way the results panel is positioned over the map, the Leaflet attribution is hidden behind it:

Visible Full Size
![image](https://cloud.githubusercontent.com/assets/1430060/8333404/b256a928-1a60-11e5-91fb-fc2e07a5aee7.png)

Visible Half Size
![image](https://cloud.githubusercontent.com/assets/1430060/8333415/bca03f7a-1a60-11e5-8804-6a99e5cdc65c.png)

Not Visible Full Size with Results Panel Header
![image](https://cloud.githubusercontent.com/assets/1430060/8333432/ccdd46c6-1a60-11e5-9810-6918374bb90a.png)

If we get rid of the Half Size view in #401 then the `/model` view will never have the attribution visible. Adjust the map size so that the attribution is visible when the panel is minimized.

**Comment by caseypt** [comment]
Since the analyze and modeling pages have been redesigned, this is no longer an issue.
