### ISSUE TITLE
Investigate feasibility of running Accumulo on EMRFS

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#5]
EMRFS is an implementation of HDFS which allows Amazon Elastic MapReduce (EMR) clusters to store data on Amazon S3. Unclear of all the details, but this could potentially get us out of having to deploy and manage HDFS as the file system for Accumulo.

---

### Resources

- http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-fs.html

**Comment by mmcfarland** [comment]
Currently using SJS.
