### ISSUE TITLE
Get national SSURGO dataset for hyrdologic soil groups

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#50]
Soil Survey Geographic (SSURGO) Database is high resolution national vector dataset with many soil attributes.  These are typically only stiched together at the county level.  There are some gridded products (gSSURGO) which come as statewide rasters with values for specific attributes.  We're interested in Hydrologic Soil Groups (A-D).  

STATSGO is a lower resolution dataset with the similar attributes.  We'll try to assembly the higher resolution data first, but this could be a fallback.

**Comment by mmcfarland** [comment]
Updated reclassifications from Barry:

1) Use A, B, C or D where designated
2) If A/B, use B
3) If B/C, use C
4) If C/D, use D
5) If A/D, use C
6) If B/D, use C

**Comment by chitchens** [comment]
I have an email in to USDA for specific info on how to get the gSSURGO data. I'll send a drive as soon as I have details.

**Comment by mmcfarland** [comment]
Data has been received.
