### ISSUE TITLE
Internet Explorer 11 issues

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#504]
This is not a high priority card right now, more a place to record issues in IE 11 as we come across them.
1. SVG Patterns do not render. Consider having a solid color fill fallback.
2. Precipitation slider does not render.  
   ![screen shot 2015-06-25 at 11 33 48 am](https://cloud.githubusercontent.com/assets/1430060/8358470/5728819c-1b2e-11e5-8360-f94086ea064f.png)
3. On a touch screen computer, polygons cannot be drawn.

**Comment by ajrobbins** [comment]
Fixed in https://github.com/WikiWatershed/model-my-watershed/pull/939, and we switched to a new Leaflet.Draw fork in https://github.com/WikiWatershed/model-my-watershed/pull/502
