### ISSUE TITLE
Remove Model and Collection suffix in favor of singular and plural nouns

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#523]
`ScenarioModel` becomes `Scenario`, `ScenarioCollection` becomes `Scenarios`, etc.

Should be simple, but there's a lot of things to update.

**Comment by caseypt** [comment]
See discussion on https://github.com/WikiWatershed/model-my-watershed/pull/513

**Comment by caseycesari** [comment]
I don't believe this would be worth the effort now, given how much we've implemented the current pattern.
