### ISSUE TITLE
Android Tablet Issues

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#526]
These issues have been observed on a Nexus 7 (2013) running Android 4.4 KitKat and Chrome 43.
- On Android, tapping a modification tile once selects it, and there is no hover state so the description is never shown:  
  ![screenshot_2015-07-01-11-24-18_skitch](https://cloud.githubusercontent.com/assets/1430060/8458544/af895490-1fe5-11e5-8815-a4e2037da37e.png)
- Also seen above is the oddly positioned "Modifications" dropdown button

The general layout of the app otherwise is satisfactory, except for the problematically placed Django Toolbar button which thankfully is only ever present in the dev environment.

**Comment by ajrobbins** [comment]
We switched to a new leaflet.draw fork in https://github.com/WikiWatershed/model-my-watershed/pull/502, and positioning is correct on Android.
