### ISSUE TITLE
iPad Issues

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#527]
Taken on iPad Mini 2 running iOS 8.3.
- The modifications dropdowns has width issues:  
  ![2015-07-01 11 07 36](https://cloud.githubusercontent.com/assets/1430060/8458809/1e7cfde2-1fe7-11e5-87bb-5e6ded9f31a3.png)
- In some cases, the modification thumbnails are offscreen and the user cannot scroll below to see them:  
  ![2015-07-01 11 07 23](https://cloud.githubusercontent.com/assets/1430060/8458828/3d1743ac-1fe7-11e5-864b-38de5bb48f7f.png)
- Unlike behavior on Android, on an iPad tapping once simulates a Hover, and tapping twice simulates a Click (selection). Thus the user must tap twice on any modification to select it, which is not very obvious. Also, when the user is in the "Draw" mode, there is no visual feedback for this (unlike on the desktop where the cursor changes and has an attached tooltip).

**Comment by ajrobbins** [comment]
No longer observed.
