### ISSUE TITLE
Create Input Model/Collection for model inputs

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#529]
Model inputs are currently using `ModificationModel` and `ModificationCollection`, which results in the inputs having modification fields, like `area` and `shape`.

![image](https://cloud.githubusercontent.com/assets/1042475/8461545/7f38f7f8-1ffb-11e5-8e75-2a4307ace9a3.png)

Inputs should have their own model and collection.

**Comment by kdeloach** [comment]
Forgot to reply to this in the PR. This is a good idea, but I didn't feel like there was enough of a difference between inputs & modifications (from a data point of view) to justify unique model/collection classes.

**Comment by caseypt** [comment]
Yeah, there isn't much considering they are arbitrary both JSON blobs, but I think it might be confusing down the line when we are debugging and writing new code against the inputs. We may think one of those fields is supposed to be there, or we may need to a field with the same name in a different way.

**Comment by caseypt** [comment]
This is unlikely to be changed and hasn't proved to be problem.
