### ISSUE TITLE
Refactor Celery Task Identifier

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#557]
## Introduction

Each task in a Celery Task has a unique identifier (UUID). A Celery Chain has the UUID of the final task in the chain. Consider [`_initiate_tr55_job_chain`](https://github.com/WikiWatershed/model-my-watershed/blob/847aa082b35bf20270ac39801849cbb49416d487/src/mmw/apps/modeling/views.py#L212-L216):

``` python
def _initiate_tr55_job_chain(model_input, job_id):
    return chain(tasks.make_gt_service_call_task.s(model_input),
                 tasks.run_tr55.s(model_input),
                 save_job_result.s(job_id, model_input)) \
        .apply_async(link_error=save_job_error.s(job_id))
```

In [`start_tr55`](https://github.com/WikiWatershed/model-my-watershed/blob/847aa082b35bf20270ac39801849cbb49416d487/src/mmw/apps/modeling/views.py#L193-L209), we return this chain's UUID to the client so they may poll for status:

``` python
def start_tr55(...):
    ...
    task_list = _initiate_tr55_job_chain(model_input, job.id)
    job.uuid = task_list.id
    job.save()

    return Response({
        'job': task_list.id,
        'status': 'started',
    })
```

Later, in [`get_job`](https://github.com/WikiWatershed/model-my-watershed/blob/847aa082b35bf20270ac39801849cbb49416d487/src/mmw/apps/modeling/views.py#L163-L184), the same UUID is used to get the status of a running job:

``` python
def get_job(..., job_uuid):
    ...
    job = get_object_or_404(Job, uuid=job_uuid, user=user)
    ...
    return Response(
        {
            'job_uuid': job.uuid,
            'status': job.status,
            'result': job.result,
            'error': job.error,
            'started': job.created_at,
            'finished': job.delivered_at,
        }
    )
```
## Inconsistency

The UUID of the chain, which is actually the UUID of the last task in the chain, which in this case is `save_job_result`, is always stored in the MMW database in `core_job`. In case of success, this task is recorded in Celery and is available for viewing in Flower. However, if there is an exception in one of the earlier tasks in the chain, this final task is never executed and never recorded in Celery and is not available in Flower. For example, a successful run of `_initiate_tr55_job_chain` would be:
1. :white_circle: `tasks.make_gt_service_call_task`
2. :white_circle: `tasks.run_tr55`
3. :white_circle: `save_job_result` 

But an unsuccessful run would be:
1. :white_circle: `tasks.make_gt_service_call_task`
2. :red_circle: `tasks.run_tr55`
3. :white_circle: `save_job_error`

where :white_circle: indicates successful completion of task, and :red_circle: indicates failure.

Since the UUID used in the API corresponds to `save_job_result`, linking that to the failing `tasks.run_tr55` is difficult. Currently we must follow [these steps](https://github.com/WikiWatershed/model-my-watershed/pull/551#issuecomment-119333146):

> - Using the failing job's UUID, find the job's internal ID:  
> 
> ``` sql
> SELECT id FROM core_job WHERE uuid = 'e7394277-962e-4996-a8a8-653e982c16c1';
> 
> id
> ---
> 675
> ```
> - Using this internal ID, grep the logs (or search in [Kibana](http://localhost:5601/#/discover?_a=%28columns:!%28tags%29,filters:!%28!n,%28meta:%28disabled:!f,index:'*',key:tags,negate:!f,value:celery%29,query:%28match:%28tags:%28query:celery,type:phrase%29%29%29%29%29,index:'*',interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:exception%29%29,sort:!%28'@timestamp',desc%29%29&_g=%28time:%28from:now-12h,mode:quick,to:now%29%29)):  
> 
> ``` shell
> $ vagrant ssh worker -c 'grep "job 675" /var/log/celery/*'
> 
> /var/log/celery/worker1.log:[2015-07-07 16:05:26,061: ERROR/Worker-1] Task 233509e8-bb76-41f2-8e6e-9c8ad6e8c149 run from job 675 raised exception: No precipitation value defined
> ```
> - Use this task ID to see details in Flower: [`http://localhost:5555/task/233509e8-bb76-41f2-8e6e-9c8ad6e8c149`](http://localhost:5555/task/233509e8-bb76-41f2-8e6e-9c8ad6e8c149)
> 
> ![image](https://cloud.githubusercontent.com/assets/1430060/8556858/ba9fd872-24c7-11e5-8483-b78e0433c113.png)
## Possible Solutions
1. One solution might be to use the UUID of the chain when logging the error, which would allow an engineer to find the failing job in Kibana using the job ID used in the API call. This would be difficult though since that UUID might not be available to `save_job_error` which is what writes to the log.
2. Another solution might be to generate a new UUID in `start_tr55` and use that instead of the chain's (rather unreliable) ID. This will allow us to explicitly name each job throughout our system, from client API to out database to Celery, thus making tracing easier. We can also make this available to all tasks in the chain, without having to wait for any to finish first. However, since this will touch a number of aspects of the system it will require careful testing to ensure that current behavior is still functional.

When working on this card, please also look at #316. Solution to one may help guide the other.

**Comment by ajrobbins** [comment]
With our work to shift to the Collections API, these Celery improvements are no longer needed.
