### ISSUE TITLE
Layer selector broken in Analyze after drawing shape

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#559]
After drawing a shape and being directed to the Analyze view, if you select the Default layer and then the World Imagery Layer, the layer does not show up, and some error messages are shown in the console. This only happens when the area of interest is drawn, and is not a Congressional District.

This might not be worth fixing because we might decide to hide the layer selector outside of the main map view.

**Comment by mmcfarland** [comment]
This may have been inadvertently fixed.

**Comment by lewfish** [comment]
The bug is still present on develop as of right now.

**Comment by lliss** [comment]
I just tested on staging and could not reproduce on firefox on chrome.

**Comment by mmcfarland** [comment]
Sadly, this bug is not present on the main repo and only occurs on the fork we use for touch support.  I'll continue to track it down and see if it is something that can patched easily on the fork.
