### ISSUE TITLE
Clone project via URL flag

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#560]
#### Start from an existing project

ITSI portal Activities will be initiating student assignments via a GET request to a per-assignment URL.  Teachers can specify a base project, which may include an AoI, scenarios, model package and any number of modifications.  By creating a project and copying the URL, they can embed that base project in an Activity.  When a student visits the Activity page, and the request is sent to our servers and could take the form of:

http://mmw.azavea.com/project/123/scenario/123?initialize_itsi=true

This would cause the original project to be copied to the currently logged in user's account and then redirect the browser to the new project, which the correspondingly mapped scenario tab (if present) active.

I'm not sure what form the `initialize_itsi=true` flag should take, but I do think it's important that we require the teacher to modify the URL from the "share" link as little as possible before submitting it to an activity.

For this issue, assume the following, whose nuances will be handled by separate issues:
* Original project is public
* Current user is logged in via ITSI

**Comment by rajadain** [comment]
We can consider adding an "Get ITSI Embed Link" option to the project dropdown, only visible to ITSI users, which will, just like the "Share" option, prompt the user to first make the project public (or even do it under the hood without asking permission?). This will enforce both assumptions.

We can set a flag in the `user` object to indicate if they are an ITSI user or not, and then use that flag to customize the Project menu.

Having the "make public" a part of the sharing will ensure that the project is public before we get the link.

Having a popup already populated with the correct URL is easier than having the teacher edit a regular Share URL.

The existing Share menu should still be available.

**Comment by mmcfarland** [comment]
@rajadain Good idea, the teacher shouldn't have to modify anything, we should have the app provide it like you suggest.
