### ISSUE TITLE
Embed MMW Interactive into ITSI Activity

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#564]
Tying all the pieces of #560, #561, #562 & #563, create a new Interactive using the MMW URL structures developed in the previous issues.  This issue is for identifying and fixing problems and assumptions with the full site.

https://learn.staging.concord.org/

**Comment by rajadain** [comment]
Scott mentioned that certain browsers like Safari may have problems setting third party cookies inside iframes. He also mentioned that the oAuth redirection dance can be fragile inside iframes. These are a few issues to watch out for when doing the final embed.

**Comment by rajadain** [comment]
When I try to create a new activity / interactive as a Teacher user, I don't see a way to embed a custom app. I can only browse and search in the existing options:

![image](https://cloud.githubusercontent.com/assets/1430060/8913041/8546af14-3464-11e5-8c45-6789f65bfef3.png)

I think we may have to talk to Scott about getting MMW into the library.

**Comment by rajadain** [comment]
With recent additions to #613 and the lack of URL manipulation as noted in https://github.com/WikiWatershed/model-my-watershed/issues/563#issuecomment-126824774, while we have a (somewhat) working implementation of #561 within an activity, we don't yet of #560 whose interface is URL-only. We will need to come up with a UI mechanism to enable cloning.
