### ISSUE TITLE
Add stream network data to setupdb script

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#581]
To support #575, the data must be available to load in dev and prod environments.  We'll want the data to be exported from @lewfish's db along the lines of:

`pg_dump -c --if-exists -O -t [table] -h localhost -U mmw mmw`

to fit in with the existing data load script.

**Comment by mmcfarland** [comment]
@lewfish if you run the above command and gzip the sql file, I'll incorporate it into the load script.  Just scp it to my machine somewhere.

**Comment by lewfish** [comment]
The files are on your machine at:
/tmp/20r.sql.gz
/tmp/50r.sql.gz
/tmp/100r.sql.gz
