### ISSUE TITLE
Compare views: scrolling improvements

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#597]
We may or may not want to add the following improvements:
- Gray out navigation buttons if clicking won't have any effect
- Connect arrow keys to navigation butttons
- Horizontal scrolling only on touch screens
- Consider making it so that clicking / tapping the off-screen scenario bring it in to view
- Consider adding sliding animation so that the change is more apparent

**Comment by mmcfarland** [comment]
Compare view is being rewritten.
