### ISSUE TITLE
Add NLCD overlay

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#601]
@echeipesh is loading tiled display rasters for the NLCD data set into S3.  Add this layer as a map overlay option when we have a URL scheme for it.

**Comment by mmcfarland** [comment]
https://s3.amazonaws.com/com.azavea.datahub.tms/nlcd/{z}/{x}/{y}.png although we may end up putting this URL behind a CloudFront CDN or similar.

**Comment by caseypt** [comment]
Is it possible to follow whatever process generated these tiles, and do the same for the watershed, congressional district, and stream layers? Just thinking of consolidating where we serve our layers from, and that this (without knowing how they were generated) seems simpler then our current set-up.

**Comment by mmcfarland** [comment]
These were generated from the raw original raster set by the GT team and use the default color classes and have no interactivity.  The other layers are sourced from vector files and also generate utfgrids of attributes we want to display and are custom styled.  I'm more hesitant to maintain a permanent cache of these things for the whole country at every zoom level since they are tweakable.  I think the changes coming with #447 provide a good mix of performance and flexibility.
