### ISSUE TITLE
Preserve unsaved project while logging in with ITSI

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#603]
If, as an anonymous user, you have an unsaved project and then initiate a login via ITSI, you are redirected away, losing your work and then ultimately end up at the base page.  We should preserve the work locally and specify a return to `/project` after the oAuth dance which should reestablish the project and initiate a save. 

Consider #399 in this work.

**Comment by ajrobbins** [comment]
Superceded by https://github.com/WikiWatershed/model-my-watershed/issues/1555
