### ISSUE TITLE
Ensure that modifications, BMPs are non-overlapping

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/model-my-watershed#608]
The Geotrellis/TR-55 work in https://github.com/WikiWatershed/model-my-watershed/pull/604 assumes that land use modifications and BMPs are non-overlapping (actually it is okay for a modification and a BMP to overlap, but not a modification and a modification or a BMP and a BMP to overlap).  

The client code should send a non-overlapping list of polygons.

**Comment by caseypt** [comment]
Related to #255

**Comment by jamesmcclain** [comment]
Ah, I was unaware that we already had an issue for this.  Should I close this issue?

**Comment by caseypt** [comment]
I'll close #255, this is more detailed.

**Comment by jamesmcclain** [comment]
Okay.
