### ISSUE TITLE
Split out geoprocessing dependencies from main base project

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#611]
The goal here is to reduce the amount of things that need to be compiled any time code changes are made to the base project.

See also: https://github.com/sbt/sbt-assembly#splitting-your-project-and-deps-jars

**Comment by mmcfarland** [comment]
@hectcastro I think this can be closed - the geoprocessing dependencies are now containerized within `mmw-geoprocessing`, right?

**Comment by caseypt** [comment]
I also think this can be closed now.
