### ISSUE TITLE
Micro site produces a large number of requests for static assets

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#618]
May be related to Retina.js, but regardless, it would be good to lower this number of requests some how (maybe lazily loading or CSS sprites):

<img width="676" alt="model_my_watershed_-_micro_site_storm_model" src="https://cloud.githubusercontent.com/assets/43639/8917093/0265d650-347e-11e5-8f7f-f3aca7ea712f.png">

**Comment by rajadain** [comment]
Since a number of these assets are used _only_ on this page, we may consider using sprites, and downloading one big image rather than a large number of smaller ones.

**Comment by rajadain** [comment]
Might be preferable to do try the CDN idea first #1483

**Comment by rajadain** [comment]
I was just looking at Retina.js, and found that when running via JavaScript it does a `HEAD` request first to check the file exists, and then `GET` request for the actual file. The latest version of Retina.js does support mixins for SCSS https://github.com/imulus/retinajs#media-queries which we could use to bake the behavior into our CSS, thus reducing the number of requests by a third. `HEAD` requests are pretty lightweight though, not sure how much of a benefit in terms of scalability that would be.

**Comment by mmcfarland** [comment]
Micro-site has been removed to it's own s3 website.
