### ISSUE TITLE
Geocoder searching, error, and no results mock-ups

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#62]
We need mock-ups/designs around what the the geocoder should do/look like when

- A searching is being executed
- An error occurred
- There are no results for the current query

**Comment by caseypt** [comment]
Since we are using a difference service for suggestions and geocoding, we need a mockup for when you click on a result in the list and are waiting for the geocode response.

**Comment by caseypt** [comment]
Also, I think we should implement this soon.

**Comment by ctaylo37** [comment]
I think we should have the loading spinner in-line with the result that has been clicked:

![image](https://cloud.githubusercontent.com/assets/5880793/8161790/3c59d5da-1347-11e5-821b-1b23c97731c4.png)

**Comment by mmcfarland** [comment]
This would be a nice-to-have for this sprint, but not a main priority.  Updated label.
