### ISSUE TITLE
Model output tabs are reversed

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#624]
Runoff should remain the initial tab on the output window, currently Water Quality is.

![screenshot from 2015-07-28 12 37 17](https://cloud.githubusercontent.com/assets/1014341/8937298/7ce54058-3525-11e5-8c89-d0ad40e0d815.png)

**Comment by rajadain** [comment]
Modifications also seem to be reversed:

![image](https://cloud.githubusercontent.com/assets/1430060/8961605/35bd6fb0-35e4-11e5-8ff4-abf4ed63cbde.png)

I wonder if it has anything to do with the re-ordering of internal representation done for #548
