### ISSUE TITLE
Add 1km² "stamp" drawing tool

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#625]
Allow the user to place a fixed-size (1km²) square as an Area of Interest selector.  Ideally, we could show the square size as it's being placed, but I suspect it will be much easier to place a point and generate the polygon similarly to how we're mocking the delineate watershed feature.

**Comment by caseypt** [comment]
See this project for a potential implementation: http://apps.npr.org/moore-oklahoma-tornado-damage/

**Comment by mmcfarland** [comment]
We are going to change the "Draw Area" button to a "Draw" dropdown that includes both Draw Area and a new option for this "Draw Square Km" tool.  This is similar to the Delineate dropdown.
