### ISSUE TITLE
Add pre-columbian output to display

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#626]
When (https://github.com/WikiWatershed/tr-55/issues/36) TR-55 produces pre-columbian values, we need to include the results in the display.  Still need to determine where it should show up:

* Just current conditions?
* ~~Every scenario?~~
* ~~As a component of compare?~~

**Comment by mmcfarland** [comment]
Add to the "Current Conditions" tab.

**Comment by mmcfarland** [comment]
Blocked until https://github.com/WikiWatershed/tr-55/issues/39 is resolved.

**Comment by caseypt** [comment]
Version 0.2.0 released https://github.com/WikiWatershed/tr-55/releases/tag/0.2.0
