### ISSUE TITLE
Add overlay layers and control

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#629]
Initially, let's reuse the 4 existing boundary layers + a new layer for school districts (we need to source this data).

We should merge the basemap control this control with input from @ctaylo37

**Comment by mmcfarland** [comment]
These layers are merely for display and don't need initially need utfgrid support initially.  Overlays should be available in all draw/analyze/model maps windows.

**Comment by caseypt** [comment]
Re: school districts, are we looking for a dataset that covers the entire U.S.?

**Comment by mmcfarland** [comment]
> Re: school districts, are we looking for a dataset that covers the entire U.S.?

Yes, we were told it exists nationally.

**Comment by caseypt** [comment]
School district work should be done in #730
