### ISSUE TITLE
Ensure activity mode is not set it a user doesn't own the activity

### ISSUE THREAD

**Issue by lliss** [WikiWatershed/model-my-watershed#630]
Related to the work in https://github.com/WikiWatershed/model-my-watershed/pull/610

If an activity (project with activity flag set to true) is public and a user visits it who is not the activity owner, then activity mode is activated and the user will not be allowed to create new projects. Attempting to do so will fire DELETE requests at the API to remove the scenarios on the project/activity but these will be denied by the API.

**Comment by ajrobbins** [comment]
Implemented, closing.
