### ISSUE TITLE
Clear boundry layers after choosing to cancel modifications in activityMode

### ISSUE THREAD

**Issue by lliss** [WikiWatershed/model-my-watershed#631]
Related to https://github.com/WikiWatershed/model-my-watershed/pull/610

When a user is in activity mode (a result of creating a project via ITSI portal) then they will continue to overwrite the same project throughout the session. If they try to change the AOI we prompt them to confirm such changes because they necessarily destroy the validity of the current scenarios on the project.

If the user attempts to use the boundary selection tool they are prompted to confirm or deny this change. If they deny it, the boundary tool does not go away and clicking resets the AOI, though it does not overwrite the existing project data.

**Comment by rajadain** [comment]
Here's an illustration of the problem:

![mmw-clear-aoi-issue-3](https://cloud.githubusercontent.com/assets/1430060/8942801/792d5778-3545-11e5-92ec-480850671ab8.gif)

> If going back to existing AoI and selecting "Boundary Layers", they are still clickable if they are within the AoI, and lead to an inconsistent state.

> But the good thing is that the inconsistency isn't persisted, as seen in the above GIF. The only thing it might affect are the model results for which we send the AoI each time, and they aren't recalculated when loading the project next time because the inputs and modifications are the same, but the AoI is different.

[source](https://github.com/WikiWatershed/model-my-watershed/pull/610#issuecomment-125745361)

**Comment by ajrobbins** [comment]
The post-revamp user interface has a "New Project" button to restart the project. Boundary layers behave as expected.
