### ISSUE TITLE
Updates to support mobile device screen size

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#633]
From the Education Team:

> Scaling of the interface needs to be formatted to work on mobile devices in all alignments - no overlapping (approximately 30% of our classrooms will be accessing MMW solely from mobile devices.)

**Comment by mmcfarland** [comment]
The stream slider will be getting moved to it's own control area shortly, but when working on this task, #659 is related.

**Comment by kdeloach** [comment]
Is this done?

**Comment by mmcfarland** [comment]
Touch/small screen issues have been resolved and an updated UI is proposed and wireframed.
