### ISSUE TITLE
Cancel Warning in Activity Mode is inconsistent

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#638]
## Overview

When starting a new project in Activity Mode #610, the Cancel Warning is correctly shown before resetting a shape, and it is correctly restored:

![mmw-clear-aoi-issue-4-1](https://cloud.githubusercontent.com/assets/1430060/8961717/ca6d70d8-35e4-11e5-958d-4858edc46e55.gif)

However, when returning to a project for which `is_activity` is set, the Cancel Warning is not shown until after the shape has been reset, and canceling does not restore the original shape:

![mmw-clear-aoi-issue-4-2](https://cloud.githubusercontent.com/assets/1430060/8961756/188fd102-35e5-11e5-9491-f0e33bb60d7f.gif)

Possibly related to #630 / #631 
## Instructions to reproduce
1. Go to the home page of the app, and use the `/?itsi_embed` flag to enable embed mode.
2. Create a project
3. Go back to analyze and draw views and reset the shape. You should see the warning before resetting, and clicking "Cancel" should restore original shape.
4. Log out. Log back in using the ITSI button in the Login screen.  
   _This step is necessary because if the `itsi_embed` session variable is set `activityMode` will always be enabled, so we need to end the current session and start a new one._
5. Go to the project created in step 2. `activityMode` should now be set.
6. Go back to analyze and draw views and reset the shape. You should not see a warning before resetting, only when you draw a second shape. And if you click "Cancel" in that second shape, your original shape will not be restored.

Ideally, step 6. should be identical to step 3.

**Comment by ajrobbins** [comment]
We no longer have this warning post-UI revamp.
