### ISSUE TITLE
Height keeps growing in /compare on Firefox

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#642]
Before adding a kludge to fix it, in the compare views in Firefox, every time a drop down was clicked, the map-regions grew vertically. The kludge was to make the sum of the heights of the regions in each column sum to 95%. This fixed the problem for me on Firefox 38.0.5, but not for @rajadain on Firefox 39.0. We should find a better solution if possible. See #596.

**Comment by rajadain** [comment]
This seems to have been fixed in one of the recent Compare view PRs. Can you talk about how it was fixed and close this card? I can no longer reproduce this with my Firefox 40.0

**Comment by lewfish** [comment]
This was fixed by using units of vh instead of % for the height of the regions in each column. I'm not sure why this works.
