### ISSUE TITLE
Add Alert Modal

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#645]
Currently we have a Share Modal, an Input Modal, and a Confirmation Modal. We need to add an Alert Modal which shows a message, perhaps an Icon (to differentiate Info vs Warning vs Error or something along those lines), and a dismiss button (OK or something). The user should also be able to dismiss it by clicking anywhere outside or using <kbd>Esc</kbd>.

Replace current usage of `window.alert` with this Modal.

**Comment by jamesmcclain** [comment]
The code introduced in https://github.com/WikiWatershed/model-my-watershed/pull/932 should be updated to use this new modal (the `window.alert` should be replaced).

**Comment by mmcfarland** [comment]
We have a number of `window.alert` usage now and I think it's time to create this and replace the usage across the app.
