### ISSUE TITLE
Prepare SSURGO data

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#646]
We have raw USDA gSSURGO data, we'll need to evaluate its content and format so we can work with GT team to get this data into our S3 data bucket.

Updated reclassifications from Barry Evans:

1) Use A, B, C or D where designated
2) If A/B, use B
3) If B/C, use C
4) If C/D, use D
5) If A/D, use C
6) If B/D, use C

**Comment by caseypt** [comment]
Just an idea, but I think this sort of information should be exposed to the user somewhere in the UI along with any other conversions or assumptions we made. Maybe some sort of model/data details?

**Comment by mmcfarland** [comment]
Yeah, and in fact we have non-trivial changes added to TR55 in generally.  There were talks previously about having a model details page for each of models that give specific implementation details.  I don't remember if we ultimately decided that this should belong on the github page for the model or not, but we should have an issue to track this and make sure it happens.

**Comment by caseypt** [comment]
Cool. I'll create it.

**Comment by mmcfarland** [comment]
A new approach has been identified for generating the final product, and this card was used to generate a "raw" mukey value raster and a corresponding attribute table for hydrological soil groups.
