### ISSUE TITLE
Windows Touch Screen support

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#649]
With work on #502 we established some parameters of devices that we were willing not to support due to problems in our L.Draw fork.  A workshop user was unable to close a polygon on the draw screen using an HP Intel ProBook, which is claiming _not_ to be a touch device, although the screengrab of the settings for that computer indicate that there is some touch support (see `System` -> `Pen and Touch` below).

![img_0542](https://cloud.githubusercontent.com/assets/1014341/9007774/aab1e448-3762-11e5-82ca-b2bf461f39f0.jpg)

**Comment by rajadain** [comment]
Just tested on a Windows touchscreen with Leaflet.Draw [0.3.0](https://github.com/Leaflet/Leaflet.draw/releases/tag/v0.3.0) (latest release version) and [0.3.2](https://github.com/Leaflet/Leaflet.draw/releases/tag/v0.3.2) (latest available tag), with not great results.

Chrome 52 still doesn't close shapes when using the mouse. Touch works correctly.
Firefox 42 closes shapes correctly using the mouse, but Touch is _really_ flaky.
Edge and IE11 seem to be working perfectly in both cases, which is an improvement over the last version where the site wouldn't render in IE.

So for our Windows users, we should recommend Edge.

I'm going to put up a PR that upgrades to 0.3.0, the latest stable version. There is https://github.com/Leaflet/Leaflet.draw/issues/548, which I've subscribed to. Unfortunately, if we want to investigate the guts of Leaflet.draw to see if this can be figured out, we'll need more points.
