### ISSUE TITLE
On small screens, zoom buttons are inaccessible

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#659]
On small screens, the zoom buttons are covered by the container div for the other map tools and can only be clicked along their outer right edge.

<img width="347" alt="screen shot 2015-08-03 at 2 26 45 pm" src="https://cloud.githubusercontent.com/assets/1042475/9044609/c5ac089c-39eb-11e5-9f7c-f00314d7dfff.png">

The map tools are generally a little squeezed:

<img width="1278" alt="screen shot 2015-08-03 at 2 28 11 pm" src="https://cloud.githubusercontent.com/assets/1042475/9044627/dbf2fad4-39eb-11e5-9a6e-0b6006f09624.png">

**Comment by mmcfarland** [comment]
After removing stream slider and delineate, there is room for navigation controls on a portrait mode iPad
![screenshot from 2015-09-21 11 33 45](https://cloud.githubusercontent.com/assets/1014341/9996362/b2ceec1e-6054-11e5-884c-24159a55ab2d.png)
