### ISSUE TITLE
Consider allowing the compare panels to fill the visible space on the page

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#679]
There is a lot of unused real estate when only comparing a few scenarios, even on a small screen:

<img width="638" alt="screen shot 2015-08-11 at 10 39 10 am" src="https://cloud.githubusercontent.com/assets/1042475/9200309/36266ade-4015-11e5-8483-b13012aad0a9.png">

**Comment by mmcfarland** [comment]
Closing, new wireframes exist for a re-imagined compare screen.
