### ISSUE TITLE
Handle charts where bars all have value of zero

### ISSUE THREAD

**Issue by lewfish** [WikiWatershed/model-my-watershed#686]
When the models are run with a precipitation of zero, the bars in the Water Quality chart are all zero. In this case the bars are not visible, and the x-axis disappears since the bars don't span a range of values. A better way of handling this might be to display a message to the user in place of the usual chart.

**Comment by ajrobbins** [comment]
We will be replacing the WQ bar chart with a bullet chart https://github.com/WikiWatershed/model-my-watershed/issues/2165
