### ISSUE TITLE
Scenario tab order is changed after save+reload

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#689]
Saving a project with one scenario, then reloading the project resulted in Current Conditions being the 2nd tab instead of the first.

![screenshot from 2015-08-13 09 23 41](https://cloud.githubusercontent.com/assets/1014341/9250823/de379eee-419d-11e5-8142-e9b5c80c85dc.png)

**Comment by rajadain** [comment]
My initial guess for why this is happening is: when saving a project we send simultaneous `POST` requests for both scenarios, but we cannot guarantee the order in which they will be received by the server. In cases when the "New Scenario" gets created before "Current Conditions", it has a lower `id` and thus appears first when ordered by ascending `id`.

When loading a project, we should pick "Current Conditions" from the collection and always make it the first scenario before [making it active](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/models.js#L647).
