### ISSUE TITLE
Saved project should persist in forward navigation

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#690]
Currently, if you are on a /project page for a saved model, navigate back to Analyze via the UI back button, and then move forward again, you are started at a blank project.  The saved project should persist during this kind of navigation - perhaps even back to the Draw page, similarly to the "Single Activity Mode" created for ITSI integration.

**Comment by caseypt** [comment]
I imagine this will require a bit of reworking how we are storing the current project.

When doing this, consider renaming `currProject` to `currentProject`.
