### ISSUE TITLE
Safari makes multiple "Get Your Location" requests

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#691]
Users are reporting that Safari will request to gain access to your location multiple times, sometimes being satiated after 3 times, but often occurring infinitely, requiring a Force Stop.

Reported version:
Safari  Version 8.0 (10600.1.25.1)

**Comment by caseypt** [comment]
Verified this is happening in 8.0.7. Stuck in an infinite loop.
