### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#698]
Include a Stroud-linked account for Google Analytics, we'll need specific details on what events they would like to track and what might been to be split out into a separate metrics tracking path in the app.

**Comment by mmcfarland** [comment]
@SRGDamia1  @chitchens Can you provide a Google Analytics key that you'd like to use in production?

**Comment by SRGDamia1** [comment]
I think @chitchens should already have a key.

**Comment by chitchens** [comment]
@SRGDamia1 Hmm...if I did, I don't think I do anymore.

**Comment by SRGDamia1** [comment]
I think I'm confusing Google Analytics with Amazon Web Services.  I'll check with @aufdenkampe on it.

**Comment by mmcfarland** [comment]
The Stroud GA key  is `UA-47047573-7`

**Comment by mmcfarland** [comment]
When this gets released, we should ask Stroud to verify that requests are logging into their account.

**Comment by SRGDamia1** [comment]
Looking at the latest analytic report from @HeatherBrooks , I'm not quite sure if the analytics are actually working right or not.  We're seeing hits for /analyze and /project but we're not seeing any hits for /micro.  I know I've hit the micro site a number of times myself so it should show page hits.

For some reason, GitHub isn't allowing me to attach the pdf of the analytics. Sorry!

**Comment by mmcfarland** [comment]
Thanks for the comment - we'll check to make sure that the embedded code is also in the micro site

**Comment by mmcfarland** [comment]
Re-closing - refer to #920
