### ISSUE TITLE
In Firefox, precipitation slider label overlaps control, and control sits outside of container

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#699]
![screen shot 2015-08-13 at 1 26 34 pm](https://cloud.githubusercontent.com/assets/1042475/9256748/4ab9f410-41bf-11e5-9bf8-d49e9f4d7aa4.png)

**Comment by kellyi** [comment]
Was looking through old issues and I think this one might be the same problem referenced in #1184

**Comment by kellyi** [comment]
Closing this one
