### ISSUE TITLE
Add "geop" VM to vagrant setup

### ISSUE THREAD

**Issue by jwalgran** [WikiWatershed/model-my-watershed#7]
The geoprocessing VM (geop) is the host for scala/geotrellis web services.

  * Provisioning should be based on https://github.com/geotrellis/vagrant.geotrellis
  * OpenJDK 1.7
  * Scala 2.10

**Comment by mmcfarland** [comment]
We had talked about doubling up some VMs so as to not have unnecessary overhead of another VM.  I'm thinking that `tiler` would be a good candidate since it's probably the least utilized and would still be disassociated from `app` & `worker`, so we'll have higher confidence that services are exposed and separated correctly.  Thoughts?  

@kdeloach @hcastro

**Comment by hectcastro** [comment]
Didn't see this until today.

I agree that the `tiler` is the most underutilized VM in the bunch. My only concern is that we make sure all of the GeoTrellis dependencies get recorded, even if they happen to overlap with whatever local VM we put it on. That way, when we separate things later, everything will still work.

I still don't feel like I have a clear picture of how work makes it to GeoTrellis and back. Are we still planning to funnel jobs through Celery, then hit a GeoTrellis HTTP endpoint and wait for it to complete?

Also, do we know how large the development data set needs to be? If we plan to use the S3 catalog for production, can we get away with a smaller catalog in S3 as well for development?

**Comment by mmcfarland** [comment]
@hectcastro 
Yeah, that's still the approach.  Ideally, we'll be replacing [this](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/tasks.py#L127-L152) with an HTTP call to a geop endpoint and some post-processing of results.

I don't know what a sufficient size would be for development.  From my perspective, having something the size of the [DRB](https://www.google.com/search?q=delaware+river+basin&espv=2&biw=1272&bih=940&tbm=isch&tbo=u&source=univ&sa=X&ved=0CC8QsARqFQoTCLK-huid28YCFcg0PgodXscDxQ#imgrc=YxTZPbiWoj2hgM%3A) would work well, but I'm not sure if that's too large to have functional code pulling things down from S3 locally.  I suspect we'll be figuring out this stuff soon as we really try to wire this stuff together, but I'm keen for any input/advice.

**Comment by hectcastro** [comment]
If that ends up being too large, we can look into setting up a local HTTP cache or something to avoid pulling down the same data across requests. Rob and I talked about this a while ago. Depending on how this ends up working, it may not be a terrible thing to have across all environments, especially if we're careful with how we apply updates to the data in S3.
