### ISSUE TITLE
Swap out current MapBox account for non-demo account

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#702]
We are currently using the `ctaylor` account for MapBox. We should swap this out for a non-demo account.

**Comment by caseypt** [comment]
Just noticed this again. We should probably swap this out soon.

**Comment by mmcfarland** [comment]
Just noticed this _again_ - we should definitely swap this out.

@chitchens can you start discussion on getting Stroud a MapBox account (or switch to another provider)?

cc/ @SRGDamia1

**Comment by kdeloach** [comment]
We just noticed this *again*... when our tiles disappeared after we went over the account limit.

**Comment by chitchens** [comment]
I'll bring it up with Stroud and @SRGDamia1

**Comment by ajrobbins** [comment]
@SRGDamia1 has created a MapBox account to use, and @jfrankl added the "Run, Bike, and Hike" basemap to it. Next step is to consider putting separate staging vs. production accounts in place, and ultimately replace the interim Streets basemap currently in use on staging & production.
