### ISSUE TITLE
Land use descriptions are different for main site and micro site.

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#711]
The main site is using land use descriptions from the old version of the mini app: http://www.stroudcenter.org/mmw/mini/

The micro site is using land use descriptions from the NLCD: http://www.mrlc.gov/nlcd11_leg.php.

We should make them consistent.

**Comment by mmcfarland** [comment]
This is supplanted by a list under development by Stroud which will contain custom text for each type (https://docs.google.com/a/stroudcenter.org/document/d/13HVyNkrtKKtLufBguCZJq0RDabBCTkjL0vT1PCwz8Lg/edit?usp=sharing).
