### ISSUE TITLE
Target area for selecting a boundary is incorrect

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#719]
On staging, clicks have to occur on the leftmost or rightmost edges of the dropdown in order for its events to trigger:

<img width="313" alt="model_my_watershed" src="https://cloud.githubusercontent.com/assets/43639/9475418/97cf2486-4b34-11e5-80d8-f3fc45d1be38.png">

**Comment by caseypt** [comment]
This may be due to new CSS rules or event binding changes introduced by https://github.com/WikiWatershed/model-my-watershed/pull/715

**Comment by caseypt** [comment]
You can also click in the space between the name and question mark.
