### ISSUE TITLE
For complicated AoI's, analyze and modeling endpoints are slow

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#720]
Each endpoint takes a few seconds even with the fake endpoints.

I think this is because we are posting large BLOBs of GeoJSON.

To reproduce, select a the Lower Delaware Subbasin, and note the request times on the analyze and modeling pages.

![screen shot 2015-08-25 at 2 23 37 pm](https://cloud.githubusercontent.com/assets/1042475/9475480/f30d7802-4b34-11e5-8f60-6213eadcb73e.png)

**Comment by mmcfarland** [comment]
Does the network graph distinguish between transfer time and waiting time?  Do we still have a `sleep` in the stub endpoint? Would be interesting to see that breakdown, but ultimately we may want to revisit #303.  6 seconds is a long time for no real processing.

**Comment by caseypt** [comment]
Interesting. I went back to get more information, and now repeating the steps above is pretty fast. I was testing `mmw-dev` and tried a number of different watersheds, all of which were slow. But using the 1 sq kilometer tool was fast.

Maybe it was something related to the environment getting setup?

Closing for now.

**Comment by mmcfarland** [comment]
Sure - depending on when you were testing it, our internet at the office was really slow.  During the Stroud call, we had to phone in because the VoIP stuff wouldn't work.  Chip said that we were at ~25% capacity at the time, could have been related.
