### ISSUE TITLE
Add back arrow to allow navigation from compare to the project modeling page

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#724]
The only way I see is by modifying the URL

**Comment by rajadain** [comment]
Or clicking the "back" button in the browser. But I agree, there should be UI for this.

**Comment by caseypt** [comment]
Yeah, and using the browser buttons can sometimes get the compare view into a broken state. I think I'm finally able to reproduce it consistently, so I'll open another issue.

**Comment by mmcfarland** [comment]
I'm not sure if there were wireframe/mockups for this, but the assumption is that the back arrow element on the other screens would be present here.  I'm going to change the issue title to reflect adding it in.

**Comment by caseypt** [comment]
I think I thought to give this two points instead of one because I thought this issue and this one ( https://github.com/WikiWatershed/model-my-watershed/issues/725) were one in the same. But feel free to ignore if that's too much.

**Comment by jamesmcclain** [comment]
Okay, I might as well investigate #725 and see if I can do it, as well.
