### ISSUE TITLE
Graph colors aren't color blind friendly

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#731]
Using [ColorOracle](http://colororacle.org/) with the most common colorblindness setting turned on.

<img width="584" alt="screen shot 2015-08-27 at 4 42 04 pm" src="https://cloud.githubusercontent.com/assets/1042475/9532624/c3269aae-4cda-11e5-98d1-73f1713c190c.png">

**Comment by mmcfarland** [comment]
Superseded by #1685
