### ISSUE TITLE
Make Pasture and Prairie have easily-distinguished patterns

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/model-my-watershed#740]
The colors associated with the land uses were changed to their NLCD colors in #737.

Since "pasture" and "short-grass prairie" have the same NLCD code and therefore the same color.  We should change the patterns of one or both of them to make them easily distinguished.

![screenshot from 2015-08-31 13 01 05](https://cloud.githubusercontent.com/assets/11281373/9584767/1b99a402-4fe1-11e5-8220-6d276b99afb1.png)

![screenshot from 2015-08-31 13 00 36](https://cloud.githubusercontent.com/assets/11281373/9584769/1f2d353e-4fe1-11e5-91a1-920537d36a71.png)

![image](https://cloud.githubusercontent.com/assets/1430060/9588746/ecccb21a-4ff7-11e5-9273-7ad5910ac875.png)

**Comment by mmcfarland** [comment]
Removed all psuedo-classes and duplicated NLCD codes, so this issue can no longer happen.  We may need to have patterns for NLCD codes that have _similar_ colors, but we'll track that separately.
