### ISSUE TITLE
Bottom of map is covered up by analyze window header

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#742]
![screen shot 2015-08-31 at 5 40 52 pm](https://cloud.githubusercontent.com/assets/1042475/9591144/74445662-5007-11e5-8c86-0a86d25e6cd3.png)

(The layer control is obscured by the header in this screenshot).

To reproduce:

- Select an AoI
- Move back to the draw page from the analyze page.
- The layer control will now be covered up by the analyze header.

This is because we aren't actually resizing the map when returning to the draw page.

Currently, the map only has a [full size and half size](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/views.js#L480-L494).

To fix the above issue, should we implement more sizes? Or maybe adjust our sass so that the map can't overlap with the analyze header (make the analyze header take up vertical space)?

Also, if you are in this this state, and you start drawing, the analyze header disappears. Then, if you don't finish drawing but press escape, the analyze header is brought back. Any solution should consider this workflow as well.

**Comment by caseypt** [comment]
This also happens on the modeling page when the modeling results window is minimized:

![screen shot 2015-09-02 at 9 26 20 am](https://cloud.githubusercontent.com/assets/1042475/9632364/c3672082-5154-11e5-89f1-9d3f87e4cd18.png)

**Comment by mmcfarland** [comment]
Similar to #497.

There is however some design work being done to investigate a different approach to the horizontal panel navigation (and resulting slim map area).  Let's hold off on working these issues until we see where that leads.

**Comment by mmcfarland** [comment]
@jfrankl has provided some css based fixes that can accommodate proper map sizing in #831 that need to be implemented.
