### ISSUE TITLE
Replace FontAwesome with Fontello

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#749]
The designs for the custom layer control use the following icon:

![screen shot 2015-09-02 at 8 42 45 am](https://cloud.githubusercontent.com/assets/1042475/9631393/9bfd2e8e-514e-11e5-9cd0-32146d1948d0.png)

However, this icon is not in the current icon set we are using, FontAwesome.

As a temporary fix, I used an icon of the globe.

We could either find a new icon for the control that's in FontAwesome, or build a custom icon set with Fontello.

**Comment by jfrankl** [comment]
Generated a config.json file for Fontello. Sent to Casey.

**Comment by caseypt** [comment]
The stream slider and layers icon are included in the Fontello icon set created by @jfrankl.

Config available [here](https://gist.github.com/caseypt/d8181cae7eade1ee17be).

**Comment by caseypt** [comment]
This doesn't seem to be an issue, and the layer selector is likely to be redesigned in the next design phase.
