### ISSUE TITLE
Gray out inapplicable overlays

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#754]
As of #750 we have an NLCD layer which is available at only certain zoom levels. If the user is zoomed beyond those levels, clicking the button in the layer selector has no effect. There should be feedback for the user that indicates when certain layers are not available at certain zoom levels.

> Currently, beyond a certain zoom level the NLCD tiles just disappear:
> 
> ![mmw-nlcd-zoom-in](https://cloud.githubusercontent.com/assets/1430060/9639066/1c886680-5178-11e5-88a0-a08ddfedffb7.gif)
> 
> If we can specify the max-zoom level for each overlay, we can give the user some feedback (such as the checkbox and label being grayed out) for zoom levels where certain layers are not available, like this:
> 
> ![image](https://cloud.githubusercontent.com/assets/1430060/9639213/f3e8d678-5178-11e5-86b4-3f1ac9ec7c9e.png)
> 
> Or even a ["not visible"](http://fortawesome.github.io/Font-Awesome/icon/eye-slash/) icon with a tooltip explaining that the overlay is not available at this zoom level.

[Original Comment](https://github.com/WikiWatershed/model-my-watershed/pull/750#issuecomment-137187337)

> @rajadain re: graying out the layer names, I do like that approach. It's how ArcGIS handles it, and I think it works pretty well. I think we should create an issue and consult with @jfrankl.

[Original Comment](https://github.com/WikiWatershed/model-my-watershed/pull/750#issuecomment-137466149)

This could benefit from design input.

**Comment by mmcfarland** [comment]
I think additionally we may want to over-zoom the layer on the client (it will get pixelated, but so will generating from source at further resolutions).  The previous MMW1 app had it available at high zoom and with an 8bit nintendo game feeling to it.

**Comment by jfrankl** [comment]
@mmcfarland Overzooming means it would be available at all zoom levels? So we wouldn't need to change the formatting on the legend?

**Comment by mmcfarland** [comment]
Potentially, but not sure how crummy it would actually look.  I think whatever the solution ends up being, the goal should be to be able to display something at zoom levels ~18 which is a far cry from where we are now.  I believe this is 30m cell resolution, so it's going to be super blocky at that point.

**Comment by caseypt** [comment]
One thing to note is that you can't tell Leaflet when to stop stretching a layer–it will continue to stretch it until the map reaches the max zoom. The MapBox base maps go until 18, but ESRI and Google can go to 21 or so.

**Comment by jfrankl** [comment]
Got it. Would it be possible for me to see an example of these stretched
layers so I can help evaluate?

On Thu, Sep 3, 2015 at 2:57 PM, Casey Thomas <notifications@github.com>
wrote:

> One thing to note is that you can't tell Leaflet when to stop stretching a
> layer–it will continue to stretch it until the map reaches the max zoom.
> The MapBox base maps go until 18, but ESRI and Google can go to 21 or so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WikiWatershed/model-my-watershed/issues/754#issuecomment-137542054>
> .
>



-- 
Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<http://twitter.com>

**Comment by rajadain** [comment]
The layer gets stretched before disappearing after zooming in the GIF above. I imagine the actual versions will look similar.

**Comment by mmcfarland** [comment]
Unfortunately, I don't think we really have a choice to evaluate.  If the users are doing work at levels >= 18 (and we have been told they are) then they're going to want/need NLCD at that level, too.

**Comment by rajadain** [comment]
Should we close this card in lieu of another which instructs to stretch all layers?

**Comment by mmcfarland** [comment]
@rajadain I think so, it's an "it is what it is" sort of situation.

**Comment by caseypt** [comment]
I think we should expand that issue to be a "use leaflet layer settings specified in the layer config when creating layers" issue. That'll take care of the opacity too. 

Right here: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/views.js#L312-L324

**Comment by rajadain** [comment]
Created #757. @caseypt could you please amend that with your suggestion above? Closing this card.
