### ISSUE TITLE
Stretch overlays when zooming beyond available levels

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#757]
Currently, beyond a certain zoom level the NLCD tiles just disappear:

![mmw-nlcd-zoom-in](https://cloud.githubusercontent.com/assets/1430060/9639066/1c886680-5178-11e5-88a0-a08ddfedffb7.gif)

They should instead still be visible at all visible levels. When tiles for a particular zoom level are not available, we should display the closest available level tiles stretched out.

See #750 and #754 for further discussion.

**Comment by caseypt** [comment]
A broader implementation could use any Leaflet settings added to layers in the [layer settings](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/layer_settings.py) when the layers are [being created](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/views.js#L312-L324).

A simple implementation:

Layer settings:
```python
    {
        'display': 'National Land Cover Database',
        'short_display': 'NLCD',
        'helptext': 'National Land Cover Database defines'
                    'land use across the U.S.',
        'url': 'https://s3.amazonaws.com/com.azavea.datahub.tms/'
               'nlcd/{z}/{x}/{y}.png',
        'overlay': True,
        # Leaflet specific settings
        'maxNativeZoom': 13,
        'opacity': 0.5
    },
```

Layer creation:

```
    buildLayers: function(layerConfig) {
        var self = this,
            layers = {};
     

            _.each(layerConfig, function(layer) {
                var leafletLayer;

             // Make sure there are defaults
             var zIndex = layer.overlay ? 1 : 0;
             var defaults =  {
                  opacity: 1.0,
                  maxNativeZoom: null,
                  zIndex: zIndex
             }

                // Check to see if the google api service has been loaded
                // before creating a google layer
                if (self._googleMaps && layer.type === 'google') {
                    leafletLayer = new L.Google(layer.googleType, settings);
                } else {
                       var tileUrl = (layer.url.match(/png/) === null ?
                                    layer.url + '.png' : layer.url),
                       settings = _defaults(defaults, layer);

                    leafletLayer = new L.TileLayer(tileUrl, settings);
                }

                layers[layer['display']] = leafletLayer;
            });

        return layers;
    },
```

**Comment by mmcfarland** [comment]
Just reconfirmed with Stroud that having this layer visible beyond 13 is important, and that the resolution is not a problem (and is something of a teaching aide in describing what a "30 meter resolution" data layer implies in terms of coverage/coarseness)

**Comment by jamesmcclain** [comment]
Okay, sounds good.  I have a `maxZoom` of 18 in there to match with the other layers.  I can remove that entirely if needed.
