### ISSUE TITLE
Trouble Downloading School District Boundaries

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/model-my-watershed#758]
When I attempt to load the boundaries using the `setupdb.sh` script, they fail to load.  The following can also be observed:

```
vagrant@app:~$ curl -s https://s3.amazonaws.com/data.mmw.azavea.com/boundary_school_districts.sql.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>...</RequestId><HostId>...</HostId></Error>
vagrant@app:~$
```

**Comment by mmcfarland** [comment]
There's a typo in the script, `districts` should not be plural.  PR forthcoming, as a temporary fix, you can drop the superfluous `s`.
