### ISSUE TITLE
Align MMW land covers to NLCD

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#765]
A review of what is currently being used by MMW and MMW-micro resulted in several changes required. 

We all believe that it is not helpful to offer land cover names that do not match the underlying data or provide additional modeling output options.
Some of the current mapping of names to NLCD Level II classes is incorrect and gives bad model output as a result (i.e. turf_grass/urban_grass in clay loam is producing less run-off than forest)
There are 3 places that the Land Cover names get shown
* https://mmw.azavea.com/analyze, under the Land tab. These should show all 16 NLCD Level II Classes (20 classes minus 52, 72, 73, 74, which are in Alaska only), exactly as they are listed here: http://www.mrlc.gov/nlcd11_leg.php.
* https://mmw.azavea.com/micro/ presently shows 12 Land Cover types, but these do not have 1:1 mappings with NLCD classes
* Land cover button in Model New Scenarios shows the same Land Cover classes as the Micro model.

These are the 12 land cover names we should use, in both New Scenario and Micro apps. In the help text, we should include the NLCD code and definition, but also list examples and alternative names to help users choose.  Sara and Melinda will work on the help text.  

1. Open Water (NLCD 11, including ponds and lakes). Specifically want to include this because someone might want to modify a scenario by adding a pond or waterway
1. Developed, Open Space (NLCD 21 - turf grass, urban grass, park)
1. Developed, Low Intensity (NLCD 22 - low density single family homes) title could be shorted to “Developed-Low”
1. Developed, Medium Intensity (NLCD 23 - high density single family homes)
title could be shorted to “Developed-Med.”
1. Developed, High Intensity (NLCD 24 - commercial and industrial)
title could be shorted to “Developed-High”
1. Barren Land (NLCD 31, including desert)
1. Forest (NLCD 41, 42, 43, including deciduous, evergreen and mixed forest)
1. Shrub/Scrub (NLCD 52, including chaparral, )
1. Grassland/Herbaceous (NLCD 71 including tall and shortgrass prairie, savanna)
title could be shorted to “Grassland”
1. Pasture/Hay (NLCD 81)
1. Cultivated Crops (NLCD 82, includes row crops, orchards, vineyards)
title could be shorted to “Crops”
1. Wetlands (NLCD 90, 95, including wooded wetland, herbaceous wetland, marsh, bog)

Correspondingly, there should be a consolidation of the `LAND_USE_VALUES` described in TR55, but we need to discover the implications of removing our "meta-classes", which might be used for custom logic.
https://github.com/WikiWatershed/tr-55/blob/develop/tr55/tables.py#L387

**Comment by lliss** [comment]
> These should show all 16 NLCD Level II Classes (20 classes minus 52, 72, 73, 74, which are in Alaska only), exactly as they are listed here:

NLCD type 52 is not Alaska only as far as I can tell and 51 is. Is this a typo?

**Comment by lliss** [comment]
> These should show all 16 NLCD Level II Classes

Right now we don't show any types that have no coverage in the selected area. Should we show a table with zeros?
Type | Area | Coverage
Developed High Intensity 	|1.29	| 43.7
Developed, Medium Intensity	| 0.96	| 32.6
Open Water	| 0.25	| 8.5
Developed, Low Intensity.	| 0.2 | 	6.9
Developed, Open Space|	0.12	| 4.1
Deciduous Forest | 	0.05	| 1.5
Pasture/Hay|	0.04	| 1.4
Woody Wetland|	0.02	| 0.6
Emergent Herbaceous Wetlands|	0.01|	0.2
Mixed Forest | 	0.01|	0.5


VS

Type | Area | Coverage
Developed High Intensity 	|1.29	| 43.7
Developed, Medium Intensity	| 0.96	| 32.6
Open Water	| 0.25	| 8.5
Developed, Low Intensity.	| 0.2 | 	6.9
Developed, Open Space|	0.12	| 4.1
Deciduous Forest | 	0.05	| 1.5
Pasture/Hay|	0.04	| 1.4
Woody Wetland|	0.02	| 0.6
Emergent Herbaceous Wetlands|	0.01|	0.2
Mixed Forest | 	0.01|	0.5
Perennial Ice/Snow|0.00|0.0
Evergreen Forest|0.00|0.0
Barren Land (Rock/Sand/Clay)|0.00|0.0
Grassland/Herbaceous|0.00|0.0
Cultivated Crops|0.00|0.0
Shrub/Scrub|0.00|0.0

**Comment by mmcfarland** [comment]
Correct, that looks like a typo.  52 (scrub/shrub) is listed as a type to include.

**Comment by mmcfarland** [comment]
Yes, I think we should include them all, to be explicit.  There will probably be a feature down the line which links each class to a pre-configured microsite setting to explore the type, so we'll want the text there to link.

**Comment by lliss** [comment]
I'm not sure what to do with "Tall Grass Prairie" in the micro site. In the NLCD descriptions, what we're using as "Tall Grass Prairie" is the same as "Shrub/Scrub" which we already have as "Chaparral".

**Comment by lliss** [comment]
In the microsite "Short Grass Prairie" aligns with NLCD 51 which is "Dwarf Scrub", one of the Alaska only types.

**Comment by mmcfarland** [comment]
We're removing Chaparral and just sticking with actual NLCD classes (some combined).  The 12 listed above should be the only ones left - and we'll just use the lowest numbered class for the ones that are combined.

**Comment by mmcfarland** [comment]
For Prairie, see list item 9.
