### ISSUE TITLE
Update land cover artwork on Micro Site

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#766]
The coloring in the art for these types should match up with the NLCD coloring.  

See #765

**Comment by mmcfarland** [comment]
@chitchens - putting this on your radar for designers.

**Comment by mmcfarland** [comment]
The breakdown, in my estimation, of the status of the existing Micro Site Land Types and the mapping to the proposed, actual NLCD classes in #765 

#### New
* Open Water (Lake, Pond, River)
* Shrub/Scrub (Includes Chaparral)
* Wetlands wooded wetland, herbaceous wetland, marsh, bog)

#### Combine
* Grassland: Grassland, Tall & Short Prairie

#### Rename/Enhance
* Developed, Open Space:  Turf Grass
* Developed, Low: LIR
* Developed, Medium: HIR
* Developed, High: Commercial
* Barren Land: Desert
* Crops: Row Crops

#### No Change
* Forrest: Forrest
* Pasture/Hay: Pasture

**Comment by mmcfarland** [comment]
End result for this task is the need for Open Water and Wetlands.  We may want placeholder values soon if the final products won't be available by the end of September.

/cc @jfrankl

**Comment by chitchens** [comment]
Artwork is now available: smb://fileshare/projects/Stroud_ModelMyWatershed/documents/design/visual design/mini app/updates
