### ISSUE TITLE
Compare Mode: Lock/Sync precipitation slider values

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#771]
The initial implementation of Compare Mode should lock all the precipitation values for all scenarios.  Adjusting any slider should adjust all scenarios and re-run the model output.  This shouldn't bee too expensive, because the geoprocessing results are cached.

**Comment by rajadain** [comment]
What should happen if there are three scenarios, each with different precipitation values, in the Model view, and then the user enters the Compare view? Should the Compare view start with different values, but as soon as the user changes one it updates all of them to the same value? Should there be a toggle button that allows the user to update one value at a time?

**Comment by mmcfarland** [comment]
I think we should default all the models precipitation to the same value we start new scenarios to.  I think it should be clear that we're starting from a new universal value.  We may also luck out if they haven't changed the sliders for some, because the result should be 100% cached in that case and no job is submitted.  In all cases, we should be verifying that we're not requesting a geop job.

FYI, in the future this feature will be expanded to let users unlock the sliders, and be able to compare based on "climate scenarios", that is, the same/similar modifications against different predictions of future climate.
