### ISSUE TITLE
Add grouping to Layer Control

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#776]
We'll allow two groups of overlays, for convenience, "vector" and "raster", though they are all burned image tiles.  The boundary layers and the NLCD/Soil will each be in their own group and be mutually exclusive within the group.  You can select one "vector" and one "raster" layer at a time. 

Should help partially resolve #741

**Comment by caseypt** [comment]
In other words, there should now be the following categories with the following layers?

- Basemaps
- Vector
    - County
    - Schools
    - HUCs
    - Congressional Districts
- Raster
    - NLCD
    - Soil

**Comment by mmcfarland** [comment]
Correct-ish, I think that the vector/raster groups remain on the same "overlays" tab, though.  And we need better names.  Boundary and coverage?  Not sure.

**Comment by caseypt** [comment]
Ohh. I see. Same tab, but groups within the tab.

So something like this:

- Basemap
- Overlays
    - "Boundary"
        - County
        - Schools
        - HUCs
        - Congressional Districts
    - "Coverage"
    - NLCD
    - SURRGO

**Comment by mmcfarland** [comment]
Yep, updated the indentation under "Coverage" (probably a typo).  Looks right to me.  Each group under overlays can have one layer selected at a time
