### ISSUE TITLE
Add Feature Switching based on Environment

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#782]
Arising out of issues such as #778, there is a need to enable different features across different environments. Investigate feature switching options, such as https://github.com/jsocol/django-waffle, and implement a mechanism that will allow different features in different environments.

**Comment by kdeloach** [comment]
Can we close this?

**Comment by rajadain** [comment]
From @hectcastro [here](https://github.com/WikiWatershed/model-my-watershed/pull/861#issuecomment-143776906):

> Technically, I think it can, but I also think that this approach doesn't scale very well. I'm fine with using it for the number of dynamic settings we have across environments now, but I would prefer to work toward a more flexible solution if we plan on adding a dozen more settings.
> 
> Right now, the AMI will get baked using whatever settings are put in place by Ansible. That same AMI will be used in all EC2 environments, but stacks will have the option to override specific settings via CloudFormation parameters.

So I'd get input from @mmcfarland if he envisions us having a lot more environment variables going forward or not. If not, we can close this.

**Comment by mmcfarland** [comment]
I do not anticipate many more environment based features, I think we should close and revisit if that assumption proves false.
