### ISSUE TITLE
Remove "Undo all of my work" from ITSI embed

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#790]
The 'undo all of my work' button should be removed when MMW is embedded inside of ITSI. This is done by handling the getExtendedSupport message: 

http://concord-consortium.github.io/lara-interactive-api/docs/#getextendedsupport

and returning a message `extendedSupport` with the content of `{reset: false}`

**Comment by rajadain** [comment]
Shares a point with #788
