### ISSUE TITLE
Test #updateModificationHash generates and sets modification_hash... passes in Firefox but fails on Chrome.

### ISSUE THREAD

**Issue by lliss** [WikiWatershed/model-my-watershed#797]
The following failure appears when running testem in chrome.

```
#updateModificationHash
generates and sets modification_hash based on the scenario's modifications ‣
AssertionError: expected 'ffbe87a3cb242794d380ca25b388b5f8' to equal '5e02dc1cf4b55bdb209683473f6dac45'
    at Context.<anonymous> (http://localhost:7357/js/test.bundle.js:10992:28)
    at Test.Runnable.run (http://localhost:7357/testem/mocha.js:4212:32)
    at Runner.runTest (http://localhost:7357/testem/mocha.js:4584:10)
    at http://localhost:7357/testem/mocha.js:4630:12
    at next (http://localhost:7357/testem/mocha.js:4510:14)
    at http://localhost:7357/testem/mocha.js:4519:7
    at next (http://localhost:7357/testem/mocha.js:4463:23)
    at http://localhost:7357/testem/mocha.js:4487:5
    at timeslice (http://localhost:7357/testem/mocha.js:5480:27)
```

**Comment by mmcfarland** [comment]
This could indicate that chrome based sessions are re-running geoprocessing task unnecessarily.

**Comment by lliss** [comment]
I suspect this has to do with the fact that we don't sort the keys of objects in arrays.

**Comment by rajadain** [comment]
I can't seem to reproduce this failing test in Firefox, Chrome or Safari. I'm testing off the latest `develop`. Could you confirm that this is still happening, @lliss? If not, we can close this card until this resurfaces.

**Comment by rajadain** [comment]
Closing for now. Feel free to revive if this is observed again.

**Comment by lliss** [comment]
Just tested this out. Still happens.
Firefox - Linux - 41.0
Chromium Version 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)

**Comment by lliss** [comment]
Maybe its just my machine. In any event, it doesn't seem like an issue worth any real time investment.

**Comment by rajadain** [comment]
Thanks. Tested on Chrome 45 on Mac OS X Yosemite, Safari 8.0.8 on Mac, Firefox 40.0.3 on Mac, and Chrome 45 on Windows 7. I think we should be good for now, may reopen in the future.
