### ISSUE TITLE
Choose a development extent and create a set of small dev rasters

### ISSUE THREAD

**Issue by jwalgran** [WikiWatershed/model-my-watershed#8]
Working with large raster data sets on a development VM is painful, so we want to create a set of small, development rasters, with a small extent, clipped from the full-size production rasters.

To generate the data for the TR55 model we need the following rasters:
  * NLCD
  * Soil types

The dev rasters should be committed under ``/dev/data`` so they can be deployed into the geoprocessing data store as part of vagrant provisioning.

**Comment by jamesmcclain** [comment]
The data appear to be okay.  When I take statistics on the `gSSURGO_DE_10m1.tif` file (the one that is supposed to contain the soil type information), I get
```
  256 buckets from 1.60336e+06 to 2.4799e+06:
  51219687 206156 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9692 0 0 0 0 0 1832509 0 0 0 0 0 0 0 0 4812 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 133320 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10599803 362179 
  NoData Value=2147483647
```
indicating a large range of values, but just a few discrete values.

Also, there are about 348 entries of the form
```
  <Row index="348">
    <F>349</F>
    <F>2479901</F>
    <F>362179</F>
    <F>2479901</F>
    <F>TdB</F>
    <F>Talleyville-Montalto-Urban land complex, 0 to 8 percent slopes</F>
    <F>24.52000045776367</F>
    <F>B</F>
  </Row>
```
in the metadata file `gSSURGO_DE_10m1.tif.aux.xml` where the last field appears to be the soil type.  These ~348 distinct values (which I think map to a wide range of 32-bit encodings) are consistent with the histogram above.

I am not sure if this explanation meets everyone's needs, but if not, I can do more on this.

**Comment by jamesmcclain** [comment]
One can use `ogrinfo -al name.dbf` to get a mapping between 32-bit words and soil types.
