### ISSUE TITLE
Remove extra width in Compare view in ITSI screenshot

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#808]
Compare view screenshots look like this:

![image](https://cloud.githubusercontent.com/assets/1430060/9945008/ccfef768-5d58-11e5-8b8e-887aa5610769.png)

Because PhantomJS doesn't handle `vw`, which was used to fix #642. Find a solution that works for both cases.

**Comment by rajadain** [comment]
Also see related, from https://github.com/WikiWatershed/model-my-watershed/pull/1025#issuecomment-157739010:

> The additional columns are now showing up:

> ![screenshot from 2015-11-18 09 52 21](https://cloud.githubusercontent.com/assets/1014341/11244157/179e9ba0-8dda-11e5-893f-ec9550a9a6ab.png)

> but the screenshot tries to fit all of the columns in on the shot - not sure if this was the behavior from before or is related to this changeset.  Also not sure what the expected behavior should be, since we can't fit them all in at once on the actual screen.

> https://ccshutterbugtest.s3.amazonaws.com/293cdeef199.png

**Comment by ajrobbins** [comment]
Compare View Revamp makes this issue moot.
