### ISSUE TITLE
Format Analysis Output with 2 digits of precision

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#812]
Sorting on `Area` can produce visually confusing results since some values don't report a second digit of precision if it's `0`, making it look like a smaller number than following values.

![screenshot from 2015-09-18 15 23 27](https://cloud.githubusercontent.com/assets/1014341/9968903/5db27ef4-5e19-11e5-8dae-0686529660ae.png)

**Comment by jamesmcclain** [comment]
It looks like it is sorting lexicographically instead of numerically.

**Comment by jamesmcclain** [comment]
It seems like some of this could also be due to the fact that we are using a variable-width font for these numbers.
