### ISSUE TITLE
Analysis `Area` Output is not sorted correctly

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#813]
When sorting the table values on the `Area` column, the numbers are not appropriately sorted.  Note that the `Coverage` column _is_ sorted correctly.

![screenshot from 2015-09-18 15 23 27](https://cloud.githubusercontent.com/assets/1014341/9968970/adc228fe-5e19-11e5-9f27-65ab135372c1.png)

**Comment by mmcfarland** [comment]
As @jamesmcclain [pointed out](https://github.com/WikiWatershed/model-my-watershed/issues/812#issuecomment-141696557), the numbers are being sorted correctly lexicographical and not numerically.

**Comment by mmcfarland** [comment]
`bootstrap-table`'s default sort example also sorts numerical data incorrectly:  http://issues.wenzhixin.net.cn/bootstrap-table/#options/basic-sort.html

**Comment by jamesmcclain** [comment]
It looks as though there is a way to define a custom sorting function.
