### ISSUE TITLE
Implement My Projects page

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#820]
A simple listing of the current user's saved projects.  From the design below, do not include Search or Tags.  Allow navigation to this page from the Login/User dropdown (replace "Profile") and from the Project dropdown .

![screenshot from 2015-09-21 12 45 52](https://cloud.githubusercontent.com/assets/1014341/9998390/d0e97854-605e-11e5-9577-010c9f45d1a3.png)

**Comment by mmcfarland** [comment]
Consider incorporating an indication of the public/private status of the project.   Maybe a [locked](http://fortawesome.github.io/Font-Awesome/icon/lock/)/[unlock](http://fortawesome.github.io/Font-Awesome/icon/unlock/) icon?

**Comment by rajadain** [comment]
Should the "My Projects" page navigation be hidden when in ITSI embed mode, so that users can't switch to a different project?

**Comment by mmcfarland** [comment]
Good question.  I think so, by switching to another project, they'd probably end up associating it with the assignment.
