### ISSUE TITLE
NLCD Chart Order by Class ID

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#836]
The order of the NLCD chart on the Geospatial Analysis page should be that of the NLCD class ID, ascending.

**Comment by caseypt** [comment]
http://www.mrlc.gov/nlcd01_leg.php

**Comment by mmcfarland** [comment]
NLCD Class Id should be a part of the response as of 59881a94a6c0c016b78e2a0ca14a7bc0374ef244 under the `nlcd` key.
