### ISSUE TITLE
Model Output results disappear when modification is added outside of area being analyzed 

### ISSUE THREAD

**Issue by arobbi7** [WikiWatershed/model-my-watershed#846]
To replicate:
1. Draw/select any area for analysis
2. Proceed to Model view
3. Add land cover or conservation area modification outside of analysis area/polygon

Connects #818

**Comment by arobbi7** [comment]
This is what it looks like when I try:
![screen shot 2015-09-24 at 9 46 45 am](https://cloud.githubusercontent.com/assets/12868342/10075066/c9cc85b2-62a1-11e5-9fbb-d79c6615e78c.png)

**Comment by rajadain** [comment]
Currently if a modification is drawn completely outside the AoI, it has an effective area of 0, which causes the model run to fail, even if there are other non-zero modifications:

![image](https://cloud.githubusercontent.com/assets/1430060/10372588/7b4ee162-6db6-11e5-96bb-75b93e46624c.png)

Consider warning the user or simply ignoring those modifications.
