### ISSUE TITLE
Fix Layer Selector Button

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#850]
It behaves oddly on staging when opened in Chrome:

![image](https://cloud.githubusercontent.com/assets/1430060/10079007/aef9a6de-62b5-11e5-9bb1-f74d3acec9d8.png)

It should stay where it is and not move when clicked.

**Comment by mmcfarland** [comment]
This was fixed previously and seems to be behaving correctly for me on staging in Chrome, are you sure it's not some cached css?

![screenshot from 2015-09-25 09 30 24](https://cloud.githubusercontent.com/assets/1014341/10101706/3eccaf10-6368-11e5-92ef-32aa283fa1b7.png)

**Comment by rajadain** [comment]
Yep sorry, just hard refreshed and it's fixed.
