### ISSUE TITLE
First digit of load numbers is cut off in Compare view - Firefox & Safari

### ISSUE THREAD

**Issue by arobbi7** [WikiWatershed/model-my-watershed#853]
![screen shot 2015-09-24 at 11 50 43 am](https://cloud.githubusercontent.com/assets/12868342/10080336/28d75468-62bd-11e5-837e-aa2b846b83a2.png)

**Comment by lliss** [comment]
It turns out that this happens in all browsers with an appropriately large AIO. After 5 digits, there is not enough space for the numbers in the axis.

**Comment by arobbi7** [comment]
@lewfish, will the work you're doing on charting in MMW address this?

**Comment by lewfish** [comment]
Yes!
