### ISSUE TITLE
Chart labels are cut off or obscured on small screens

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#857]
The left side of the longer labels are cut-off.

<img width="717" alt="screen shot 2015-09-25 at 2 04 24 pm" src="https://cloud.githubusercontent.com/assets/1042475/10108340/5a9a8732-638e-11e5-900a-15d8bd1d73e5.png">

This is in Chrome on a 13" MacBook.

**Comment by rajadain** [comment]
They're all really **crammed** in there too. Perhaps we can add some vertical spacing as well?

**Comment by caseypt** [comment]
In addition, on mobile the axis labels are unreadable

![img_1963](https://cloud.githubusercontent.com/assets/1042475/10459013/8f526ad8-719b-11e5-8bf8-2866ae95f1d1.PNG)
![img_1962](https://cloud.githubusercontent.com/assets/1042475/10459011/8f4dabec-719b-11e5-807a-daaf4cb5a461.PNG)

**Comment by lewfish** [comment]
Below a certain screen size, it's impossible to fit all the labels in without cramming. So I'm thinking we need make the axis font smaller, or leave out some labels when possible (like with tick marks).

**Comment by rajadain** [comment]
I agree. In addition we can also consider staggering the labels on two rows, so they alternate and leave more room. But not showing all labels / showing only a subset seems like the best way forward.

**Comment by mmcfarland** [comment]
I was also thinking about a two row alternating approach.  Additionally, for squished values that are numeric we could abbreviate them 1,000,000 -> 1m, etc.

**Comment by lewfish** [comment]
We could also display 1,000,000 as 1.0 and append ' (million)' to the axis label (eg. Level (millions)) to save more space on the tick labels.

**Comment by lewfish** [comment]
Could we just turn the vertical bar chart above (and also the one in https://github.com/WikiWatershed/model-my-watershed/issues/994) into horizontal bar charts? That would avoid the issue with the tick labels overlapping. I don't think the staggered approach is going to look very nice, and will be more work to implement. The only vertical bar charts left in the app would be in the compare view, but those aren't problematic since there's only one bar in each chart.

**Comment by rajadain** [comment]
I would be okay with us transitioning the charts to horizontal below a certain width. In the runoff results above there seems like a lot of unused horizontal space, so perhaps we can ensure we use all the available horizontal space before deciding to switch.

Another possibility is to use vertical or slanted labels, like this:

![image](https://cloud.githubusercontent.com/assets/1430060/11002800/f3ddf870-847c-11e5-9c3f-ab3c9912bcc1.png)
