### ISSUE TITLE
Reloading page on /project results in a 404

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#860]
When not logged in, or before modifications are made to a new, but savable, project on /project - the user will get a 404 if they refresh the page.   We obviously can't send someone back to a page we didn't save, so probably it should just route back to the home page.

**Comment by caseypt** [comment]
This was fixed in https://github.com/WikiWatershed/model-my-watershed/pull/908. Refreshing now directs to the My Projects page.

**Comment by caseypt** [comment]
Or the home page if you aren't logged in.
