### ISSUE TITLE
Add code for taking metrics

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/model-my-watershed#871]
@hectcastro suggested adding code to take metrics on the geoprocessing code.

The following suggestion was made:

> Some example usage of the StatsD client is in the [Boto mailer backend](https://github.com/WikiWatershed/model-my-watershed/blob/53c325afa9b0ba209ce9ca7c29ccf2b3eec8ee3a/src/mmw/apps/core/mail/backends/boto_ses_mailer.py). More detail into the available data types can be found [here](http://statsd.readthedocs.org/en/latest/types.html). 

And suggested areas for doing that are in the `histogram_start` and `histogram_finish` functions in `geoprocessing.py` which will be introduced in https://github.com/WikiWatershed/model-my-watershed/pull/826

**Comment by mmcfarland** [comment]
I'm specifically interested in getting some timing metrics for how much of the geoprocessing time is due to networking latency.  I suspect this might be hard to isolate since it's embedded int he trellis library code.  At the very least, we need to know how long the job takes to complete.
