### ISSUE TITLE
Research creating a DRF endpoint for districts and other shapes

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#88]
The purpose of using Django Rest Framework is to spare us from having to create custom views with filtering/sorting/etc. logic for each data set.

To accomplish this, we may have to add post-processing to the fixture data so that we don't have to do any transformations per request.

From Matt:

> Let's consider how we want to handle the generation of this one control. There will be a lot of elements in the UI, and we should support interactive features like filtering. With many data sources this will get expensive to generate, but will be very static. We should try to separate it in the most cachable way, probably as pre-rendered html. I don't think we need to address this in this PR, but I'll create a new issue for it.

**Comment by mmcfarland** [comment]
Closing based on comment https://github.com/WikiWatershed/model-my-watershed/issues/88#issuecomment-95772403

We took a different approach for this feature.
