### ISSUE TITLE
Refreshing twice results in 404

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#889]
1. Open the Layers panel
2. Click Overlays (URL is now `/#overlays-layer-list`)
3. Refresh page (URL becomes `/overlays-layer-list`)
4. Refresh again (404)

![image](https://cloud.githubusercontent.com/assets/43062/10196106/19825f98-675f-11e5-89a7-7166e39ea178.png)

Source: mmw.azavea.com version ccdf9d75de0fa44435e37a92e64b51546864b0ae.

**Comment by rajadain** [comment]
Clicking the Layers panel should not update the URL at all.

**Comment by mmcfarland** [comment]
Yeah, this doesn't happen for me on any of my browsers, might be a Windows thing?

**Comment by kdeloach** [comment]
It looks like I experienced a few bugs that were isolated to my machine. I'll verify and close these issues later if nobody else is able to reproduce these.

**Comment by rajadain** [comment]
Can we close this?

**Comment by kdeloach** [comment]
Yes. Closing.
