### ISSUE TITLE
Strange shading on layer control button

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#890]
![image](https://cloud.githubusercontent.com/assets/43062/10196169/87e4a4aa-675f-11e5-8ff3-7a312931558c.png)

Source: mmw.azavea.com version ccdf9d75de0fa44435e37a92e64b51546864b0ae.

**Comment by caseypt** [comment]
Above screenshot is taken on a touch screen laptop.

Also observed on Chrome on an iPhone 6 with iOS 9 and a Nexus 7 using the built-in browser.

![unnamed](https://cloud.githubusercontent.com/assets/1042475/10458920/2815caea-719b-11e5-84dd-c1e960448b96.jpg)

**Comment by mmcfarland** [comment]
I believe this has been fixed, has anyone seen this problem recently?

**Comment by caseypt** [comment]
Still seeing it in Chrome on iOS.

**Comment by caseypt** [comment]
![img_2140](https://cloud.githubusercontent.com/assets/1042475/13129853/b69aa918-d5ad-11e5-832c-a61e3278eab2.PNG)

**Comment by ajrobbins** [comment]
We no longer have a globe icon for the layer selector; it's its own menu.
