### ISSUE TITLE
Current selection not selected in boundary layer dropdown

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#891]
There should be some kind of indication about which boundary layer is active. The "Select by Boundary" text should be replaced by the currently active layer.

![image](https://cloud.githubusercontent.com/assets/43062/10196256/f9c4f0c0-675f-11e5-882e-416075f39641.png)

Source: mmw.azavea.com version ccdf9d75de0fa44435e37a92e64b51546864b0ae.

**Comment by ajrobbins** [comment]
UI has been redesigned and boundary selection is now evident:
![screen shot 2017-08-18 at 3 42 50 pm](https://user-images.githubusercontent.com/12868342/29474989-f1b84d74-842b-11e7-884f-d6ffcffa3b2b.png)
