### ISSUE TITLE
Unable to close shape on Free Draw

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#892]
Clicking the first point doesn't close the shape and double-clicking didn't work either.

![image](https://cloud.githubusercontent.com/assets/43062/10196413/cfc889a2-6760-11e5-953c-cf42b874b2c7.png)

Source: mmw.azavea.com version ccdf9d75de0fa44435e37a92e64b51546864b0ae.

**Comment by caseypt** [comment]
Which browser?

**Comment by kdeloach** [comment]
I was on Windows 10 Chrome 45 and my device had a touch screen (although I was using a mouse in this case).

**Comment by caseypt** [comment]
Probably related to https://github.com/WikiWatershed/model-my-watershed/pull/502.

**Comment by rajadain** [comment]
Duplicate of #649, we should probably merge these two.
