### ISSUE TITLE
Graph and/or TR-55 bug

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/model-my-watershed#895]
There are some instances in which a graph on the modeling page can become taller than it should be (notice the graph on the right below).  I have only noticed this when I have had a large Green Roof that covers almost the entire AoI.  This makes me suspect that the TR-55 code is probably not handling that correctly and is returning negative runoff values, but I have not confirmed it.

![screenshot from 2015-10-01 14 02 33](https://cloud.githubusercontent.com/assets/11281373/10231695/2c396f3e-6852-11e5-9b03-71d7abe25bd1.png)

**Comment by mmcfarland** [comment]
We should add a unit test to TR55 to mimic this input and assert that the result does not exceed precipitation.
