### ISSUE TITLE
Evaluate usage of WebSockets for passing messages to client web application

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#9]
The use of WebSockets for notifying the application of changes to the state of any asynchronous tasks we kick off seems like potentially a good fit. That said, managing a bunch of long-lived connections on the backend can also be pretty challenging (on top of all of other challenging components of this application). If we choose to entertain this route, I think relying on a WebSockets service provider would be a good compromise.

An approach for making this all work for development environments would also be necessary. Seems like exposing endpoints for callbacks from the WebSockets service with a tool like `ngrok` would be an approach.
---
### Resources
- https://www.pubnub.com/
- https://pusher.com/

**Comment by caseypt** [comment]
FYI: We are currently polling for job results with HTTP requests.

https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/models.js#L38-L84

**Comment by caseypt** [comment]
This is unlikely to be implemented at this point.
