### ISSUE TITLE
Excessive Zoom in Safari on iOS 9

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#904]
Main site:

![img_0090](https://cloud.githubusercontent.com/assets/1430060/10284982/c4513f40-6b54-11e5-911c-0059540b3d3a.PNG)

Micro site:

![img_0091](https://cloud.githubusercontent.com/assets/1430060/10284989/c879a40e-6b54-11e5-961f-991800b56c6f.PNG)

Tested on iPad Mini running iOS 9.0.1.

Possible reason: https://twitter.com/rwd/status/647414588342841344

**Comment by rajadain** [comment]
Confirmed on iOS 9.0.2 as well.

**Comment by ajrobbins** [comment]
Site is at appropriate zoom on iPads.
