### ISSUE TITLE
Touchup Open Water microsite art

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#907]
See illustrations and comments in https://github.com/WikiWatershed/model-my-watershed/pull/900#issuecomment-145573457

**Comment by designmatty** [comment]
My mistake! I forgot to pull over those layers when making the image. I've update those files on the fileshare:

smb://FILESHARE.internal.azavea.com/projects/Stroud_ModelMyWatershed/documents/design/visual design/mini app/updates/land_cover/art_land_openwater@2x.png

**Comment by rajadain** [comment]
Shares a point with #920
