### ISSUE TITLE
Login modal adds height to page and a scrolll bar on small screen

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#911]
On a 13" MacBook Pro in Chrome.

<img width="865" alt="screen shot 2015-10-06 at 5 02 21 pm" src="https://cloud.githubusercontent.com/assets/1042475/10322531/18cc60ca-6c4c-11e5-85d9-5a92d2254677.png">

**Comment by caseypt** [comment]
I'm still able to reproduce this.

**Comment by ajrobbins** [comment]
No scroll observed on 13" macbook air in Chrome, and modals have been redesigned.
