### ISSUE TITLE
Land Cover & Conservation Practice panes missing artwork in Internet Explorer

### ISSUE THREAD

**Issue by arobbi7** [WikiWatershed/model-my-watershed#916]
Running IE 11 on a Windows VM:
![screen shot 2015-10-06 at 5 26 04 pm](https://cloud.githubusercontent.com/assets/12868342/10340232/2886ccf8-6cdd-11e5-9ea0-95339770f4bd.png)
![screen shot 2015-10-06 at 5 26 20 pm](https://cloud.githubusercontent.com/assets/12868342/10340236/2a8f0f06-6cdd-11e5-9023-4337dc4b31b4.png)

**Comment by rajadain** [comment]
Fixed by #939.
