### ISSUE TITLE
Add GA key to microsite view

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#920]
> Looking at the latest analytic report from @HeatherBrooks , I'm not quite sure if the analytics are actually working right or not. We're seeing hits for /analyze and /project but we're not seeing any hits for /micro. I know I've hit the micro site a number of times myself so it should show page hits.

It appears that the microsite view is not passing the GA application key to the template when it's rendered, as it's not there in the registration step:

`ga('create', '', 'auto');`

(from prod)

**Comment by SRGDamia1** [comment]
We are still not seeing any hits to /micro on our google analytics results as of this morning.  Perhaps we are not understanding how the analytics key works and what we should be looking for.  Should this be appearing as a /micro page of will using the same key mean that the hits from this will be joined in with the hits to the full application?

**Comment by mmcfarland** [comment]
@SRGDamia1 this code (referenced in this PR above, #928) was merged in after the deployment on the 30th.  It will be included in the next release and is available on mmw-dev/micro currently.
