### ISSUE TITLE
Modals don't protect against double clicks

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#922]
See original comment https://github.com/WikiWatershed/model-my-watershed/pull/908#issuecomment-146012938

**Comment by rajadain** [comment]
@lliss could you please elaborate?

**Comment by lliss** [comment]
If you click on the button in the modal a few times very fast, you should be able to trigger a few events. The first one usually works and the send one usually throws an error or at least does an HTTP request that fails.

**Comment by lliss** [comment]
Attempt to reproduce by going to the projects page, selecting delete and then confirming the deletion by clicking the button a few times very quickly. You should see a successful network request and a failed one as well.

**Comment by lliss** [comment]
Same things happens with hitting "enter" a few times.
