### ISSUE TITLE
More graceful handling of 0-area modifications

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#924]
Currently if a modification is drawn completely outside the AoI, it has an effective area of 0, which causes the model run to fail, even if there are other non-zero modifications:

![image](https://cloud.githubusercontent.com/assets/1430060/10372588/7b4ee162-6db6-11e5-96bb-75b93e46624c.png)

Consider warning the user or simply ignoring those modifications.

**Comment by mmcfarland** [comment]
See also #846

**Comment by rajadain** [comment]
Ah sorry, didn't realize this was already reported. Will move my comment over and close this in favor of #846.
