### ISSUE TITLE
Delay in chart refresh after spinner ends for new scenarios

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#940]
Similar to https://github.com/WikiWatershed/model-my-watershed/issues/732, but only happens when the scenario is initially added.

As of now, this is happening on `develop` and `mmw-dev.azavea.com`, but not `mmw.azavea.com`, so the cause may be into between 13ff68067f9c44c250ac85592bef5fe0d56d7525 and c645cbd1732801330c0febf92fdc48d5102c4ae3.

![spinner](https://cloud.githubusercontent.com/assets/1042475/10438928/94b80d1c-7104-11e5-8e6f-b10231d6018b.gif)

**Comment by jamesmcclain** [comment]
You may need to repoint this.
