### ISSUE TITLE
On small screens/mobile browsers overlays tab doesn't activate on click

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#944]
Tested on Chrome on an iPhone 6 with iOS 9 and a Nexus 7 using the built-in browser.

In the layer control, tapping on the "Overlays" header doesn't activate the overlays tab.

**Comment by caseypt** [comment]
On the Nexus Tablet, clicking the link updates the url with `#overlays-layer-list`.

**Comment by SRGDamia1** [comment]
We've had several people encounter this bug recently, on a Windows Surface and a variety of mobile phones.  I'm also seeing this in Firefox on a Nexus 5.

I'm encountering the same behavior in Chrome on a Windows 7 touch screen laptop.  Clicking the link on the laptop shows the #overlays-layer-list in the URL.

**Comment by SRGDamia1** [comment]
Is it known if this is a problem on Chrome Books?  Most students in schools are using these.

**Comment by kellyi** [comment]
For reference:

I looked into this a little with the Nexus 7 tablet and it seemed like removing this line:

`L.DomEvent.on(listContainer, 'click', L.DomEvent.stopPropagation);`

at https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/layerControl.js#L70 made the Layer Control overlays tabs work.

I've only been able to test it on the Nexus so far.

**Comment by kellyi** [comment]
Encountered this again when working on #1539 

Happens on iPad in Safari and on a Windows touch tablet.

**Comment by ajrobbins** [comment]
No longer observed.
