### ISSUE TITLE
Overlay button style is distorted on mobile

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#945]
Tested on Chrome on an iPhone 6 with iOS 9 and a Nexus 7 using the built-in browser.

Screenshot from iPhone.

![unnamed](https://cloud.githubusercontent.com/assets/1042475/10458570/684b9326-7199-11e5-9f58-fd238f01320e.jpg)

**Comment by rajadain** [comment]
See also: #890

**Comment by caseypt** [comment]
Interesting. I don't see it on my laptop.

**Comment by kdeloach** [comment]
I witnessed this problem on my touchscreen laptop (See #890).

**Comment by caseypt** [comment]
Got it. Thanks.

**Comment by caseypt** [comment]
Updated the other issue. Closing this.
