### ISSUE TITLE
Minor button misalignment

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#948]
The draw tools are not consistently sized, with the Search bar and Reset buttons being smaller than the Select by Boundary and Draw Area buttons.

![image](https://cloud.githubusercontent.com/assets/1430060/10465010/b39f5d96-71ba-11e5-9c07-b9f9e240d123.png)

![image](https://cloud.githubusercontent.com/assets/1430060/10465027/c40ecbb2-71ba-11e5-8a29-4e9b1b885b28.png)

Also, in the Model view toolbar, the precipitation slider bounding box is lower than the others:

![image](https://cloud.githubusercontent.com/assets/1430060/10465170/7363642e-71bb-11e5-923a-2eeedcc17705.png)

**Comment by ajrobbins** [comment]
New UI does not have buttons across the top of the map.
