### ISSUE TITLE
Extra Geoprocessing Calls

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/model-my-watershed#956]
The same data requested from the geoprocessing endpoint which are used to construct the "survey" for the `/analyze` page could also be used to construct the `aoi_census` when the user transitions from the analyze page to the modeling page.

Since there are are two (identical) geoprocessing queries over the AoI done when the modeling page is entered (one for current conditions and one for the new scenario [in spite of caching because the `aoi_census` does not exist upon entry]), this would reduce the number of queries over the entire AoI from 3 to 1.

**Comment by mmcfarland** [comment]
Is it truly the same survey since the analyze doesn't currently account for soils per query?  Not sure if that's technically true or not.

**Comment by jamesmcclain** [comment]
There may be some information missing such that it is not possible to reconstruct the census from the survey, but I believe that the actual calls to the backend are the same (I could be mistaken).

**Comment by mmcfarland** [comment]
Cool, definitely worth investigating.

**Comment by kdeloach** [comment]
Is this done?

**Comment by jamesmcclain** [comment]
No, solution got rejected.

**Comment by mmcfarland** [comment]
I think we wanted to do it, but would like to invest in a refactor of project creation first, since this gets attached (or should) to it.  

If it doesn't look like we're going to get to that refactor, we should consider if having this reduced load on geop in the interim should override the initial decision.

**Comment by mmcfarland** [comment]
See previous discussion here: https://github.com/WikiWatershed/model-my-watershed/pull/973
