### ISSUE TITLE
Rain Garden, Veg Basin, Porous Paving produce null results

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#960]
In the Model view, when Rain Garden, Veg Basin, or Porous Paving are added to any scenario, they nullify the results. The API response says `BMP rain_garden incompatible with soil d`:

![image](https://cloud.githubusercontent.com/assets/1430060/10543317/a8d08a60-73eb-11e5-9bc0-2fa347c4a0c4.png)

Deleting these modifications from a scenario allows the results to calculate and render correctly.

**Comment by caseypt** [comment]
See https://github.com/WikiWatershed/tr-55/issues/34

**Comment by rajadain** [comment]
Ah thanks. Moreover, we have #851! I even searched GitHub for "Basin" looking for that issue because I _knew_ there had to be one, but I couldn't find it.

**Comment by rajadain** [comment]
Closing this in favor of the TR-55 issue.
