### ISSUE TITLE
Deleting Project leads to inconsistent state

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#965]
1. Log in and create a new project (so it is saved to the server).
 2. Delete the project. You should be taken back to the Draw view with the same AoI
 3. Proceed to Analyze. Proceed to Model view.
 4. The app should crash into an inconsistent state, with a 404 for the old project ID in the console window

![screen shot 2015-10-17 at 9 22 56 pm](https://cloud.githubusercontent.com/assets/1430060/10562040/3ce46e2c-7515-11e5-849a-144a1574a343.png)

**Comment by mmcfarland** [comment]
I think this should take you back to your My Projects page upon encountering that 404.
