### ISSUE TITLE
SJS encoded string length error

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#975]
Not getting a lot of context about where this error is generated from, but production monitoring shows a lot of these `akka.actor` errors being produced.

```
JobServer-akka.actor.default-dispatcher-10759] ERROR akka.actor.OneForOneStrategy -  
encoded string too long: 157368 bytes
```

**Comment by ajrobbins** [comment]
Shift to Collections API will negate the use of SJS; and this issue is no longer observed.
