### ISSUE TITLE
Upgrade TR55 and check chart size error

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#977]
There were some bug fixes that may fix the chart size error on this public project in production:

https://mmw.azavea.com/project/145/scenario/345

We may need to pluck that AoI and Scenario into a dev environment.

**Comment by jamesmcclain** [comment]
I have already done some testing on this.  Not on that particular scenario, but I was able to confirm that the newer TR-55 does not exhibit the chart bug.

**Comment by mmcfarland** [comment]
I updated TR55 locally and copied the project/scenario from the production DB.  Results appear correct:

![screenshot from 2015-10-26 17 02 28](https://cloud.githubusercontent.com/assets/1014341/10742401/6459ecee-7c03-11e5-821a-04fb6e46ef5b.png)

**Comment by jamesmcclain** [comment]
+1 Everything worked for me with the new module.
