### ISSUE TITLE
Bottom bar missing in Modeling view screenshots

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#979]
Expected:

![image](https://cloud.githubusercontent.com/assets/1430060/10671695/18caab5c-78ba-11e5-94b6-25a6d36777d7.png)

Observed:

![image](https://cloud.githubusercontent.com/assets/1430060/10671708/26528286-78ba-11e5-8b2a-9e1a8693ecbb.png)

As seen in Chrome on OS X. In Firefox, the bottom bar is also missing, but the gray overlay stretches all the way down, making it seem less aberrant:

![image](https://cloud.githubusercontent.com/assets/1430060/10671731/477def22-78ba-11e5-95e1-570e714d151a.png)

**Comment by ajrobbins** [comment]
UI redesign eliminated bottom bar in favor of sidebar.
