### ISSUE TITLE
Evaluate dynamic time series charting

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#981]
Use a sample observation time series result from the forthcoming API to evaluate a plotting library that allows zooming and interactivity.   Set up a module to add the chart to a popup.

**Comment by mmcfarland** [comment]
[HighStocks](http://www.highcharts.com/stock/demo/data-grouping) has the most sophisticated timeseries chart option I've found and it appears that Stroud falls under the CC license availability.  We're checking to see if there are funder's requirements to use a true open source library.

**Comment by mmcfarland** [comment]
Using this as the basis of my data understanding, though it might differ.  Awaiting documentation about what `data_type` values are available besides `vizerData`.  Libraries I've seen seem to like data in an array with an assumed poll interval configured, but `vizerData` seems to be indexed by timestamp.  Could easily be converted and filled with non-values for timestamps that are not represented by the lowest interval.

http://www.wikiwatershed-vs.org/ssa/get_platform_data.php?sid=0.030394606525078416&platform_id=DEOS_DLWG&var_id=A1_BarPress&data_type=vizerData'

**Comment by mmcfarland** [comment]
Stroud has expressed interest in unifying a branded plotting look across several projects they are funding, both browser based (MMW, BigCZ) and "ToolKit" based (ODM2Tools).  They've asked that we try to accomodate a project like:

- Bokeh: http://bokeh.pydata.org/en/latest/
- mpld3: http://mpld3.github.io/

The general idea is these charts are manipulated and rendered in a python environment, but they produce static html and javascript that can be used in browsers, IPython Notebook and as output from a CLI.  This doesn't optimize the workflow for our web app implementation, but I think it could be accommodated.

It appears that Bokeh can generate individual `script` and `div` tags to allow insertion into an existing page.
http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#components

**Comment by mmcfarland** [comment]
After additional discussion with Stroud, HighStocks is again a front runner for plotting the observation timeseries.

**Comment by mmcfarland** [comment]
A very basic Highstock that consumes Vizer data http://jsfiddle.net/jGALb/122/ (chrome will need to be started with --disable-web-security) to allow XSS.

**Comment by rajadain** [comment]
+1 for HighCharts. It's one of the most polished and stable libraries out there.
