### ISSUE TITLE
Incorrect land cover totals with results from mmw-geo 0.2.0

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#984]
The recent switch to new nlcd tiles resulted in a change in the output of the area reported for land cover.  I assume this has something to do with the switch in tile projections.

##### mmw-geo 0.1.1 (pretty close to the right amount)
![screenshot from 2015-10-26 14 48 39](https://cloud.githubusercontent.com/assets/1014341/10739046/b518f458-7bf0-11e5-9e59-f8582dbce12c.png)

##### mmw-geo 0.2.0 (numbers are pretty far off, almost 4x)
![screenshot from 2015-10-26 14 48 54](https://cloud.githubusercontent.com/assets/1014341/10739050/ba6bdb6e-7bf0-11e5-85e7-d6d045b00d80.png)

**Comment by jamesmcclain** [comment]
We also need to lower the cap on the maximum AoI size by a factor of about 9.

**Comment by jamesmcclain** [comment]
Note, mmw-geoprocessing 0.2.0 is already out.  This card is for getting the application ready for the upcoming release of mmw-geoprocessing.
