### ISSUE TITLE
Water quality load units are crowded/overlapping in Model view graph

### ISSUE THREAD

**Issue by arobbi7** [WikiWatershed/model-my-watershed#995]
When the load numbers are large enough, the x-axis interval numbers start to get really crowded and overlap on the water quality bar graph in Model view.

Observed in Chrome, Firefox, and Safari on 13" Mac, and in IE 11 on Windows.

This project can be used to replicate: https://mmw-dev.azavea.com/project/443/scenario/882

![screen shot 2015-11-05 at 10 24 46 am](https://cloud.githubusercontent.com/assets/12868342/10972631/1a24e17c-83a8-11e5-80c7-652bfebaeaf9.png)

**Comment by jamesmcclain** [comment]
Who do I need to login as in order to be able to see this project?

**Comment by jamesmcclain** [comment]
This issue has already been solved.

**Comment by lewfish** [comment]
There are still some situations that result in crowded labels. I think to fix this you would have to change the threshold at which NVD3 changes the number of tick marks. 

![screen shot 2015-12-02 at 11 31 49 am 2](https://cloud.githubusercontent.com/assets/1896461/11536898/7f155f94-98e8-11e5-80a5-78d7514f5a4f.png)

**Comment by jamesmcclain** [comment]
Should I reopen this, then?
